NativeScript/NativeScript

- apps/tests/image-source-tests.ts
- image-source/image-source-common.ts
- image-source/image-source.android.ts
- image-source/image-source.d.ts
- image-source/image-source.ios.ts
> load image-source from base64 string added + tests

- apps/tests/xml-declaration/xml-declaration-tests.ts
- ui/builder/component-builder.ts
> Binding gestures event handlers support added

- CrossPlatformModules.csproj
- apps/tests/testRunner.ts
- apps/tests/timer-tests.ts
- apps/tests/ui/helper.ts
- apps/tests/ui/list-view/list-view-tests.ts
- apps/tests/weak-event-listener-tests.ts
- ui/button/button-common.ts
- ui/core/bindable.ts
- ui/core/weak-event-listener.d.ts
- ui/core/weak-event-listener.ts
- ui/list-view/list-view-common.ts
- ui/list-view/list-view.ios.ts
- ui/text-base/text-base.ts
In this PR:
* ListView uses weakEventListener to attach to items change events when it is observable
* Some refactoring on the weakEventListener
> List view weak events

- apps/perf-tests/controls-page.ts
- apps/tests/layouts/wrap-layout-tests.ts
- apps/tests/testRunner.ts
- apps/tests/ui/helper.ts
- apps/tests/ui/page/page-tests-common.ts
- ui/frame/frame.android.ts
- ui/frame/frame.ios.ts
- ui/page/page-common.ts
- ui/page/page.d.ts
> Page navigation events

- ui/frame/frame.ios.ts
> Request layout when showing/hiding the navbar

- declarations.d.ts
See https://github.com/borisyankov/DefinitelyTyped/blob/master/node/node.d.ts#L48
> Add Node's `exports` to declarations (same as module.exports)

- apps/tests/ui/list-view/list-view-tests.ts
- ui/list-view/list-view.android.ts
- ui/list-view/list-view.d.ts
- ui/list-view/list-view.ios.ts
> view parent exposed in itemLoading event

- apps/tests/testRunner.ts
- apps/tests/ui/search-bar/search-bar-tests-native.android.ts
- apps/tests/ui/search-bar/search-bar-tests-native.d.ts
- apps/tests/ui/search-bar/search-bar-tests-native.ios.ts
- apps/tests/ui/search-bar/search-bar-tests.ts
- ui/search-bar/search-bar-common.ts
- ui/search-bar/search-bar.android.ts
- ui/search-bar/search-bar.d.ts
- ui/search-bar/search-bar.ios.ts
This commit should be pushed under the proper email address.
> Search bar hint color

- apps/tests/ui/segmented-bar/segmented-bar-tests-native.android.ts
- apps/tests/ui/segmented-bar/segmented-bar-tests-native.d.ts
- apps/tests/ui/segmented-bar/segmented-bar-tests-native.ios.ts
- apps/tests/ui/segmented-bar/segmented-bar-tests.ts
- ui/segmented-bar/segmented-bar.android.ts
> Segmented bar android color

- apps/tests/xml-declaration/xml-declaration-tests.ts
- ui/core/view-common.ts
- ui/core/view.d.ts
Implemented https://github.com/NativeScript/NativeScript/issues/268.
> backgroundImage exposed to View

- ui/frame/frame.ios.ts
- ui/segmented-bar/segmented-bar.android.ts
Change the property types to the base public types.
> Better public type fix by not exposing the private types.

- ui/enums/enums.d.ts
- ui/enums/enums.ts
- ui/styling/converters.ts
- ui/styling/style.ts
- ui/styling/stylers.android.ts
> Collapse property added. Collapsed property is now obsolete.

- apps/tests/xml-declaration/xml-declaration-tests.ts
- ui/builder/builder.ts
> platform specific component declaration support for UI builder + tests

- apps/tests/app/mainPage.ts
- apps/tests/layouts/grid-layout-tests.ts
* Increase the GridLayout measure delta
* Change the clearTimeout to enqueue a second callback instead of waiting for the timeout to expire.
> "Fix" sporadically failing tests

- apps/tests/xml-declaration/xml-declaration-tests.ts
- ui/builder/component-builder.ts
> look for plugins/modules in tns_modules folder + test

- ui/dialogs/dialogs.ios.ts
Fix for https://github.com/NativeScript/NativeScript/issues/395
> action for iPad 8.x fixed

- ui/dialogs/dialogs.ios.ts
Fixed https://github.com/NativeScript/NativeScript/issues/406
> dialogs result in iOS7 fixed

- ui/dialogs/dialogs.ios.ts
Fix for https://github.com/NativeScript/NativeScript/issues/422
> login dialog result for iOS7 fixed

- application/application.android.ts
Changed interface extending in application module so it is in sync with static bindings generation.
> changed interface extending in application module

- CrossPlatformModules.csproj
- apps/action-bar-demo/main-page.xml
- apps/action-bar-demo/pages/action-bar-hidden.ts
- apps/action-bar-demo/pages/action-bar-hidden.xml
- ui/action-bar/action-bar-common.ts
- ui/action-bar/action-bar.android.ts
- ui/action-bar/action-bar.d.ts
- ui/frame/frame.ios.ts
- ui/page/page-common.ts
- ui/page/page.android.ts
- ui/page/page.d.ts
- ui/page/page.ios.ts
- ui/tab-view/tab-view.android.ts
In this PR:
* Page property renamed: `navigationBarHidden` ->  `actionBarHidden`
* Bug fixes for issues logged in #263
> Property renamed and bug fixes

- apps/tests/layouts/stack-layout-tests.ts
- ui/layouts/layout.d.ts
- ui/layouts/layout.ts
- Layout.insertChild(atIndex, child)
- Layout.getChildIndex(child): number
Needed by the angular renderer.
> Layout child API extensions

- CrossPlatformModules.csproj
- application/application.android.ts
- application/application.d.ts
- application/application.ios.ts
- apps/connectivity-demo/app.ts
- apps/connectivity-demo/main-page.ts
- apps/connectivity-demo/main-page.xml
- apps/notifications-demo/app.ts
- apps/notifications-demo/main-page.ts
- apps/notifications-demo/main-page.xml
- apps/notifications-demo/package.json
- apps/tests/application-tests-common.ts
- apps/tests/application-tests.android.ts
- apps/tests/application-tests.ios.ts
- apps/tests/connectivity-tests.ts
- connectivity/connectivity.android.ts
- connectivity/connectivity.d.ts
- connectivity/connectivity.ios.ts
- declarations.ios.d.ts
Resolved Issue #473: Add support for Notification Observers (iOS) and Broadcast Receivers (Android)
> Resolved Issue #451: Improve the Network Stack

- apps/tests/xml-declaration/xml-declaration-tests.ts
- ui/builder/component-builder.ts
Implemented https://github.com/NativeScript/NativeScript/issues/309
> Support lower-case-dashed component declaration in the XML added

- application-settings/application-settings.android.ts
- camera/camera.android.ts
- connectivity/connectivity.android.ts
- file-system/file-system-access.android.ts
- image-source/image-source.android.ts
- location/location.android.ts
- platform/platform.android.ts
- utils/utils.android.ts
- utils/utils.d.ts
"application" replaced with "utils"
> getApplication() and getApplicationContext() added/used to/from utils

- apps/tests/ui/style/style-tests.ts
- color/color-common.ts
- color/color.d.ts
- ui/styling/css-selector.ts
- ui/styling/style.ts
> Handle exceptions when setting CSS vlaues

- application/application.android.ts
- apps/tests/ui/page/page-tests-common.ts
- ui/page/page-common.ts
> Default page background - white

- CrossPlatformModules.csproj
- application/application-common.ts
- application/application.android.ts
- application/application.d.ts
- application/application.ios.ts
- apps/notifications-demo/main-page.ts
- apps/notifications-demo/main-page.xml
- apps/orientation-demo/app.ts
- apps/orientation-demo/main-page.port.xml
- apps/orientation-demo/main-page.ts
- apps/orientation-demo/package.json
- file-system/file-name-resolver.d.ts
- file-system/file-name-resolver.ts
- platform/platform.android.ts
- platform/platform.ios.ts
- ui/builder/builder.ts
- ui/enums/enums.d.ts
- ui/enums/enums.ts
- ui/frame/frame-common.ts
> Application orientation changed event

- application/application.ios.ts
This class is automatically created - we should not instantiate it!
> wrong app delegate creation removed

- ui/layouts/grid-layout/grid-layout.android.ts
> Fix ItemSpec length is rounded

- CrossPlatformModules.csproj
- ui/core/view.android.ts
- ui/core/view.ios.ts
- ui/image/image.ios.ts
- ui/label/label.ios.ts
- ui/layouts/layout.android.ts
- ui/layouts/layout.ios.ts
- ui/list-view/list-view.android.ts
- ui/repeater/repeater.d.ts
- ui/repeater/repeater.ts
- ui/ui.d.ts
Remove some unnecessary traces
> Fix ListView module to check for layoutBase instead of Layout

- CrossPlatformModules.csproj
- apps/ui-tests-app/pages/gesture-binding.ts
- apps/ui-tests-app/pages/gesture-binding.xml
- ui/builder/component-builder.ts
Fixed https://github.com/NativeScript/NativeScript/issues/558
> gesture binding fixed + test

- CrossPlatformModules.csproj
- apps/ui-tests-app/pages/html-view.ts
- apps/ui-tests-app/pages/html-view.xml
- ui/html-view/html-view.ios.ts
> br not handled properly by HtmlView + functional test

- CHANGELOG.md
Changelog updates for 1.2.1 release
> [Don't Merge] Chagelog updated

- org.nativescript.widgets.d.ts
- ui/styling/stylers.android.ts
- ui/styling/styling.d.ts
> Image rounded coreners clip

- apps/tests/ui/style/style-tests.ts
- ui/styling/style-scope.ts
> url('some.css') is now optional

- CrossPlatformModules.csproj
- apps/ui-tests-app/web-view/test.css
- apps/ui-tests-app/web-view/test.html
- apps/ui-tests-app/web-view/webview.xml
- apps/ui-tests-app/web-view/webviewlocalfile.xml
- ui/web-view/web-view.android.ts
- ui/web-view/web-view.ios.ts
Fixed https://github.com/NativeScript/NativeScript/issues/613
> Webview base url

- ui/repeater/repeater.ts
Fixed https://github.com/NativeScript/NativeScript/issues/590
> repeater children now created no matter if isLoaded is true

- apps/tests/ui/bindable-tests.ts
- apps/tests/ui/list-view/list-view-tests.ts
- data/observable/observable.d.ts
- data/observable/observable.ts
- ui/core/bindable.ts
- ui/list-view/list-view-common.ts
- ui/list-view/list-view.android.ts
- ui/list-view/list-view.d.ts
- ui/list-view/list-view.ios.ts
Implemented https://github.com/NativeScript/NativeScript/issues/578
> scrollToIndex added to ListView

- apps/tests/ui/view/view-tests-common.ts
- ui/core/view-common.ts
- ui/core/view.d.ts
Implemented https://github.com/NativeScript/NativeScript/issues/619
> setInlineStyle implementation + test

- CrossPlatformModules.csproj
- apps/tests/pages/fonts-test.ts
- apps/tests/ui/scroll-view/scroll-view-tests.ts
- apps/tests/ui/search-bar/search-bar-tests.ts
- apps/tests/ui/view/view-tests-common.ts
- apps/ui-tests-app/pages/text/button.ts
- apps/ui-tests-app/pages/text/button.xml
- apps/ui-tests-app/pages/text/label.ts
- apps/ui-tests-app/pages/text/text-field.ts
- apps/ui-tests-app/pages/text/text-view.ts
- ui/core/dependency-observable.d.ts
- ui/core/dependency-observable.ts
- ui/page/page-common.ts
- ui/styling/css-selector.ts
- ui/styling/style-property.d.ts
- ui/styling/style-property.ts
- ui/styling/style.ts
- ui/styling/stylers.android.ts
- utils/android_constants.ts
- utils/types.ts
Fix for types - isString and isNumber.
Fix page background to be applied in onLoaded method.
Fix for SearchBar reseColorProperty method.
Modified several tests to pass on VS Emulator for Android.
Enhancements for dependency-observable - it is now possible to add defaultValueGetter function to extract default value for a property. It can also be cached or not.
Remove android_constants because they are per theme and we cannot use them safely.
> Fix for Button padding, broderWidth & background in android.

- apps/tests/gestures-tests.ts
- apps/ui-tests-app/pages/gestures.ts
- ui/builder/component-builder.ts
- ui/core/view-common.ts
- ui/core/view.d.ts
- ui/gestures/gestures.android.ts
- ui/gestures/gestures.d.ts
- ui/gestures/gestures.ios.ts
Now you can do:
```XML
<Page loaded="pageLoaded">
<StackLayout>
</StackLayout>
</Page>
```
```TypeScript
import observable = require("data/observable");
import view = require("ui/core/view");
import gestures = require("ui/gestures");
import label = require("ui/label");
import button = require("ui/button");
import pages = require("ui/page");
import stackLayout = require("ui/layouts/stack-layout");
export function pageLoaded(args: observable.EventData) {
var page = <pages.Page>args.object;
var stack = <stackLayout.StackLayout>page.content;
var lbl1 = new label.Label();
lbl1.text = "Label1";
// Add single gesture
lbl1.on(gestures.GestureTypes.tap, (args: gestures.GestureEventData) => {
console.log("Event: " + args.eventName + ", sender: " + args.object);
});
stack.addChild(lbl1);
var lbl2 = …
```
> gestures now can be added with on() and removed with off()

- apps/connectivity-demo/main-page.ts
- apps/tests/connectivity-tests.ts
- connectivity/connectivity.android.ts
- connectivity/connectivity.d.ts
- connectivity/connectivity.ios.ts
Fixed typo with API (starMonitoring -> startMonitoring)
> Fixed typo

- ui/core/view-common.ts
- ui/core/view.android.ts
- ui/core/view.d.ts
- ui/gestures/gestures-common.ts
- ui/gestures/gestures.android.ts
> Fixed multiple gestures for Android

- apps/tests/layouts/layout-helper.android.ts
Export types used by public properties in tests/**/layout-helper.android.ts
> Fix compile errors.

- CrossPlatformModules.csproj
- CrossPlatformModules.sln
- apps/tests/TKUnit.ts
- apps/tests/pages/page19.ts
- apps/tests/pages/page19.xml
- apps/tests/pages/page20.ts
- apps/tests/pages/page20.xml
- apps/tests/ui/page/page-tests-common.ts
- apps/tests/ui/page/page21.ts
- apps/tests/ui/page/page21.xml
- ui/page/page.ios.ts
> Fix iOS layout in modal pages.

- apps/tests/http-tests.ts
- apps/tests/ui/list-view/list-view-tests.ts
- http/http-request.ios.ts
- http/http.ts
> Promises rejected properly when loading wrong content

- apps/tests/http-tests.ts
- http/http-request.android.ts
- http/http-request.ios.ts
- utils/utils-common.ts
- utils/utils.d.ts
Implemented https://github.com/NativeScript/NativeScript/pull/688
> http jsonp support added

- apps/tests/testRunner.ts
- apps/tests/ui/segmented-bar/segmented-bar-tests.ts
- ui/segmented-bar/segmented-bar-common.ts
- ui/segmented-bar/segmented-bar.android.ts
- ui/segmented-bar/segmented-bar.d.ts
- ui/segmented-bar/segmented-bar.ios.ts
> SegmentedBar selectedIndexChanged added

- ui/builder/component-builder.d.ts
- ui/builder/component-builder.ts
Used by the Angular2 renderer only (for now)
> Component builder functionality exposed to users

- utils/utils.android.ts
- utils/utils.d.ts
- utils/utils.ios.ts
> openUrl added

- ui/builder/component-builder.d.ts
- ui/builder/special-properties.d.ts
- ui/builder/special-properties.ts
This one should have gone in with my yesterday's PR really...
> Fix public declarations for the "ui/builder/special-properties" module.

- apps/tests/xml-declaration/xml-declaration-tests.ts
- ui/builder/component-builder.ts
- ui/core/bindable.ts
- ui/core/view-common.ts
- ui/core/view.d.ts
> Support for binding expressions in event bindings

- ui/dialogs/dialogs.android.ts
Fix for https://github.com/NativeScript/NativeScript/issues/720
> startActivity used if no foregroundActivity

- ui/action-bar/action-bar.ios.ts
Perform a cherry-pick of the fix from the `master` branch
> Fix for issue #740.

- CrossPlatformModules.csproj
- data/observable/observable.ts
> Add and remove event listener fixes

- apps/tests/ui/text-field/text-field-tests.ts
- ui/editable-text-base/editable-text-base.android.ts
- ui/text-field/text-field.ios.ts
> text-field hint now can be set to number

- ui/styling/stylers.ios.ts
> borderRadius not working on UILabel

- console/console.ts
- globals/globals.ts
> console.dump implemented for ios

- apps/tests/ui/segmented-bar/segmented-bar-tests-native.android.ts
- apps/tests/ui/segmented-bar/segmented-bar-tests-native.d.ts
- apps/tests/ui/segmented-bar/segmented-bar-tests-native.ios.ts
- apps/tests/ui/segmented-bar/segmented-bar-tests.ts
- ui/segmented-bar/segmented-bar.android.ts
> segmented bar selectedIndexChanged fix

- tsconfig.json
- ui/frame/frame-common.ts
- ui/frame/frame.d.ts
- ui/frame/frame.ios.ts
- ui/page/page.ios.ts
> Page background now spans under ActionBar

- apps/tests/xml-declaration/xml-declaration-tests.ts
- ui/builder/component-builder.ts
component builder now can handle properly empty text or text with spaces. 
Fix for #837.
> component builder fixed

- ui/editable-text-base/editable-text-base.android.ts
- ui/text-field/text-field-common.ts
- ui/text-field/text-field.android.ts
- ui/text-field/text-field.d.ts
- ui/text-field/text-field.ios.ts
Adds a returnPress event for the TexField widget. #713
> implements #713

- CrossPlatformModules.csproj
- apps/tests/testRunner.ts
- apps/tests/ui/placeholder/placeholder-tests.ts
- ui/core/view.ios.ts
- ui/placeholder/placeholder.android.ts
- ui/placeholder/placeholder.ios.ts
> placeholder creatingView event fixed + tests

- ui/dialogs/dialogs.android.ts
> Message will be set only if you do not have actions since message and actions are mutually exclusive.

- ui/layouts/grid-layout/grid-layout-common.ts
- ui/layouts/grid-layout/grid-layout.d.ts
- ui/layouts/grid-layout/grid-layout.ios.ts
- ui/layouts/layout-base.d.ts
- ui/layouts/layout-base.ts
> Layout changes

- utils/utils.d.ts
> async declaration removed

- camera/camera.ios.ts
> code refactored to support ios9

- ui/action-bar/action-bar.ios.ts
- ui/core/view.ios.ts
- ui/frame/frame.ios.ts
- ui/layouts/layout.ios.ts
- ui/list-view/list-view.ios.ts
- ui/page/page-common.ts
- ui/page/page.d.ts
- ui/page/page.ios.ts
- ui/tab-view/tab-view.ios.ts
- ui/utils.d.ts
- ui/utils.ios.ts
> Implement Page background option to span under status bar (iOS only)

- ui/core/view-common.ts
This should fix applying CSS on child views.
> isLoaded is set before calling applyStyleFromScope

- connectivity/connectivity.ios.ts
~~Merge after https://github.com/NativeScript/ios-runtime/pull/351.~~ This is ready for merging now.
> Remove redundant CFRelease calls

- application/application.android.ts
- application/application.ios.ts
https://github.com/NativeScript/ios-runtime/issues/78
> Integrate recent iOS Runtime global.__onUncaughtError feature

- apps/tests/layouts/grid-layout-tests.ts
- ui/frame/frame.android.ts
- ui/layouts/grid-layout/grid-layout.ios.ts
- ui/page/page.android.ts
Fix showModal Page size method for Android
Fix showModal Page actionBar is now hidden
> Fix GridLayout desiredSize when not stretched.

- apps/action-bar-demo/main-page.ts
- apps/action-bar-demo/main-page.xml
- ui/action-bar/action-bar.ios.ts
- ui/core/view-common.ts
- ui/core/view.d.ts
- ui/styling/style.ts
- ui/styling/stylers.android.ts
- ui/styling/stylers.ios.ts
UI test can be implemented to test the visual changes
> Action bar title color stylers

- apps/tests/TKUnit.ts
- apps/tests/layouts/absolute-layout-tests.ts
- apps/tests/layouts/dock-layout-tests.ts
- apps/tests/layouts/grid-layout-tests.ts
- apps/tests/layouts/stack-layout-tests.ts
- apps/tests/layouts/wrap-layout-tests.ts
- apps/tests/testRunner.ts
- apps/tests/ui-test.ts
- apps/tests/ui/scroll-view/scroll-view-tests.ts
- apps/tests/ui/web-view/web-view-tests.ts
Reduce all Layouts, ScrollView & WebView test time
> Add module duration

- apps/tests/ui/style/style-properties-tests.ts
- ui/core/view-common.ts
- ui/enums/enums.d.ts
- ui/enums/enums.ts
- ui/layouts/stack-layout/stack-layout.ios.ts
- ui/styling/stylers.android.ts
Fixed https://github.com/NativeScript/NativeScript/issues/889
> vertical-alignment middle support added

- apps/ui-tests-app/pages/gestures.ts
- ui/gestures/gestures.ios.ts
> Gestures ios event

- apps/tests/application-tests-common.ts
- apps/tests/testRunner.ts
- ui/core/proxy.ts
- ui/image/image-common.ts
- ui/layouts/dock-layout/dock-layout-common.ts
- ui/layouts/stack-layout/stack-layout-common.ts
- ui/layouts/wrap-layout/wrap-layout-common.ts
- ui/page/page-common.ts
- ui/styling/style.ts
> global.android replaced with platform.device.os === platform.platformNames.android

- ui/editable-text-base/editable-text-base.android.ts
- ui/search-bar/search-bar-common.ts
- ui/search-bar/search-bar.android.ts
- ui/search-bar/search-bar.d.ts
- ui/search-bar/search-bar.ios.ts
- utils/utils.android.ts
- utils/utils.d.ts
> dismissSoftInput implemented

- apps/tests/ui/progress/progress-tests.ts
- ui/styling/stylers.android.ts
- ui/styling/stylers.ios.ts
> progress css support for color and backgroundColor added

- CrossPlatformModules.csproj
- apps/tests/ui/switch/switch-tests.ts
- apps/ui-tests-app/pages/switchandprogress.xml
- ui/core/view.ios.ts
- ui/styling/style.d.ts
- ui/styling/style.ts
- ui/styling/stylers.android.ts
- ui/styling/stylers.ios.ts
> Switch color and background-color css support added

- apps/ui-tests-app/web-view/webviewhtmlwithimages.xml
- ui/web-view/web-view.android.ts
> WebView html with images fixed

- apps/tests/xml-declaration/custom-css-file.css
- apps/tests/xml-declaration/xml-declaration-tests.ts
- ui/styling/css-selector.ts
> lower-case-dashed components css support fixed

- CrossPlatformModules.csproj
- apps/tests/ui/tab-view/tab-view-navigation-tests.ts
- apps/tests/ui/tab-view/tab-view-tests.ts
- apps/ui-tests-app/web-view/wvlocal.xml
- ui/web-view/web-view.android.ts
> android 6 support

- apps/tests/ui/text-field/text-field-tests.ts
- apps/tests/ui/text-view/text-view-tests.ts
- ui/styling/stylers.ios.ts
> TextField CSS cursor color support added

- apps/tests/ui/button/button-tests-native.android.ts
- apps/tests/ui/button/button-tests-native.d.ts
- apps/tests/ui/button/button-tests-native.ios.ts
- apps/tests/ui/button/button-tests.ts
- ui/button/button-common.ts
- ui/button/button.android.ts
- ui/button/button.d.ts
- ui/button/button.ios.ts
> Button textWrap implemented

- apps/tests/ui/activity-indicator/activity-indicator-tests.ts
- ui/styling/stylers.android.ts
- ui/styling/stylers.ios.ts
> ActivityIndicator CSS color support fixed

- apps/tests/ui/slider/slider-tests.ts
- ui/styling/stylers.android.ts
- ui/styling/stylers.ios.ts
> Slider CSS color and background-color support fixed

- application/application.ios.ts
> application should not crash when start() method called multiple times

- gruntfile.js
- package.json
Removes bom from xml, css, js and ts files.
> Add a bom-removal task

- apps/tests/xml-declaration/xml-declaration-tests.ts
- ui/core/bindable.ts
> binding to special properties fixed

- apps/tests/ui/web-view/test.html
- apps/tests/ui/web-view/web-view-tests.ts
- ui/web-view/web-view.android.ts
> Web view utf fix

- application/application.android.ts
- ui/frame/frame.d.ts
- ui/frame/frame.ios.ts
> Implemented LiveSync page reload.

- apps/tests/ui/tab-view/tab-view-tests.ts
- ui/tab-view/tab-view.ios.ts
> selectedIndex behavior when no tabs fixed

- ui/styling/stylers.android.ts
> Use software layer for rounded borders on android 17

- apps/tests/ui/scroll-view/scroll-view-tests.ts
- ui/scroll-view/scroll-view-common.ts
- ui/scroll-view/scroll-view.android.ts
- ui/scroll-view/scroll-view.d.ts
- ui/scroll-view/scroll-view.ios.ts
> ScrollView scroll event

- apps/ui-tests-app/pages/gestures.ts
- ui/gestures/gestures-common.ts
- ui/gestures/gestures.android.ts
- ui/gestures/gestures.d.ts
- ui/gestures/gestures.ios.ts
> states for various gestures added

- CrossPlatformModules.csproj
- apps/tests/ui/style/style-properties-tests.ts
- apps/ui-tests-app/css/text-decoration.ts
- apps/ui-tests-app/css/text-decoration.xml
- apps/ui-tests-app/css/white-space.ts
- apps/ui-tests-app/css/white-space.xml
- apps/ui-tests-app/mainPage.ts
- tsconfig.json
- ui/button/button-common.ts
- ui/button/button.android.ts
- ui/button/button.d.ts
- ui/button/button.ios.ts
- ui/enums/enums.d.ts
- ui/enums/enums.ts
- ui/label/label-common.ts
- ui/label/label.android.ts
- ui/label/label.ios.ts
- ui/styling/converters.ts
- ui/styling/style.d.ts
- ui/styling/style.ts
- ui/styling/stylers.android.ts
- ui/styling/stylers.ios.ts
- ui/styling/styling.d.ts
> white-space CSS support added

- CrossPlatformModules.csproj
- gruntfile.js
- package.json
> Disable color output in grunt invocations from within Visual Studio.

- CrossPlatformModules.csproj
- apps/ui-tests-app/css/background.xml
- css-value/index.js
- css-value/reworkcss-value.d.ts
- ui/styling/background-common.ts
Related to #1018. In this PR:
* Support for negative values in `background-position`.
* Handle the case when only one value(ex. "left") is specified in `background-position`.
* UI - test cases for the fixes
> Fix: background-position with negative values

- apps/tests/TKUnit.ts
- apps/tests/ui/style/style-properties-tests.ts
- apps/ui-tests-app/css/text-transform.ts
- apps/ui-tests-app/css/text-transform.xml
- apps/ui-tests-app/mainPage.ts
- tsconfig.json
- ui/editable-text-base/editable-text-base.android.ts
- ui/enums/enums.d.ts
- ui/enums/enums.ts
- ui/styling/converters.ts
- ui/styling/style.d.ts
- ui/styling/style.ts
- ui/styling/stylers.android.ts
- ui/styling/stylers.ios.ts
- ui/styling/styling.d.ts
- ui/text-base/text-base.ts
- ui/text-field/text-field.ios.ts
- ui/text-view/text-view.ios.ts
> text-transform 

- apps/tests/ui/time-picker/time-picker-tests.ts
- ui/time-picker/time-picker-common.ts
- ui/time-picker/time-picker.android.ts
- ui/time-picker/time-picker.d.ts
- ui/time-picker/time-picker.ios.ts
> time picker minHour, maxHour, minMinute and maxMinute properties added

- es6-promise.d.ts
Making it possible to compile code referencing Angular Promise-based APIs.
> Unify the Promise definition with the one in es6-shim.

- es6-promise.d.ts
Fixing "That minor change can't break anything"...
> Fix a compile error in Promise def.

- apps/tests/observable-array-tests.ts
- data/observable-array/observable-array.ts
> setItem event fixed

- ui/gestures/gestures.android.ts
- ui/gestures/gestures.d.ts
- ui/gestures/gestures.ios.ts
> Add getFocusX() and getFocusY() methods to PinchGestureEventData

- apps/gallery-app/views/dialogs.ts
- apps/gallery-app/views/dialogs.xml
- ui/dialogs/dialogs-common.ts
- ui/dialogs/dialogs.android.ts
- ui/dialogs/dialogs.ios.ts
> alert fixed

- ui/tab-view/tab-view.ios.ts
> Correct TabView icon rendering mode

- apps/tests/xml-declaration/template-builder-tests/event-in-template.ts
- apps/tests/xml-declaration/template-builder-tests/event-in-template.xml
- apps/tests/xml-declaration/template-builder-tests/template-view.ts
- apps/tests/xml-declaration/xml-declaration-tests.ts
- tsconfig.json
- ui/builder/builder.ts
This fixes a regression introduced with #1125.
> Propagate context to template Views

- apps/tests/ui/action-bar/action-bar-tests-common.ts
- ui/action-bar/action-bar-common.ts
- ui/action-bar/action-bar.android.ts
- ui/action-bar/action-bar.d.ts
- ui/action-bar/action-bar.ios.ts
> Support for android.systemIcon in NavigationBar in Android

- apps/tests/TKUnit.ts
- apps/tests/ui/action-bar/action-bar-tests-common.ts
- apps/tests/ui/action-bar/action-bar-tests.android.ts
- apps/tests/ui/action-bar/action-bar-tests.ios.ts
- ui/action-bar/action-bar-common.ts
- ui/action-bar/action-bar.android.ts
- ui/action-bar/action-bar.d.ts
- ui/action-bar/action-bar.ios.ts
> ActionItems visibility

- ui/web-view/web-view.android.ts
> WebViewClientClass exported

- apps/ui-tests-app/font/tab-view.xml
- ui/styling/style.ts
- ui/styling/stylers.android.ts
- ui/styling/stylers.ios.ts
- ui/tab-view/tab-view-common.ts
- ui/tab-view/tab-view.d.ts
- ui/tab-view/tab-view.ios.ts
> font-family implemented

- .travis.yml
Add an npm install step so that local grunt gets found
Update the nodejs version used to 4.2.2
> Fix the travis build

- apps/tests/ui/action-bar/action-bar-tests-common.ts
- ui/action-bar/action-bar-common.ts
- ui/action-bar/action-bar.d.ts
> Implement page property for ActionItem

- apps/tests/ui/style/style-properties-tests.ts
- apps/ui-tests-app/css/decoration-transform-formattedtext.xml
- apps/ui-tests-app/css/text-transform.xml
- ui/button/button-common.ts
- ui/button/button.ios.ts
- ui/text-base/text-base-styler.android.ts
- ui/text-base/text-base-styler.ios.ts
- utils/utils.android.ts
- utils/utils.d.ts
- utils/utils.ios.ts
> text-transform and text-decoration with formattedText fixed

- ui/styling/background.android.ts
> If only backgroundColor is set use setColorFilter

- fetch/fetch.js
> fetch fixed to require XMLHttpRequest if not avaliable

- apps/tests/text/formatted-string-tests.ts
- text/span-common.ts
> Span colors fixed to accept known colors

- apps/tests/ui/image/image-tests.ts
- ui/image/image-common.ts
> Image src now can be set to Data URI

- apps/tests/layouts/wrap-layout-tests.ts
- ui/layouts/wrap-layout/wrap-layout.ios.ts
> Fixed wrap-layout

- apps/tests/layouts/grid-layout-tests.ts
- ui/layouts/grid-layout/grid-layout-common.ts
> Accept whitespace separators in grid rows and cols properties

- console/console.ts
related to https://github.com/NativeScript/android-runtime/pull/333
> send console messages to debugger

- CrossPlatformModules.csproj
- apps/ui-tests-app/mainPage.ts
- apps/ui-tests-app/pages/touch-event.ts
- apps/ui-tests-app/pages/touch-event.xml
- tsconfig.json
- ui/core/view.android.ts
- ui/gestures/gestures-common.ts
- ui/gestures/gestures.android.ts
- ui/gestures/gestures.d.ts
- ui/gestures/gestures.ios.ts
Related to #1366
There is also a test page prepared for ui-tests (@vchimev)
> Touch gesture implemented

- apps/tests/layouts/grid-layout-tests.ts
- apps/tests/layouts/layout-helper.android.ts
- apps/tests/layouts/layout-helper.d.ts
- apps/tests/layouts/layout-helper.ios.ts
- apps/tests/layouts/stack-layout-tests.ts
- apps/tests/xml-declaration/xml-declaration-tests.ts
- package.json
- ui/layouts/grid-layout/grid-layout-common.ts
- ui/layouts/grid-layout/grid-layout.ios.ts
> Fixed bug in GridLayout

- apps/tests/layouts/grid-layout-tests.ts
- ui/layouts/absolute-layout/absolute-layout-common.ts
- ui/layouts/absolute-layout/absolute-layout.android.ts
- ui/layouts/absolute-layout/absolute-layout.d.ts
- ui/layouts/absolute-layout/absolute-layout.ios.ts
- ui/layouts/dock-layout/dock-layout-common.ts
- ui/layouts/dock-layout/dock-layout.android.ts
- ui/layouts/dock-layout/dock-layout.d.ts
- ui/layouts/dock-layout/dock-layout.ios.ts
- ui/layouts/grid-layout/grid-layout-common.ts
- ui/layouts/grid-layout/grid-layout.android.ts
- ui/layouts/grid-layout/grid-layout.d.ts
- ui/layouts/grid-layout/grid-layout.ios.ts
- ui/layouts/stack-layout/stack-layout-common.ts
- ui/layouts/stack-layout/stack-layout.android.ts
- ui/layouts/stack-layout/stack-layout.d.ts
- ui/layouts/stack-layout/stack-layout.ios.ts
- ui/layouts/wrap-layout/wrap-layout-common.ts
- ui/layouts/wrap-layout/wrap-layout.android.ts
- ui/layouts/wrap-layout/wrap-layout.d.ts
- ui/layouts/wrap-layout/wrap-layout.ios.ts
Added test.
Improved code readability.
> GridLayout now calls virtual methods when rows/columns are set in XML.

- package.json
> Set version to 1.5.2

- apps/tests/http-tests.ts
- http/http-request.android.ts
- http/http-request.ios.ts
- http/http.d.ts
- http/http.ts
Related to https://github.com/NativeScript/NativeScript/issues/585
> file download implemented

- CrossPlatformModules.csproj
- apps/ui-tests-app/css/tab-view.xml
- apps/ui-tests-app/css/text.css
- ui/tab-view/tab-view.ios.ts
> wrong for loop count fixed

- http/http-request.android.ts
- http/http-request.ios.ts
Related to https://github.com/NativeScript/NativeScript/issues/1463
> Fix for failed url encoding techniques removed

- apps/tests/xhr-tests.ts
- gruntfile.js
- xhr/xhr.ts
- Part of the XMLHttpRequest level 2 API.
- Fixes a crash with the Angular2 Http service.
> Detect JSON response in XHR and auto-parse the response.

- CrossPlatformModules.csproj
- application/application.android.ts
- application/application.d.ts
- application/application.ios.ts
- apps/custom-root-view/app.ts
- apps/custom-root-view/list-view.xml
- apps/custom-root-view/main-page.css
- apps/custom-root-view/main-page.xml
- apps/custom-root-view/package.json
- tsconfig.json
- ui/core/view.android.ts
- ui/frame/frame.android.ts
- ui/frame/frame.d.ts
- ui/tab-view/tab-view.android.ts
Fixed TabView to use _nativeView instead of Frame.
Added an option to change the rootView.
> Fixed crash where activity was incorrectly using existing initialized frame.

- apps/ui-tests-app/css/background.xml
- ui/styling/background.android.ts
Degraded after adding antialiasing to the rounded corners drawing.
> Fix android corner radius in cases when the radius is less than half the border width

- application/application.ios.ts
- apps/animations/opacity.ts
- apps/perf-tests/NavigationTest/list-picker-page.ts
- package.json
Fix the unused variables it detected before dying with a stack overflow.
> Upgrade tslint

- package.json
To be merged after creating release branches of:
https://github.com/NativeScript/android-widgets
https://github.com/NativeScript/ios-runtime
https://github.com/NativeScript/android-runtime
> Update package.json for 1.6.0

- apps/tests/ui/label/label-tests.ts
- ui/text-base/text-base.ts
> Fixed null and undefined as Label text

- file-system/file-system-access.android.ts
> File exists fixed

- ui/page/page.ios.ts
> present and dismiss modal animated

- apps/tests/ui/action-bar/action-bar-tests-common.ts
- ui/frame/frame.android.ts
- ui/styling/style.ts
> Fix: background properties not respected with remote background image

- module.d.ts
> Fix a weird compile error happening on Jenkins runners.

- declarations.d.ts
- globals/globals.ts
> Experimental decorator added

- CrossPlatformModules.csproj
- apps/tests/ui/action-bar/action-bar-tests-common.ts
- apps/ui-tests-app/action-bar/action-view.ts
- apps/ui-tests-app/action-bar/action-view.xml
- apps/ui-tests-app/mainPage.ts
- tsconfig.json
- ui/action-bar/action-bar-common.ts
- ui/action-bar/action-bar.android.ts
- ui/action-bar/action-bar.d.ts
- ui/action-bar/action-bar.ios.ts
> Action item custom view

- application/application.android.ts
- utils/utils.android.ts
> Android app initialization error handling improved

- apps/tests/file-system-access-tests/file-system-access-tests.ts
- file-system/file-system-access.android.ts
- file-system/file-system-access.ios.ts
> File.exists() code reverted

- apps/tests/ui/text-field/text-field-tests.ts
- apps/tests/ui/text-view/text-view-tests.ts
- ui/editable-text-base/editable-text-base.android.ts
- ui/text-view/text-view.ios.ts
> TextView and TextField shows null and undefined

- xhr/xhr.ts
> FIX: XHR json response sometimes is not parsed.

- apps/modal-views-demo/main-page.ts
- ui/frame/frame.android.ts
- ui/frame/frame.ios.ts
- ui/list-view/list-view.android.ts
- ui/scroll-view/scroll-view.android.ts
- ui/tab-view/tab-view.android.ts
Fixed after application suspend/resume the UI was not restored.
Fixed modal-views page
> Fixed jumpy navigation between pages in iOS.

- application-settings/application-settings.android.ts
- application-settings/application-settings.d.ts
- application-settings/application-settings.ios.ts
- apps/tests/application-settings-tests.ts
> clear() method added

- ui/dialogs/dialogs.android.ts
> 1631|fix(dialogs): change alert dialog context

- camera/camera.android.ts
> fixed image rotation

- package.json
Now depending on tns-core-modules-widgets@1.6.1
> Upgrade dependencies versions

- CrossPlatformModules.csproj
- application/application.android.ts
- application/application.d.ts
- declarations.d.ts
- globals/globals.ts
- ui/frame/frame.android.ts
- ui/frame/frame.d.ts
> Add support for custom activity

- apps/tests/http-tests.ts
- http/http-request.android.ts
- http/http-request.ios.ts
- http/http.d.ts
- http/http.ts
> Allow multiple headers with the same name to be retrieved from a HTTP response

- ui/editable-text-base/editable-text-base.android.ts
> TextField returnPress event will be raised if event KeyCode is ENTER

- apps/tests/xml-declaration/xml-declaration-tests.ts
- ui/builder/builder.ts
> Code file exports fixed

- ui/action-bar/action-bar.android.ts
> Action bar safety checks in property changed events

- data/observable/observable.d.ts
Dear friend, we, the rest of the NativeScript community thank you for your
contribution! Because we want to present a really nice, readable changelog with each
release, please provide the following information:
Please, ensure your title is less than 50 characters and starts with a capital
letter. We strive to follow the guidelines in the
[How to Write a Git Commit Message] (http://chris.beams.io/posts/git-commit/)
article for PR titles.
If not, why?
If not, please tell us why tests are not included, and list all steps needed to test your pull request manually.
> Minor spelling correction

- apps/tests/ui/web-view/web-view-tests.ts
- ios.d.ts
- ui/web-view/web-view-common.ts
- ui/web-view/web-view.android.ts
- ui/web-view/web-view.d.ts
- ui/web-view/web-view.ios.ts
> Added Support for WebView Navigation Types

- gruntfile.js
> Exclude generated d.ts files from initial file list generation.

- apps/tests/xhr-tests.ts
- xhr/xhr.ts
> null ref fixed

- apps/tests/ui/style/style-tests.ts
- ui/builder/component-builder.ts
- ui/styling/css-selector.ts
- utils/utils-common.ts
- utils/utils.d.ts
> Plain component properties now can be applied from CSS

- apps/tests/color-tests.ts
- color/color-common.ts
> rgb() and rgba() support added

- ui/text-field/text-field.ios.ts
> Fix NSRangeException when typing in a TextField with formatted text

- apps/tests/ui/button/button-tests.ts
- apps/tests/ui/text-field/text-field-tests.ts
- apps/tests/xml-declaration/xml-declaration-tests.ts
- ui/button/button-common.ts
- ui/button/button.android.ts
- ui/button/button.ios.ts
- ui/text-base/text-base-common.ts
- ui/text-base/text-base.android.ts
- ui/text-base/text-base.ios.ts
> Update TextBase/Button `text` property when `formattedText` changes

- apps/tests/ui/list-view/list-view-tests.ts
Fixed https://github.com/NativeScript/docs/issues/277
> separatorColor snippet added

- apps/tests/ui/view/view-tests-common.ts
- ui/core/view-common.ts
- ui/core/view.android.ts
- ui/core/view.d.ts
- ui/core/view.ios.ts
> Add public instance methods to View for getting locations and size

- ui/editable-text-base/editable-text-base.android.ts
> return press fixed

- ui/layouts/layout-base.d.ts
- ui/layouts/layout-base.ts
> Add `LayoutBase.clipToBounds` property

- ui/layouts/layout-base.ts
> Add onSetNativeValue callback for clipToBounds

- ui/layouts/layout-base.ts
> Fix onClipToBoundsChanged implementation

- apps/tests/ui/animation/animation-tests.ts
- ui/animation/animation-common.ts
> Animation error handing improved

- image-source/image-source.ios.ts
> Attempt to load at least jpg images for versions lower than 9

- http/http-request.ios.ts
> Attempt to read headers with duplicate keys using different approach

- CrossPlatformModules.csproj
- ios.d.ts
- trace/trace.d.ts
- trace/trace.ts
- tsconfig.json
- ui/frame/frame-common.ts
- ui/frame/frame.ios.ts
- ui/page/page.ios.ts
- ui/transition/fade-transition.d.ts
- ui/transition/slide-transition.d.ts
- ui/transition/transition.d.ts
- ui/transition/transition.ios.ts
Fixes https://github.com/NativeScript/NativeScript/issues/1776
No. It needs external test because I'm not able to simulate Back swipe gesture in code.
> Fix swipe-back in iOS

- apps/ui-tests-app/css/decoration-transform-formattedtext.xml
- ui/button/button.android.ts
> TransformationMethod set to null in order to apply formattedText

- application/application.android.ts
Fixes/Implements #1820 .
It can't have unit tests, since it involves sending the app to the background and starting multiple activities.
> Resumed activities should be marked as foreground

- platform/platform.android.ts
- platform/platform.d.ts
- platform/platform.ios.ts
Refactored `platform` module structure. Introduced `Screen` and `Device` interfaces.
Now the module export instance of these interfaces instead of classes with static methods.
> Platform module refactoring

- apps/ui-tests-app/css/letter-spacing.xml
- ui/button/button.ios.ts
- ui/styling/converters.ts
- ui/styling/style.d.ts
- ui/styling/style.ts
- ui/styling/styling.d.ts
- ui/text-base/text-base-styler.android.ts
- ui/text-base/text-base-styler.ios.ts
- utils/utils.d.ts
- utils/utils.ios.ts
> Letter spacing CSS support added

- apps/ui-tests-app/css/listview.ts
- apps/ui-tests-app/css/listview.xml
- ui/text-base/text-base-common.ts
> Text transform and decoration updated on binding context changed

- image-source/image-source.android.ts
Dear friend, we, the rest of the NativeScript community thank you for your
contribution! Because we want to present a really nice, readable changelog with each
release, please provide the following information:
Please, ensure your title is less than 50 characters and starts with a capital
letter. We strive to follow the guidelines in the
[How to Write a Git Commit Message] (http://chris.beams.io/posts/git-commit/)
article for PR titles.
If not, why?
If not, please tell us why tests are not included, and list all steps needed to test your pull request manually.
> Fixed typo in ImageSource function: getTargetFromat -> getTargetFormat

- application/application.d.ts
- apps/tests/ui/date-picker/date-picker-tests.ts
Fix for some failing tests for DatePicker control.
> DatePicker tests fix.

- apps/tests/ui-test.ts
- apps/tests/ui/bindable-tests.ts
- trace/trace.ts
- ui/core/bindable.ts
- utils/utils.android.ts
- utils/utils.ios.ts
All error messages (traced with type as error) will be printed on all trace writers (console is the default one).
> Better tracing (logging) of run-time errors.

- .travis.yml
Related to #1599 
No tests, the build either gets run in travis or not.
> Build the declarations in travis

- application/application-common.ts
- application/application.d.ts
- ui/styling/style-scope.d.ts
- ui/styling/style-scope.ts
> Fixed: CSS animations from the application-wide .css file do not aply

- ui/animation/animation.ios.ts
- ui/animation/keyframe-animation.d.ts
- ui/animation/keyframe-animation.ts
- ui/core/view-common.ts
- ui/core/view.d.ts
- ui/styling/css-selector.ts
- ui/styling/visual-state.ts
> Fixed: Visual states not working properly when the animation is canceled

- ui/button/button.android.ts
- ui/text-base/text-base-styler.android.ts
> Style properties are now applied on Buttons

- apps/ui-tests-app/css/text-decoration.ts
- apps/ui-tests-app/css/text-decoration.xml
- apps/ui-tests-app/css/text-transform.ts
- apps/ui-tests-app/css/text-transform.xml
- ui/button/button-common.ts
- ui/text-base/text-base-common.ts
- ui/text-field/text-field.ios.ts
- ui/text-view/text-view.ios.ts
> TextBase and Button text-decoration and text-transform fixes

- ui/page/page.ios.ts
> Modal pages fixed for iOS7

- ui/animation/animation.android.ts
- ui/styling/css-selector.ts
> Fixed: There is a crash when executing animations in Android too fast

- apps/tests/TKUnit.ts
- apps/tests/frame-tests.ts
- apps/tests/navigation/navigation-tests.ts
- apps/tests/navigation/transition-tests.ts
- apps/tests/testRunner.ts
- apps/tests/ui-test.ts
- apps/tests/ui/action-bar/action-bar-tests-common.ts
- apps/tests/ui/action-bar/action-bar-tests.android.ts
- apps/tests/ui/action-bar/action-bar-tests.ios.ts
- apps/tests/ui/animation/animation-tests.ts
- apps/tests/ui/animation/css-animation-tests.ts
- apps/tests/ui/bindable-tests.ts
- apps/tests/ui/binding-expressions-tests.ts
- apps/tests/ui/helper.ts
- apps/tests/ui/html-view/html-view-tests.ts
- apps/tests/ui/list-picker/list-picker-tests.ts
- apps/tests/ui/page/page-tests-common.ts
- apps/tests/ui/page/page-tests.android.ts
- apps/tests/ui/page/page-tests.ios.ts
- apps/tests/ui/scroll-view/scroll-view-tests.ts
- apps/tests/ui/style/style-properties-tests.ts
- apps/tests/ui/style/style-tests.ts
- apps/tests/ui/style/value-source-tests.ts
- apps/tests/ui/tab-view/tab-view-navigation-tests.ts
- apps/tests/ui/view/view-tests-common.ts
- apps/tests/ui/view/view-tests.android.ts
- apps/tests/ui/view/view-tests.ios.ts
- apps/tests/xml-declaration/xml-declaration-tests.ts
- ui/styling/style-scope.ts
Faster and more reliable unit-tests
> Improve unit-tests

- apps/ui-tests-app/time-picker/time-picker.xml
- ui/time-picker/time-picker.android.ts
> valid time used instead

- ui/animation/animation.ios.ts
> Fixed: animation play count is wrong in iOS

- apps/ui-tests-app/tab-view/nowrap.xml
- ui/segmented-bar/segmented-bar.android.ts
> SegmentedBar item titles wrapping fixed. Now similar to iOS.

- .travis.yml
- apps/tests/testRunner.ts
- build/travis-scripts/check-testrun-broken.js
Related to the builds, running on Travis-CI
Related to #1930 #1943 
No unit tests for the Travis builds themselves. This is a build, running the tests.
**Details**
Increase the timeouts of the failing webview tests
Account for fractions in time taken (run result checker)
Specify a skin to improve grid calculations
> Fix the tests failing on an Arm device

- ui/editable-text-base/editable-text-base.android.ts
> Fix: editable not working when keyboardType is set

- CrossPlatformModules.csproj
- apps/tests/app/mainPage.ts
- apps/tests/observable-tests.ts
- apps/tests/testRunner.ts
- apps/tests/timer-tests.ts
- apps/tests/ui/activity-indicator/activity-indicator-tests.ts
- apps/tests/ui/animation/animation-tests.ts
- apps/tests/ui/animation/css-animation-tests.ts
- apps/tests/ui/bindable-tests.ts
- apps/tests/ui/helper.ts
- apps/tests/ui/page/page-tests-common.ts
- apps/tests/ui/page/page-tests.ios.ts
- apps/tests/ui/repeater/repeater-tests.ts
- apps/tests/ui/tab-view/tab-view-navigation-tests.ts
- apps/tests/ui/view/view-tests-common.ts
- apps/tests/weak-event-listener-tests.ts
- apps/tests/xml-declaration/xml-declaration-tests.ts
- timer/timer.ios.ts
- ui/core/view.d.ts
- ui/page/page.d.ts
- ui/page/page.ios.ts
Fixed showModal for iOS7 with animation.
> Fixed some slow tests.

- .travis.yml
Related to #1930 and #1943 
No unit tests, PR is itself a build, running the tests.
**Details**
Update the API key
Improve the formatting of the .travis file
> Fix the deployment to npm

- ui/segmented-bar/segmented-bar-common.ts
Fix for some tslint errors from my previous commit.
> Tslint error fix.

- apps/sample-fonts/main-page.ts
- apps/sample-fonts/main-page.xml
- ui/enums/enums.d.ts
- ui/enums/enums.ts
- ui/styling/font-common.ts
- ui/styling/font.android.ts
- ui/styling/font.ios.ts
- ui/styling/style.ts
> Add support for CSS font-weight + sample app for testing fonts

- xhr/xhr.ts
Related to NativeScript/nativescript-angular#89
> Attach toString() method to xhr response

- ui/animation/keyframe-animation.ts
> Fixed: There is a crash in Android when running animations too fast

- apps/tests/ui/text-field/text-field-tests.ts
- text/formatted-string.android.ts
- text/formatted-string.ios.ts
- ui/editable-text-base/editable-text-base.android.ts
- ui/text-base/text-base.android.ts
- ui/text-base/text-base.ios.ts
- utils/types.d.ts
- utils/types.ts
Resolves NativeScript/nativescript-angular#180
> Fix: setting text in Span to number/null/undefined

- apps/ui-tests-app/css/zindex.xml
- ui/core/view.android.ts
- ui/core/view.ios.ts
- ui/styling/converters.ts
- ui/styling/style.d.ts
- ui/styling/style.ts
> z-index support added

- apps/tests/ui/bindable-tests.ts
- ui/core/bindable.ts
Fix for using same name properties in binding.
> Fix for using same name properties in binding.

- apps/perf-tests/nav-page.ts
- apps/tests/navigation/navigation-tests.ts
- ui/frame/frame.android.ts
- ui/transition/transition.android.ts
- ui/transition/transition.d.ts
> Fix: Android pages disappear before their exit transition has finished

- apps/modal-views-demo/login-page.ts
- apps/modal-views-demo/login-page.xml
- ui/dialogs/dialogs.ios.ts
> Fixed: Unable to show dialog from a modal page

- ui/action-bar/action-bar.android.ts
> Fix: Multiple actionView items do not handle tap event correctly

- ui/activity-indicator/activity-indicator.ios.ts
> Fixed: iOS ActivityIndicator disrespects its visibility property

- CrossPlatformModules.csproj
- apps/ui-tests-app/mainPage.ts
- apps/ui-tests-app/padding/padding.css
- apps/ui-tests-app/padding/padding.xml
- ui/text-view/text-view.ios.ts
> Fixed: Unable to set padding for TextView

- apps/tests/timer-tests.ts
- timer/timer.ios.ts
Fix for crashing timer in IOS
Ping @hshristov  @tjvantoll
> Fix: Timer somtimes crashing in IOS

- apps/tests/ui/bindable-tests.ts
- ui/core/bindable.ts
This commit fixes an issue with crashing `cuteness`.
> Fixed stack overflow exception in binding.

- ui/activity-indicator/activity-indicator.ios.ts
This reverts commit e2692253362a5dae69aae8b32f7810a042710c34.
> Revert "Fixed: iOS ActivityIndicator disrespects its visibility

- apps/tests/ui/bindable-tests.ts
- ui/core/bindable.ts
Additional fix for changing binding context issue.
> Additional fix for changing binding context issue.

- ui/web-view/web-view.android.ts
> Fixed: WebView still visible in chrome://inspect after page is destroyed

- ui/package.json
This breaks bundling for #1563
> Delete missing main module in ui/package.json

- gruntfile.js
No related issue, this is a small refactoring only.
No tests, the change is in the build script itself.
> Remove redundant comments from the gruntfile

- globals/globals.ts
> Add __extends in case it's missing

- application/application.ios.ts
> Fix: Cannot change the iOS status bar text color

- apps/tests/ui/bindable-tests.ts
- ui/core/bindable.ts
Fixed issue with simple object as binding context.
> Fixed issue with simple object as binding context.

- apps/tests/xml-declaration/xml-declaration-tests.ts
- build/run-testsapp.grunt.js
- ui/builder/builder.d.ts
- ui/builder/builder.ts
- ui/builder/component-builder.d.ts
- ui/builder/component-builder.ts
- ui/builder/special-properties.d.ts
- ui/builder/special-properties.ts
- utils/utils-common.ts
- utils/utils.d.ts
> Expose configurable attributes property when loading components

- apps/tests/ui/switch/switch.md
> Spell mistake on Docs isEanbled to isEnabled

- apps/tests/camera-tests.ts
- apps/tests/camera.md
- camera/Readme.md
- camera/camera.android.ts
- camera/camera.d.ts
- camera/camera.ios.ts
Nope
If not, why?
If not, please tell us why tests are not included, and list all steps needed to test your pull request manually.
I updated the camera-tests.ts
> Add Method to see if camera is available

- camera/Readme.md
- camera/camera-common.ts
- camera/camera.android.ts
- camera/camera.d.ts
- camera/camera.ios.ts
Generally reverted some breaking change from a previous commit with some other adjustments like returning scaled image for all cases (saveToGallery and not). Also changed all vars to lets.
> Fixed breaking change in camera for android.

- ui/action-bar/action-bar.ios.ts
> Fixed: App crashes when animating ActionBar

- apps/tests/ui/page/page-tests.ios.ts
- ui/frame/frame-common.ts
- ui/frame/frame.d.ts
- ui/page/page-common.ts
- ui/page/page.ios.ts
Fix for https://github.com/NativeScript/NativeScript/issues/2076
> Fix iOS corrupted navigation stack

- ui/gestures/gestures.android.ts
Extended PR #2114 related to Issue #2113
> The original josh use get raw x y instead of get x y to allow smoother panning coordinates

- apps/ui-tests-app/css/clip-path.xml
- apps/ui-tests-app/css/zindex.xml
- apps/ui-tests-app/mainPage.ts
- apps/ui-tests-app/padding/padding.xml
- apps/ui-tests-app/time-picker/time-picker.xml
> Update test pages

- apps/tests/application-tests.ios.ts
Related to https://github.com/NativeScript/docs/issues/367
> iOS App delegate example added

- ui/styling/styling.d.ts
> zIndex added

- apps/ui-tests-app/mainPage.ts
- apps/ui-tests-app/pages/pan-event.ts
- apps/ui-tests-app/pages/pan-event.xml
> Add pan event test page

- CHANGELOG.md
CHANGELOG text styling improvements done by @erikruth in the docs repo applied to the origin of the article.
No tests, textual content improvements only.
> Apply changelog styling changes by Erik

- tests/app/navigation/navigation-tests.ts
- tests/app/navigation/transition-tests.ts
- tests/app/ui/helper.ts
- tests/app/ui/list-view/list-view-tests.ts
- tests/app/ui/page/page-tests-common.ts
- tests/app/ui/page/page-tests.android.ts
- tests/app/ui/page/page-tests.ios.ts
- tns-core-modules/ui/frame/frame.android.ts
Unit tests re-factoring and improvements
> Fixed test_NavigateToNewPage_WithAndroidCache failure on API 17

- tns-core-modules/application/application-common.ts
- tns-core-modules/application/application.android.ts
- tns-core-modules/application/application.ios.ts
Related to NativeScript/nativescript-cli#1777
> LiveSync improved

- tsconfig.json
> Include pan-event.ts test page in tsconfig.json

- tests/app/App_Resources/Android/AndroidManifest.xml
- tests/app/ui/view/view-tests.android.ts
- tns-core-modules/ui/styling/background.android.ts
- tns-core-modules/ui/styling/style.ts
> Fixed:  Android layerType should not be changed if there is no need

- tns-core-modules/ui/frame/frame.android.ts
This should fix the problem with gong back to the main page in cuteness.io
Related to #1948
> Fixed a problem with going back with cachePagesOnNavigate

- tns-core-modules/ui/frame/frame-common.ts
Related to https://github.com/NativeScript/nativescript-cli/issues/1481
> Close current modal page on livesync

- tns-core-modules/ui/animation/animation.android.ts
- tns-core-modules/ui/styling/background.android.ts
- tns-core-modules/utils/utils.d.ts
> Enable hardware acceleration for views animations in Android

- tns-core-modules/ui/frame/frame-common.ts
- tns-core-modules/ui/frame/frame.android.ts
- tns-core-modules/ui/transition/slide-transition.android.ts
- tns-core-modules/ui/transition/transition.android.ts
- tns-core-modules/ui/transition/transition.d.ts
> Fixed: The exit transition of the current page is not played

- tns-core-modules/ui/frame/frame.android.ts
- tns-core-modules/ui/transition/transition.android.ts
> More transition fixes and optimizations

- tests/app/ui/label/label-tests.ts
- tns-core-modules/ui/label/label.ios.ts
- tns-core-modules/ui/text-base/text-base-common.ts
- tns-core-modules/ui/text-base/text-base.d.ts
- tns-core-modules/ui/text-base/text-base.ios.ts
This is related to the list view speed improvement in the QSF.
> Layout will not requestLayout when its text is changed if it has fixed size

- tests/app/ui/dependency-observable-tests.ts
- tests/app/ui/styling/value-source-tests.ts
- tns-core-modules/ui/core/dependency-observable.d.ts
- tns-core-modules/ui/core/dependency-observable.ts
> Undefined can be set as localValue to dependency observable

- tns-core-modules/ui/action-bar/action-bar.ios.ts
https://github.com/NativeScript/nativescript-angular/issues/121
> Fixed a crash in action bar on iOS 9.3

- gruntfile.js
- tns-core-modules/application/application.android.ts
- tns-core-modules/ui/frame/frame.android.ts
Fix android activity destroy/resume.
Fix tslint - skipped all from node_modules & platforms
> Fix android orientation exception.

- expect.exp
- tests/app/testRunner.ts
- tests/app/ui/image/image-tests.ts
- tns-core-modules/ui/image/image-common.ts
There is a test, but due to the async nature of the problem it should have quite some timeout and may not be very reliable. I've added the test but it won't be executed on builds as we need stable unit testing.
> Fix setting src on async image mismatching imageSource

- tns-core-modules/ui/frame/frame.ios.ts
- tns-core-modules/ui/transition/fade-transition.ios.ts
- tns-core-modules/ui/transition/slide-transition.ios.ts
> Fixed a visual glitch with manual iOS transitions

- tns-core-modules/org.nativescript.widgets.d.ts
- tns-core-modules/ui/label/label.ios.ts
Refactor Label class to the new use TNSLabel class.
Added definition class.
> Move UILableImpl as TNSLabel in widgets.

- tests/app/app/style_props.ts
- tests/app/ui/label/label-tests.ts
- tns-core-modules/ui/activity-indicator/activity-indicator-common.ts
- tns-core-modules/ui/activity-indicator/activity-indicator.ios.ts
- tns-core-modules/ui/button/button-common.ts
- tns-core-modules/ui/button/button.d.ts
- tns-core-modules/ui/label/label-common.ts
- tns-core-modules/ui/progress/progress-common.ts
- tns-core-modules/ui/search-bar/search-bar-common.ts
- tns-core-modules/ui/tab-view/tab-view-common.ts
- tsconfig.json
Android will invalidate itself when needed.
> AffectsLayout done only for iOS.

- gruntfile.js
- tns-core-modules/ui/activity-indicator/activity-indicator-common.ts
> Fix ts-lint error

- tns-core-modules/ui/search-bar/search-bar.ios.ts
> Fixed: SearchBar.textFieldHintColor not respected on iOS

- tests/app/ui/search-bar/search-bar-tests-native.ios.ts
- tests/app/ui/search-bar/search-bar-tests.ts
> Add unit test for SearchBar.textFieldHintColor on iOS

- tns-core-modules/debugger/webinspector.ios.ts
> TypeScript debug fixed

- tns-core-modules/ui/action-bar/action-bar.ios.ts
> Fixed: Custom ActionItem gets displaced in IOS

- tns-core-modules/ui/animation/animation.android.ts
- tns-core-modules/ui/animation/animation.ios.ts
- tns-core-modules/ui/animation/keyframe-animation.ts
- tns-core-modules/ui/core/view-common.ts
- tns-core-modules/ui/core/view.android.ts
- tns-core-modules/ui/core/view.ios.ts
- tns-core-modules/ui/styling/css-selector.ts
> Fixed: iOS CSS Animation rotate() do not reset the value after 360 degrees rotation

- tns-core-modules/ui/core/view.android.ts
> Fixed: CSS-Animation w/ iteration-count:infinite is never reset causing out of memory

- tns-core-modules/ui/animation/animation.ios.ts
> Fixed: TranslateX and Animate in iOS strange behaviour on 2.0

- tests/app/ui/button/button-tests-native.android.ts
- tests/app/ui/label/label-tests-native.android.ts
- tests/app/ui/label/label-tests.ts
- tests/app/ui/text-field/text-field-tests-native.android.ts
- tests/app/ui/text-view/text-view-tests-native.android.ts
- tests/app/ui/view/view-tests.android.ts
- tns-core-modules/org.nativescript.widgets.d.ts
- tns-core-modules/ui/styling/background.android.ts
> Implement the BorderDrawable class used in background.android.ts in Java

- tns-core-modules/ui/builder/builder.ts
- tns-core-modules/ui/builder/component-builder.ts
Just the most important part of PR #2357:
- Prefer registered modules in builder and component-builder.
Ping @jasssonpet
> Bundling and Snapshotting fixes

- tns-core-modules/org.nativescript.widgets.d.ts
- tns-core-modules/ui/core/view.android.ts
- tns-core-modules/ui/styling/background-common.ts
- tns-core-modules/ui/styling/background.android.ts
- tns-core-modules/ui/styling/background.d.ts
- tns-core-modules/ui/styling/style.ts
> Background performance optimizations

- tns-core-modules/ui/builder/component-builder.ts
> Use global require to avoid custom webpack resolve

- tns-core-modules/ui/core/view.android.ts
- tns-core-modules/ui/layouts/absolute-layout/absolute-layout.android.ts
- tns-core-modules/ui/layouts/dock-layout/dock-layout.android.ts
- tns-core-modules/ui/layouts/grid-layout/grid-layout.android.ts
- tns-core-modules/ui/tab-view/tab-view.android.ts
Fixes https://github.com/NativeScript/NativeScript/issues/1710
> android LayoutParams are not overridden

- tns-core-modules/ui/styling/background-common.ts
- tns-core-modules/ui/styling/background.android.ts
- tns-core-modules/ui/styling/style.ts
> Fix: background-repeat is not respected

- tns-core-modules/ui/scroll-view/scroll-view.android.ts
> Fix: Multiple ScrollViews on one page fires scrollEvent simultaneously

- tests/app/data/observable-array-tests.ts
- tests/app/platform-tests.ts
- tests/app/ui/activity-indicator/activity-indicator-tests.ts
- tests/app/ui/border/border-tests.ts
- tests/app/ui/dialogs/dialog-tests.ts
- tests/app/ui/list-view/list-view-tests.ts
- tests/app/ui/page/page.md
- tests/app/ui/placeholder/placeholder-tests.ts
- tests/app/ui/progress/progress-tests.ts
- tests/app/ui/repeater/repeater-tests.ts
- tests/app/ui/scroll-view/scroll-view-tests.ts
- tests/app/ui/search-bar/search-bar-tests.ts
- tests/app/ui/slider/slider-tests.ts
It was breaking the snippet extraction regexes.
> Remove unicode nonbreaking whitespace in snippet declarations.

- tns-core-modules/declarations.android.d.ts
- tns-core-modules/ui/image-cache/image-cache.android.ts
Depends on https://github.com/NativeScript/tns-core-modules-widgets/pull/43
> Reflects some refactoring in the widgest for Android.

- apps/tsconfig.json
> Change apps tsconfig.json noImplicitAny to false

- apps/app/ui-tests-app/main-page-view-model.ts
- apps/app/ui-tests-app/mainPage.ts
> Remove some unnecessary variables

- tns-core-modules/ui/action-bar/action-bar.android.ts
ActionBar's Title is not updated when bound and bindingContext is set in OnLoaded event.
> fix: ActionBar's title not updating in OnLoaded event

- tns-core-modules/ui/page/page-common.ts
- tns-core-modules/ui/styling/css-selector.ts
- tns-core-modules/ui/styling/style.ts
> Unregister animations only once - on reset css

- tests/app/ui/layouts/grid-layout-tests.ts
- tests/app/ui/page/page-tests-common.ts
- tests/package.json
- tns-core-modules/ui/page/page-common.ts
> Fix: Set the binding context of a page automatically when navigated to.

- tests/app/ui/bindable-tests.ts
- tns-core-modules/data/observable/observable.ts
> Creating observables from a nested json.

- apps/app/ui-tests-app/css/tab-view-more.xml
- apps/app/ui-tests-app/tab-view/main-page.ts
> Update main-Page.ts and tab-view-more.xml css

- apps/tsconfig.json
- tests/app/file-system-tests.ts
- tests/tsconfig.json
- tns-core-modules/file-system/file-system-access.ios.ts
- tns-core-modules/file-system/file-system.d.ts
- tns-core-modules/file-system/file-system.ts
- tsconfig.json
> Add iOS-specific known folders to fs.knownFolders

- tests/app/navigation/navigation-tests.ts
- tns-core-modules/ui/frame/frame.ios.ts
- tns-core-modules/ui/page/page.ios.ts
FIX: isBackNavigation wrong when navigation away form page that is not backstack visible
> FIX: isBackNavigation wrong parameter 

- apps/app/ui-tests-app/css/label-background-image.css
- apps/app/ui-tests-app/css/label-background-image.xml
- apps/app/ui-tests-app/css/main-page.ts
- apps/app/ui-tests-app/web-view/web-view-test.xml
- apps/package.json
- tns-core-modules/ui/styling/background.ios.ts
> Fix: CSS background-image on Label not loading in iOS

- tns-core-modules/utils/types.d.ts
- tns-core-modules/utils/types.ts
- tns-core-modules/xhr/xhr.ts
Resolves  NativeScript/nativescript-angular#352
> Add toString() method on response with type is text

- tests/app/ui/tab-view/tab-view-tests.ts
- tests/app/ui/tab-view/tab-view.md
> Added documentation for selectedIndexChanged event.

- tns-core-modules/camera/Readme.md
There is no issue open for this.
Documentation, so no tests required.
> Simple typo fix in the camera module Readme.md

- README.md
> README updated with NPM stats

- .github/PULL_REQUEST_TEMPLATE.md
Makes the PR template shorter and easier for understanding.
> Improve the pull request template wording

- apps/app/ui-tests-app/css/letter-spacing.xml
- apps/app/ui-tests-app/mainPage.ts
- tests/app/ui/button/button-tests.ts
- tests/app/ui/label/label-tests.ts
- tests/app/ui/text-field/text-field-tests.ts
- tests/app/ui/text-view/text-view-tests.ts
- tns-core-modules/ui/button/button.ios.ts
- tns-core-modules/ui/styling/styling.d.ts
- tns-core-modules/ui/text-base/text-base-styler.android.ts
- tns-core-modules/ui/text-base/text-base-styler.ios.ts
> Letter spacing in EM units

- package.json
- tests/app/ui/button/button-tests.ts
- tests/app/ui/label/label-tests.ts
- tests/app/ui/text-field/text-field-tests.ts
- tests/app/ui/text-view/text-view-tests.ts
- tns-core-modules/ui/button/button.android.ts
- tns-core-modules/ui/text-base/text-base-styler.android.ts
LetterSpacing handlers are added for iOS and Android API 21+
> Fix unit-tests checks.

- tns-core-modules/application/application-common.ts
https://github.com/NativeScript/nativescript-cli/issues/1958
ping @vakrilov , @hshristov
> Fixed: CSS is not automatically livesynced in angular apps

- tns-core-modules/ui/button/button.android.ts
- tns-core-modules/ui/text-base/text-base-common.ts
> fix snapshot

- tns-core-modules/ui/core/view.android.ts
> z-index handler added only for API 21+

- tests/app/data/observable-tests.ts
- tests/app/ui/bindable-tests.ts
- tns-core-modules/data/observable/observable.d.ts
- tns-core-modules/data/observable/observable.ts
> Fixed creating Observable object from nested JSON object.

- tns-core-modules/ui/button/button.ios.ts
1. Create a new {N} project.
2. On a button click add a new button
3. On a second button click, remove the button
4. Run and test the app
#2599
> Fixed: There is an exception when removing a button

- tests/app/xhr-tests.ts
- tns-core-modules/xhr/xhr.ts
> Parse XHR response content type with +json as JSON

- tests/app/location-tests.ts
> Location test fixed.

- tns-core-modules/ui/button/button.ios.ts
> Fix: Button with text-decoration can't change text

- tests/app/ui/text-field/text-field-tests-native.android.ts
- tests/app/ui/text-field/text-field-tests-native.d.ts
- tests/app/ui/text-field/text-field-tests-native.ios.ts
- tests/app/ui/text-field/text-field-tests.ts
- tns-core-modules/ui/styling/style.d.ts
- tns-core-modules/ui/styling/style.ts
- tns-core-modules/ui/styling/styling.d.ts
- tns-core-modules/ui/styling/styling.ts
- tns-core-modules/ui/text-base/text-base-styler.android.ts
- tns-core-modules/ui/text-field/text-field.ios.ts
> Add placeholder-color style property.

- apps/app/ui-tests-app/css/zindex.xml
Remove `color: black; ` of the image as tint color is now supported.
> Update an ui-tests-app test page

- tests/.vscode/launch.json
- tests/app/ui/image/image-tests.ts
> Added unit test that tests tintColor in Image class

- apps/app/ui-tests-app/mainPage.xml
> Update automationText of run button

- tns-core-modules/ui/animation/animation.ios.ts
> Fixed regression issue: rotate() doesn't reset after 360 degrees rotation

- tns-core-modules/debugger/webinspector.ios.ts
Fix for https://github.com/NativeScript/NativeScript/issues/2742
> utils.ios should not be required in webinspector

- tns-core-modules/ui/styling/background.android.ts
> Prevent padding from accumulating

- tests/app/ui/html-view/html-view.md
No issue, fixing breaking URLs in the documentation.
> Fix a broken url, add a redirect to save other breakages

- tests/app/ui/view/view-tests-common.ts
- tns-core-modules/ui/core/view.android.ts
> number now can be set as id in android

- tns-core-modules/http/http-request.ios.ts
> Correct device in user agent

- apps/app/ui-tests-app/css/all-non-uniform-border.css
- apps/app/ui-tests-app/css/all-non-uniform-border.xml
- apps/app/ui-tests-app/css/all-uniform-border.css
- apps/app/ui-tests-app/css/all-uniform-border.xml
- apps/app/ui-tests-app/css/main-page.ts
- tns-core-modules/ui/progress/progress.android.ts
- tns-core-modules/ui/progress/progress.ios.ts
- tns-core-modules/ui/search-bar/search-bar.android.ts
- tns-core-modules/ui/search-bar/search-bar.ios.ts
- tns-core-modules/ui/slider/slider.android.ts
- tns-core-modules/ui/switch/switch.android.ts
- tns-core-modules/ui/switch/switch.ios.ts
> Add two more sample pages for testing borders.

- apps/app/ui-tests-app/css/label-border.css
- tests/app/ui/styling/style-properties-tests.ts
- tns-core-modules/ui/styling/style.ts
> Fix: CSS border-color does not recognize rgb and rgba values

- tns-platform-declarations/.npmignore
> Ignore test and .tgz and package

- apps/app/ui-tests-app/css/all-non-uniform-border.css
- apps/app/ui-tests-app/css/all-uniform-border.css
- apps/app/ui-tests-app/css/all-uniform-border.xml
- tns-core-modules/ui/styling/background.ios.ts
> Fix: CSS border-width causes text to overflow TextView

- .vscode/settings.json
- apps/app/ui-tests-app/css/all-non-uniform-border.xml
- apps/app/ui-tests-app/css/all-uniform-border.xml
> Stop activity-indicator from rotating in the ui-tests

- gruntfile.js
- tns-core-modules/tns-core-modules.es2016.d.ts
- tns-platform-declarations/README.md
- tns-platform-declarations/package.json
added tns-core-modules.es2016.d.ts for declarations references
+ updated README and package.json for tns-platform-declarations
> added tns-core-modules.es2016.d.ts for declarations references

- README.md
> Added information on where to get help

- apps/app/ui-tests-app/css/all-non-uniform-border.ts
- apps/app/ui-tests-app/css/all-non-uniform-border.xml
- apps/app/ui-tests-app/css/all-uniform-border.ts
- apps/app/ui-tests-app/css/all-uniform-border.xml
- apps/app/ui-tests-app/css/text-view-border.css
- apps/app/ui-tests-app/css/text-view-border.xml
Ping @hamorphis & @SvetoslavTsenov.
> Update border test pages

- tests/app/console-tests.ts
- tests/app/data/observable-array-tests.ts
- tests/app/fetch-tests.ts
No unit tests, the change addresses snippets in the documentation, problem found in-team. A manual verification showed these pass.
> Fix some broken code snippets

- tests/app/xml-declaration/mainPage.ts
- tns-core-modules/camera/camera.android.ts
- tns-core-modules/image-asset/image-asset-common.ts
- tns-core-modules/image-asset/image-asset.android.ts
- tns-core-modules/image-asset/image-asset.d.ts
- tns-core-modules/image-asset/image-asset.ios.ts
- tns-core-modules/image-asset/package.json
- tns-core-modules/image-source/image-source-common.ts
- tns-core-modules/image-source/image-source.android.ts
- tns-core-modules/image-source/image-source.d.ts
- tns-core-modules/image-source/image-source.ios.ts
- tns-core-modules/tns-core-modules.base.d.ts
- tns-core-modules/ui/image/image-common.ts
- tns-core-modules/ui/image/image.android.ts
- tns-platform-declarations/android/org.nativescript.widgets.d.ts
Added image-asset class (which instance will be returned from nativescript-camera plugin). Also some modifications to image-source (to support image-asset) and image (rotation logic moved from camera to image (native java)).
> Refactored image loading from camera.

- tns-core-modules/image-asset/image-asset.ios.ts
> Fixed issue when asset is created with native UIImage.

- tns-core-modules/application/application.android.ts
Need to be tested by QA. Not suitable for unit test.
> Fix LaunchTheme not cleared in some cases

- apps/app/ui-tests-app/bindings/xmlbasics.xml
> Remove automationText from listview items

- tns-core-modules/ui/gestures/gestures.ios.ts
Fix https://github.com/NativeScript/NativeScript/issues/2879
> Fix gestures support for iOS 10

- tns-core-modules/ui/frame/frame.d.ts
> Small typo

- tests/app/application-tests.android.ts
- tns-core-modules/application/application.android.ts
- tns-core-modules/application/application.d.ts
- tns-core-modules/ui/dialogs/dialogs.android.ts
- tns-core-modules/ui/frame/activity.android.ts
- tns-core-modules/ui/frame/activity.d.ts
- tns-core-modules/ui/frame/frame.android.ts
Resolves #2884
cc: @NathanWalker
> Application and ActivityEvents improvements

- DevelopmentWorkflow.md
> Update the DevelopmentWorkflow.md

- tests/app/app/mainPage.ts
- tests/app/application-tests.android.ts
- tns-core-modules/application/application.android.ts
- tns-core-modules/ui/frame/activity.android.ts
- tns-core-modules/ui/frame/activity.d.ts
Fixes the snapshot build after #2885
> Snapshot fix

- apps/app/ui-tests-app/css/zindex.xml
> Update all text field of  zIndex page with autocorrect=false

- tns-core-modules/ui/core/dependency-observable.ts
> Padding was reset incorrectly

- tns-core-modules/xhr/xhr.ts
> Xhr response converted to string so Angular could use it correctly.

- tests/app/ui/list-view/list-view-tests.ts
- tests/app/ui/list-view/list-view.md
> Add ListView item template selector code snippets

- tests/app/ui/frame/frame-tests.ts
- tests/app/ui/layouts/absolute-layout-tests.ts
- tests/app/ui/layouts/common-layout-tests.ts
- tests/app/ui/layouts/dock-layout-tests.ts
- tests/app/ui/layouts/grid-layout-tests.ts
- tests/app/ui/layouts/wrap-layout-tests.ts
- tests/app/ui/page/page-tests-common.ts
- tns-core-modules/ui/content-view/content-view.ts
- tns-core-modules/ui/core/view-common.ts
- tns-core-modules/ui/core/view.d.ts
- tns-core-modules/ui/frame/frame.ios.ts
- tns-core-modules/ui/layouts/layout-base-common.ts
- tns-core-modules/ui/page/page.ios.ts
ContentView, Page and all layouts will have their margins, width and height calculated based on a value set through percent. 
For example:
StackLayout {
margin: 30% 15% 30% 15%;
}
> Support of percentage margins for certain elements

- apps/app/ui-tests-app/segmented-bar/all.xml
> Added border-related properties to SegmentedBar ui-tests example

- tests/app/ui/button/button-tests.ts
- tests/app/ui/label/label-tests.ts
- tns-core-modules/ui/button/button.ios.ts
- tns-core-modules/ui/core/view-common.ts
Disabled state is actually added to view, so it is available for all controls.
> Added pressed, active and disabled states for button.

- apps/app/ui-tests-app/flexbox/flexbox.css
- apps/app/ui-tests-app/flexbox/flexbox.ts
- apps/app/ui-tests-app/flexbox/flexbox.xml
- tests/app/ui/layouts/flexbox-layout-tests.ts
- tns-core-modules/ui/layouts/flexbox-layout/flexbox-layout-common.ts
- tns-core-modules/ui/layouts/flexbox-layout/flexbox-layout.android.ts
- tns-core-modules/ui/layouts/flexbox-layout/flexbox-layout.ios.ts
Fix the order property. Add alignSelf and flexWrapBefore properties in the ui example.
> Flexbox ui tests

- apps/app/ui-tests-app/css/main-page.ts
- apps/app/ui-tests-app/css/tab-view.ts
- apps/app/ui-tests-app/css/tab-view.xml
- tns-core-modules/ui/styling/style.d.ts
- tns-core-modules/ui/styling/style.ts
- tns-core-modules/ui/styling/styling.d.ts
- tns-core-modules/ui/tab-view/tab-view-common.ts
- tns-core-modules/ui/tab-view/tab-view.android.ts
- tns-core-modules/ui/tab-view/tab-view.d.ts
- tns-core-modules/ui/tab-view/tab-view.ios.ts
- tns-core-modules/utils/utils.android.ts
- tns-core-modules/utils/utils.d.ts
- tns-platform-declarations/android/org.nativescript.widgets.d.ts
Implements #2738
TabView {
tab-text-color: green;
tab-background-color: yellow;
selected-tab-text-color: red;
android-selected-tab-highlight-color: orange;
text-transform: uppercase;
}
> Add support for TabView CSS

- tests/app/ui/layouts/flexbox-layout-page.xml
- tests/app/ui/layouts/flexbox-layout-tests.ts
- tests/app/ui/layouts/flexbox-layout.md
Along with a how-to use in XML, fairly complex layout and a few links to flex box in general article, explained mapping between our javascript properties and the css ones.
> Add flexbox-layout md

- tns-core-modules/application/application.ios.ts
Fix wrong width of child views on iPad SplitView/SlideOver.
> iPad SplitView/SlideOver support

- apps/app/ui-tests-app/tab-view/all.xml
> Add text-color yellow in the all.xml page

- apps/app/ui-tests-app/tab-view/tab-view-css.xml
> Wrapped all buttons in ScrollView

- apps/app/ui-tests-app/issues/issue-2911.css
- apps/app/ui-tests-app/issues/issue-2911.xml
- apps/app/ui-tests-app/issues/main-page.ts
- apps/app/ui-tests-app/issues/main-page.xml
- apps/app/ui-tests-app/mainPage.ts
- tns-core-modules/ui/styling/background.ios.ts
> Fix: CSS scale breaks background properties on iOS

- apps/app/ui-tests-app/css/main-page.ts
- apps/app/ui-tests-app/css/margins-paddings-with-percentage.ts
- apps/app/ui-tests-app/css/margins-paddings-with-percentage.xml
- apps/app/ui-tests-app/tab-view/main-page.ts
> Add new test page for layouts

- tns-core-modules/application/application.android.ts
> Remove console.log() leftover

- tns-core-modules/ui/styling/style.ts
> Added support for scale(x)

- apps/app/ui-tests-app/segmented-bar/all.xml
- tns-core-modules/ui/segmented-bar/segmented-bar-common.ts
- tns-core-modules/ui/segmented-bar/segmented-bar.android.ts
- tns-core-modules/ui/segmented-bar/segmented-bar.ios.ts
- tns-core-modules/ui/styling/style.d.ts
- tns-core-modules/ui/styling/style.ts
- tns-core-modules/ui/styling/styling.d.ts
SegmentedBar selectedBackgroundColor property will be set via css like:
SegmentedBar {
selected-background-color: red;
}
> SelectedBackgroundColor property exposed via css.

- tns-core-modules/ui/segmented-bar/segmented-bar.ios.ts
> SelectedBackgroundColor set via css ios.

- tns-core-modules/ui/segmented-bar/segmented-bar.ios.ts
> Removed unused function in segmented-bar.ios.ts

- tns-core-modules/ui/image/image.android.ts
> Fixed issue with image rotation.

- tests/.vscode/settings.json
- tests/app/testRunner.ts
- tests/app/ui/image/image-tests.ts
- tns-core-modules/ui/image/image.android.ts
- tns-platform-declarations/android/org.nativescript.widgets.d.ts
This is done so that we can clean up the bitmap if imageView is removed from window and then load it again if imageView is added to window.
> Image loading is done through native imageView

- tns-core-modules/ui/styling/background.android.ts
> Fix: Enhancement: Android Actionbar elevation lost with background-color

- tests/app/xml-declaration/xml-declaration-tests.ts
- tns-core-modules/ui/builder/component-builder.ts
> Added import attribute to page module.

- tns-core-modules/ui/layouts/flexbox-layout/flexbox-layout.ios.ts
Lost in the translation from Java to TS. GJ @vchimev
> Fix flexbox crash for iOS

- apps/app/ui-tests-app/action-bar/background.xml
- tns-core-modules/ui/styling/background.android.ts
> Use setColorFilter on post-21 ActionBars only

- tests/app/file-system-access-tests/file-system-access-tests.ts
- tests/app/ui/styling/style-tests.ts
- tns-core-modules/file-system/file-system-access.android.ts
- tns-core-modules/ui/styling/style-scope.d.ts
- tns-core-modules/ui/styling/style-scope.ts
If the css sheet is not in the app directory, try to find it in the
tns_modules folder.
> Feat(style-scope): Resolve css sheets from tns_modules

- tns-core-modules/ui/date-picker/date-picker.android.ts
> Fixed DatePicker issues with date 7-th.

- package.json
- tns-core-modules/ui/layouts/flexbox-layout/flexbox-layout-common.ts
- tns-core-modules/ui/layouts/flexbox-layout/flexbox-layout.android.ts
- tns-core-modules/ui/layouts/flexbox-layout/flexbox-layout.d.ts
- tns-core-modules/ui/layouts/flexbox-layout/flexbox-layout.ios.ts
- tns-core-modules/utils/types.d.ts
- tns-core-modules/utils/types.ts
Lets properties for the FlexboxLayout to be set in CSS. Adds support for flex and flex-flow shorthands.
> Flexbox css able

- tns-core-modules/ui/page/page.ios.ts
> Fixed: jumping action bar reported in #2941

- tns-core-modules/ui/styling/style-scope.ts
> Fix(style-scope): remove isFileOrResourcePath check

- tns-core-modules/application/application.android.ts
> Foreground activity cleared on activity destroyed.

- tests/app/ui/tab-view/tab-view-tests.ts
> Delete inconsistently failing test

- tns-core-modules/connectivity/connectivity.android.ts
> Fix: connectivity module always returns undefined on android <= 4.4

- tns-core-modules/ui/segmented-bar/segmented-bar.android.ts
- tns-core-modules/ui/styling/background.android.ts
> API Level 14 Compatibility

- apps/app/ui-tests-app/issues/issue-3113.css
- apps/app/ui-tests-app/issues/issue-3113.xml
- apps/app/ui-tests-app/issues/main-page.ts
- apps/package.json
- tests/app/ui/tab-view/tab-view-tests.ts
- tests/package.json
- tns-core-modules/ui/styling/background.android.ts
> Fix: Transparent border rendered as black

- apps/app/ui-tests-app/modal-view/login-page.xml
- tns-core-modules/ui/page/page.android.ts
> Fix: Modal dialogs don't have background color

- tns-core-modules/ui/core/view.android.ts
- tns-core-modules/ui/core/view.ios.ts
> Fix: Setting automationText to a number crashes the app on Android

- tests/app/application-settings.md
updated information in section for **_setNumber_** - related to [https://github.com/NativeScript/NativeScript/issues/3109#issuecomment-261498536](https://github.com/NativeScript/NativeScript/issues/3109#issuecomment-261498536)
> updated Cookbook article application-settings

- apps/app/ui-tests-app/issues/issue-3007.xml
> Add ScrollView to issue-3007.xml page

- .gitignore
- .travis.yml
- tests/app/app/mainPage.ts
- tests/app/testRunner.ts
- tests/hooks/after-install/after-install.js
- tns-core-modules/application/application.d.ts
> Adding request for write storage permissions for tests app.

- tns-core-modules/ui/segmented-bar/segmented-bar.android.ts
> setColorFilter used if android.os.Build.VERSION.SDK_INT >= 21

- tests/app/app/mainPage.ts
- tests/app/testRunner.ts
> Fixed tests to run on iOS.

- tns-core-modules/ui/frame/frame.ios.ts
- tns-core-modules/ui/page/page.ios.ts
> Fixed: ActionBar w/translucent navigationBar set to false is creating whitish transition

- tns-core-modules/http/http-request.android.ts
- tns-core-modules/http/http-request.ios.ts
- tns-core-modules/http/http.d.ts
> GBK encoding support for http

- tns-core-modules/ui/segmented-bar/segmented-bar.android.ts
> Api 21 fix

- tns-core-modules/ui/editable-text-base/editable-text-base.android.ts
> Fix: TextView new line closes virtual keyboard on Android

- apps/app/ui-tests-app/issues/issue-3175.xml
- apps/app/ui-tests-app/issues/main-page.ts
- tests/app/ui/styling/style-properties-tests.ts
- tns-core-modules/ui/styling/style.ts
> Fix: Invalid value 500 for property fontWeight in XML

- tns-core-modules/ui/proxy-view-container/proxy-view-container.ts
Skip iterating children that are not visible
> Skip iterating children that are not visible

- tns-core-modules/image-asset/image-asset-common.ts
- tns-core-modules/image-asset/image-asset.d.ts
- tns-core-modules/image-source/image-source.ios.ts
> ImageAsset extends Observable

- tns-core-modules/ui/button/button.android.ts
This needs an automation test since it need the app to be suspended and resumed.
> Android button active state fixed to work after app suspend and resume

- tns-core-modules/application/application.ios.ts
Integration with existing iOS app
> Allow iOS app to be started multiple times

- tns-core-modules/ui/list-view/list-view-common.ts
- tns-core-modules/ui/list-view/list-view.android.ts
- tns-core-modules/ui/list-view/list-view.ios.ts
- tns-core-modules/ui/styling/style.d.ts
- tns-core-modules/ui/styling/style.ts
- tns-core-modules/ui/styling/styling.d.ts
separatorColor property can be set through CSS as follows:
ListView {
separator-color: lightskyblue;
}
> separatorColor property of ListView can be set in CSS

- tns-core-modules/platform/platform.android.ts
> Fixes the metrics issue when soft-navigation is used on a device/emulator

- tests/app/ui/list-view/list-view-tests.ts
> Removed myst ListView test for ios

- tests/app/text/formatted-string-tests.ts
- tests/app/ui/button/button-tests.ts
> Fix tsc errors

- apps/app/ui-tests-app/app.css
- apps/app/ui-tests-app/issues/component/customView.xml
- apps/app/ui-tests-app/issues/component2/customView2.xml
- apps/app/ui-tests-app/issues/component3/customView3.xml
- apps/app/ui-tests-app/issues/issue-1639.xml
- apps/app/ui-tests-app/issues/main-page.ts
- apps/package.json
> Added UI test for nested components CSS application

- tns-core-modules/application/application.ios.ts
> Fixed: XML/HTML livesync not working on iOS

- apps/package.json
- package.json
- tests/package.json
- tns-platform-declarations/package.json
> Lock all Typescript versions to ~2.0.10

- apps/app/ui-tests-app/css/text-decoration.ts
- apps/app/ui-tests-app/css/text-decoration.xml
- apps/app/ui-tests-app/css/text-transform.ts
- tns-core-modules/tns-core-modules.base.d.ts
- tns-core-modules/ui/core/view-base.ts
- tns-core-modules/ui/core/view-common.ts
- tns-core-modules/ui/core/view.d.ts
- tns-core-modules/ui/definitions.d.ts
- tns-core-modules/ui/layouts/flexbox-layout/flexbox-layout-common.ts
- tns-core-modules/ui/styling/converters.ts
- tns-core-modules/ui/styling/style.d.ts
- tns-core-modules/ui/styling/style.ts
- tns-core-modules/ui/text-base/text-base-common.ts
- tns-core-modules/ui/text-base/text-base.android.ts
- tns-core-modules/ui/text-base/text-base.d.ts
- tns-core-modules/ui/text-base/text-base.ios.ts
> Fixed: getViewById, TextDecoration

- tests/app/xml-declaration/xml-declaration-tests.ts
Added tns-core-modules to some paths - due to making tns-core-modules true npm plugin.
> Fixed tests tns-core-modules true plugin.

- tns-core-modules/ui/core/view-common.ts
- tns-core-modules/ui/styling/font-common.ts
- tns-core-modules/ui/styling/font.android.ts
- tns-core-modules/ui/styling/font.d.ts
- tns-core-modules/ui/styling/font.ios.ts
- tns-core-modules/ui/styling/style.d.ts
- tns-core-modules/ui/styling/style.ts
- tsconfig.json
> FontStyle and FontWeight enums everywhere

- tns-core-modules/ui/core/view-common.ts
- tns-core-modules/ui/core/view.d.ts
- tns-core-modules/ui/styling/background-common.ts
- tns-core-modules/ui/styling/background.d.ts
- tns-core-modules/ui/styling/style.d.ts
- tns-core-modules/ui/styling/style.ts
> BackgroundRepeat enum

- tns-core-modules/ui/activity-indicator/activity-indicator.android.ts
- tns-core-modules/ui/activity-indicator/activity-indicator.ios.ts
- tns-core-modules/ui/core/view-base.ts
- tns-core-modules/ui/core/view-common.ts
- tns-core-modules/ui/core/view.android.ts
- tns-core-modules/ui/core/view.d.ts
- tns-core-modules/ui/core/view.ios.ts
- tns-core-modules/ui/styling/converters.ts
- tns-core-modules/ui/styling/style.d.ts
- tns-core-modules/ui/styling/style.ts
> Visibility

- tns-core-modules/ui/action-bar/action-bar-common.ts
- tns-core-modules/ui/core/view-common.ts
- tns-core-modules/ui/core/view.android.ts
- tns-core-modules/ui/core/view.d.ts
- tns-core-modules/ui/enums/enums.ts
- tns-core-modules/ui/layouts/stack-layout/stack-layout.ios.ts
- tns-core-modules/ui/page/page.android.ts
- tns-core-modules/ui/styling/style.d.ts
- tns-core-modules/ui/styling/style.ts
> HorizontalAlignment and VerticalAlignment

- apps/app/ui-tests-app/font/label.ts
- apps/app/ui-tests-app/font/text-field.ts
- apps/app/ui-tests-app/font/text-view.ts
- apps/app/ui-tests-app/issues/issue-3164.ts
- apps/app/ui-tests-app/layouts-percent/myview.ts
- apps/app/ui-tests-app/layouts/myview.ts
- tns-core-modules/ui/enums/enums.d.ts
> Fixed ~60 tsc errors

- apps/app/ui-tests-app/layouts-percent/grid.ts
- apps/app/ui-tests-app/layouts/grid.ts
- apps/app/ui-tests-app/page/page-status-bar-css.ts
- apps/app/ui-tests-app/pages/pan-event.ts
- tns-core-modules/ui/layouts/grid-layout/grid-layout-common.ts
- tns-core-modules/ui/layouts/grid-layout/grid-layout.android.ts
- tns-core-modules/ui/layouts/grid-layout/grid-layout.d.ts
> GridUnitType enum + fixes

- apps/app/ui-tests-app/app.ts
- apps/app/ui-tests-app/tab-view/tab-view-icon.ts
- tns-core-modules/application/application.d.ts
> apps app can now compile

- tns-core-modules/ui/core/view-base.ts
> added class property to ViewBase

- apps/app/package.json
- tns-core-modules/ui/editable-text-base/editable-text-base.android.ts
- tns-core-modules/ui/tab-view/tab-view.android.ts
- tns-core-modules/ui/tab-view/tab-view.ios.ts
- tns-core-modules/ui/text-field/text-field-common.ts
> Comment out TabView where it does not compile

- apps/.vscode/launch.json
- apps/app/ui-tests-app/app.ts
- tns-core-modules/ui/core/view.android.ts
- tns-core-modules/ui/styling/background.android.ts
- tns-platform-declarations/android/org.nativescript.widgets.d.ts
> Fixed Android _onAttached logic. Fixes setting props in code-behind.

- tns-core-modules/ui/switch/switch-common.ts
- tns-core-modules/ui/switch/switch.android.ts
- tns-core-modules/ui/switch/switch.ios.ts
> Fixed Switch

- tns-core-modules/ui/html-view/html-view-common.ts
- tns-core-modules/ui/html-view/html-view.android.ts
- tns-core-modules/ui/html-view/html-view.ios.ts
> Fixed HtmlView

- tns-core-modules/ui/date-picker/date-picker.android.ts
> Fix DatePicker

- tns-core-modules/ui/time-picker/time-picker.android.ts
> Fix TimePicker for Android

- tns-core-modules/ui/search-bar/search-bar.android.ts
> Fix SearchBar for Android

- apps/app/ui-tests-app/css/all-uniform-border.xml
- tns-core-modules/ui/web-view/web-view-common.ts
> Fix WebView

- tns-core-modules/ui/core/properties.ts
- tns-core-modules/ui/repeater/repeater.ts
> Fix Repeater

- tests/app/testRunner.ts
- tests/app/ui/button/button-tests.ts
- tns-core-modules/ui/core/properties.ts
- tns-core-modules/ui/core/view-base.ts
- tns-core-modules/ui/core/view-common.ts
- tns-core-modules/ui/gestures/gestures.android.ts
ScrollView failed on android. We have to double check the ScrollView tests.
> Button tests now run except for those on TextBase

- tns-core-modules/ui/switch/switch.ios.ts
> Switch tests for ios.

- tests/app/ui/segmented-bar/segmented-bar-tests.ts
- tns-core-modules/ui/segmented-bar/segmented-bar-common.ts
- tns-core-modules/ui/segmented-bar/segmented-bar.android.ts
> Fix: SegmentedBar crash using a number as title

- tns-core-modules/utils/types.ts
> Fix utils/types class name resolution regex.

- tns-core-modules/ui/core/properties.ts
- tns-core-modules/ui/core/view-common.ts
- tns-core-modules/ui/core/view.d.ts
- tns-core-modules/ui/definitions.d.ts
- tns-core-modules/ui/layouts/flexbox-layout/flexbox-layout-common.ts
- tns-core-modules/ui/layouts/layout-base-common.ts
- tns-core-modules/ui/layouts/layout-base.d.ts
- tns-core-modules/ui/styling/style.d.ts
- tns-core-modules/ui/styling/style.ts
- tns-core-modules/ui/text-base/text-base-common.ts
- tns-core-modules/ui/text-base/text-base.d.ts
- tns-core-modules/ui/text-field/text-field.ios.ts
> Fix all property types

- tns-core-modules/ui/search-bar/search-bar.android.ts
- tns-core-modules/ui/segmented-bar/segmented-bar.android.ts
- tns-core-modules/ui/tab-view/tab-view.android.ts
- tns-core-modules/ui/text-base/text-base.android.ts
> Fix font on Android

- tns-core-modules/application/application-common.ts
- tns-core-modules/application/application.android.ts
- tns-core-modules/application/application.ios.ts
> Fix: application.setCssFileName does not work

- tests/app/TKUnit.ts
- tests/app/testRunner.ts
- tns-core-modules/ui/core/view-base.ts
- tns-core-modules/ui/core/view-common.ts
- tns-core-modules/ui/core/view.android.ts
- tns-core-modules/ui/layouts/flexbox-layout/flexbox-layout-common.ts
- tns-core-modules/ui/segmented-bar/segmented-bar.android.ts
- tns-core-modules/ui/tab-view/tab-view.android.ts
move some native setters from TabView to TabViewItem.
shorthand properties converters now accounts for unsetValue.
better formatting for test duration.
> clear nativeView field.

- tns-core-modules/ui/core/view-common.ts
> Fix: Resetting backgroundImage throws

- tns-core-modules/ui/core/view-common.ts
- tns-core-modules/ui/core/view.d.ts
- tns-core-modules/ui/styling/style.d.ts
- tns-core-modules/ui/styling/style.ts
> Make border radii Lengths

- tns-core-modules/ui/text-base/text-base.android.ts
> Fix: All formatted string appear with commas between each letter

- tns-core-modules/ui/styling/style-scope.ts
> Fixed style scope.

- tests/app/file-name-resolver-tests/file-name-resolver-tests.ts
- tests/app/testRunner.ts
- tests/app/ui/segmented-bar/segmented-bar-tests-native.android.ts
- tests/app/ui/segmented-bar/segmented-bar-tests.ts
- tns-core-modules/ui/core/properties.ts
- tns-core-modules/ui/segmented-bar/segmented-bar-common.ts
- tns-core-modules/ui/segmented-bar/segmented-bar.android.ts
> SegmentedBar tests fixed.

- tns-core-modules/ui/button/button.android.ts
- tns-core-modules/ui/core/view-common.ts
> Fix zIndex for Android buttons

- tests/app/xml-declaration/template-builder-tests/template-view.ts
- tns-core-modules/ui/segmented-bar/segmented-bar.android.ts
- tns-core-modules/ui/segmented-bar/segmented-bar.ios.ts
> Fixed tslint errors.

- tests/app/ui/tab-view/tab-view-tests.ts
- tests/app/xml-declaration/xml-declaration-tests.ts
- tns-core-modules/ui/text-base/text-base.android.ts
- tns-core-modules/ui/text-base/text-base.ios.ts
- tns-core-modules/ui/text-field/text-field.ios.ts
- tns-core-modules/ui/text-view/text-view.ios.ts
> Fix text & fromattedText failing tests

- apps/app/ui-tests-app/web-view/web-view-error.ts
- apps/app/ui-tests-app/web-view/web-view-error.xml
- tests/app/ui/web-view/web-view-tests.ts
Should be tested with no connection
> test moved to ui-tests-app

- apps/app/ui-tests-app/page/page-status-bar-css.xml
- tns-core-modules/ui/action-bar/action-bar.android.ts
backgroundColor property is added in the ActionBarStyler property thus allowing changing it runtime. 
The ui-test is updated so that scenarios for android only are recognized more easily.
> backgroundColor added in ActionBarStyler

- tests/app/testRunner.ts
- tns-core-modules/color/color-common.ts
- tns-core-modules/ui/styling/css-animation-parser.ts
> Fixed CSS-ANIMATION tests

- tests/app/xml-declaration/xml-declaration-tests.ts
> Require ui/label instead of tns_modules/tns-core-modules/ui/label in tests

- .travis.yml
> chore(travis): Update npm token

- .travis.yml
- apps/app/ui-tests-app/page/page-status-bar-css.xml
- build/version.js
- tns-core-modules/ui/action-bar/action-bar.android.ts
- tns-core-modules/ui/page/page.android.ts
> Status bar pick

- tns-core-modules/application/application.ios.ts
- tns-core-modules/ui/core/view.ios.ts
- tns-core-modules/ui/dialogs/dialogs.ios.ts
- tns-core-modules/ui/page/page.android.ts
- tns-core-modules/ui/page/page.ios.ts
> Fix: Modal crashes in Android and IOS

- tns-core-modules/ui/styling/style.ts
> Android: ActionBar transparent background crashes

- apps/app/ui-tests-app/action-bar/main-page.ts
- apps/app/ui-tests-app/action-bar/transparent-bg-css.css
- apps/app/ui-tests-app/action-bar/transparent-bg-css.ts
- apps/app/ui-tests-app/action-bar/transparent-bg-css.xml
> UI test: Transparent Action Bar example

- .vscode/settings.json
- tests/.vscode/launch.json
- tests/.vscode/settings.json
- tests/package.json
- tns-core-modules/ui/core/properties.ts
- tns-core-modules/ui/core/view-base.ts
- tns-core-modules/ui/definitions.d.ts
- tns-core-modules/ui/label/label.ios.ts
- tns-core-modules/ui/segmented-bar/segmented-bar.android.ts
- tns-core-modules/ui/styling/background.ios.ts
- tns-core-modules/ui/tab-view/tab-view.android.ts
- tns-core-modules/ui/text-base/text-base.ios.ts
CoercableProperty now inherits from Property
VS Code typescript sdk removed
ViewBase will no longer clear native view if recycleNativeView is false
> Improve background setter in iOS

- tns-core-modules/package.json
> Bump version to 3.0

- apps/app/App_Resources/iOS/Info.plist
- apps/app/cuteness.io/reddit-app-view-model.ts
- apps/app/cuteness.io/reddit-item-view-model.ts
- tns-core-modules/data/observable-array/observable-array.ts
- tns-core-modules/data/virtual-array/virtual-array.ts
- tns-core-modules/ui/image/image-common.ts
- tns-core-modules/ui/image/image.android.ts
- tns-core-modules/ui/list-view/list-view-common.ts
- Fix: Setting ImageSource to image.src
- Added IOS http permission for apps		
- Fix: ListView not showing first items of VirtualArray
> Cuteness bugs

- tests/app/ui/web-view/web-view.md
Related to [https://github.com/NativeScript/docs/issues/677](https://github.com/NativeScript/docs/issues/677)
> updated webview article sub titles

- .vscode/settings.json
- apps/app/ui-tests-app/css/letter-spacing.xml
- apps/package.json
- tests/app/color-tests.ts
- tests/app/timer-tests.ts
- tests/app/ui/button/button-tests.ts
- tests/app/ui/label/label-tests.ts
- tests/app/ui/page/page-tests-common.ts
- tests/app/ui/search-bar/search-bar-tests.ts
- tests/app/ui/text-field/text-field-tests.ts
- tests/app/ui/text-view/text-view-tests.ts
- tests/app/ui/view/view-tests-common.ts
- tns-core-modules/color/color-common.ts
- tns-core-modules/color/color.android.ts
- tns-core-modules/color/color.ios.ts
- tns-core-modules/ui/text-base/text-base.ios.ts
Fixed text decoration tests, Color will now store just a single argb info in 32bit unsigned int internally and covert to a/r/g/b or hex when necessary.
> Fixed text decoration tests and color

- package.json
- Upgrade to latest TypeDoc
- Use the TypeDoc theme from GitHub (syncing with latest changes)
> TypeDoc upgrades

- apps/app/ui-tests-app/tab-view/all.xml
- apps/app/ui-tests-app/tab-view/selected.xml
- apps/app/ui-tests-app/tab-view/tabsBackground.xml
- tns-core-modules/ui/tab-view/tab-view-common.ts
- tns-core-modules/ui/tab-view/tab-view.android.ts
- tns-core-modules/ui/tab-view/tab-view.ios.ts
> Tab view fixes

- apps/app/ui-tests-app/page/page-status-bar-css.ts
- apps/app/ui-tests-app/page/page-status-bar-css.xml
> Update status bar test page

- apps/app/ui-tests-app/css/listview.ts
- apps/app/ui-tests-app/css/listview.xml
- apps/app/ui-tests-app/css/main-page.ts
> Include test for listview with separator color

- tns-core-modules/application/application-common.ts
- tns-core-modules/ui/styling/style-scope.ts
> addCssFile on application module wasn’t changing the app styles

- tns-core-modules/ui/core/view-common.ts
- tns-core-modules/ui/styling/background-common.ts
- tns-core-modules/ui/styling/background.android.ts
- tns-core-modules/ui/styling/background.ios.ts
In this PR
* Inset clip path
* [IOS]Background circ-ref
> Inset clip path + Background circ-ref

- tns-core-modules/ui/segmented-bar/segmented-bar.android.ts
> Fix: Setting slected color on SegmentedBar affects all seg-bars

- tests/app/ui/layouts/flexbox-layout-tests.ts
- tns-core-modules/ui/layouts/flexbox-layout/flexbox-layout.ios.ts
The master-based version of #3675
> Fix a crash when nesting a ProxyViewContainer in FlexboxLayout.

- apps/app/ui-tests-app/css/textview-hint-color.xml
> Change hint color text

- tests/app/ui/text-field/text-field.md
Minor fix of a snippet in the TextField docs
> Fix text field code snippet
