apps/app/ui-tests-app/page/page-status-bar-css.xml, tns-core-modules/ui/action-bar/action-bar.ios.ts
FIX: ActionBar background color in IOS is not resetting
=> Fix: Action-bar bg-color in ios not resetting

apps/package.json, tests/package.json
=> Update apps and test modules deps to *

tns-core-modules/ui/list-view/list-view.ios.ts
FIX: Make list view cells transparent
=> FIX: Make list view cells transparent

tns-core-modules/ui/activity-indicator/activity-indicator.android.ts
Crash when setting color to activity indicator
=> FIX: Crash setting color to activity-indicator

tns-core-modules/ui/frame/frame-common.ts
Nomination for minimalistic PR award
=> FIX: Livesync event not firing for frame

apps/app/ui-tests-app/css/hint-text-color.ts, apps/app/ui-tests-app/css/hint-text-color.xml, apps/app/ui-tests-app/css/main-page.ts, apps/app/ui-tests-app/css/textview-hint-color.xml, tests/app/ui/text-view/text-view-tests.ts, tns-core-modules/ui/text-view/text-view.ios.ts
=> Implemented placeholder-color for text-view IOS

tns-core-modules/application/application.ios.ts, tns-core-modules/ui/label/label.ios.ts
=> FIX: IOS measure bug + livesinc

tns-core-modules/ui/segmented-bar/segmented-bar.android.ts, tns-platform-declarations/android/org.nativescript.widgets.d.ts
=> FIX: Segmenter bar thickness

tns-core-modules/utils/types.ts
=> Cherry-pick: Fix utils/types class name resolution regex.

tns-core-modules/ui/label/label.ios.ts
=> Label borders are transformed to DIP before setting to native view

tests/app/ui/tab-view/tab-view-tests.ts, tns-core-modules/ui/tab-view/tab-view-common.ts, tns-core-modules/ui/time-picker/time-picker-common.ts
Add assert in existing test
Code formatting
=> Fix TabView args.object for selectedIndexChangedEvent

apps/app/ui-tests-app/css/main-page.ts, apps/app/ui-tests-app/css/pixels.xml
Pixels perfect and device independent pixels
=> Add pixels perfect test page

tns-core-modules/ui/label/label.android.ts
=> Made label to be single line again

apps/app/ui-tests-app/css/layouts-border-overlap.xml, apps/app/ui-tests-app/css/margins-paddings-with-percentage.ts, tns-core-modules/ui/core/view/view.ios.ts
FIX[IOS]: Apply clipping when there are non-uniform borders too.
=> Borders clip

tns-core-modules/ui/core/properties/properties.ts
=> fix(animations): register both style's "name" and "cssName"

tests/app/ui/layouts/dock-layout.md
related to [https://github.com/NativeScript/docs/issues/695](https://github.com/NativeScript/docs/issues/695)
=> Cookbook typo

tests/app/ui/layouts/flexbox-layout-tests.ts, tns-core-modules/ui/layouts/flexbox-layout/flexbox-layout.ios.ts
Reproducible in Angular apps on iOS.
Fixes NativeScript/nativescript-angular#629
=> [Release branch] Fix a crash when nesting a ProxyViewContainer in FlexboxLayout.

tns-core-modules/ui/tab-view/tab-view.android.ts
=> [Release branch] Fix a crash in Android tabview when resetting font property.

tns-core-modules/ui/action-bar/action-bar-common.ts, tns-core-modules/ui/core/view/view.android.ts
ActionBar titleView aligments are applied only if no alignment are set to titleView and after view is added to visual tree otherwise they were reset in addView method
=> Apply gravity in android if LayoutParams have gravity field.

tns-core-modules/ui/action-bar/action-bar.ios.ts, tns-core-modules/ui/core/view/view-common.ts, tns-core-modules/ui/core/view/view.android.ts, tns-core-modules/ui/core/view/view.ios.ts, tns-core-modules/ui/html-view/html-view.ios.ts, tns-core-modules/ui/label/label.ios.ts, tns-core-modules/ui/page/page.ios.ts, tns-core-modules/ui/styling/background.ios.ts, tns-core-modules/ui/styling/style-properties.ts, tns-core-modules/ui/styling/style/style.d.ts, tns-core-modules/ui/styling/style/style.ts, tns-core-modules/ui/switch/switch.ios.ts, tns-core-modules/ui/tab-view/tab-view.ios.ts, tns-core-modules/ui/text-base/text-base-common.ts, tns-core-modules/utils/utils-common.ts, tns-core-modules/utils/utils.android.ts, tns-core-modules/utils/utils.d.ts, tns-core-modules/utils/utils.ios.ts
Add helper method to layout module to convert to/from dips to px and measure the native view
whiteSpace affects layout added for iOS
Fix bug in switch onMeasure implementation
Fix bug in cssValueToDevicePixels iOS implementation
ActionBar for iOS is measured with AT_MOST modifier
=> Layout round instead of ceiling

tns-core-modules/ui/frame/frame.ios.ts, tns-core-modules/ui/page/page.ios.ts
Not resolving ../utils imports. Reproducible in `ui/page/page.ios.ts` and `ui/frame/frame.ios.ts`
=> Work around an issue with webpack's extension resolution.

tns-core-modules/ui/styling/style-scope.ts
=> Livesync reloads css

tns-core-modules/ui/border/border.ts, tns-core-modules/ui/content-view/content-view.ts, tns-core-modules/ui/core/view/view-common.ts, tns-core-modules/ui/html-view/html-view.ios.ts, tns-core-modules/ui/label/label.ios.ts, tns-core-modules/utils/utils.ios.ts
makeMeasureSpec will clamp to 0
=> Label textWrap fix for iOS

apps/app/gallery-app/content/web-view.xml, tns-core-modules/ui/web-view/web-view-common.ts, tns-core-modules/ui/web-view/web-view.android.ts, tns-core-modules/ui/web-view/web-view.ios.ts
Using `url` will throw exception now.
=> FIX: WebView not showing in gallery app

tns-core-modules/ui/list-picker/list-picker-common.ts, tns-core-modules/ui/list-picker/list-picker.android.ts, tns-core-modules/ui/list-picker/list-picker.ios.ts
Coerce selected index after we have set items to native view.
=> List picker coerse

tests/app/console/console.md, tests/app/image-source/image-source-tests.ts, tests/app/timer/timer-tests.ts, tests/app/timer/timer.md, tests/app/ui/image/image-tests.ts
Resolve broken snippet references to make the docs build work against the master branch.
=> Fix doc snippets.

tns-core-modules/http/http-request/http-request.ios.ts
=> iOS http-request header User-Agent always reports iOS 6

tests/app/application/application-tests.d.ts, tests/app/ui/action-bar/action-bar-tests.d.ts, tests/app/ui/frame/frame-tests.d.ts, tests/app/ui/page/page-tests.d.ts
=> Remove imports from some d.ts unit-tests

CodingConvention.md
=> Fix wrong example of Quotes usage

apps/app/ui-tests-app/tab-view/main-page.ts, apps/app/ui-tests-app/tab-view/text-transform.ts, apps/app/ui-tests-app/tab-view/text-transform.xml, tests/app/ui/text-field/text-field-tests.ts, tns-core-modules/ui/tab-view/tab-view-common.ts, tns-core-modules/ui/tab-view/tab-view.android.ts, tns-core-modules/ui/tab-view/tab-view.d.ts, tns-core-modules/ui/tab-view/tab-view.ios.ts, tns-core-modules/ui/text-base/text-base-common.ts, tns-core-modules/ui/text-base/text-base.android.ts, tns-core-modules/ui/text-base/text-base.ios.ts
Removed the default value for `text-transform`.
@SvetoslavTsenov or @vchimev - I have also added a new UI test app: `tab-view -> text-transform`
=> Initial value for text transform

tests/app/ui/view/view-tests-common.ts, tns-core-modules/ui/styling/background.ios.ts
=> ios cornder radius is rendered as circle now

tns-core-modules/ui/editable-text-base/editable-text-base.android.ts
=> fix(ui) updateTextTrigger="focusLost" for Android

tns-core-modules/ui/core/properties/properties.d.ts, tns-core-modules/ui/core/properties/properties.ts, tns-core-modules/ui/core/view-base/view-base.ts, tns-core-modules/ui/segmented-bar/segmented-bar.android.ts
segmented bar createNativeView returns the nativeView
=> propagate inheritable values only on child added.

tns-core-modules/ui/core/properties/properties.ts, tns-core-modules/ui/frame/frame-common.ts, tns-core-modules/ui/page/page-common.ts, tns-core-modules/ui/styling/style-scope.d.ts, tns-core-modules/ui/styling/style-scope.ts
=> Apply page css when using nav-entry with create method

build-docs.sh, package.json
- Extract cookbook articles.
- Extract snippets.
- Build API reference.
=> Add docs build script.

tns-core-modules/ui/animation/animation.android.ts
"curve instanceof Interpolator" returns false for PathInterpolator instances.
=> Fix android PathInterpolator

tests/app/ui/view/view-tests-common.ts
=> The asserted border and corner radius values were not rounded, we now round on dip to px conversion

tns-core-modules/ui/dialogs/dialogs-common.ts, tns-core-modules/ui/dialogs/dialogs.android.ts, tns-core-modules/ui/dialogs/dialogs.d.ts, tns-core-modules/ui/dialogs/dialogs.ios.ts
=> Feature: New Dialog-Prompt-Input-Type for E-Mails

tests/app/ui/text-field/text-field.md, tests/app/ui/text-view/text-view-tests.ts, tests/app/ui/text-view/text-view.md
Related to [https://github.com/NativeScript/docs/issues/336](https://github.com/NativeScript/docs/issues/336)
=> Fixing broken snippets in documentation

tests/app/connectivity/connectivity.md
=> Permissions update at connectivity module

tns-core-modules/package.json
=> Bump version

tns-core-modules/ui/page/page-common.ts, tns-core-modules/ui/page/page.d.ts, tns-core-modules/ui/styling/style/style.d.ts, tns-core-modules/ui/styling/style/style.ts
The `statusBarStyle` of `Page` should be implemented as a proxy to `page.style.statusBarStyle`
=> Expose statusBarStyle on page

tns-core-modules/ui/list-view/list-view-common.ts, tns-core-modules/ui/page/page-common.ts, tns-core-modules/ui/page/page.d.ts, tns-core-modules/ui/segmented-bar/segmented-bar-common.ts, tns-core-modules/ui/segmented-bar/segmented-bar.d.ts
=> implement get/set for selectedBackgroundColor property

tests/app/ui/placeholder/placeholder-tests.ts, tns-core-modules/ui/placeholder/placeholder.android.ts, tns-core-modules/ui/placeholder/placeholder.ios.ts, tns-core-modules/ui/placeholder/placeholder.ts
Fix https://github.com/NativeScript/NativeScript/issues/4043
=> Fix ios placeholder implementation

tns-core-modules/ui/animation/animation.d.ts, tns-core-modules/ui/animation/keyframe-animation.d.ts
Fix two broken links in the API reference documentation.
=> Fix wrong API ref links

apps/app/ui-tests-app/dialogs/dialogs.xml, apps/app/ui-tests-app/dialogs/view-model.ts
Add prompts with inputType password and email. https://github.com/NativeScript/NativeScript/issues/3118
=> Update dialogs test page

README.md
=> Changing “Angular 2” references to just “Angular”

tns-platform-declarations/README.md, tns-platform-declarations/package.json
- Updated instructions in README.md
- bumped version to 3.0.1
=> Update README + bump version

apps/app/ui-tests-app/css/combinators.css, apps/app/ui-tests-app/css/combinators.xml, apps/app/ui-tests-app/css/main-page.ts, tests/app/ui/styling/css-selector.ts, tns-core-modules/ui/styling/css-selector/css-selector.d.ts, tns-core-modules/ui/styling/css-selector/css-selector.ts
Merging @SBats sibling css selector PR.
Satisfied tslint. Rebased onto master. Sqashed.
=> Sibling css selector

tests/app/ui/button/button-tests.ts, tests/package.json, tns-core-modules/ui/text-base/text-base.android.ts
=> FIX: Span with unknown font-family crash

tests/app/profiling/profiling-tests.ts, tests/app/testRunner.ts, tns-core-modules/profiling/package.json, tns-core-modules/profiling/profiling.d.ts, tns-core-modules/profiling/profiling.ts
Added profiling module with some profiling methods.
=> Profiling module

apps/app/ui-tests-app/font/all-fonts.ts, apps/app/ui-tests-app/pages/touch-event.ts, tests/app/profiling/profiling-tests.ts, tests/app/ui/border/border-tests.ts, tns-core-modules/profiling/profiling.d.ts, tns-core-modules/profiling/profiling.ts
Decorator method calls are called inside try/finally.
More tests added
=> Profiling - handle exceptions inside deocrator

tns-core-modules/tns-core-modules.d.ts
Relates to https://github.com/NativeScript/ios-runtime/pull/753
=> Add objc decorator definitions

tns-core-modules/ui/tab-view/tab-view.ios.ts
Implements #4105 
Added updateItemIconPosition() function to center the TabViewItem icon properly when the title is not present.
=> Implemented Feature Request: TabView with icons properly centered

tests/app/ui/web-view/web-view-code-snippet.ts, tests/app/ui/web-view/web-view.md
add an example how to use `WebView` with gestures for both iOS and Android
=> add an example how to use webview with gestures for both iOS and Android

tests/app/profiling/profiling-tests.ts
Stopped execution of failing profiling tests for Android.
=> Fix: Slow profiling tests for android

tests/app/ui/web-view/web-view-code-snippet.ts
fix broken closing tag for the snippet
=> fix broken closing tag for the snippet

tns-core-modules/ui/web-view/web-view.d.ts
=> Fix web-view typedoc

tests/app/ui/view/view-tests-common.ts, tns-core-modules/ui/core/properties/properties.ts
Added support for `getDefault` callback for `CssAnimationProperty`
Related to #4147
=> Support getDefault for CssAnimationProperty

tests/app/ui/search-bar/search-bar-code-snippet.ts, tests/app/ui/search-bar/search-bar.md
example declare `SearchBar` component via XML
=> example declare SearchBar component via XML

tests/app/image-source/image-source-snippet.ts, tests/app/image-source/image-source.md
add sample -image source from imageAsset and save it to PNG
=> add sample -image source from imageAsset and save it to PNG

tests/app/http/http-tests.ts, tns-core-modules/http/http-request/http-request-common.ts, tns-core-modules/http/http-request/http-request.android.ts, tns-core-modules/http/http-request/http-request.ios.ts, tns-core-modules/http/http.ts
Rebased and test fixed version of #3999
Courtesy of @vjoao 
Related to #3957
=> Support http.getFile for URLs with query params

tns-core-modules/ui/editable-text-base/editable-text-base-common.ts, tns-core-modules/ui/editable-text-base/editable-text-base.android.ts, tns-core-modules/ui/editable-text-base/editable-text-base.d.ts, tns-core-modules/ui/text-field/text-field.ios.ts, tns-core-modules/ui/text-view/text-view.ios.ts
Rebased @EddyVerbruggen 's #3902 and resolved minor conflicts. Rerunning tests before merge.
=> Implemented feature request: TextField `maxLength` property support.

apps/app/ui-tests-app/issues/issue-4287.xml, apps/app/ui-tests-app/issues/main-page.ts, tests/app/ui/layouts/flexbox-layout-page.xml, tns-core-modules/ui/button/button-common.ts, tns-core-modules/ui/button/button.ios.ts, tns-core-modules/ui/label/label.android.ts, tns-core-modules/ui/label/label.ios.ts
Related to #4287
UI testa added `issues->issue-4287`
cc @SvetoslavTsenov
=> Implement custom measure for ios btn when textWrap is true

tns-core-modules/debugger/dom-node.ts
Fix for crash caused by list-view dom-nodes + devtools
=> FIX: ListView items' dom-nodes are disposed before remove

apps/app/ui-tests-app/search-bar/issue-4147.xml, tests/app/ui/search-bar/search-bar-tests-native.android.ts, tns-core-modules/ui/search-bar/search-bar.android.ts
=> Use AppCompat SearchView

tests/app/timer/timer-tests.ts, tests/app/timer/timer.md
Duplicated snippets removed from tests/app/timer.ts
=> snippet fix for timer

tests/app/timer/timer-tests.ts
=> Fix timer snippets

tests/app/ui/text-field/text-field.md
add sample code snippet for `maxLength` property
=> add sample code snippet for maxLength property

tests/app/ui/web-view/test with spaces.html, tests/app/ui/web-view/web-view-tests.ts, tns-core-modules/ui/web-view/web-view-common.ts
=> Ability to load local files in a WebView on iOS devices

apps/app/ui-tests-app/font/all-fonts.ts, tns-core-modules/ui/styling/font-common.ts, tns-core-modules/ui/styling/font.android.ts, tns-core-modules/ui/styling/font.ios.ts
Reworked how fonts are retrieved in IOS. Related to #4342
I have also created [ns-fonts-tests application](https://github.com/vakrilov/ns-fonts-tests) to test the fix.
=> Fonts refactored

tns-core-modules/ui/frame/frame.ios.ts
for #4283 
This problem also happens while phone call.
It can be tested by Alt+Y  on emulator.
=> Fix iOS ActionBar problem while internet sharing #4283

tns-core-modules/application/application.android.ts
=> Refactored getting root view in android

tns-core-modules/profiling/profiling.ts
=> Fix uptime with snapshot

.travis.yml
=> Do not publish next version from Travis CI

tns-platform-declarations/README.md
Updated instructions for using tns-platform-declarations
=> updated instructions for tns-platform-declarations

CHANGELOG.md
Add https://github.com/NativeScript/NativeScript/issues/4342 to the changelog for 2.5.3.
=> Update changelog for 2.5.3

tns-core-modules/ui/animation/animation.android.ts, tns-core-modules/ui/core/properties/properties.d.ts, tns-core-modules/ui/core/properties/properties.ts, tns-core-modules/ui/core/view/view-common.ts
=> Fix CssAnimationProperty default value

tests/app/testRunner.ts
Remove generation of `tests-results.xml`
=> Remove generation of test-results.xml

tests/app/ui/scroll-view/scroll-view-tests.ts, tns-core-modules/ui/scroll-view/scroll-view-common.ts, tns-core-modules/ui/scroll-view/scroll-view.android.ts, tns-core-modules/ui/scroll-view/scroll-view.d.ts, tns-core-modules/ui/scroll-view/scroll-view.ios.ts
Implements #4522
Okay, so I wasn't able to get the tests running here locally... kept crashing.  I took the source and put it in a hello world to test with.
=> Allow toggling of visible scrollbar indicators

tns-core-modules/image-source/image-source.android.ts
separate checking JPG and JPEG  formats
=> separate checking JPG and JPEG  formats in getTargetFormat

tns-core-modules/ui/core/view/view.android.ts
layerType wasn't recycled correctly
=> fix layer type recycling

apps/app/ui-tests-app/action-bar/flat.ts, apps/app/ui-tests-app/action-bar/flat.xml, tns-core-modules/ui/action-bar/action-bar.ios.ts
Update UI when flat property changes in IOS.
Related to #2740
=> Fix: refresh flat property on change in IOS

tests/app/ui/view/view-tests-common.ts, tns-core-modules/ui/styling/background.android.ts
=> Fix: Background drawable cache conflicts with local property

apps/app/ui-tests-app/css/line-height.ts, apps/app/ui-tests-app/css/line-height.xml, apps/app/ui-tests-app/css/main-page.ts, tns-core-modules/ui/text-base/text-base.d.ts
Tests https://github.com/NativeScript/NativeScript/issues/1664.
=> Add line-height test page

app/ui-tests-app/issues/issue-4450.xml
The original file is [here](https://github.com/NativeScript/NativeScript/blob/master/apps/app/ui-tests-app/issues/issue-4450.xml).
=> Delete an unnecessary file

CHANGELOG.md
=> Changelog updated for 3.1.1

build-docs.sh
Pin version of dependency in order to build docs.
=> @types/handlebars@4.0.33

tests/app/ui/slider/slider-tests.ts, tests/package.json, tns-core-modules/ui/slider/slider.android.ts
Made singleton listener for SeekBar
Fix slider issue
Add slider test
Fix https://github.com/NativeScript/NativeScript/issues/4424
=> Cache android.widget.SeekBar as SeekBar for better performance

tns-core-modules/ui/styling/background.android.ts
Fix https://github.com/NativeScript/nativescript-cli/issues/2981
Fix https://github.com/NativeScript/NativeScript/issues/4650
=> Image cache is cleared when livesync happens

apps/app/perf-app/main-page.ts, apps/app/perf-app/recycling/main-page.ts, apps/app/perf-app/recycling/main-page.xml, apps/app/perf-app/recycling/tests.ts, tns-core-modules/image-source/image-source.ios.ts, tns-core-modules/ui/text-base/text-base.android.ts
Add new perf-test page for view recycling
Changed the initialization of TextTransformation field
=> Fix failing test on ios 11

tns-core-modules/application/application.d.ts, tns-core-modules/connectivity/connectivity.d.ts, tns-core-modules/file-system/file-system-access.d.ts, tns-core-modules/image-source/image-source.d.ts, tns-core-modules/platform/platform.d.ts, tns-core-modules/ui/gestures/gestures.d.ts, tns-core-modules/ui/html-view/html-view.d.ts, tns-core-modules/ui/image/image.d.ts, tns-core-modules/ui/layouts/dock-layout/dock-layout.d.ts, tns-core-modules/ui/layouts/grid-layout/grid-layout.d.ts, tns-core-modules/ui/list-view/list-view.d.ts, tns-core-modules/ui/page/page-common.ts, tns-core-modules/ui/page/page.d.ts, tns-core-modules/ui/search-bar/search-bar.d.ts, tns-core-modules/ui/tab-view/tab-view.d.ts, tns-core-modules/ui/web-view/web-view.d.ts, tns-core-modules/utils/utils.d.ts
This PR corrects (mainly) spelling errors / typo's in `.ts.d` files that caught my eye.
I was actually only going to correct this comment of the native element in `html-view.d.ts`:
https://github.com/NativeScript/NativeScript/blob/2701ea3c1e2b758674fbb344f74ffb39ec223288/tns-core-modules/ui/html-view/html-view.d.ts#L22
.. but then I got carried away. 😋 🙃
=> Fixed a bunch of typo's and minor errors in TypeScript definition files.

tns-core-modules/ui/list-view/list-view.ios.ts
=> Removes list-view selected state when rowHeight is set

tests/app/ui/tab-view/tab-view-tests-native.android.ts, tests/app/ui/tab-view/tab-view-tests-native.d.ts, tests/app/ui/tab-view/tab-view-tests-native.ios.ts, tests/app/ui/tab-view/tab-view-tests.ts, tns-core-modules/ui/tab-view/tab-view.ios.ts
Fix https://github.com/NativeScript/NativeScript/issues/4302
Fix tests for that issue
=> Fix Icon font on TabViewItem

tns-core-modules/ui/tab-view/tab-view.android.ts, tns-core-modules/utils/utils.android.ts, tns-core-modules/utils/utils.d.ts
=> fix: typo on android utils, getPalleteColor to getPaletteColor

tns-core-modules/ui/animation/animation.android.ts, tns-core-modules/ui/core/view/view.android.ts, tns-core-modules/ui/styling/background.android.ts, tns-core-modules/utils/utils.d.ts
I don't know why we did this in the first place,
but changing the rendering mode can not be good.
Let's re-run all possible UI tests.
=> Do not change the Android layer types (hardware/software)

tns-core-modules/application/application.d.ts, tns-core-modules/ui/core/view-base/view-base.ts, tns-core-modules/ui/frame/frame.android.ts
Exposed savedInstanceState on LaunchEventArgs so some controls that need Bundle to initialize could get it from there.
=> Fix breaking change - nativeView property should have setter

tests/app/xml-parser-tests/itemTemplates.xml, tests/app/xml-parser-tests/xml-parser-tests.ts, tns-core-modules/ui/builder/builder.ts
=> Fix MultiTemplateParser to not eat its closing tag

tests/app/ui/view/view-tests.android.ts
For now the layer type sticks with the default.
=> Delete the layer type tests

.gitignore, apps/app/ui-tests-app/list-view/main-page.ts, apps/app/ui-tests-app/list-view/scrolling-and-sizing.css, apps/app/ui-tests-app/list-view/scrolling-and-sizing.ts, apps/app/ui-tests-app/list-view/scrolling-and-sizing.xml, apps/app/ui-tests-app/main-page.ts, apps/app/ui-tests-app/scroll-view/main-page.ts, apps/app/ui-tests-app/scroll-view/main-page.xml, apps/app/ui-tests-app/scroll-view/scrolling-and-sizing.css, apps/app/ui-tests-app/scroll-view/scrolling-and-sizing.xml, apps/app/ui-tests-app/text-view/scrolling-and-sizing.css, apps/app/ui-tests-app/text-view/scrolling-and-sizing.xml, tns-core-modules/ui/core/view/view.ios.ts, tns-core-modules/ui/list-view/list-view.ios.ts, tns-core-modules/ui/scroll-view/scroll-view.ios.ts, tns-core-modules/ui/styling/background.ios.ts, tns-core-modules/ui/text-view/text-view.ios.ts
This PR is for the #4733 issue.
=> UIScrollViews will now report 'scroll' events and the background in ios will adjust added layers

tns-core-modules/ui/image/image-common.ts, tns-core-modules/ui/image/image.android.ts, tns-core-modules/ui/styling/style-properties.ts
=> TypeScript 2.5 compatibility

tns-core-modules/ui/date-picker/date-picker.android.ts
=> fix(date-picker): Date picker changed check

tns-core-modules/ui/frame/frame.d.ts
edit broken link animation's enums
=> edit broken link

tests/app/TKUnit.ts, tests/app/testRunner.ts, tests/app/ui/page/page.md, tns-core-modules/ui/core/view/view.d.ts, tns-core-modules/ui/date-picker/date-picker.android.ts, tns-core-modules/ui/image/image-common.ts, tns-core-modules/ui/image/image.android.ts, tns-core-modules/ui/styling/style-properties.ts
=> edit broken page snippet tag

tests/app/xhr/xhr-tests.ts, tns-core-modules/xhr/xhr.ts
Fixes https://github.com/NativeScript/nativescript-angular/issues/985 partially.
=> Add RssFeed to the ContentTypes considered as text

tests/app/ui/date-picker/date-picker-tests.ts, tns-core-modules/ui/date-picker/date-picker.android.ts
=> fix: DatePicker month off by 1 in Android

CodingConvention.md
=> Minor fixes on text (proposal) - Typo

tns-core-modules/utils/types.d.ts
Fixes https://github.com/NativeScript/docs/issues/881
CC @etabakov
=> chore(docs): Update method descriptions

.github/ISSUE_TEMPLATE.md
Add note about the possible usage of NativeScript Playground.
=> Update ISSUE_TEMPLATE.md to point to the NS Playground

CHANGELOG.md
Changelog update for `3.3.0` release
=> docs: add changelog for 3.3.0

WritingUnitTests.md, tests/app/ui/text-field/text-field-tests.ts, tns-core-modules/ui/text-field/text-field.android.ts
https://github.com/NativeScript/NativeScript/issues/4738
=> fix(TextField): not secure when keyboardType="number"

tns-core-modules/ui/scroll-view/scroll-view-common.ts
Related to [https://github.com/NativeScript/NativeScript/issues/4993](https://github.com/NativeScript/NativeScript/issues/4993).
=> fix(ScrollView): removeEventListener super call

apps/app/ui-tests-app/css/background-shorthand.ts, apps/app/ui-tests-app/css/background-shorthand.xml, apps/app/ui-tests-app/css/main-page.ts, tns-core-modules/css/parser.ts, tns-core-modules/ui/core/view/view-common.ts, tns-core-modules/ui/core/view/view.d.ts, tns-core-modules/ui/styling/style-properties.d.ts, tns-core-modules/ui/styling/style-properties.ts, tns-core-modules/ui/styling/style/style.d.ts, tns-core-modules/ui/styling/style/style.ts, unit-tests/css/parser.ts
=> Introduce background shorthand property

CONTRIBUTING.md
Fixed a typo found.
No.
No, since the typo is in the documentation.
=> Found a typo

tests/app/ui/web-view/web-view-tests.ts, tns-core-modules/ui/web-view/web-view.d.ts, tns-core-modules/ui/web-view/web-view.ios.ts
Updated the native view to use the recommend WKWebView for 8.0+ apps
Yes
=> WebView upgrade [IOS]

README.md
- add links to Playground, Marketplace, forum
- update CLI badge to point to CLI project
- add link to Slack in Get Help section
=> chore(readme): link more resources; update cli badge link

README.md
=> chore: update Readme with the common NS diagram

tns-core-modules/image-source/image-source.android.ts, tns-core-modules/image-source/image-source.d.ts, tns-core-modules/image-source/image-source.ios.ts
https://github.com/NativeScript/NativeScript/issues/3605
=> refactor(image-source): throw if source is not a correct native instance

tns-core-modules/ui/frame/frame-common.ts
- Add `defaultPage` string property to Frame 
- Forbid inline content for Frame (_Frame page should be only specified by `defaultPage` property_)
=> feat(frame): introduce defaultPage property

tns-core-modules/ui/tab-view/tab-view.android.ts
Android TabView pager adapter's notifyDataSetChanged() was called unnecessary too many times, which causes the view pager to refresh.
Changes:
1. Remove setAdapterItems() from initNativeView and disposeNativeView since it's called in onLoaded and onUnloaded.
2. Add a check that calls notifyDataSetChanged() only if the newly assigned items are different. Both onLoaded and the items binding are calling it simultaneously on navigate.
=> refactor(android-tabview): adapter data change called unnecessary

tests/app/http/http-tests.ts, tests/app/image-source/image-source-snippet.ts, tests/app/image-source/image-source-tests.ts, tests/app/image-source/image-source.md
Related to feedback form request to add examples of base64 methods. [https://github.com/NativeScript/docs/issues/995](https://github.com/NativeScript/docs/issues/995)
=> refactor: update image source documentation snippets and tests

tests/app/ui/image/image-tests.ts, tests/app/ui/image/image.md
=> edit cookbook/image article improve code snippets

tns-core-modules/application/application.d.ts
https://github.com/NativeScript/NativeScript/issues/5307
=> refactor: unmark startActivity as deprecated

apps/app/ui-tests-app/app-root.xml, apps/app/ui-tests-app/app.ts, tests/app/http/http-tests.ts, tns-core-modules/application/application-common.ts, tns-core-modules/application/application.android.ts, tns-core-modules/application/application.d.ts, tns-core-modules/application/application.ios.ts, tns-core-modules/ui/builder/builder.ts, tns-core-modules/ui/frame/activity.android.ts, tns-core-modules/ui/frame/frame.android.ts, tns-core-modules/ui/frame/frame.d.ts
Expose a method to open a new root view when your app is running. It will be useful for test apps and angular livesync.
=> feat: add option to set a different root view at run time

tests/app/testRunner.ts, tests/app/ui/page/page-tests-common.ts, tns-core-modules/ui/core/view-base/view-base.d.ts, tns-core-modules/ui/core/view-base/view-base.ts, tns-core-modules/ui/core/view/view-common.ts, tns-core-modules/ui/frame/frame-common.ts, tns-core-modules/ui/frame/frame.android.ts
- Fixes https://github.com/NativeScript/NativeScript/issues/5398
- Revises fix for https://github.com/NativeScript/NativeScript/issues/5340
- Logged new feature https://github.com/NativeScript/NativeScript/issues/5407
=> fix(frame): root tabview with modal frame when suspend/resume app Fixes #5398

tns-core-modules/application/application-common.ts, tns-core-modules/application/application.ios.ts, tns-core-modules/css/parser.ts, tns-core-modules/package.json, tns-core-modules/profiling/profiling.d.ts, tns-core-modules/profiling/profiling.ts, tns-core-modules/ui/styling/css-selector/css-selector.ts, tns-platform-declarations/package.json, unit-tests/css/parser.ts
Should be merged with 'rebase and merge'.
=> Cherry-pick onDisplayed event for iOS and TS 2.7 fixes

tests/app/profiling/profiling-tests.ts, tns-core-modules/profiling/profiling.ts
=> fix(profiling): resetProfiles doesn't reset all profiles

CHANGELOG.md
Add changelog for 3.4.1 release.
=> chore: 3.4.1 changelog

tests/app/navigation/reset-root-view-tests.ts, tests/app/testRunner.ts, tns-core-modules/application/application-common.ts, tns-core-modules/application/application.android.ts, tns-core-modules/application/application.ios.ts, tns-core-modules/ui/core/view-base/view-base.d.ts, tns-core-modules/ui/core/view-base/view-base.ts, tns-core-modules/ui/frame/frame-common.ts, tns-core-modules/ui/frame/frame.android.ts
* Add _resetRootView() tests
* Fix an issue where resetting the root view doesn't clear the frame stack properly
=> test: add reset root view tests

apps/app/ui-tests-app/events/console.ts
- [ x] Tests for the changes are included - https://github.com/NativeScript/NativeScript/blob/master/WritingUnitTests.md.
Currently `console.dir` does not print the object dump as expected.
This PR extends the functional tests targeting the `console.log/console.dir` behavior on iOS.
=> Extend console tests for iOS

tns-core-modules/connectivity/connectivity.android.ts, tns-core-modules/connectivity/connectivity.ios.ts
Adding zonedCallback in connectivity module. 
Related to https://github.com/NativeScript/nativescript-angular/issues/1229
=> zonedCallback in connectivity module

e2e/modal-navigation/app/home/home-page.ts
Update application with https://github.com/NativeScript/NativeScript/pull/5496.
=> refactor(e2e/modal-navigation): stretch modal tab view

tns-core-modules/ui/html-view/html-view.d.ts
Code comment says that the related native iOS component is UILabel, actual code uses UITextView instead.
Code comment now references correct iOS component.
=> html-view: update reference to native iOS component in code comment

tns-core-modules/http/http.ts
Added from to the below line
export * from "./http-request";
Removed below line
global.moduleMerge(httpRequest, exports);
=> Update http.ts  ( To get this work in iOS )

tests/app/ui/list-view/list-view-tests.ts, tns-core-modules/ui/list-view/list-view-common.ts, tns-core-modules/ui/list-view/list-view.android.ts, tns-core-modules/ui/list-view/list-view.d.ts, tns-core-modules/ui/list-view/list-view.ios.ts
There is no way to check if an item is in the ViewPort
This PR adds a new function for both Android and IOS ListView, that allows checking if the Item is visible or not. 
the function is a member function for the ListView Class, called isItemAtIndexVisible.
and is callable with a reference to the ListView
```(javascript)
ListView.isItemAtIndexVisible(1 /** index of item **/) // returns true/false if item is in view port. 
```
=> Feat(List-View) : Add the Ability to check if an item is visible or not. 

tns-core-modules/ui/web-view/web-view.ios.ts
Just remove a useless evaluation.
=> refactor(ios-webview) Remove useless code

tns-core-modules/ui/dialogs/dialogs-common.ts, tns-core-modules/ui/dialogs/dialogs.android.ts, tns-core-modules/ui/dialogs/dialogs.ios.ts
Fix: Global `Button`, `Label` and `Text` selectors with color styling, should be applied to dialogs
=> fix(style): Styles are not applied to dialogs

tests/app/ui/tab-view/tab-view.md
=> new tabview examples

tests/app/navigation/navigation-tests.ts, tns-core-modules/ui/frame/frame-common.ts
Fixes https://github.com/NativeScript/NativeScript/issues/5642
=> fix(navigation): fix frame.navigate call inside page.navigatedTo handler Fixes #5642

tns-core-modules/ui/image/image.d.ts
=> chore(image): expose decode image properties for the public API

tns-core-modules/ui/builder/builder.ts
This should enable building pages from xml bundled with webpack. Currently, we copy the xml files even though they are already bundled.
=> feat(builder): enable reading xml from bundle

apps/app/ui-tests-app/list-view/main-page.ts, apps/app/ui-tests-app/list-view/row-height.css, apps/app/ui-tests-app/list-view/row-height.ts, apps/app/ui-tests-app/list-view/row-height.xml, tns-core-modules/ui/list-view/list-view.ios.ts
Fix https://github.com/NativeScript/NativeScript/issues/5441
=> fix(list-view-ios): fix rowHeight property to apply proper item size for iOS

tests/app/ui/page/page-tests-common.ts, tns-core-modules/ui/core/view-base/view-base.ts
Fixes https://github.com/NativeScript/NativeScript/issues/5735
=> fix(modal): exception when calling ViewBase.showModal(...)

apps/app/ui-tests-app/flexbox/flexbox-4834.css, apps/app/ui-tests-app/flexbox/flexbox-4834.xml, apps/app/ui-tests-app/flexbox/flexbox-main-page.ts, tns-core-modules/ui/label/label.ios.ts, tns-core-modules/ui/layouts/flexbox-layout/flexbox-layout.ios.ts
Fixes https://github.com/NativeScript/NativeScript/issues/4834
Fixes https://github.com/NativeScript/NativeScript/issues/3834
Should be tested with https://github.com/NativeScript/tns-core-modules-widgets/pull/121
@SvetoslavTsenov added new test page for the ui tests app:  https://github.com/NativeScript/NativeScript/commit/6400e11d4bd99fa288e789d6cac16952695f7b6e
=>  fix: label text wrapping inside flexbox layout

tests/app/ui/page/page-tests-common.ts, tns-core-modules/ui/core/view-base/view-base.d.ts, tns-core-modules/ui/core/view-base/view-base.ts, tns-core-modules/ui/core/view/view-common.ts
=> fix(modal): innerView.closeModal(...) not passing back context

tns-core-modules/ui/builder/builder.ts
related to https://github.com/NativeScript/nativescript-dev-webpack/pull/529
=> fix(builder): check for custom components registered at build time

tns-core-modules/ui/layouts/flexbox-layout/flexbox-layout.ios.ts
Fix https://github.com/NativeScript/NativeScript/issues/5262
=> fix(flexbox-ios): resolve text size issue for ListView with flexbox layout template

tns-core-modules/ui/animation/keyframe-animation.ts
Usage of `throw` destabilizes apps during animation handling.
Promise rejection is now removed around keyframe handling since there was no valid way to handle. With tracing enabled developers can now have meaningful and productive debug sessions.
https://github.com/NativeScript/nativescript-angular/issues/431
=> fix(animation): remove throw and fix promise handling

tns-core-modules/globals/globals.ts
Fix typescript errors with typescript@2.9.1
=> chore: Fix TS transpile error with 2.9

tests/app/ui/label/label-tests.ts, tns-core-modules/ui/text-base/text-base-common.ts
Fixes https://github.com/NativeScript/NativeScript/issues/5793
=> fix(android): label width shrinking on shorter text change

CONTRIBUTING.md, HandlingErrors.md, tests/app/testRunner.ts, tests/app/trace/trace-error-tests.ts, tns-core-modules/trace/trace.d.ts, tns-core-modules/trace/trace.ts
=> feat: Flexible Error/Exception handling

e2e/animation/app/App_Resources/Android/app.gradle, e2e/animation/app/chaining-with-animation-set/page.ts, e2e/animation/app/chaining-with-animation-set/page.xml, e2e/animation/app/home/home-page.ts, e2e/animation/app/home/home-page.xml, e2e/animation/e2e/animation.e2e-spec.ts, e2e/animation/e2e/screen.ts, e2e/animation/package.json
Refactor new e2e animation app to streamline it with https://github.com/NativeScript/animation-demo
=> refactor: animation app

tns-core-modules/image-source/image-source.ios.ts
Normalisation formula is wrong due to wrong operator priority. So it does not normalise the value to be between 0 and 1. 
Fixes the formula to include parenthesis for correct formula. 
=> fix normalisation formula

tns-core-modules/package.json
`platforms/ios` folder is omitted from the built tns-core-modules NPM package
`platforms/ios` folder is included in the built tns-core-modules NPM package
=> fix(build): Add platforms/ios folder to produced NPM package

apps/app/ui-tests-app/list-view/main-page.ts, apps/app/ui-tests-app/list-view/width-percent.ts, apps/app/ui-tests-app/list-view/width-percent.xml
Depends on https://github.com/NativeScript/tns-core-modules-widgets/pull/127
=> chore(listview-tests): add tests for width property with percentages

tns-platform-declarations/android/android-declarations.d.ts
=> Add missing globalAndroid import

tns-core-modules/ui/list-view/list-view-common.ts, tns-core-modules/ui/list-view/list-view.android.ts, tns-core-modules/ui/list-view/list-view.d.ts, tns-core-modules/ui/list-view/list-view.ios.ts
- [x ] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/CONTRIBUTING.md#commit-messages.
- [x ] You have signed the [CLA](http://www.nativescript.org/cla).
Currently, the listview doesn't support animated scroll to index
After merging this, the listview will support animated scroll to index
=> feat(UI): Added animated scroll to index for ListView

apps/app/ui-tests-app/list-view/list-view.ts, apps/app/ui-tests-app/list-view/list-view.xml
Add test scenarios for Listview scrolltoIndex() and scrollToIndexAnimated().
=> test(): add scenarios for listview scrolling

tests/app/ui/styling/style-tests.ts, tns-core-modules/ui/styling/style-scope.d.ts, tns-core-modules/ui/styling/style-scope.ts
Implements https://github.com/NativeScript/NativeScript/issues/6021.
=> feat(CSS): import of relative paths

tns-core-modules/ui/frame/fragment.transitions.android.ts
Seems AndroidP sdk already returns 28 -- https://developer.android.com/preview/setup-sdk
=> chore(android): update AndroidP sdk version check

tns-core-modules/file-system/file-system.d.ts
Update file-system iOS api reference to reflect https://github.com/NativeScript/NativeScript/pull/2699
Related to https://github.com/NativeScript/NativeScript/issues/3433
=> chore: update file-system api reference

CONTRIBUTING.md
Add a note about CI phrases we use on community PR to avoid confusion.
=> chore: Add comments about CI phrases

CHANGELOG.md
Adding some breaking changes to the changelog connected with the android typings.
=> docs: add Android typings breaking changes to CHANGELOG.md

tests/app/ui/list-view/list-view-tests.ts, tns-core-modules/ui/list-view/list-view.ios.ts
Fixes https://github.com/NativeScript/NativeScript/issues/5353
=> fix(ios): listview scrollToIndex crash with async data

tns-core-modules/ui/core/view/view.android.ts, tns-core-modules/ui/search-bar/search-bar.android.ts, tns-core-modules/ui/segmented-bar/segmented-bar.android.ts, tns-core-modules/ui/styling/background.android.ts
Make necessary changes because of https://github.com/NativeScript/tns-core-modules-widgets/pull/137
=> refactor: remove obsolete ViewHelper.setBackground method

tests/app/ui/layouts/layout-tests-helper.ts, tests/app/ui/layouts/safe-area-tests.ts, tests/app/ui/list-view/list-view-safe-area-tests.ts, tests/app/ui/scroll-view/scroll-view-safe-area-tests.ts, tns-core-modules/ui/layouts/flexbox-layout/flexbox-layout.ios.ts
Fix justify content calculations for flex end value of flexbox layout.
=> fix-next(flexbox): flex end for justify content

tns-core-modules/ui/repeater/repeater.ts
Fixes QSF margin/padding test.
=> fix-next: apply repeater onLayout initial values

tns-core-modules/ui/frame/frame.android.ts
Fixes https://github.com/NativeScript/NativeScript/issues/6312
Fixes https://github.com/NativeScript/NativeScript/issues/6201
=> fix(android): nested frames on app suspend/resume

tns-core-modules/ui/frame/fragment.transitions.android.ts
Fixes https://github.com/NativeScript/NativeScript/issues/6302
Issue is caused by a bug in Android view animations with zero duration that raise animation listener events in illogical order -- workaround is to use duration of 1ms instead. Note that this hack will be removed as soon as we migrate back to the Animators API (vs view animations).
=> fix(android): second livesync

tns-core-modules/application/application.ios.ts
Fixes the RadSideDrawer appearing black in `next`. The problem was caused by https://github.com/NativeScript/NativeScript/pull/6102 . The issue was that we waited for the native views to be instantiated before we create the wrapper UILayoutViewController. RadSideDrawer checks its modes when its native view is created. It requires the view controller to be created before the native view.
=> fix-next: drawer plugin viewcontroller init

tests/app/ui/tab-view/tab-view-root-tests.ts, tns-core-modules/ui/core/view/view.android.ts, tns-core-modules/ui/frame/frame.android.ts, tns-core-modules/ui/frame/frame.d.ts, tns-core-modules/ui/tab-view/tab-view.android.ts
Fixes https://github.com/NativeScript/NativeScript/issues/6292
~~TODO: review tab fragments' logic with respect to this change (and how did it work so far in the first place).~~
=> fix: nested fragments interact thru child fragment manager

tns-core-modules/ui/core/view/view.android.ts
Related to https://github.com/NativeScript/NativeScript/pull/6293
=> refactor(android): root fragment manager usage

e2e/animation/app/slide-in-effect/page.ts
The files at `tns-core-modules/ui/layouts/layout` were removed - https://github.com/NativeScript/NativeScript/pull/6228
=> chore: fix animations e2e app layout import

tests/app/navigation/custom-transition.android.ts, tns-core-modules/ui/frame/fragment.android.ts, tns-core-modules/ui/frame/fragment.transitions.android.ts, tns-core-modules/ui/frame/fragment.transitions.d.ts, tns-core-modules/ui/frame/frame.android.ts, tns-core-modules/ui/frame/frame.d.ts, tns-core-modules/ui/transition/fade-transition.android.ts, tns-core-modules/ui/transition/flip-transition.android.ts, tns-core-modules/ui/transition/slide-transition.android.ts, tns-core-modules/ui/transition/transition.android.ts, tns-core-modules/ui/transition/transition.d.ts, tns-core-modules/ui/transition/transition.ios.ts
Related to https://github.com/NativeScript/NativeScript/pull/6129#issuecomment-409852341
=> refactor: restore animators api usage

CHANGELOG.md
=> docs: 5.0.0-rc changelog

tns-core-modules/css/parser.ts, tns-core-modules/ui/core/dependency-observable/dependency-observable.d.ts, tns-core-modules/ui/core/dependency-observable/dependency-observable.ts
Fix compilation errors with typescript@3.1.3
=> refactor: fix ts compilation errors

tests/app/ui/action-bar/action-bar-tests-common.ts, tests/app/ui/action-bar/action-bar-tests.ios.ts, tns-core-modules/ui/frame/frame-common.ts, tns-core-modules/ui/frame/frame.android.ts, tns-core-modules/ui/frame/frame.d.ts, tns-core-modules/ui/frame/frame.ios.ts
I think we can later remove the ios.navBarVisibility property of the iOSFrame class.
=> feat(frame): add new actionBarVisibility property

tns-core-modules/ui/html-view/html-view.d.ts
Current iOS support documentation link returns a 404.
The new link shows the intended documentation
=> docs:  updated iOS support documentation link for HtmlView

tns-core-modules/ui/frame/frame.android.ts
Fixes: https://github.com/NativeScript/NativeScript/issues/6488
=> fix(android): back navigation on app suspend/resume

tests/app/ui/helper.ts, tests/app/ui/tab-view/tab-view-navigation-tests.ts, tests/package.json
Related to https://github.com/NativeScript/NativeScript/issues/6490
Related to https://github.com/NativeScript/NativeScript/pull/6495
=> test: add test for #6490

tns-core-modules/ui/frame/frame-common.ts, tns-core-modules/ui/frame/frame.d.ts, tns-core-modules/ui/tab-view/tab-view.android.ts, tns-core-modules/ui/tab-view/tab-view.ios.ts
Fixes: https://github.com/NativeScript/nativescript-angular/issues/1596
=> fix: nested frames order with tabs & suspend/resume

apps/package.json, e2e/modal-navigation/package.json, package.json, tests/package.json, tns-platform-declarations/package.json
=> chore: update to TS 3

tns-core-modules/ui/frame/frame.android.ts
Related to https://github.com/NativeScript/NativeScript/pull/6495
=> fix(android-fragment): child already has a parent

apps/app/ui-tests-app/tab-view/main-page.ts, apps/app/ui-tests-app/tab-view/tab-view-android-swipe.xml, tns-core-modules/ui/tab-view/tab-view-common.ts, tns-core-modules/ui/tab-view/tab-view.android.ts, tns-core-modules/ui/tab-view/tab-view.d.ts
Copied from https://github.com/NativeScript/NativeScript/pull/6258 with comments applied as it seems @Rjgoolsby deleted the forked repo on his side.
Fixes/Implements/Closes #2449
=> feat(tabview): add androidSwipeEnabled property

tns-core-modules/ui/core/view/view-common.ts
Fix regression in modals in angular caused by #6637
=> fix(modals): regression with modals in angular

package.json
Building with the current 0.5.10 now fails because it depends on typescript
before 2.4. This causes the following errors:
```
NativeScript@ typedoc /root/NativeScript
> typedoc --tsconfig tsconfig.typedoc.json --out bin/dist/apiref --includeDeclarations --name NativeScript --theme ./node_modules/nativescript-typedoc-theme --excludeExternals --externalPattern "**/+(tns-core-modules|module).d.ts"
Loaded plugin typedoc-plugin-external-module-name
Using TypeScript 2.2.2 from /root/NativeScript/node_modules/typedoc/node_modules/typescript/lib
Error: /root/NativeScript/tns-core-modules/module.d.ts(67)
In ambient enum declarations member initializer must be constant expression.
Error: /root/NativeScript/tns-core-modules/module.d.ts(68)
In ambient enum declarations member initializer must be …
```
=> chore(docs): Upgrade typedoc to version 0.13.0

apps/app/css-perf-test/main-page.ts, apps/app/cuteness.io/main-page.ts
Adding some missing whitespaces to fix lint errors.
=> Fix some lint errors

tns-core-modules/ui/core/view/view.android.ts
=> fix(modal): Fix crash if modal is destroyed before dismissed in Android

e2e/nested-frame-navigation/e2e/layout-root.e2e-spec.ts, tns-core-modules/ui/core/view/view.android.ts
Set the correct application theme while creating the dialog fragment. 
The current code `this.getTheme` always returns  `0` and does not set the correct theme for the fragment. 
Fixes https://github.com/NativeScript/NativeScript/issues/6690
=> set the correct application theme while creating the dialog fragment

tns-core-modules/LICENSE
skip ci
The LICENSE file is different from the main one - it should refer to Progress Software as the legal entity. The year is also updated.
Legal name and year are updated.
=> chore: update LICENSE for tns-core-modules

tns-core-modules/application/application.android.ts, tns-core-modules/ui/frame/activity.android.ts, tns-core-modules/ui/frame/frame.android.ts, tns-core-modules/ui/frame/frame.d.ts
Fixes: https://github.com/NativeScript/NativeScript/issues/6708
=> fix(android): raise resume event on activity.onPostResume()

CodingConvention.md
Some examples had "if(..." instead of the expected "if (...", this is only a documentation PR, it does not affect production code.
The Coding Convention says "Also, notice the use of whitespace before and after the condition statement." whereas in some of the examples the statements used are "if(...)" (missing space between if and opening parenthesis)
I added a space between the if and the opening parenthesis.
No issues found related to this, this is my first time contributing to an OSS project, are issues mandatory when creating a PR?
None, user documentation only
=> docs(coding-convention): if-statements examples not respecting the coding convention

tests/app/livesync/livesync-tests.ts, tns-core-modules/application/application-common.ts, tns-core-modules/application/application.android.ts, tns-core-modules/application/application.ios.ts, tns-core-modules/module.d.ts
There is a `HmrType` and `HmrContext`.
Rename them to more accurate `ModuleType` and `ModuleContext`.
=> refactor: rename HmrContext to ModuleContext

tns-core-modules/tns-core-modules.d.ts
It is no longer necessary. Fixes #6854.
=> Remove incomplete declaration of Array#filter.

tests/app/ui/styling/style-tests.ts, tns-core-modules/application/application-common.ts, tns-core-modules/application/application.ios.ts, tns-core-modules/module.d.ts, tns-core-modules/ui/core/view/view-common.ts, tns-core-modules/ui/core/view/view.d.ts, tns-core-modules/ui/frame/frame-common.ts, tns-core-modules/ui/frame/frame.android.ts, tns-core-modules/ui/styling/style-scope.d.ts, tns-core-modules/ui/styling/style-scope.ts
Currently, a style change in page `.css` or `.scss` navigates to the same page where the change is applied.
The new behavior uses the context passed by `nativescript-dev-webpack` to determinate whether changes have been made to page `.css` or `.scss` file. If so, apply them at runtime and avoid executing navigation to the same page.
This is an implementation for the scenarios where the root of the app is a `Frame`.
=> feat(HMR): apply changes in page styles at runtime

tns-core-modules/ui/text-base/text-base.ios.ts
Fixes: https://github.com/NativeScript/NativeScript/issues/6345
=> fix(ios-textview): text alignment reset to default on blur

tests/app/ui/search-bar/search-bar-tests-native.ios.ts, tests/app/ui/search-bar/search-bar-tests.ts, tns-core-modules/ui/search-bar/search-bar.ios.ts
fixes https://github.com/NativeScript/NativeScript/issues/6901
=> fix(ios): searcbar hint color before hint property

tns-core-modules/application/application.d.ts, tns-core-modules/ui/core/view/view.d.ts, tns-core-modules/ui/page/page.d.ts
They were removed in #6927 because we thought they were
unnecessary.
=> fix(angular): Re-add references to `tns-core-modules.d.ts`

e2e/nested-frame-navigation/app/home/home-page.ts, e2e/nested-frame-navigation/app/home/home-page.xml, e2e/nested-frame-navigation/app/some-page/some-page.ts, e2e/nested-frame-navigation/app/some-page/some-page.xml, e2e/nested-frame-navigation/app/still-other-page/still-other-page.ts, e2e/nested-frame-navigation/app/still-other-page/still-other-page.xml, e2e/nested-frame-navigation/e2e/frame-root.e2e-spec.ts, e2e/nested-frame-navigation/e2e/screen.ts, e2e/nested-frame-navigation/e2e/shared.e2e-spec.ts, tns-core-modules/ui/frame/fragment.transitions.android.ts
Fixes: https://github.com/NativeScript/NativeScript/issues/6985
Fixes: https://github.com/NativeScript/NativeScript/issues/7010
Fixes: https://github.com/NativeScript/nativescript-angular/issues/1744
=> fix: navigation b/n single and nested frame pages

tns-core-modules/application/application.android.ts
Throw a new error if no activity callbacks.
=> fix(Android): throw new Error if no activity callbacks

tns-core-modules/http/http-request/http-request.android.ts, tns-core-modules/http/http-request/http-request.ios.ts
=> refactor: restore lazy load requires in http module

tests/app/http/http-tests.ts
Removing `// >> http-post-json`, which breaks the docs build
=> removing `http-post-json`

apps/app/ui-tests-app/font/all-fonts.ts, tests/app/TKUnit.ts, tests/app/application/application-tests.ios.ts, tests/app/pages/page5.ts, tests/app/ui/date-picker/date-picker-tests-native.ios.ts, tests/app/ui/helper.ts, tests/app/ui/layouts/safe-area-tests.ts, tests/app/ui/time-picker/time-picker-tests-native.ios.ts, tns-core-modules/application-settings/application-settings.ios.ts, tns-core-modules/application/application.ios.ts, tns-core-modules/debugger/webinspector-network.ios.ts, tns-core-modules/file-system/file-system-access.ios.ts, tns-core-modules/fps-meter/fps-native.ios.ts, tns-core-modules/http/http-request/http-request.ios.ts, tns-core-modules/platform/platform.ios.ts, tns-core-modules/timer/timer.ios.ts, tns-core-modules/ui/animation/animation.ios.ts, tns-core-modules/ui/core/view/view.ios.ts, tns-core-modules/ui/date-picker/date-picker.ios.ts, tns-core-modules/ui/gestures/gestures.ios.ts, tns-core-modules/ui/image-cache/image-cache.ios.ts, tns-core-modules/ui/segmented-bar/segmented-bar.ios.ts, tns-core-modules/ui/styling/background.ios.ts, tns-core-modules/ui/styling/font.ios.ts, tns-core-modules/ui/time-picker/time-picker.ios.ts, tns-core-modules/ui/utils.ios.ts, tns-core-modules/utils/utils.d.ts, tns-core-modules/utils/utils.ios.ts
Deprecate utils.ios.getter and remove its usage from NativeScript repo.
=> refactor(ios): deprecate utils.ios.getter

tns-core-modules/ui/core/view/view.ios.ts, tns-core-modules/ui/page/page.ios.ts, tns-core-modules/ui/tab-view/tab-view.ios.ts
Fixes https://github.com/NativeScript/NativeScript/issues/7065
=> fix(ios): flat action bar incorrect layout after navigation

apps/app/ui-tests-app/issues/issue-5125.ts, apps/app/ui-tests-app/issues/issue-5125.xml, apps/app/ui-tests-app/issues/main-page.ts, tns-core-modules/ui/text-base/text-base.android.ts
Fixes: https://github.com/NativeScript/NativeScript/issues/5125
=>  fix(label-android): numeric text ignores text-transform

tns-core-modules-widgets/android/gradlew, tns-core-modules-widgets/android/gradlew.bat, tns-core-modules-widgets/android/widgets/gradlew, tns-core-modules-widgets/android/widgets/gradlew.bat
Related to https://github.com/NativeScript/android-runtime/issues/1349
Update gradlew to the latest version working with sh
=> chore: update gradlew

package.json
`npm i`  fails on non windows os because of `http-server` dev dependency.
`npm i` to pass.
See https://github.com/indexzero/http-server/issues/521
=> chore: remove http-server dependency

CHANGELOG.md, tns-core-modules/package.json, tns-platform-declarations/package.json
=> release: cut the 5.3.2 release

apps/app/ui-tests-app/tab-view/main-page.ts, apps/app/ui-tests-app/tab-view/tab-text-color.xml, tns-core-modules/ui/tab-view/tab-view.ios.ts
fixes https://github.com/NativeScript/NativeScript/issues/7166
=> fix(ios-tabview): crash when setting tab text color

e2e/animation/package.json, e2e/modal-navigation/package.json, e2e/nested-frame-navigation/package.json
Remove clashing `@types/node` dependency
=> chore: remove clashing typings

tns-core-modules/application/application.ios.ts, tns-core-modules/module.d.ts, tns-core-modules/ui/core/view/view-common.ts, tns-core-modules/ui/core/view/view.d.ts, tns-core-modules/ui/frame/frame-common.ts, tns-core-modules/ui/frame/frame.android.ts, tns-core-modules/ui/frame/frame.ios.ts, tns-core-modules/ui/page/page-common.ts
As https://github.com/NativeScript/NativeScript/pull/7146 broke it.
=> fix-next(HMR): apply changes in page styles when app root is frame

apps/app/ui-tests-app/button/button-border.css, apps/app/ui-tests-app/css/pixels.xml, apps/app/ui-tests-app/flexbox/flexbox.css, apps/app/ui-tests-app/issues/issue-3113.css
Leverages the new `androidElevation` property introduced with https://github.com/NativeScript/NativeScript/pull/7136 and reverts the ui test changes from https://github.com/NativeScript/NativeScript/pull/7055
=> chore: update ui tests with androidElevation

tns-core-modules/ui/button/button.android.ts, tns-core-modules/ui/core/view/view.android.ts
Fixes: https://github.com/NativeScript/NativeScript/issues/7249
=> fix(android): elevation should not require explicit dynamic elevation

apps/app/ui-tests-app/animation/animation-army-100.ts, apps/app/ui-tests-app/animation/animation-army-100.xml, apps/app/ui-tests-app/animation/animation-curves.ts, apps/app/ui-tests-app/animation/animation-curves.xml, apps/app/ui-tests-app/animation/effect-summary-details.ts, apps/app/ui-tests-app/animation/effect-summary-details.xml, apps/app/ui-tests-app/animation/height-basic.ts, apps/app/ui-tests-app/animation/height-basic.xml, apps/app/ui-tests-app/animation/layout-stack-height.ts, apps/app/ui-tests-app/animation/layout-stack-height.xml, apps/app/ui-tests-app/animation/main-page.ts, apps/app/ui-tests-app/animation/main-page.xml, apps/app/ui-tests-app/main-page.ts, apps/app/ui-tests-app/test-page-main-view-model.ts, tests/app/ui/animation/animation-tests.ts, tests/app/ui/styling/style-properties-tests.ts, tns-core-modules/globals/globals.ts, tns-core-modules/ui/animation/animation-common.ts, tns-core-modules/ui/animation/animation.android.ts, tns-core-modules/ui/animation/animation.d.ts, tns-core-modules/ui/animation/animation.ios.ts, tns-core-modules/ui/animation/keyframe-animation.ts, tns-core-modules/ui/styling/style-properties.d.ts, tns-core-modules/ui/styling/style-properties.ts
Original PR https://github.com/NativeScript/NativeScript/pull/4917 by @justindujardin that implements https://github.com/NativeScript/NativeScript/issues/1764.
=> feat(animation): support animating width/height properties

tns-core-modules-widgets/android/widgets/src/main/java/org/nativescript/widgets/CommonLayoutParams.java
Blind fix for a customer reported scenario with back navigation that we cannot reproduce consistently.
=> fix(android): CommonLayoutParams measure/layout child guard

CHANGELOG.md, tns-core-modules-widgets/package.json, tns-core-modules/package.json, tns-platform-declarations/package.json
=> release: cut the 5.4.1 release

tests/app/livesync/livesync-button-page.scss, tests/app/livesync/livesync-tests.ts, tns-core-modules/ui/frame/fragment.transitions.android.ts, tns-core-modules/ui/frame/frame-common.ts, tns-core-modules/ui/frame/frame.android.ts, tns-core-modules/ui/frame/frame.d.ts, tns-core-modules/ui/frame/frame.ios.ts, tns-core-modules/ui/page/page.ios.ts
Fixes: https://github.com/NativeScript/NativeScript/issues/7294
=> fix(hmr): support for multi module replacement

build/tslint.json, package.json, tns-platform-declarations/android/androidx-17.d.ts, tns-platform-declarations/android/androidx-23.d.ts, tns-platform-declarations/android/androidx-26.d.ts, tns-platform-declarations/android/androidx-28.d.ts
Android typings does not include information for deprecated methods.
To know when a method is deprecated when using android api.
Implements #7363.
=> feat: Update android typings to include @deprecated attributes

CHANGELOG.md, tns-core-modules/package.json, tns-platform-declarations/package.json
=> release: cut the 5.4.3 release

e2e/ui-tests-app/app/css/test-page.css, e2e/ui-tests-app/app/tab-view/tab-view-more-page.css, e2e/ui-tests-app/app/tab-view/tab-view-more-page.xml, e2e/ui-tests-app/app/web-view/query-params-page.ts, e2e/ui-tests-app/app/web-view/web-view-test-page.xml, tns-core-modules/image-source/image-source.ios.ts
A few updates related to the *bundle workflow* and `ui-tests-app`: https://github.com/NativeScript/NativeScript/issues/7320.
=> tests(ui-tests-app): update examples

tns-core-modules/ui/bottom-navigation/bottom-navigation.android.ts
[Android] Fix crash when switching between tabs with or withouth Frame
[Android] Fix crash when app suspend/resume then selecting/reselecting tab
=> fix(bottom-navigation): current TabContentItem index not set

tns-core-modules/ui/tabs/tabs.ios.ts
Note 1: `tabBar.delegate` was cleared after some time. Storing it in a local var and clearing on dispose.
Note 2: Enable tabStrip items selection only if no current animation in progress.
Fix https://github.com/NativeScript/NativeScript/issues/7435
Fix -> Changing fast tabStrip items causes glitches and content items problem
=> fix(ios-tabs): tabstripitem tap does not change tabs

tns-core-modules/ui/frame/fragment.transitions.android.ts
Fixes: https://github.com/NativeScript/NativeScript/issues/7481
=> refactor(android): no transition duration to 1ms

tns-core-modules/ui/bottom-navigation/bottom-navigation.android.ts, tns-core-modules/ui/bottom-navigation/bottom-navigation.ios.ts, tns-core-modules/ui/tabs/tabs.ios.ts
This pull request refactors strip item creation for both Android and iOS.
Implements https://github.com/NativeScript/nativescript-angular/issues/1893.
Rebase and merge after https://github.com/NativeScript/NativeScript/pull/7466.
=> refactor(bottom-navigation): strip item creation

tns-core-modules/package.json, tns-core-modules/ui/bottom-navigation/bottom-navigation.android.ts, tns-core-modules/ui/tabs/tabs.android.ts, tns-platform-declarations/package.json
Bump tns-core-modules and tns-platform-declaration version to 6.0.1
=> fix(bottom-navigation-android): tabStripItem backgroundColor

tns-core-modules-widgets/android/widgets/src/main/java/org/nativescript/widgets/TabLayout.java, tns-core-modules/ui/tabs/tabs.android.ts
Fix https://github.com/NativeScript/NativeScript/issues/7519
=> fix(tabs-android): wrong tabStripItem selected

tns-core-modules/package.json, tns-platform-declarations/package.json
=> chore: bump package versions

tsconfig.typedoc.json
=> fixing docs build

CHANGELOG.md, tns-core-modules/package.json, tns-platform-declarations/package.json
Release tns-core-modules@6.0.5
=> release: cut the 6.0.5 release

e2e/file-qualifiers/app/App_Resources/Android/src/main/res/values/strings.xml, e2e/file-qualifiers/app/app.css, e2e/file-qualifiers/app/app.land.css, e2e/file-qualifiers/app/main/main-page.land.xml, e2e/file-qualifiers/app/main/main-page.xml, e2e/file-qualifiers/app/other/other-page.land.xml, e2e/file-qualifiers/app/other/other-page.xml, e2e/file-qualifiers/nsconfig.json, e2e/file-qualifiers/package.json, e2e/file-qualifiers/webpack.config.js, tests/app/ui/label/label-tests.ts, tns-core-modules/module-name-resolver/module-name-resolver.ts, tns-core-modules/module-name-resolver/non-bundle-workflow-compat.ts, tns-core-modules/trace/trace.d.ts, tns-core-modules/trace/trace.ts, tns-core-modules/ui/builder/module-name-sanitizer.ts, tns-core-modules/ui/styling/style-scope.ts
Enable missing CSS check and that were disabled in #7499 and #7501
=> refactor: Enable missing css check and test

tns-core-modules/module-name-resolver/non-bundle-workflow-compat.ts
Handle empty folders in non-bundle-workflow-compat.
Empty folders are sometimes leftovers form previous apps in playground/preview application. If this is the case we should keep looking for modules to register.
=> fix: handle empty folders in non-bundle-compat

e2e/cuteness.io/package.json
nativescript@6.0 require typescript 3.4.5 or above.
=> chore: make cuteness compatible with 6.0 cli

tests/app/livesync/livesync-modal-view-page.ts, tests/app/livesync/livesync-modal-view-page.xml, tests/app/livesync/livesync-tests.ts, tns-core-modules/ui/core/view/view-common.ts, tns-core-modules/ui/core/view/view.d.ts
Any opened modal views are not updated or closed during HMR livesync
Any opened modal views are closed during HMR livesync
https://github.com/NativeScript/NativeScript/issues/7668
=> fix(hmr): close modal views during livesync #7668

tns-core-modules/ui/tabs/tabs.ios.ts
The new Tabs component crashed on iOS 10 and 9, because of usage of APIs that were removed on these versions (the safe area insets APIs).
Fixes iOS 10 and 9 tests on CI. Should test on these versions.
=> fix(ios): handle tabs extended layout for ios 10

tests/app/globals/globals-tests.ts, tests/app/test-runner.ts, tns-core-modules/globals/core/globals-core.ts
Return the the `System.import` polyfill that was accidentally removed [here](https://github.com/NativeScript/NativeScript/pull/7505/files#diff-45ac627cb7cf62128c2c13b0cc00b064L35-L45).
=> fix-next: Add accidentally removed System.import

e2e/ui-tests-app/app/bottom-navigation/binding-page.xml, e2e/ui-tests-app/app/bottom-navigation/bottom-navigation-page.xml, e2e/ui-tests-app/app/bottom-navigation/fancy-fonts-page.xml, e2e/ui-tests-app/app/bottom-navigation/icon-change-page.xml, tns-core-modules/ui/bottom-navigation/bottom-navigation.ios.ts, tns-core-modules/ui/tabs/tabs.ios.ts
Fixes https://github.com/NativeScript/NativeScript/issues/7733
=> feat(ios): add icon rendering mode for bottom navigation

tns-core-modules/ui/list-picker/list-picker.android.ts
Note that Android ListPicker.color property had some weird get/set arguments and return values that I have now removed because as far as I can see:
- These were never documented as public API, could not find any sample usage, or references anywhere
- Setting different values for wheelColor and textColor worked only on initial load of the compoent, once you started scrolling textColor was lost and the input text was painted with wheelColor
- Now that api29 introduces proper public methods for manipulating this functionality, it exposed a single NumberPicker.setTextColor(...) native method that sets both wheelColor and textColor (in the older terms).
Fixes: https://github.com/NativeScript/NativeScript/issues/7785
=> fix(android-list-picker): NoSuchFieldException on api29

tns-core-modules/ui/core/properties/properties.ts
"reduce-css-calc" is imported via default export, breaks in published `tns-core-modules@6.1.0`.
Causes errors like this:
```bash
JS: Error: Failed to evaluate css-calc for property [font-size] for expression [calc(18 * 1)] to Button(7)@main-page.xml:29:9;. TypeError: reduce_css_calc_1.default is not a function
JS:     at Object._evaluateCssCalcExpression (file:///node_modules/tns-core-modules/ui/core/properties/properties.js:85:0)
JS:     at evaluateCssExpressions (file:///node_modules/tns-core-modules/ui/styling/style-scope.js:40:0)
JS:     at CssState.push.../node_modules/tns-core-modules/ui/styling/style-scope.js.CssState.setPropertyValues (file:///node_modules/tns-core-modules/ui/styling/style-scope.js:460:0)
JS:     at file:///node_modules/tns-core-modules/ui/styling/style-scope.js:38 …
```
=> fix(css-calc): reduce_css_calc_1.default is not a function

DevelopmentWorkflow.md
update workflow info - `tns-core-modules`
=> docs: update workflow info - tns-core-modules

tns-core-modules/ui/core/properties/properties.ts
Cherry-pick https://github.com/NativeScript/NativeScript/pull/7787
=> fix(css-calc): reduce_css_calc_1.default is not a function (#7787)

CHANGELOG.md, tns-core-modules/package.json, tns-platform-declarations/package.json
=> release: cut the 6.1.1 release

tests/app/ui/test-pages/bindingExpressions_logicalComparisonOperators_testPage.xml
=> Escape amp in tests release

README.md
updated slack channel link in Readme file
=> docs: Updated slack channel link

tns-core-modules/bundle-entry-points.ts, tns-core-modules/color/color-common.ts, tns-core-modules/fetch/fetch.js, tns-core-modules/js-libs/polymer-expressions/polymer-expressions.js, tns-core-modules/ui/frame/frame-common.ts
Remove all left short imports in the codebase.
=> chore: remove short imports

DevelopmentWorkflow.md
Related to https://github.com/NativeScript/NativeScript/issues/7905
=> chore: update dev workflow

tns-core-modules/application/application-common.ts, tns-core-modules/application/application.android.ts, tns-core-modules/application/application.d.ts, tns-core-modules/application/application.ios.ts, tns-core-modules/css/system-classes.d.ts, tns-core-modules/css/system-classes.ts, tns-core-modules/ui/bottom-navigation/bottom-navigation.ios.ts, tns-core-modules/ui/core/view/view.d.ts, tns-core-modules/ui/core/view/view.ios.ts, tns-core-modules/ui/enums/enums.d.ts, tns-core-modules/ui/enums/enums.ts, tns-core-modules/ui/frame/frame.android.ts, tns-core-modules/ui/frame/frame.ios.ts, tns-core-modules/ui/page/page.ios.ts, tns-core-modules/ui/tab-view/tab-view.ios.ts, tns-core-modules/ui/tabs/tabs.ios.ts
Implements
expose a `systemAppearance` property to the application module,
expose a `systemAppearanceChanged` event
of https://github.com/NativeScript/NativeScript/issues/7800.
=> feat(dark-mode): add system appearance property, event and CSS classes

tns-core-modules/application/application.android.ts, tns-core-modules/application/application.d.ts, tns-core-modules/application/application.ios.ts
As per the problem I reported here:
https://github.com/NativeScript/theme/issues/179
When using component scoped CSS there is no need to trigger a full global refresh of the styles.
This change does *not* affect performance or function of using `encapsulation: ViewEncapsulation.None` on a component.
This PR goes hand in hand with a [modification to `nativescript-angular`](https://github.com/NativeScript/nativescript-angular/pull/1999) to employ the below changes (PR coming up right after this).
=> feat(css): add attribute scoped css without global refresh

DevelopmentWorkflow.md, e2e/ui-tests-app/e2e/suites/tab-navigation/tab-view/tab-view-css-properties.e2e-spec.ts, tns-core-modules/ui/action-bar/action-bar-common.ts, tns-core-modules/ui/action-bar/action-bar.android.ts, tns-core-modules/ui/action-bar/action-bar.ios.ts
iOS counterpart of https://github.com/NativeScript/NativeScript/pull/7842
=> fix(action-bar-ios): navigation button support for font icons

tns-core-modules/ui/action-bar/action-bar.ios.ts
Related to https://github.com/NativeScript/ios-runtime/issues/1210#issuecomment-542569926
=> fix(action-bar-ios13): action bar items population

.gitignore
Some windows users will accidentally push `thumbs.db` file to the repo and may trouble other windows users.
Now Windows users can submit a PR and `thumbs.db` file will not get pushed.
=> chore: add thumbs.db to .gitignore

nativescript-core/ui/core/view/view.android.ts, nativescript-core/ui/frame/fragment.transitions.android.ts
Kudos to @vakrilov for tracking this!
=> refactor: android.R to const for perf reasons

.travis.yml, CONTRIBUTING.md, package.json
Added automatic check for changes in public API
=> chore: add api-report check to travis

build-docs.sh
fixing API ref  build script - docs
=> fix: fixing API ref  build script - docs

tns-core-modules-package/tns-core-modules.d.ts
Just removed extra symbol in declaration comment and added new line at the end
=> chore: d.ts file cleanup

tns-core-modules-widgets/android/widgets/src/main/java/org/nativescript/widgets/Async.java
Cherry-picked https://github.com/NativeScript/NativeScript/pull/8061
=> fix(android): Fatal Exception: java.lang.OutOfMemoryError (#8061)

nativescript-core/ui/frame/frame.android.ts
Fix https://github.com/NativeScript/NativeScript/issues/8094
=> fix(frame): nested frame wrong background after parent navigation

CHANGELOG.md
Corrected Spelling mistake of Permissions
=> docs(changelog): typo

nativescript-core/ui/frame/frame-common.ts, nativescript-core/ui/frame/frame.android.ts
Fix https://github.com/NativeScript/NativeScript/issues/7594 https://github.com/NativeScript/NativeScript/issues/8048
=> fix(frame): push recreated frame back in frameStack when Don't Keep Activities enabled

nativescript-core/package.json, tns-core-modules-package/package.json, tns-core-modules-widgets/package.json, tns-platform-declarations/package.json
=> chore: cut 6.2.3 release

nativescript-core/globals/polyfills/dialogs/dialogs.ts, nativescript-core/module.d.ts, nativescript-core/ui/builder/component-builder/component-builder.ts, nativescript-core/ui/frame/frame.d.ts, nativescript-core/xml/xml.ts
Replace legacy mentions of `tns-core-modules`
=> chore: remove mentions of tns-core-modules

CONTRIBUTING.md
Fix code blocks in CONTRIBUTING.md
=> docs: fix codeblocks

build/prepare-compat.sh, nativescript-core/platforms/ios/Podfile
Updated MaterialComponents pod version to '~> 94.5'
Related to #7928
=> chore: update MaterialComponents pod

CHANGELOG.md, e2e/scoped-packages/package.json
=> chore: cut 6.3.0 release

CHANGELOG.md, nativescript-core/package.json, tns-core-modules-package/package.json, tns-core-modules-widgets/package.json, tns-platform-declarations/package.json
=> chore: cut release 6.3.2

tests/app/ui/image-cache/image-cache-tests.ts
The image-cache tests are using the `TKUnit.waitUntilReady` method to wait for the expected result.
The image-cache tests are using the async API.
=> test: make image-cache tests async

api-reports/NativeScript.api.md, e2e/ui-tests-app/app/css/all-non-uniform-border-page.css, e2e/ui-tests-app/app/css/all-non-uniform-border-page.xml, nativescript-core/color/color-common.ts, nativescript-core/color/color.d.ts, nativescript-core/color/color.ios.ts, nativescript-core/ui/html-view/html-view-common.ts, nativescript-core/ui/html-view/html-view.android.ts, nativescript-core/ui/html-view/html-view.ios.ts
- Customizing the font, text color and link color using CSS is not supported.
- Text is not selectable on Android.
- Unnecessary left padding on IOS.
- Allow to set text color with `color` CSS property.
- Allow to set link color with `link-color` CSS property.
- Allow to set font attributes with `font-family` and `font-size` CSS properties.
- Make text selectable on Android by default (for consistency with IOS).
- Remove extra padding on IOS.
Implements #1266
Related:  #1268 #4358 #4746
The appearance of `HtmlView` component may change in existing apps.
=> feat(html-view): Additional properties for HtmlView component

tns-core-modules-widgets/android/widgets/src/main/java/org/nativescript/widgets/Async.java
Fix http requests to use read timeout in addition to connect timeout.
Http timeout doesn't work as expected [#6523 ](https://github.com/NativeScript/NativeScript/issues/6523). When timeout is set, the request times out only if connection is not established within the timeout threshold. 
When timeout is set, the request will time out when the request has not completed within the timeout threshold. This can be due to failed connection or a response that takes too long to finish.
Fixes/Implements/Closes [#6523 ](https://github.com/NativeScript/NativeScript/issues/6523).
I'm not sure how I should proceed with regard to writing the tests for a few reasons:
- In what module should I write the test(s)? http?
- I don't have an iOS device to test with.
- To test that a request connects but then …
=> fix(android): Request Timeout #6523

nativescript-core/ui/page/page.ios.ts
The `preferredStatusBarStyle` property is implemented by the `UIViewControllerImpl` in `Page`
Related to #7153
=> feat(ios): set preferredStatusBarStyle in Page VCs

nativescript-core/ui/date-picker/date-picker.ios.ts
Fixes https://github.com/NativeScript/NativeScript/issues/8264
=> fix(ios): date picker owner not updating its comps on iOS

nativescript-core/platforms/ios/native-api-usage.json, tests/app/App_Resources/iOS/native-api-usage.json
refs https://github.com/NativeScript/nativescript-cli/issues/5220
=> feat: Add iOS APIs usage list

nativescript-core/ui/frame/fragment.transitions.android.ts
Fixes https://github.com/NativeScript/NativeScript/issues/8100
=> fix: flipLeft and flipRight on Android

Modules30Changes.md
Corrected spelling mistakes in file Modules30Changes.md: 
changed "popery" to "property" and "ot" to "of"
=> docs: fix typo

build/generate-barrel-dts.sh, build/pack-compat.sh, build/prepare-core.sh, package.json, tns-platform-declarations/package.json
Modify build script to always use local typescript.
=> chore(build): always use local typescript

nativescript-core/ui/styling/background.android.ts
=> fix: guard cachedDrawable

nativescript-core/package.json
=> fix(build): Add platforms/android to NPM package

CHANGELOG.md, e2e/scoped-packages/package.json, nativescript-core/package.json, tns-core-modules-package/package.json, tns-platform-declarations/package.json
=> release: cut the 6.4.1 release

tns-core-modules-widgets/package.json
bump tns-core-modules-widgets version
=> chore: bump tns-core-modules-widgets version

nativescript-core/globals/register-module-helpers.ts
`.kt` extensions are not recognized
Adds the `.kt` extension to known ones, just like `.ts`
Related to: https://github.com/NativeScript/NativeScript/issues/5379
=> feat: Add .kt extension to  known extensions map

nativescript-core/xhr/xhr.ts
Related to https://github.com/NativeScript/NativeScript/issues/8357
=> fix: XHR readystatechange event

CHANGELOG.md, build/generate-barrel-dts.sh, build/pack-compat.sh, build/prepare-core.sh, nativescript-core/package.json, nativescript-core/ui/bottom-navigation/bottom-navigation.android.ts, nativescript-core/ui/frame/fragment.transitions.android.ts, nativescript-core/ui/tab-navigation-base/tab-strip-item/tab-strip-item.ts, nativescript-core/ui/tabs/tabs.android.ts, package.json, tns-platform-declarations/package.json
=> Release to master

CHANGELOG.md
=> chore: release 6.4.2

nativescript-core/ui/bottom-navigation/bottom-navigation.android.ts, tns-core-modules-widgets/android/widgets/src/main/java/org/nativescript/widgets/BottomNavigationBar.java, tns-core-modules-widgets/android/widgets/src/main/java/org/nativescript/widgets/TabItemSpec.java, tns-platform-declarations/android/org.nativescript.widgets.d.ts
=> fix(bottom-nav): align text with different icons

e2e/ui-tests-app/app/bottom-navigation/dynamic-color-change-page.css, e2e/ui-tests-app/app/bottom-navigation/dynamic-color-change-page.ts, e2e/ui-tests-app/app/bottom-navigation/dynamic-color-change-page.xml, e2e/ui-tests-app/app/bottom-navigation/main-page.ts, e2e/ui-tests-app/app/tabs/dynamic-color-change-page.css, e2e/ui-tests-app/app/tabs/dynamic-color-change-page.ts, e2e/ui-tests-app/app/tabs/dynamic-color-change-page.xml, e2e/ui-tests-app/app/tabs/main-page.ts, e2e/ui-tests-app/e2e/suites/tab-navigation/bottom-navigation/bottom-navigation.e2e-spec.ts, e2e/ui-tests-app/e2e/suites/tab-navigation/tabs/tabs-tests.e2e-spec.ts, nativescript-core/ui/bottom-navigation/bottom-navigation.android.ts, nativescript-core/ui/tabs/tabs.android.ts, nativescript-core/ui/tabs/tabs.ios.ts
Fixed dynamically setting tabs/bottom navigation colors.
Fixes #8459.
=> fix(tabs): dynamic styling colors fixed

CHANGELOG.md, nativescript-core/package.json, tns-core-modules-package/package.json, tns-platform-declarations/package.json
=> chore: cut the 6.5.1 release

e2e/file-qualifiers/app/App_Resources/Android/src/main/AndroidManifest.xml
If you have the WRITE_EXTERNAL_STORAGE permission you don't need [READ_EXTERNAL_STORAGE](https://developer.android.com/reference/android/Manifest.permission#READ_EXTERNAL_STORAGE)
=> build: remove unecessary permission grant

nativescript-core/ui/text-base/text-base.android.ts
=> fix: call to nativeView

e2e/ui-tests-app/app/button/tappable-span-page.ts, e2e/ui-tests-app/app/button/tappable-span-page.xml
Added a test that was missed in the following PR #8256.
=> test: added missing page

nativescript-core/ui/text-field/text-field.ios.ts
This is a simple refactoring in the sense that now the intelligence of the `UITextFieldDelegate` is in the `TextField` class.
This is a really nice addition for plugin developers like me.
For example in `nativescript-material-textfield` i wanted to add a feature to limit digits that a textfield can accept.
This has to be handled in the delegate. Right now i have to rewrite and duplicate the whole delegate code from {N}  to keep the feature of the {N} Textfield. It also means maintaining the delegate through {N} updates.
This makes it possible to simply "override" the delegate methods from your subclass of `TextField`
The only unknown there is, should those delegate functions be added in the typings
=> chore: refactor for easy subclassing and new features

nativescript-core/ui/core/view/view.ios.ts
https://github.com/NativeScript/nativescript-cli/issues/5293
Fixes https://github.com/NativeScript/nativescript-cli/issues/5293.
=> fix: fix ios hmr

CHANGELOG.md
Add changelog for 6.5.2 release.
=> chore: changelog for 6.5.2

README.md
=> docs: Added Easy Navigation Badge in README.md

nativescript-core/ui/gestures/gestures.ios.ts
closes https://github.com/NativeScript/NativeScript/issues/8641
=> fix(ios): gesture handling resilience when views are destroyed quickly

nativescript-core/ui/text-base/span.ts
closes https://github.com/NativeScript/NativeScript/issues/8647
=> fix(span): value handling for strings and numbers

nativescript-core/ui/text-view/text-view.ios.ts
As done in https://github.com/NativeScript/NativeScript/pull/8514 for the text-field this PR refactors ios text-view so that methods can be overriden in own implementations.
=> chore(text-view): refactor ios for easy subclassing

nativescript-core/ui/text-base/text-base.android.ts
=> fix(snapshots): android is not defined

nativescript-core/ui/dialogs/dialogs.d.ts, nativescript-core/ui/dialogs/dialogs.ios.ts
User can create default actions in iOS.
User can now create destructive actions in iOS as well.
Implements #6749. Related to #3830, #5553.
=> feature(ios/core/dialog): set destructive style from options

nativescript-core/ui/tabs/tabs-common.ts, nativescript-core/ui/tabs/tabs.android.ts, nativescript-core/ui/tabs/tabs.ios.ts, tns-core-modules-widgets/android/widgets/src/main/java/org/nativescript/widgets/TabViewPager.java
=> feat(tabs): add animationEnabled property

apps/app/modaltest/main-page.ts, apps/app/modaltest/modal-tab.ts, apps/app/modaltest/page.2.ts
=> Refactor modaltest ts files

nativescript-core/package.json, nativescript-core/ui/list-picker/list-picker.android.ts, package.json, tns-core-modules-package/package.json, tns-platform-declarations/package.json
=> fix(android): list picker getTextColor api level issue

packages/webpack/package.json, packages/webpack/templates/webpack.react.js
* Working React config for NativeScript 7
/cc @shirakaba
=> fix(webpack): react config

packages/webpack/verify/update.js
=> fix: runtime module error

packages/types-android/src/lib/android/org.nativescript.widgets.d.ts
=> added missing typing for TabViewPager

packages/core/data/observable/index.ts
Using "Tap" as the example event, but this actually applies to **ALL** events.
The new Global Events, does not allow you to capture __ALL__ "Tap" events easily, it is currently setup to allow you to only get all "Tap" events on a specific class you use its `on` function.  So if you do `Button.on('tap', ...)` you will catch all Tap events on all Buttons, but no other elements "Tap" events will be captured without you manually adding them also using there `on` handler.  
This updates the code so you can now ALSO do `Observable.on('tap', ...)` and you will see ALL `Tap` events on ALL elements since you are registering the event on the base observable class.
=> feat: global support for Global Events

nativescript-core/ui/date-picker/date-picker.ios.ts, nativescript-core/ui/time-picker/time-picker.ios.ts, tns-platform-declarations/ios/objc-x86_64/objc!UIKit.d.ts
TimePicker/DatePicker crashes on iOS 14
Does not crash
Fixes/Implements/Closes #8862
=> fix(ios): time-picker and date-picker for iOS 14

packages/core/ui/text-base/text-base-common.ts
Explains for future generations why this getter exists.  :grinning:
=> chore: comment for why nativeTextViewProtected

nativescript-core/ui/date-picker/date-picker-common.ts, nativescript-core/ui/date-picker/date-picker.d.ts, nativescript-core/ui/date-picker/date-picker.ios.ts, nativescript-core/ui/time-picker/time-picker-common.ts, nativescript-core/ui/time-picker/time-picker.d.ts, nativescript-core/ui/time-picker/time-picker.ios.ts
=> fix(ios): preferredDatePickerStyle

packages/core/ui/frame/fragment.android.ts
Might fix https://github.com/NativeScript/NativeScript/issues/8918
=> fix wrong method being called

packages/ui-mobile-base/ios/TNSWidgets/TNSWidgets.xcodeproj/project.pbxproj
This change permit to enable Bitcode on apps that use NS.
=> Enable BITCODE

packages/webpack/helpers/projectFilesManager.js, packages/webpack/helpers/projectHelpers.js, packages/webpack/templates/webpack.config.spec.ts, packages/webpack/templates/webpack.svelte.js
Depends on:
https://github.com/NativeScript/nativescript-cli/pull/5418
https://github.com/NativeScript/nativescript-app-templates/pull/170
N/A
Added svelte webpack config template
=> feat(webpack): add svelte support

packages/core/animation-frame/index.ts, packages/core/utils/macrotask-scheduler.ts
related to this https://github.com/NativeScript/NativeScript/pull/8904#issuecomment-726239927
=> Fix trace path issue

.eslintrc.json, packages/core/css/parser.ts, packages/core/profiling/index.ts, packages/core/ui/animation/animation-common.ts, packages/core/ui/builder/binding-builder.ts, packages/core/utils/utils-common.ts
this fixes the regression discovered here https://github.com/NativeScript/NativeScript/pull/9017#issuecomment-726242266
=> fix: rollback regexp eslint changes

packages/core/css/parser.ts
Automated Test w/ background image fails do to a change in PR#9001
- This fixes the automated test that was broken by PR#9001
- Revert some of the RegEx's from PR #9028 / #9017 
- Added notes for some weird code that was being flagged as unitialized
- Minor Cleanup in the parser file
=> fix: parser broken in prior PR's

packages/core/ui/frame/frame-common.ts, packages/core/ui/frame/index.d.ts
very practical when you want to know the state of the navigation at  higher level.
Like a drawer menu
=> add frame navigation events

packages/webpack5/__tests__/configuration/__snapshots__/svelte.spec.ts.snap, packages/webpack5/__tests__/configuration/svelte.spec.ts, packages/webpack5/package.json, packages/webpack5/src/configuration/svelte.ts
=> feat: svelte config

e2e/ui-tests-app/app/tabs/frame-in-tabs-inner-page-1.xml, e2e/ui-tests-app/app/tabs/frame-in-tabs-overflow.xml, e2e/ui-tests-app/app/tabs/main-page.ts, nativescript-core/ui/tabs/tabs.ios.ts
=> backport: fix(tabs): ios safeArea calculation

packages/webpack5/src/configuration/base.ts, packages/webpack5/src/configuration/svelte.ts, packages/webpack5/src/helpers/copyRules.ts
Those are a bunch of fixes that i found while testing webpack 5
=> Webpack5 fixes

apps/ui/src/tabs/frame-in-tabs-inner-page-1.xml, apps/ui/src/tabs/frame-in-tabs-overflow.xml, apps/ui/src/tabs/main-page.ts, packages/core/ui/tabs/index.ios.ts
=> fix(tabs): ios safeArea calculation

packages/webpack/package.json, packages/webpack/templates/webpack.angular.js, packages/webpack/templates/webpack.javascript.js, packages/webpack/templates/webpack.svelte.js, packages/webpack/templates/webpack.typescript.js, packages/webpack/templates/webpack.vue.js
HMR non-functional
HMR functional
Closes https://github.com/shirakaba/react-nativescript/issues/65
Closes #8849
Not aware of any breaking changes; this is fixing a regression more than anything.
=> fix: roll back CopyWebpackPlugin to v4.6.0

packages/core/platform/index.d.ts
=> fix(core): const initializer in an ambient context

packages/core/ui/core/view/index.d.ts
=> types: missing typings for iosIgnoreSafeArea

CHANGELOG.md, package.json, packages/core/index.d.ts, packages/core/index.ts, packages/core/package.json, packages/core/ui/bottom-navigation/index.android.ts, packages/core/ui/core/view/index.d.ts, packages/ui-mobile-base/package.json, packages/webpack/helpers/angular-config-parser.js, packages/webpack/package.json, tools/scripts/build-docs.sh
=> ci: fix npm_install for core on CI (docs)

nativescript-core/ui/bottom-navigation/bottom-navigation.android.ts
=> fix(android): BottomNavigation fragment child already has a parent

packages/core/ui/editable-text-base/editable-text-base-common.ts, packages/core/ui/editable-text-base/index.android.ts, packages/core/ui/editable-text-base/index.d.ts, packages/core/ui/editable-text-base/index.ios.ts
this add support for `setSection` for all editable text components
=> feat: setSelection method for editable text components

packages/core/color/color-common.ts, packages/core/color/index.d.ts
Should fill most needs and remove the need for external libs like tinycolor
Also the constructor support passing a `Color` object or a `Color` "json" object
=> feat(core): convenient color utility methods to avoid additional external libs

packages/core/ui/styling/style-scope.ts
very simple change preventing unecessary batchUpdate
=> fix: no need for batchUdated if no selector

CODE_OF_CONDUCT.md
=> Added Code of conduct to project

packages/webpack5/src/platforms/ios.ts
=> fix: correctly sanitize project name like cli does

.github/workflows/apps_automated.yml, apps/automated/src/globals.d.ts, apps/automated/src/test-runner.ts, apps/automated/src/timer/timer-tests.ts, apps/automated/src/ui/button/button-tests-native.android.ts, apps/automated/src/ui/label/label-tests-native.android.ts, apps/automated/src/ui/label/label-tests.ts, apps/automated/src/ui/text-field/text-field-tests-native.android.ts, apps/automated/src/ui/text-view/text-view-tests-native.android.ts, apps/automated/webpack.custom.config.js, package.json, packages/core/ui/styling/background.android.ts, tools/scripts/run-automated.js
TIMER tests are flaky, we may want to try a different strategy to test timers, perhaps with https://github.com/sinonjs/fake-timers or something similar.
=> ci: run apps/automated on CI

tools/scripts/run-automated.js
=> ci: implement timeout for run-automated

apps/toolbox/src/box-shadow.ts, packages/core/ui/styling/background-common.ts, packages/core/ui/styling/background.android.ts, packages/core/ui/styling/background.d.ts, packages/core/ui/styling/background.ios.ts, packages/core/ui/styling/style-properties.ts
=> feat(core): box shadow property update

.gitignore, package.json
=> feat: add npm scripts for different package managers

packages/core/ui/index.ts
Added missing export for AndroidTransitionType.
=> chore: add export AndroidTransitionType

packages/core/ui/bottom-navigation/index.android.ts
=> fix(bottom-navigation): fragment handling

apps/toolbox/src/pages/root-layout.ts
=> fix(apps): update rootlayout page class name

packages/core/ui/layouts/root-layout/root-layout-common.ts
=> fix(layouts): fix rootlayout not closing when no shadecover transition specified

packages/webpack5/src/configuration/base.ts
=> fix: read __CSS_PARSER__ from config

packages/core/accessibility/index.ios.ts
closes https://github.com/NativeScript/NativeScript/issues/9317
=> fix(a11y): ios voiceover crash during touch

packages/webpack5/src/helpers/copyRules.ts
=> fix: prevent App_Resources from being copied

.eslintrc.json, tsconfig.eslint.json
This simply plugs eslint and prettier together. That way when you lint with eslint it also fixes indentations and such
=> chore: combine prettier with eslint

packages/core/ui/core/view-base/index.d.ts
showModal typings were not correct.
showModal typings are correct.
=> fix(core): typings for showModal correction

package.json, tools/scripts/api-extractor.json, tools/scripts/build-docs.sh, tools/scripts/tsconfig.typedoc.json
Upgraded build script for api reference generation for {N} 8
=> feat: typedoc api reference

package.json, tools/scripts/tsconfig.typedoc.json
Updated nativescript-typedoc-theme to 1.0.0
=> chore: typedoc theme 1.0.0

packages/core/accessibility/accessibility-css-helper.ts, packages/core/accessibility/font-scale-common.ts
Fixes/Implements/Closes #9336.
=> fix(a11y): font size

packages/core/ui/styling/css-shadow.ts
The shadow is removed when `box-shadow: none` is applied.
Fixes #9414.
=> fix: box shadow 'none' support

packages/core/ui/web-view/index.ios.ts
When working with a website via the WebView that has JavaScript enabled links which use window.open or target="_blank" the current WebView would ignore taps on those links. For example a custom client oauth login screen with JavaScript bound `a` links to open Terms.
This wires up the delegate to ensure loadStarted fires for these actions so developers can handle properly. More context/details here: https://stackoverflow.com/a/25853806/2192332
=> feat(WebView): allow JS bound window frame navigation to be intercepted through loadStarted

packages/webpack5/src/configuration/angular.ts
NativeClass doesn't get transformed
NativeClass gets transformed
=> fix(webpack5): add AngularWebpackPlugin transformers

packages/core/ui/styling/css-selector/index.ts, packages/core/ui/styling/style-scope.ts
=> fix: stop leaking style scopes

packages/core/profiling/index.ts
Important logs don't accept other arguments.
Allow passing arguments for important logs
Fixes/Implements/Closes #8657.
Thanks for your collaboration! <3
=> fix(log): Allow passing optional params for logs

packages/core/index.d.ts, packages/core/index.ts
setAutoSystemAppearanceChanged isn't exported
setAutoSystemAppearanceChanged is exported
=> fix(core): correctly export setAutoSystemAppearanceChanged

packages/core/ui/text-base/index.android.ts
Another fix related to `nativeTextViewProtected`. Reported here https://github.com/nativescript-community/ui-material-components/issues/319
=> fix: more text base fixes for plugins using `nativeTextViewProtected`

packages/core/ui/action-bar/index.ios.ts
=> fix(core): actionBar to use appearance api on ios13+

packages/core/ui/action-bar/index.ios.ts
https://github.com/NativeScript/NativeScript/pull/9530
Also fixes the title color.
=> fix(ios): actionBar title to use appearance api on ios15+

README.md
I have done some minor grammatical changes in readme file, and simplified some sentences which was creating a little bit problem from the contributors to understand.
=> Fix:(README.md)some grammatical misktakes and simplified it 

packages/core/ui/frame/frame-common.ts, packages/core/ui/frame/index.android.ts, packages/core/ui/frame/index.ios.ts, packages/webpack5/__tests__/configuration/__snapshots__/svelte.spec.ts.snap
=> feat: Frame replacePage by entry

packages/core/platforms/android/native-api-usage.json, packages/core/platforms/ios/native-api-usage.json
If you create a new app and add the `native-api-usage.json` in the respective `App_Resources` folder you will see that the app run fails for both iOS and Android because some used classes were not added in the core whitelist. 
This adds the required metadata filters for a new app to run. 
=> fix(core): Add missing required metadata filters

packages/core/ui/action-bar/index.ios.ts
The flat property of the action bar is not working with NS 8.1.X on IOS.
Set the relevant properties on the appearance to remove/hide shadow on action bar.
Fixes/Implements/Closes #9550.
=> fix(ios): flat property using new appearance api

packages/core/global-types.d.ts
=> fix: global __DEV__ variable type

apps/ui/src/css/background-image-page.xml, apps/ui/src/image-view/missing-image-page.xml, packages/ui-mobile-base/android/widgets/src/main/java/org/nativescript/widgets/Utils.java
Avoid StringIndexOutOfBoundsException in org.nativescript.widgets.Utils
As it is my first PR to this repo, I am not experimented that much with native development. Feel free to guide me so I'll now next time :)
For example, I don't know how to test this file in a NativeScript project :/
Calling org.nativescript.widgets.Utils::getDrawable with a uri shorter than 6 characters throws a StringIndexOutOfBoundsException.
An early check in this method ensures uri is longer than 6 characters so a warning is shown in the console.
Fixes #9562.
=> fix(android/application): org.nativescript.widgets.Utils::getDrawable

apps/automated/package.json, apps/toolbox/package.json, apps/ui/package.json
Update runtime versions in demo apps
=> chore: update runtime versions in demo apps

packages/core/js-libs/esprima/README.md
I opted to use archive link for SpiderMonkey Parser_API page because I couldn't find an alternative.
=> Updated dead links

README.md, apps/ui/README.md, tools/notes/CONTRIBUTING-webpack.md, tools/notes/CONTRIBUTING.md, tools/notes/CodingConvention.md, tools/notes/DevelopmentWorkflow.md, tools/notes/HandlingErrors.md
=> docs(README): fix grammar issues and typos in docs

packages/core/config/config.interface.ts
Adding in typings for the new `cli.packageManager` and `hooks` options coming in with cli updates NativeScript/nativescript-cli#5596 and NativeScript/nativescript-cli#5597
=> chore(typing): cli and hooks types for config

packages/webpack5/__tests__/configuration/__snapshots__/angular.spec.ts.snap, packages/webpack5/src/configuration/angular.ts
Fixes https://github.com/NativeScript/angular/issues/44
DEPENDS ON https://github.com/NativeScript/NativeScript/pull/9674
=> feat(webpack): support NG 13 and zone async/await

README.md
LICENSE type : Apache 2.0 -> MIT
Fixes/Implements/Closes #9716 .
=> Update license type in Repo README

packages/core/ui/frame/index.android.ts
@NathanWalker this is an additional fix i discovered recently which is needed with androidx latest fragment.
could we createa new custom with this?
=> Androidx fragment 1 3

packages/webpack/helpers/moduleid-compat-loader.js
=> chore: fix typo in moduleid-compat-loader.js

packages/core/ui/image/index.ios.ts
The above screenshots are produced by running the following test code, navigating to the "Show Image" page, and back.
```js
const {
Application,
Frame,
Page,
Button,
Image,
} = require("@nativescript/core");
let count = 0;
const makeModalPage = () => {
const page = new Page();
page.id = `page${count++}`;
const image = new Image();
image.src =
"https://i.picsum.photos/id/669/5000/5000.jpg?hmac=VlpchW0ODhflKm0SKOYQrc8qysLWbqKmDS1MGT9apAc";
page.content = image;
return page;
};
Application.run({
create() {
const rootFrame = new Frame();
rootFrame.navigate({
create: () => {
const page = new Page();
const button = new Button();
button.text = "Open Image";
button.on("tap", () => {
rootFrame.navigate({
create() {
return makeModalPage();
},
});
});
page.content = button;
return page;
},
}); …
```
=> fix: UIImage leaking after Image is disposed

packages/core/ui/frame/fragment.transitions.android.ts, packages/core/ui/frame/index.android.ts, packages/core/ui/tab-view/index.android.ts
=> fix: edge cases and compatibility with fragments 1.2.x

apps/automated/project.json, apps/automated/src/http/http-string-worker.ts, apps/automated/src/test-runner.ts, apps/automated/src/ui/animation/animation-tests.ts, apps/automated/src/ui/button/button-tests.ts, apps/automated/src/ui/layouts/flexbox-layout-tests.ts, apps/automated/src/ui/styling/style-properties-tests.ts, apps/automated/src/ui/styling/style-tests.ts
=> chore: cleanup automated app tests

packages/core/ui/styling/css-selector/index.ts, packages/core/ui/styling/linear-gradient.ts, packages/core/ui/styling/style-properties.ts
Simple refactoring to ensure tree shaking can work correctly
=> chore: refactoring to allow tree shaking

packages/webpack5/src/loaders/xml-namespace-loader/index.ts
In some cases `xml-namespace-loader` would add/register a global module without a suffix pointing to the xml file - which is incorrect because no-extension modules are reserved for code modules (ts/js). This resulted in the wrong context being passed to the custom component and failing to bind properly.
We should now detect the "fallback" case - and not register the extensionless modules pointing to the `xml` files.
This partially fixes #9730 - when using a `<Button>` the taps are correctly handled by the parent context handler. For some reason, unrelated to this as far as I can tell, the tap event is not emitted from the `<Label>` inside the ActionBar.
fixes #9730
=> fix(webpack): xml-namespace-loader incorrect dependency mapping

packages/types-ios/src/lib/ios/objc-x86_64/objc!AVFoundation.d.ts, packages/types-ios/src/lib/ios/objc-x86_64/objc!Accessibility.d.ts, packages/types-ios/src/lib/ios/objc-x86_64/objc!AudioToolbox.d.ts, packages/types-ios/src/lib/ios/objc-x86_64/objc!AuthenticationServices.d.ts, packages/types-ios/src/lib/ios/objc-x86_64/objc!CarPlay.d.ts, packages/types-ios/src/lib/ios/objc-x86_64/objc!Contacts.d.ts, packages/types-ios/src/lib/ios/objc-x86_64/objc!CoreMIDI.d.ts, packages/types-ios/src/lib/ios/objc-x86_64/objc!CoreMotion.d.ts, packages/types-ios/src/lib/ios/objc-x86_64/objc!Darwin.d.ts, packages/types-ios/src/lib/ios/objc-x86_64/objc!FileProvider.d.ts, packages/types-ios/src/lib/ios/objc-x86_64/objc!GameController.d.ts, packages/types-ios/src/lib/ios/objc-x86_64/objc!HealthKit.d.ts, packages/types-ios/src/lib/ios/objc-x86_64/objc!HomeKit.d.ts, packages/types-ios/src/lib/ios/objc-x86_64/objc!ICU.d.ts, packages/types-ios/src/lib/ios/objc-x86_64/objc!Intents.d.ts, packages/types-ios/src/lib/ios/objc-x86_64/objc!MetalPerformanceShadersGraph.d.ts, packages/types-ios/src/lib/ios/objc-x86_64/objc!Network.d.ts, packages/types-ios/src/lib/ios/objc-x86_64/objc!PassKit.d.ts, packages/types-ios/src/lib/ios/objc-x86_64/objc!Photos.d.ts, packages/types-ios/src/lib/ios/objc-x86_64/objc!SQLite3.d.ts, packages/types-ios/src/lib/ios/objc-x86_64/objc!SensorKit.d.ts, packages/types-ios/src/lib/ios/objc-x86_64/objc!StoreKit.d.ts, packages/types-ios/src/lib/ios/objc-x86_64/objc!UIKit.d.ts, packages/types-ios/src/lib/ios/objc-x86_64/objc!VideoToolbox.d.ts, packages/types-ios/src/lib/ios/objc-x86_64/objc!WebKit.d.ts
Compatible with Xcode 13.3 due to release soon.
=> feat(types-ios): iOS 15.4

packages/core/config/config.interface.ts
Add typing info for the existing `additionalPathsToClean` property that `ns clean` reads from.
=> feat(config): cli.additionalPathsToClean to clean other paths with 'ns clean'

packages/core/ui/action-bar/index.ios.ts
Navigation button does not accept a custom icon in iOS 15.
Navigation button will accept a custom icon in iOS 15.
Fixes/Implements/Closes #9767 .
=> fix(iOS15): Navigation button is not using custom icon.

packages/core/config/config.interface.ts
=> chore: fix typo in config.interface.ts

packages/core/ui/core/view/index.ios.ts
=> fix: removed unecessary `console.log`

packages/core/application/index.ios.ts, packages/core/index.d.ts, packages/core/index.ts
and in IOSApplicationt to be like AndroidApplication
=> fix: expose `inBackground` and `suspended in `Application`

packages/core/ui/styling/background.ios.ts
Reverts NativeScript/NativeScript#9881
=> revert: "fix: Apply proper border radius to box shadow and view sublayers"

packages/core/ui/web-view/index.android.ts
This fixes https://github.com/NativeScript/NativeScript/issues/9463
=> fix(core): android fix for webview not loading local content

packages/types-minimal/package.json, packages/types-minimal/src/lib/ios/ios.d.ts, packages/types-minimal/src/lib/ios/objc-x86_64/objc!ARKit.d.ts, packages/types-minimal/src/lib/ios/objc-x86_64/objc!AVFAudio.d.ts, packages/types-minimal/src/lib/ios/objc-x86_64/objc!PDFKit.d.ts, packages/types-minimal/src/lib/ios/objc-x86_64/objc!Speech.d.ts, packages/types-minimal/src/lib/ios/objc-x86_64/objc!Vision.d.ts, tools/scripts/typings-minimal-copy.sh
With Preview 2.0 you could not access ARKit or AVAudio apis.
With Preview 2.0 you can now access ARKit or AVAudio apis.
=> feat(types-minimal): include AVFAudio and ARKit

packages/core/platforms/android/native-api-usage.json, packages/core/platforms/ios/native-api-usage.json
Minimal app will not start correctly when metadata filtering is enabled.
App will start OK
=> Fix metadata filtering

packages/core/ui/text-base/index.d.ts
=> fix(core): missing export for `maxLinesProperty`

packages/core/inspector_modules.ios.ts
```
CONSOLE LOG: Loading inspector modules...
CONSOLE LOG: Finished loading inspector modules.
```
every time the app starts.
```
```
when the app starts. 😄
=> feat: remove inspector modules log

packages/core/ui/action-bar/action-bar-common.ts, packages/core/ui/action-bar/index.android.ts, packages/core/ui/action-bar/index.ios.ts, packages/core/ui/core/view/index.android.ts
=> fix(core): Android memory leaks

packages/core/ui/core/view/view-helper/index.ios.ts
Reverts NativeScript/NativeScript#9986
=> Revert "fix(ios): app stopped responding after screen rotation"

packages/ui-mobile-base/android/widgets/src/main/java/org/nativescript/widgets/Utils.java
`getScaledDimensions` returns wrong dimensions.
`getScaledDimensions` returns expected dimensions.
=> fix(android): getScaledDimensions

packages/core/ui/list-view/index.ios.ts
closes https://github.com/NativeScript/NativeScript/issues/10000
=> fix(ios): ListView _prepareCell null safety

packages/core/ui/gestures/index.ios.ts
Reverts NativeScript/NativeScript#10004
=> revert "fix(core): handle tap and longpress gesture conflict on iOS"

packages/core/ui/page/index.ios.ts
the getter would create the actionBar.
=> fix(core): iOS prevent creating `ActionBar` when not needed

packages/core/fps-meter/fps-native.android.ts
The feature flag value is re-evaluated multiple times.
The feature flag value is cached.
=> refactor(core): cache frame feature flag value

packages/core/ui/core/view/index.ios.ts
This is particularly important for components like collectionview which might not want `requestLayout` to propagate to the top page.
With collectionView if a cell want to relayout you dont need the page to relayout however you want:
* the cell to resize itself
*  the collectionview to be notified  so that it updates its layout
The way i do this is by overriding `performLayout` to measure+notify. However currently `PFLAG_FORCE_LAYOUT` is set after `performLayout` so it wont work as the cell wont re layout itself.
This PR fixes it. It should not have any consequences (i have this in my fork for months).
=> fix(core): ios ensure `PFLAG_FORCE_LAYOUT` before `performLayout`

.vscode/tasks.json, packages/core/project.json
Build errors during building core package on windows.
It works on windows as well.
=> fix(core): windows build

apps/ui/src/main-page-view-model.ts, apps/ui/src/search-bar/issue-5039-view-model.ts
This will get rid of minor problems/warnings in UI app regarding latest version of `ObservableArray`.
=> chore: Updated ui sample to work with latest ObservableArray changes

packages/core/file-system/file-system-access.android.ts
The previous implementation was not working.
=> fix(core): android fix for `path.normalize`

packages/core/file-system/file-system-access.android.ts
=> fix(core): new normalize method for android is only for API >= 26

packages/core/file-system/file-system-access.android.ts
=> chore: missing `SDK_VERSION` refactoring after PR merge

packages/core/utils/utils-common.ts, packages/core/utils/utils.android.ts, packages/core/utils/utils.ios.ts
=> fix(core): prevent a circular reference because of `SDK_VERSION`

packages/core/ui/frame/index.ios.ts, packages/core/ui/page/index.ios.ts
=> fix(core): frame `navigatingTo` event were not fired on iOS

.gitignore, apps/automated/project.json, apps/toolbox/project.json, apps/ui/project.json, nx.json, package.json, packages/core/project.json, tools/scripts/run-automated.js
Setup for [Nx Cloud](https://nx.app/) to help with distributed task execution & cache.
=> chore: nx-cloud setup

packages/types-android/package.json, packages/types-android/src/lib/android-33.d.ts
TODO: generate androidx typings for packages used by core or the runtime
=> feat(types-android): add android API33

packages/core/application-settings/index.android.ts
It seems that my SharedPreferences fix in #10094 has caused trouble for apps that have old float values stored because Java fails to cast Float to Long.
Added a migration step to store the outdated values anew in proper format.
Fixes/Implements/Closes #10139 .
@Semurak I believe this takes care of the problem. Let me know if you think there's a case we don't cover.
=> fix(android): Migration step for ApplicationSettings.getNumber

apps/toolbox/src/main-page.xml, apps/toolbox/src/pages/scroll-view.ts, apps/toolbox/src/pages/scroll-view.xml, packages/core/ui/scroll-view/index.android.ts, packages/core/ui/scroll-view/index.ios.ts, packages/core/ui/scroll-view/scroll-view-common.ts
Event wiring sequencing prevented the scroll event from attaching under setup conditions.
Scroll event works as normal.
cc/ @asharghi
=> fix(core): ScrollView event wiring sequencing improvement

packages/core/application/index.ios.ts
The ViewController when embedded would not be setup the view properly.
The ViewController when embedded now sets up the view properly.
=> fix(ios): sdk embedding

packages/core/application/index.ios.ts
When embedding, systemAppearance wasn't handled properly.
When embedding, systemAppearance is now handled properly.
=> fix(ios): embed systemAppearance handling

apps/automated/src/test-runner.ts, packages/core/ui/core/view/view-helper/index.ios.ts, packages/core/ui/page/index.ios.ts
small update on https://github.com/NativeScript/NativeScript/pull/10164
=> fix: re-layout conditions

packages/types-android/package.json, packages/types-ios/package.json, packages/types-ios/src/lib/ios/ios.d.ts, packages/types-ios/src/lib/ios/objc-x86_64/objc!GameKit.d.ts, packages/types-ios/src/lib/ios/objc-x86_64/objc!Intents.d.ts, packages/types-ios/src/lib/ios/objc-x86_64/objc!Matter.d.ts, packages/types-ios/src/lib/ios/objc-x86_64/objc!MetalPerformanceShadersGraph.d.ts, packages/types-ios/src/lib/ios/objc-x86_64/objc!NativeScriptUtils.d.ts, packages/types-ios/src/lib/ios/objc-x86_64/objc!Pods_iostypingsprj.d.ts, packages/types-ios/src/lib/ios/objc-x86_64/objc!SensorKit.d.ts, packages/types-ios/src/lib/ios/objc-x86_64/objc!UIKit.d.ts, packages/types-minimal/package.json, packages/types-minimal/src/lib/ios/objc-x86_64/objc!UIKit.d.ts, packages/types/package.json
ios-types didn't contain latest typings.
ios-types now has latest typings.
=> feat(ios): types for latest 16.2 sdk

packages/core/platform/index.d.ts
Reverts NativeScript/NativeScript#10269
=> revert: "fix(core/platform): fixed types for sdkVersion and osVersion"

packages/core/globals/index.ts, packages/core/jest.setup.ts
=> fix: ensure Application instance initialized early

packages/webpack5/__tests__/configuration/__snapshots__/angular.spec.ts.snap, packages/webpack5/jest.config.js, packages/webpack5/package.json, packages/webpack5/scripts/resolver.js, packages/webpack5/src/configuration/angular.ts
Adds support for angular 16.1. Fixes https://github.com/NativeScript/angular/issues/117
=> feat(webpack): angular 16.1 support

packages/core/application/application-common.ts
In some scenarios setting the initial root css classes doesn't trigger a style update.
We force update styling whenever setting root css classes.
fixes #10318
=> fix: trigger css update when setting root classes

packages/core/ui/image-cache/index.ios.ts
=> fix: class name typo

packages/core/accessibility/index.android.ts
```
09-27 22:09:10.103 10718 10718 V 1000_StackLayouts: 354
09-27 22:09:10.427 10718 10718 V 1000_StackLayouts: 324
09-27 22:09:10.707 10718 10718 V 1000_StackLayouts: 280
09-27 22:09:10.969 10718 10718 V 1000_StackLayouts: 262
09-27 22:09:11.207 10718 10718 V 1000_StackLayouts: 237
09-27 22:09:11.454 10718 10718 V 1000_StackLayouts: 247
09-27 22:09:11.712 10718 10718 V 1000_StackLayouts: 257
09-27 22:09:11.995 10718 10718 V 1000_StackLayouts: 283
09-27 22:09:12.257 10718 10718 V 1000_StackLayouts: 261
09-27 22:09:12.510 10718 10718 V 1000_StackLayouts: 251
```
Roughly 15-20% improvement in render performance:
```
09-27 22:07:35.404  9213  9213 V 1000_StackLayouts: 328
09-27 22:07:35.684  9213  9213 V 1000_StackLayouts: 279
09-27 22:07:35.929  9213  9213 V 1000_StackLayouts: 245
09-27 …
```
=> perf(android): batch setupAccessibleView calls to improve TTI

packages/core/utils/common.ts, packages/core/utils/index.d.ts
=> feat: leading support for debounce

packages/webpack5/src/configuration/base.ts
Documentation indicates https://beta.docs.nativescript.org/configuration/webpack#env-appcomponents where `--env.appComponents=./someActivity.js` can be passed. 
However,  when utilsing this, webpack throws an error `appComponents.push is not a function`  when a single Activity is added.
This PR adjusts the reading of appCompnents env and if it is a single item, its wrapped inside an array
1. Create a new app
2. Add a CustomActivity.js
3. `ns build android --env.appComponents=./CustomActivity.js`
`TypeError: appComponents.push is not a function`
Build continues normally
=> fix(webpack): Adjust appComponents Env

packages/core/ui/core/view/index.ios.ts
When it comes to reusable views, it seems that view box shadow is not removed when view gets removed from view tree.
That is because shadow layer belongs to parent and we rely on `disposeNativeView` to cleanup shadows but that doesn't seem to be the right approach.
Add/remove shadows along with view, regardless of being reusable or not. It's also a good replacement for my previous PR.
=> fix(ios): Add/remove shadow for reusable views

packages/core/package.json
=> chore: 8.6.1 next

packages/core/ui/scroll-view/scroll-view-common.ts
There are cases when attempting to remove a listener callback that does not exist breaks scroll event of ScrollView.
We follow the same principle with `Span` overrides and check the existence of listeners. This gives better control and gets rid of problems like the one described above.
Fixes #10431.
=> fix(ios): ScrollView with listeners removed scroll delegate

apps/automated/src/ui/segmented-bar/segmented-bar-tests-native.android.ts, apps/automated/src/ui/segmented-bar/segmented-bar-tests-native.d.ts, apps/automated/src/ui/segmented-bar/segmented-bar-tests.ts, apps/ui/src/segmented-bar/all-page.xml, packages/core/ui/segmented-bar/index.android.ts, packages/core/ui/segmented-bar/index.d.ts, packages/core/ui/segmented-bar/index.ios.ts, packages/core/ui/segmented-bar/segmented-bar-common.ts, packages/core/ui/styling/style/index.ts, packages/core/utils/ios/index.ts
On Android, the `selectedBackgroundColor` doesn't work at all (on first load and on select index change), we can not see the selected item.
The background color does appear at the first load and on selected index changed
Fixes/Implements/Closes #10472 .
I have added a new property for both platforms to control `selectedTextColor` that can be set for more control of the selected state.
=> Segmented bar

packages/webpack5/src/configuration/angular.ts, packages/webpack5/src/configuration/base.ts, packages/webpack5/src/helpers/copyRules.ts, packages/webpack5/src/helpers/fileReplacements.ts, packages/webpack5/src/helpers/index.ts, packages/webpack5/src/helpers/log.ts, packages/webpack5/src/helpers/platform.ts, packages/webpack5/src/helpers/virtualModules.ts, packages/webpack5/src/index.ts, packages/webpack5/src/platforms/android.ts, packages/webpack5/src/platforms/ios.ts, packages/webpack5/src/platforms/visionos.ts
Replaces and closes https://github.com/NativeScript/NativeScript/pull/10452
=> feat(wepback): custom `buildPath`support

packages/core/application/application-interfaces.ts
=> fix InitRootViewEventData description

packages/core/ui/frame/index.d.ts, packages/core/ui/frame/index.ios.ts
You can only use the default navigationbar and toolbar
You can now specify (prior to frame creation) a custom UINavigationBar class or UIToolbar class
=> feat:allow custom navigationBar and toolbar on frame

packages/core/ui/editable-text-base/index.android.ts, packages/core/ui/scroll-view/index.android.ts, packages/core/ui/search-bar/index.android.ts, packages/core/ui/text-base/index.android.ts, packages/core/ui/text-base/index.d.ts, packages/core/ui/text-base/text-base-common.ts, packages/core/ui/text-field/index.android.ts
These changes caused problem so this PR will revert them for the time being.
Fixes #10486
=> Revert "fix(android): proper change of input interaction mode programmatically (#10434)

README.md
- Added Solid JS starter to README
=> docs: added Solid JS starter

packages/core/ui/transition/page-transition.android.ts
=> fix(android): Add null check on Android transition

packages/core/ui/page/index.android.ts
There's a console.log when navigating.
No extra console log when creating/navigating Pages.
=> fix: remove debug console log in Page

packages/core/file-system/file-system-access.android.ts, packages/core/file-system/file-system-access.ios.ts
In latest core version, TypeScript complains about missing references in file-system-access module.
This PR fixes those problems.
=> fix(core): Corrected undefined references in file system access

packages/core/platforms/ios/src/NativeScriptMainWindow.swift
If defining `@State` at the root level or using `@Environment` injection on views derived from that state, the main window body can be reevaluated causing the runtime reinit or reboot in some cases.
The main window when using a SwiftUI app lifecycle based NativeScript app will no longer reinit/reboot the runtime as it's not needed in these cases.
=> fix(visionos): multi-scene improvements

packages/core/accessibility/accessibility-properties.ts, packages/core/ui/core/view/index.android.ts, packages/core/ui/core/view/index.d.ts, packages/core/ui/core/view/index.ios.ts, packages/core/ui/core/view/view-common.ts, packages/core/ui/layouts/layout-base-common.ts
This PR reverts changes done in #10482 #10518 #10522 while keeping useful cleanup changes at the same time, as there have been issues discussed in #10522.
We could revisit the case of a11y performance in the future.
=> revert: "perf: disable accessibility for layout views"

.github/workflows/apps_automated_ios.yml, apps/automated/project.json, tools/scripts/run-automated.js
- Uses Warpbuild macOS runners
=> ci: warpbuild runners

packages/core/ui/frame/fragment.transitions.android.ts, packages/core/ui/frame/frame-common.ts, packages/core/ui/frame/index.d.ts, packages/core/ui/page/index.ios.ts, tools/notes/CodingConvention.md
Right now, core navigation has several rare crashes.
Added few safety-checks to mitigate those problems (Trace messages have also been included so that we're still able to know when those cases occur).
Those checks are based on past experiences with #9204 and #9732 (the latter was more frequent during 8.2 alpha but some still face it or a similar problem at least).
Additionally @NathanWalker, this PR updates coding conventions markdown based on current prettier configurations.
=> fix(core): Added safety-checks to prevent possible navigation exceptions

packages/core/config/config.interface.ts
See CLI description:
https://github.com/NativeScript/nativescript-cli/pull/5830
Doc added: https://github.com/NativeScript/docs/pull/161
=> feat(config): ability to include native source code from any path

packages/types-ios/src/lib/ios/objc-x86_64/objc!AVFAudio.d.ts, packages/types-ios/src/lib/ios/objc-x86_64/objc!AVFoundation.d.ts, packages/types-ios/src/lib/ios/objc-x86_64/objc!Accessibility.d.ts, packages/types-ios/src/lib/ios/objc-x86_64/objc!AccessorySetupKit.d.ts, packages/types-ios/src/lib/ios/objc-x86_64/objc!AudioToolbox.d.ts, packages/types-ios/src/lib/ios/objc-x86_64/objc!AuthenticationServices.d.ts, packages/types-ios/src/lib/ios/objc-x86_64/objc!BrowserEngineKit.d.ts, packages/types-ios/src/lib/ios/objc-x86_64/objc!Foundation.d.ts, packages/types-ios/src/lib/ios/objc-x86_64/objc!HealthKit.d.ts, packages/types-ios/src/lib/ios/objc-x86_64/objc!HomeKit.d.ts, packages/types-ios/src/lib/ios/objc-x86_64/objc!MachO.d.ts, packages/types-ios/src/lib/ios/objc-x86_64/objc!Matter.d.ts, packages/types-ios/src/lib/ios/objc-x86_64/objc!Messages.d.ts, packages/types-ios/src/lib/ios/objc-x86_64/objc!MetalPerformanceShadersGraph.d.ts, packages/types-ios/src/lib/ios/objc-x86_64/objc!NativeScriptEmbedder.d.ts, packages/types-ios/src/lib/ios/objc-x86_64/objc!ObjectiveC.d.ts, packages/types-ios/src/lib/ios/objc-x86_64/objc!PassKit.d.ts, packages/types-ios/src/lib/ios/objc-x86_64/objc!PencilKit.d.ts, packages/types-ios/src/lib/ios/objc-x86_64/objc!SafariServices.d.ts, packages/types-ios/src/lib/ios/objc-x86_64/objc!Speech.d.ts, packages/types-ios/src/lib/ios/objc-x86_64/objc!UIKit.d.ts, packages/types-ios/src/lib/ios/objc-x86_64/objc!UniformTypeIdentifiers.d.ts, packages/types-ios/src/lib/ios/objc-x86_64/objc!WebKit.d.ts, packages/types-ios/src/lib/ios/objc-x86_64/objc!XPC.d.ts
Types contained 18.1 iOS SDK.
Types now contain through 18.2 iOS SDK.
=> feat(ios): 18.2 types

apps/automated/src/ui/styling/style-tests.ts, apps/toolbox/src/app.css, apps/toolbox/src/main-page.xml, package-lock.json, package.json, packages/core/color/color-common.ts, packages/core/color/color-utils.ts, packages/core/package.json, packages/core/tsconfig.json, packages/core/ui/core/properties/index.ts, packages/core/ui/styling/css-color-mix.spec.ts, packages/core/ui/styling/style-scope.ts
Some css values may use color-mix expressions.
Core now supports [color-mix expressions](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/color-mix).
closes https://github.com/NativeScript/NativeScript/issues/10718
=> feat(css): color-mix

packages/core/data/observable/index.ts, packages/core/utils/typescript-utils.d.ts
Reverts NativeScript/NativeScript#10720
This is a great set of changes @ArthurMJ96 - we'll keep in PR til next major since it does introduce some breaking changes to a few API signatures.
Can see few of them here:
https://github.com/NativeScript/NativeScript/actions/runs/13888160250/job/38855679480
=> revert "feat(observable): enhance event callback type specificity"

packages/types-android/src/lib/android/org.nativescript.widgets.d.ts
I wrongly removed some method definitions in https://github.com/NativeScript/NativeScript/commit/6dd441d6ba7d6c4b07596976451ebd1615fcd745 This PR brings back those missing methods
=> fix(android): typings fix for native GridLayout
