NativeScript/NativeScript

tests/app/ui/builder/builder-tests.ts
tests/app/xml-declaration/xml-declaration-tests.ts
tns-core-modules/ui/builder/builder.ts

If loading a component from a module fails (for example, when there is no such module/it is missing), the application crashes at runtime with:
```
JavaScript error:
file:///app/vendor.js:19492:18: JS ERROR TypeError: undefined is not an object (evaluating 'componentView._moduleName = moduleName')
```
In the same scenario, a descriptive error is thrown referring the module/file to load from: 
```
JavaScript error:
file:///app/vendor.js:19513:116: JS ERROR Error: Failed to load component from module: ./details-page.xml or file: null
```
This error could (not only) be experienced in `webpack` workflow when navigating to a module, which did not get to the application's bundle.

fix: throw if failed to load component

---

tns-core-modules/http/http-request/http-request.ios.ts

Unable to parse xml file that contains bytes encoded with ISO 8859-1. Check [here](https://stackoverflow.com/questions/3485190/nsstring-initwithdata-returns-null) for more info
Fix: https://github.com/NativeScript/NativeScript/issues/7160

fix(ios-http-get): http failure during parsing xml

---

e2e/modal-navigation/app/home/home-page.ts
e2e/modal-navigation/app/home/home-page.xml
e2e/modal-navigation/app/modal-no-page/modal-no-page.ts
e2e/modal-navigation/app/modal/modal-page.ts
e2e/modal-navigation/package.json
e2e/modal-navigation/references.d.ts
tns-core-modules/ui/core/view/view-common.ts
tns-core-modules/ui/core/view/view.ios.ts

Fixes https://github.com/NativeScript/NativeScript/issues/7050
This PR introduces a new event `popoverClosed` to the `View` class. This event is raised when a modal using the `presentationStyle: UIModalPresentationStyle.Popover` is closed by tapping outside of the popup area.

fix(ios-modal): closeCallback not being called with popover presentation style

---

tns-core-modules/ui/button/button.android.ts

Currently, a button placed in ListView item does not restore its visual state to normal on cancel touch action which occurs when button received down touch action and then ListView scroll.
A button placed in ListView item restore its visual state to normal on cancel touch action.
* current version
* fixed version

fix(android/button): possible incorrect button visual state

---

tests/app/ui/image-cache/image-cache-tests.ts

See https://github.com/NativeScript/NativeScript/issues/6643

chore(android): disable test_ImageCache_ValidUrl on api19

---

tests/app/ui/label/label-tests.ts
tns-core-modules/ui/text-base/text-base.android.ts
tns-core-modules/ui/text-base/text-base.ios.ts

See https://github.com/NativeScript/nativescript-angular/issues/1818
App no longer crashes 
Fixes https://github.com/NativeScript/nativescript-angular/issues/1818

fix(text): crash when removing FormattedText

---

tests/app/livesync/livesync-tests.ts
tns-core-modules/ui/core/view/view-common.ts
tns-core-modules/ui/frame/fragment.transitions.android.ts
tns-core-modules/ui/frame/frame.android.ts
tns-core-modules/ui/frame/frame.ios.ts
tns-core-modules/ui/page/page.ios.ts

Apply quick(100ms) fade transition upon hot module replacement on both platforms as a visual indication that hmr occurred.
Closes: https://github.com/NativeScript/NativeScript/issues/7256

fix(hmr): quick fade upon replace navigation

---

tns-core-modules/ui/styling/style-scope.ts

We are no longer using StyleScope.changeCssFile() method internally but apparently there was a discrepancy where method implementation was private but d.ts listed it as public -- synced both to public now.

refactor: update access modifier

---

tns-core-modules/ui/layouts/grid-layout/grid-layout-common.ts
tns-core-modules/ui/layouts/grid-layout/grid-layout.ios.ts
tns-core-modules/ui/proxy-view-container/proxy-view-container.ts

We, the rest of the NativeScript community, thank you for your
contribution! 
To help the rest of the community review your change, please follow the instructions in the template.
-->
- ~[ ] Tests for the changes are included - https://github.com/NativeScript/NativeScript/blob/master/WritingUnitTests.md~
In the past month we've tracked 20+ crashes with this error:
```
TypeError: undefined is not an object (evaluating 'measureSpec.setColumn')
```
We haven't been able to consistently reproduce the crash locally, but I think it is clear where it does wrong.
`GridLayout(ios).onMeasure(...)` will create `MeasureSpecs` if missing the for `child` view when it calls `this.eachLayoutChild(...)`
Fixes: #7226

fix(ios): undefined is not an object (evaluating 'measureSpec.setColumn')

---

CodingConvention.md

the usejsdoc.org links are broken. also the newly commented out section links to a file in a private repo.

updating broken links

---

tns-core-modules-widgets/ios/TNSWidgets/TNSWidgets.xcodeproj/project.pbxproj
tns-core-modules-widgets/ios/TNSWidgets/TNSWidgets/UIView+PassThroughParent.m
tns-core-modules-widgets/ios/TNSWidgets/TNSWidgets/UIView+PropertyBag.h
tns-core-modules-widgets/ios/TNSWidgets/TNSWidgets/UIView+PropertyBag.m

- Addresses potential memory leak with propertybag implementation storing nils on deallocation indefinitely.
- Restricts propertybag implementation to UIViews (not NSObjects)
- Might address obscure RadListView crash on dealloc.

fix(ios): potential memory leak with propertybag implementation

---

tns-platform-declarations/ios/objc-x86_64/objc!MediaPlayer.d.ts
tns-platform-declarations/ios/objc-x86_64/objc!PassKit.d.ts
tns-platform-declarations/ios/objc-x86_64/objc!SceneKit.d.ts
tns-platform-declarations/ios/objc-x86_64/objc!UIKit.d.ts
tns-platform-declarations/ios/objc-x86_64/objc!WebKit.d.ts

`18446744073709551615` (`0xFFFFFFFFFFFFFFFF`) is an overflow to the JS
numerical system and therefore incorrect. Integer values from `-(2^53-1)` to `(2^53-1)`
only can be safely represented in JS (`Number​.MIN_SAFE_INTEGER` to
`Number​.MAX_SAFE_INTEGER`)
There's a fix in iOS Runtime's metadata generator which now automatically
converts such values to signed. (https://github.com/NativeScript/ios-runtime/pull/1151)
refs https://github.com/NativeScript/ios-runtime/issues/1150

fix(platform-declarations-ios): Change 2^64-1 enum values to -1

---

tns-core-modules-widgets/build.ios.sh
tns-core-modules-widgets/ios/build.sh

We should provide debug symbols package so that users can upload it
to their crashlytics service provider.
requested in support ticket 1410983

chore(widgets): Build TNSWidgets.framework.dSYM package

---

tns-core-modules/ui/core/properties/properties.ts
tns-core-modules/ui/core/view-base/view-base.ts
tns-core-modules/ui/frame/frame-common.ts
tns-core-modules/ui/frame/frame.android.ts
tns-core-modules/ui/styling/style-properties.ts
tns-core-modules/ui/styling/style-scope.ts
tns-core-modules/ui/styling/style/style.d.ts
tns-core-modules/ui/styling/style/style.ts

When navigating to a Page that contains any kind of elements (GridLayout, ListView, RadListView etc.), if you navigate back and trigger JS GC those elements and the Page itself are never collected and stay in the memory.
When navigating to a Page that contains any kind of elements (GridLayout, ListView, RadListView etc.), if you navigate back and trigger JS GC those elements and the Page itself are collected and are removed from the memory.
Here is a sample project that I created to test this case: 
[memory-test.zip](https://github.com/NativeScript/NativeScript/files/3261928/memory-test.zip)

fix: clear the `resolvedPage` when entry is being cleared, change the passed `View` to be a weak reference

---

e2e/cuteness.io/app/App_Resources/Android/src/main/AndroidManifest.xml
e2e/cuteness.io/package.json
e2e/cuteness.io/webpack.config.js

The Cuteness application makes `https` calls to `https://www.reddit.com/r/aww.json?limit=`.
On CI, it makes `http` calls to `http://nsbuild01.telerik.com/aww.json?limit=`.
Documentation:
https://developer.android.com/guide/topics/manifest/application-element#usesCleartextTraffic

fix(cuteness): allow cleartext HTTP for API 28

---

tns-core-modules/ui/animation/animation-common.ts
tns-core-modules/ui/animation/animation.android.ts
tns-core-modules/ui/animation/animation.ios.ts

Error:
```
ERROR in chunk bundle [initial]
bundle.js
/home/nsbuilduser/workspace/master-tns-core-modules-unittests-android/NativeScript/tests/node_modules/ts-loader/index.js??ref--11!/home/nsbuilduser/workspace/master-tns-core-modules-unittests-android/NativeScript/tns-core-modules/ui/animation/animation.ts ddf4f3bd9f31062f8eaa54b7a06b6e39
Circular reexports "/home/nsbuilduser/workspace/master-tns-core-modules-unittests-android/NativeScript/tns-core-modules/ui/animation/animation.ts".AnimationPromise --> "/home/nsbuilduser/workspace/master-tns-core-modules-unittests-android/NativeScript/tns-core-modules/ui/animation/animation-common.ts".AnimationPromise -(circular)-> "/home/nsbuilduser/workspace/master-tns-core-modules-unittests-android/NativeScript/tns-core-modules/ui/animation/animation. …
```

fix(android): a circular reexports

---

tns-core-modules/ui/editable-text-base/editable-text-base-common.ts

TextField/TextView doesn't have focus states.
There should be a way to style the TextField/TextView focus states in CSS without the manual need to attach events and set classes.
:focus pseudo class is applied whenever a field gets focused.
Fixes/Implements/Closes #7395.

feat(EditableTextBase) Add support for :focus pseudo class in TextField/TextView

---

tns-core-modules/ui/styling/style-scope.ts

Assign CSS state applied selectors version after ensuring and matching them.
This caused sync issues between the CSS state selectors and the style scope.

fix(css-state): _appliedSelectorsVersion assignment

---

tns-core-modules/ui/core/view-base/view-base.ts
tns-core-modules/utils/utils.ios.ts

Temporarily restore utils.ios.getter(...) and ViewBase._applyXmlAttribute(...) (but do not expose them in d.ts)

chore: restore temporarily deprecated apis

---

tests/app/xml-parser-tests/xml-parser-tests.ts
tns-core-modules/js-libs/easysax/easysax.js
tns-core-modules/xml/xml.ts

Full unicode can have up to 21 bits, but the current decoding method ( `String.fromCharCode`) can only handle 16 bits. HTML entities like `&#x1f923;` (17 bits) will fail to render properly as `&#xf923;` (highest-order bits are stripped).
`&#x1f923;` is correcly rendered as the byte sequence `f0 9f a4 a3` instead of `ef a4 a3` by using `String.fromCodePoint`, which generates a string/char from any number of bytes

fix: full Unicode support in xml

---

tests/app/data/observable-array-tests.ts
tns-core-modules/data/observable-array/observable-array.ts

ObservableArray `splice` does not notify the number of updated items and it can't be inferred from the passed arguments.
ObservableArray `splice` adds all updated items to `addedCount`, using a logic of "x items removed, y items added in their place"
The amount of change in the length of the array can be always inferred by `addedCount - removed.length`.
This fixes a bug that would cause `FormattedString.spans.splice` to keep removing spans and never adding any back.
Fixes #7425.
The `addedCount` variable from ObservableArray's `splice` change event is always the amount of added items.
Migration steps:
Ideally, developers should handle the case where items are replaced by `splice`. The old `addedCount` can be obtained by
`const addedCount = event.addedCount - …

fix(observable-array): splice(...) to return correct amount of added items

---

tests/app/data/observable-array-tests.ts
tns-core-modules/data/observable-array/observable-array.ts

cherry-picked from https://github.com/NativeScript/NativeScript/pull/7426
ObservableArray `splice` does not notify the number of updated items and it can't be inferred from the passed arguments.
ObservableArray `splice` adds all updated items to `addedCount`, using a logic of "x items removed, y items added in their place"
The amount of change in the length of the array can be always inferred by `addedCount - removed.length`.
This fixes a bug that would cause `FormattedString.spans.splice` to keep removing spans and never adding any back.
Fixes #7425.
The `addedCount` variable from ObservableArray's `splice` change event is always the amount of added items.
Migration steps:
Ideally, developers should handle the case where items are replaced by `splice`. The old …

fix(observable-array): splice to notify correct amount of added items

---

tns-core-modules/file-system/file-system.d.ts
tns-core-modules/module-name-resolver/module-name-resolver.ts
tns-core-modules/module-name-resolver/non-bundle-workflow-compat.ts

Register files as modules when in non-webpack mode (like in ns-playground)

feat: compat mode for non-webpack apps (playground)

---

tns-core-modules/module-name-resolver/non-bundle-workflow-compat.ts

Fix broken snapshot because of `fs.knownFolders.currentApp()` call in the root scope of a module.

fix: snapshot build for android

---

tns-core-modules/ui/styling/style-scope.ts

fix: Missing app.css error in playground

---

tns-core-modules/ui/tabs/tabs.ios.ts

Fixes issue where iOS Tabs TabStrip erroneously lays out space for titles & images even if only titles should be displayed.

fix(ios-tabs): item appearance toggle b/n titles and images

---

tns-core-modules/ui/gestures/gestures.android.ts

Fixes https://github.com/NativeScript/NativeScript/issues/7559

fix(android): remove wait for doubletap if no gesture recognizer

---

tns-core-modules-widgets/android/widgets/src/main/java/org/nativescript/widgets/TabStrip.java

Fix https://github.com/NativeScript/NativeScript/issues/7494
More stackoverflow info about `dispatchDraw` [here](https://stackoverflow.com/questions/4827848/ondraw-on-view-draws-behind-the-layout) and [here](https://stackoverflow.com/questions/11928570/use-of-dispatchdrawcanvas-canvas)

fix(tabstrip-android):fix selection highlight not visible

---

tns-core-modules-widgets/android/widgets/src/main/java/org/nativescript/widgets/TabStrip.java
tns-core-modules-widgets/android/widgets/src/main/java/org/nativescript/widgets/TabsBar.java
tns-core-modules/ui/tabs/tabs.android.ts
tns-platform-declarations/android/org.nativescript.widgets.d.ts

- Expose new `onTabsViewPagerPageChanged` to TabStrip class that does not call `updateTabsTextColor` 
- Introduce new TabsBar java class to be used by Tabs. Currently it differs only by calling `onTabsViewPagerPageChanged` of TabStrip instead of onViewPagerPageChanged.
- Refactor _tabs.android.ts_ to use the new TabsBar java class
Fix https://github.com/NativeScript/NativeScript/issues/7495

fix(tabs-android): tabStripItem color not applied

---

tns-core-modules/ui/bottom-navigation/bottom-navigation.ios.ts
tns-core-modules/ui/tab-navigation-base/tab-navigation-base/tab-navigation-base.ts

[iOS]: execute `setViewControllers` when setting `.tabStrip` property to populate all tabStrip and tabContent items. Thus, there is no need to worry with property (items/tabStrip) is set first.
[Android]: `onTabStripChanged` was adding TabStripItem child views in BottomNavigation directly, instead of just adding the new TabStrip as a child view.
Fix: https://github.com/NativeScript/NativeScript/issues/7433

fix(bottom-navigation): created dynamically does not show tabstrip

---

tns-core-modules/platforms/ios/Podfile

Currently, if a plugin has a podfile with platform version of `8.0`, the build will fail with:
```Specs satisfying the `MaterialComponents/Tabs (~> 84.4)` dependency were found, but they required a higher minimum deployment target.
'pod install' command failed.```

fix: prevent plugin podfile platform version clash

---

tns-core-modules/ui/bottom-navigation/bottom-navigation.android.ts
tns-core-modules/ui/tabs/tabs.android.ts

In order to have the fit to spec tab icons, we need to remove this optimization.
Fixes https://github.com/NativeScript/NativeScript/issues/7713

feat(android): fit tab resource icon size based on spec

---

tns-core-modules/ui/tabs/tabs.ios.ts

Fixes https://github.com/NativeScript/NativeScript/issues/7692

fix(ios-tabs): crash when add tabstrip in loaded event

---

tests/app/ui/styling/style-tests.ts
tns-core-modules/css/parser.ts

Cherry-picked https://github.com/NativeScript/NativeScript/pull/7689

fix(css): parse css selectors with escape sequences (#7689)

---

tns-core-modules/ui/tabs/tabs.ios.ts

This handles the most common scenario in Angular, when `Tabs` is used as a root of a navigate component. In this case ns-ng wraps the component in a proxy view container which doesn't have a native view.

fix(ios-tabs): handle nesting proxy view container

---

tests/app/ui/styling/root-views-css-classes-tests.ts
tests/app/ui/styling/style-tests.ts
tns-core-modules/application/application-common.ts
tns-core-modules/application/application.d.ts
tns-core-modules/application/application.ios.ts
tns-core-modules/css/system-classes.d.ts
tns-core-modules/css/system-classes.ts
tns-core-modules/ui/core/view-base/view-base.ts
tns-core-modules/ui/core/view/view-common.ts
tns-core-modules/ui/frame/frame.android.ts
tns-core-modules/ui/utils-common.ts
tns-core-modules/ui/utils.android.ts
tns-core-modules/ui/utils.d.ts
tns-core-modules/ui/utils.ios.ts

When you set `className` to a (modal) root view, it *overwrites* view's default CSS classes.
When you set `className` to a (modal) root view, it *preserves* view's default CSS classes.
Fixes https://github.com/NativeScript/NativeScript/issues/7709.

fix-next(css): className to preserve root views classes

---

README.md

Remove obsolete Waffle.io links - related to https://github.com/NativeScript/NativeScript/issues/7751

docs: remove obsolete Waffle.io links from the README

---

tns-core-modules/application-settings/application-settings.android.ts

Currently, if `getAllKeys` (and `flush`) functions will be called before any other method of `application-settings` module next exception will be thrown
```
System.err: An uncaught Exception occurred on "main" thread.
System.err: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Error calling module function
System.err: TypeError: Cannot read property 'getAll' of undefined
System.err: File: (file:///node_modules/tns-core-modules/application-settings/application-settings.js:85:0)
System.err:
System.err: StackTrace:
System.err: 	getAllKeys(file:///node_modules/tns-core-modules/application-settings/application-settings.js:85:0)
System.err: 	at myFunction(file:///app/common/helpers.ts:331:47)
System.err: 	at (file:///app/app.ts:111:10)
System.err: …
```

fix(android/application-settings): possible uninitialized sharedPreferences variable usage

---

e2e/ui-tests-app/app/action-bar/font-icons-page.xml
tns-core-modules/ui/action-bar/action-bar.android.ts

`NavigationButton` does not process `font://` prefix in `icon` field.
`NavigationButton` processes `font://` prefix in `icon` field, the same way as `ActionItem` does.
Unfortunately, I could not found any test fro this functionality for `ActionItem`, that is why I could not implement the correct one for `NavigationButton`.

fix(android/action-bar): process Icon Fonts in NavigationButton the same way as in ActionItem

---

tns-core-modules/ui/segmented-bar/segmented-bar.ios.ts

Adding support for the new SegmentedControl's selectedSegmentTintColor property. Introduced with iOS 13.

feat: adding support for the new selectedSegmentTintColor property

---

tns-core-modules/js-libs/polymer-expressions/polymer-expressions.js

Binding expressions in the HTML of an NativeScript + Angular app do not work and throw and non critical error.
This change https://github.com/NativeScript/NativeScript/commit/beffc5736a050f4f38eb051e7e1bfb77ed0f9576 caused and error and failing tests to occur in the `nativescript-angular` repo. The source of the issue is an actual issue in the `Angular > ngtools > Webpack > enhanced-resolve` packages. We have logged [this issue](https://github.com/webpack/enhanced-resolve/issues/197) here but it is already resolved in the beta tag of the `enhanced-resolve` package. Since this fixed package needs to be updated in the ngtools package and that can take a while I am proposing this fix.
Binding expressions in the HTML of an NativeScript + Angular app work.

fix: change the way we import 'esprima' to avoid wrong path resolution in Angular projects

---

tns-core-modules/ui/builder/builder.ts

The [raw-loader](https://github.com/webpack-contrib/raw-loader/blob/6cf76b8947d34fcbe2c11fabc0a995cbf246615f/src/index.js#L18) changed the way the modules are exported e.g they've already used ES Module export instead of CommonJS. This way, the format of modules inside `bundle.js` or `vendor.js` is changed:
Previous:
```
module.exports = "<Frame defaultPage=\"bundle-main-page\" id=\"root-frame\">\n</Frame>\n"; 
```
Current:
```
__webpack_exports__["default"] = ("<Frame defaultPage=\"bundle-main-page\" id=\"root-frame1\">\n</Frame>\n");
```
On the other side, angular updated `raw-loader` to v3.1.0 in their latest minor release e.g in v8.3.0. As a result, `tns test` command doesn't work for newly created code shared applications.
This PR adds support for parsing xml modules exported via ES …

fix: xml parsing when input value is reported as object instead of string

---

tns-core-modules/platforms/ios/Podfile

The core modules had a dependency to Material Components v84.4. There is a fix in v91.0 that resolves problems with app publishing to iOS.
Update MC to latest.
Closes https://github.com/NativeScript/NativeScript/issues/7928

feat: update material components dependency to 92.3

---

tns-core-modules/application/application.android.ts
tns-core-modules/application/application.d.ts
tns-core-modules/application/application.ios.ts

This is a patch PR for https://github.com/NativeScript/NativeScript/pull/7907

feat(css): add attribute scoped css without global refresh (#7907)

---

tns-core-modules/ui/frame/frame.android.ts

Fixes: https://github.com/NativeScript/NativeScript/issues/7901
However, note that while this change fixes this specific issue we have only verified NativeScript works with androidx@1.0.0 package versions at this point.

fix(frame-android): IllegalStateException: The specified child already has a parent

---

nativescript-core/application/application-common.ts
nativescript-core/ui/styling/style-scope.d.ts
nativescript-core/ui/styling/style-scope.ts

On a runtime change of orientation or system appearance,
the respective root view CSS class updates to reflect the changes.
At the same time, increase the application CSS selector version,
so that to update styles on back navigation.
The check for back navigation is in `onNavigatingTo` method:
https://github.com/NativeScript/NativeScript/blob/6.1.0/tns-core-modules/ui/page/page-common.ts#L108-L113
Relates to #7800.

fix-next(css-classes): increase application CSS selector version at runtime

---

build/generate-tns-compat.ts
e2e/scoped-packages/app/generated-tests/tests.ts
e2e/scoped-packages/package.json

Re-exports in `tns-core-modules` (a.k.a. "compat") package are added only for moudules that have `.d.ts` or `package.json`. 
Re-exports added for all non-platfrom-specific TS files as well (ex. `view-common.ts`, `frame-common.ts`, etc.)

chore: add re-exports for ts files

---

nativescript-core/cli-hooks/before-checkForChanges.js

Add a hook that will throw an error if building Angular project without the required version fo `nativescript-dev-webpack` (1.3.0)

chore(hook): Check for min required webpack version

---

nativescript-core/application/application.ios.ts
nativescript-core/css/system-classes.d.ts
nativescript-core/css/system-classes.ts

At the application launch, the `ns-root` class is not set when loading the theme.
Relates to https://github.com/NativeScript/NativeScript/issues/7800.

fix(iOS): set root viewe css classes before setup UI

---

nativescript-core/cli-hooks/before-checkForChanges.js

The CLI hook that check required versions for CLI and nativescript-dev-webpack made more forgiving.
It will now wont match versions like `file:../../nativescript-dev-webpack.tgz`.

chore: More forgiving version check hook

---

nativescript-core/debugger/devtools-elements.common.ts

Replace `topmost()` usage in dev tools.
```
topmost() is deprecated. Use Frame.topmost() instead.
topmost(file:///app/vendor.js:22230:18)
at frameTopmost(file:///app/vendor.js:4162:124)
at getDocument(file:///app/vendor.js:4179:36)
at getDocument(file:///app/vendor.js:4606:48)
at onTap(file:///app/bundle.js:283:9)
at notify(file:///app/vendor.js:3620:37)
at _emit(file:///app/vendor.js:3640:24)
at tap(file:///app/vendor.js:15523:24)
at UIApplicationMain([native code])
at _start(file:///app/vendor.js:492:26)
at run(file:///app/vendor.js:534:11)
at file:///app/bundle.js:155:16
at ./app.js(file:///app/bundle.js:172:34)
at __webpack_require__(file:///app/runtime.js:751:34)
at checkDeferredModules(file:///app/runtime.js:44:42)
at webpackJsonpCallback(file:///app/runtime.js:31:39)
at …
```

refactor(dev-tools): replace topmost() usage

---

nativescript-core/application/application.ios.ts

Otherwise, the root view does not style in the respective system appearance.

fix(css-class): set class before showing window

---

nativescript-core/ui/bottom-navigation/bottom-navigation.android.ts

This issue was originally reported by the PNP team. Can be reproduced with [Archive.zip](https://github.com/NativeScript/NativeScript/files/3771918/Archive.zip). There is a crash when you change tabs fast and suspend/resume the app.
The app doesn't crash anymore.

fix: bot nav android crash when change tab and suspend

---

nativescript-core/ui/styling/gradient.d.ts

With typescript@3.7.2 this import throws `Import declaration conflicts with local declaration of 'LinearGradient'.`

fix(gradient): import LinearGradient with alias

---

nativescript-core/debugger/devtools-elements.common.ts

The element returned by `frame.topmost()` was used as the root of the app in chrome-devtools elements tab.
The element returned by `application.getRootView()` was used as the root of the app in chrome-devtools elements tab.

fix(dev-tools): use app root in getDocument()

---

nativescript-core/debugger/webinspector-network.ios.ts

Move the logic from core modules to iOS runtime. This way watches
and expressions evaluation in console will work for apps which
do not use the core modules (e.g. TestRunner of iOS runtime)
Merge along with https://github.com/NativeScript/ios-runtime/pull/1222
refs https://github.com/NativeScript/ios-runtime/issues/905

refactor(ios): Chrome DevTools Runtime domain

---

tns-core-modules-widgets/android/widgets/src/main/java/org/nativescript/widgets/Async.java

Crashlytics:
**Async.java line 181**
**org.nativescript.widgets.Async$Image$DownloadImageTask.doInBackground**
```
Fatal Exception: java.lang.OutOfMemoryError: Failed to allocate a 3601932 byte allocation with 970044 free bytes and 947KB until OOM
at dalvik.system.VMRuntime.newNonMovableArray(VMRuntime.java)
at android.graphics.BitmapFactory.nativeDecodeStream(BitmapFactory.java)
at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:863)
at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:839)
at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:877)
at org.nativescript.widgets.Async$Image$DownloadImageTask.doInBackground(Async.java:181)
at org.nativescript.widgets.Async$Image$4.run(Async.java:157)
at …
```

fix(android): Fatal Exception: java.lang.OutOfMemoryError

---

nativescript-core/application/application.ios.ts
nativescript-core/ui/activity-indicator/activity-indicator.ios.ts
nativescript-core/ui/bottom-navigation/bottom-navigation.ios.ts
nativescript-core/ui/core/view/view.ios.ts
nativescript-core/ui/frame/frame.ios.ts
nativescript-core/ui/html-view/html-view.ios.ts
nativescript-core/ui/page/page.ios.ts
nativescript-core/ui/tab-view/tab-view.ios.ts
nativescript-core/ui/tabs/tabs.ios.ts
nativescript-core/ui/text-base/text-base.ios.ts
nativescript-core/ui/text-view/text-view.ios.ts
tests/app/ui/page/page-tests-common.ts

Build the application with Xcode 10 (no iOS 13 APIs available) and deploy it to iOS 13.
The application crashes.
The application runs and fallbacks to APIs < 13.

fix(iOS): check for iOS 13 APIs

---

api-reports/NativeScript.api.md
build/prepare-core.sh
package.json

The `npm run setup` script was generating the api-report file each time. Executing `npm run api-extractor-ci` after that will always succeed as it will check to the newly generated api-report.  
The setup script will not re-generate the api-report and use the one coming from git.

test: execute api-extractor on CI properly

---

CONTRIBUTING.md

adding info about the test's report in the contribution guidelines

docs: add test report info in the contribution guidelines

---

.vscode/launch.json
tests/app/livesync/livesync-tests.ts

The `__hmrSyncBackup` is renamed to `__coreModulesLiveSync` starting from this PR: https://github.com/NativeScript/nativescript-dev-webpack/pull/1081/files

test: fix private nativescript-dev-webpack API usage

---

nativescript-core/application/application-common.ts
nativescript-core/application/application.ios.ts
nativescript-core/css/system-classes.d.ts
nativescript-core/css/system-classes.ts
nativescript-core/ui/core/view-base/view-base.ts
nativescript-core/ui/core/view/view-common.ts
nativescript-core/ui/frame/frame.android.ts
tests/app/ui/styling/root-views-css-classes-tests.ts
tests/app/xml-declaration/xml-declaration-tests.ts

**Based on #8084**
Currently, only a default `.ns-modal` class is assigned to root modal views.
Along with the default `.ns-modal` class, also assign:
- application platform (`.ns-android|.ns-ios`),
- device type (`.ns-phone|.ns-tablet`)
- application orientation (`.ns-portrait|.ns-landscape|.ns-unknown`)
- system appearance (`.ns-light|.ns-dark`)
and accordingly, update classes orientation and appearance on a change.
Implements a part of: https://github.com/NativeScript/theme/issues/194
Relates to: https://github.com/NativeScript/NativeScript/issues/7800

feat: System css classes for modals

---

nativescript-core/css/css-tree-parser.ts
nativescript-core/package.json
nativescript-core/ui/styling/style-scope.ts
package.json
tests/app/ui/styling/style-tests.ts
unit-tests/css-tree-parser/css-tree-parser.ts

The developer can choose between `rework` and `nativescript` css parsers (_rework_ being the default)
The developer can choose between `rework`, `nativescript` and `css-tree` (_rework_ being the default)
According to [benchmarks](https://github.com/postcss/benchmark#parsers), [css-tree](https://github.com/csstree/csstree) is the **fastest** available css parser written in javascript at the moment. It is orders of magnitude faster than the default _rework_ parser.

feat(css): Added optional css-tree parser

---

nativescript-core/ui/editable-text-base/editable-text-base-common.ts
nativescript-core/ui/editable-text-base/editable-text-base.android.ts
nativescript-core/ui/editable-text-base/editable-text-base.d.ts
nativescript-core/ui/editable-text-base/editable-text-base.ios.ts
nativescript-core/ui/enums/enums.d.ts
nativescript-core/ui/enums/enums.ts
nativescript-core/ui/text-field/text-field.android.ts

Adding integer only keyboard type for text-field and for all editable text components. This type has no additional options (which is different from the **number** type)
```XML
<TextField keyboardType="integer"/>
```
Results an integer only keyboard types (Android and iOS):
Related to feature request https://github.com/NativeScript/NativeScript/issues/3303

feat: add integer only keyboard type for text-field

---

nativescript-core/ui/styling/style-scope.ts

#PR Checklist
Rework is the current default CSS parser
css-tree is the new default CSS parser
The old parser is still available and can be enabled by setting the `cssParser` property in `package.json`:
```json
{
"main": "bundle",
"cssParser": "rework",
"android": {
"v8Flags": "--expose_gc",
"markingMode": "none"
}
}
```

feat: Make css-tree the default parser

---

nativescript-core/ui/bottom-navigation/bottom-navigation.android.ts
nativescript-core/ui/frame/frame.android.ts

Sometimes `_onAttachedToWindow` is called by Android after the app has suspended. Usually there is another call to `_onDetachFromWindow` immediately after, but on some version of android (reproduced on Oxygen 10 / OnePls 7T) there isn't. Which cause fragment manager calls too early in the lifecycle after the app is resumed and leads to crashes.
Set the `_attachedToWindow` after the `this._manager.isDestroyed()` check to make sure it is not raised falsely.
Fixes #8104

fix(android): handle fake attach

---

nativescript-core/ui/core/view/view.android.ts
nativescript-core/ui/frame/frame.android.ts
nativescript-core/utils/utils.ios.ts

_Same as #8166 but based on release branch._
Fragment is always removed from the fragment manager in the `Frame.disposeCurrentFragment()` method. Different versions of androidX behave differently if you try to remove a fragment from a fragment manager.
Added a check if the current fragment is actually contained in the fragment manager returned by the `_getFragmentManager()`
Fixes #8037

fix(android): check is disposed fragment is in the FragmentManager

---

nativescript-core/ui/gestures/gestures.android.ts
nativescript-core/ui/gestures/gestures.ios.ts

No state for longPress on iOS which leads to [this](https://github.com/NativeScript/NativeScript/issues/3573#issuecomment-514950219)
Adding a `state` argument for the iOS long press event. Android doesn't support states so it would always return state = 1 (began) when longPress is triggered.
Related to [https://github.com/NativeScript/NativeScript/issues/3573#issuecomment-514950219](https://github.com/NativeScript/NativeScript/issues/3573#issuecomment-514950219)

feat: add longPress state argument w/ UILongPressGestureRecognizer (iOS)

---

nativescript-core/ui/bottom-navigation/bottom-navigation.ios.ts

Currently, TabStrip items event emitting only when user click on UITabBar within processing `tabBarControllerDidSelectViewController` handler method of `UITabBarControllerDelegate` class. That is why when `selectedIndex` property changed programmatically TabStrip styling messed up.
Current fix, just move TabStrip items event emitting into `onSelectedIndexChanged` handler, which called on processing `tabBarControllerDidSelectViewController` handler method (within `_onViewControllerShown` method) and on processing `selectedIndex` property changed programmatically.
Fixes/Implements/Closes #7667.

fix(ios/bottom-navigation): Changing tabs programatically messes up styles

---

api-reports/NativeScript.api.md
nativescript-core/ui/bottom-navigation/bottom-navigation.android.ts
nativescript-core/ui/tab-navigation-base/tab-navigation-base/tab-navigation-base.d.ts
nativescript-core/ui/tab-navigation-base/tab-navigation-base/tab-navigation-base.ts
nativescript-core/ui/tabs/tabs.android.ts

When a tab's in tabs/bottom-navigation is activated and its background-color is changed it does not return to its default background-color after deactivating it.
When a tab's in tabs/bottom-navigation is activated and its background-color is changed it returns to its default background-color after deactivating it.
Fixes #8235.

fix: return default tab background color when the background color is not explicitely set through css

---

nativescript-core/ui/editable-text-base/editable-text-base.android.ts

Integer type on Android is always hidden (password type)
Removed the password flag to make integer type keyboard input visible. Tested with visible_palssword flag (to create even simpler number pad) but it is not working as expected from native development.
https://github.com/NativeScript/NativeScript/issues/8248#issuecomment-574638734

fix: make integer type visible

---

nativescript-core/ui/page/page.ios.ts

If swipe back navigation is cancelled - the current page ActionBar gets the style from the previous page in the nav-stack (the one that we were swiping back to).
If the swipe back navigation is cancelled - the current style of the ActionBar is preserved.
Fixes: #7430

fix(ios): ActionBar style wrong after cancelled swipe back navigation

---

nativescript-core/ui/text-base/text-base.ios.ts

When setting the format of a "text view", we need to recover existing values for properties that will get default values otherwise.
The "textAlignment" of a UIButton is available through a "titleLabel" object instead of directly on itself (see IOS documentation fo UIButton).
Currently, when setting a new format on a UIButton, the recovered value for textAlignment would always be `undefined`, and therefore the default value for textAlignment would always be applied when instantiating a new paragraphStyling.
After this commit, the previously set textAlignment (if any) is properly recovered and reused.
fixes pr #8151

fix(ios-text-base): button textAlignment on IOS (UIButton)

---

tests/app/ui/image-cache/image-cache-tests.ts

The `[IMAGE-CACHE.test_ImageCache_ValidUrl]` unit test is failing on API levels < 20
The `[IMAGE-CACHE.test_ImageCache_ValidUrl]` unit test is passing on API levels < 20

fix: invoke done callback in image cache unit test for API Level < 20

---

nativescript-core/ui/core/view/view.android.ts

Crash when setting android button properties that set `StateListAnimator`
The current `StateListAnimator` is flashed (using `jumpToCurrentState`) before setting the new one
Fixes #7886
Fixes #7532
Fixes #4256

fix(android): crash on setting elevation on API21

---

nativescript-core/ui/text-field/text-field.android.ts

Related to https://github.com/NativeScript/NativeScript/issues/8285
Updating the TextField code as well.

fix: remove the password type for Integer-type keyboard in TextField

---

nativescript-core/ui/bottom-navigation/bottom-navigation.android.ts
nativescript-core/ui/tab-navigation-base/tab-strip-item/tab-strip-item.ts
nativescript-core/ui/tabs/tabs.android.ts

When changing fonts for tab strip items (ex. with `:active`) style dynamically there are cases when the title disappears(#8310) or app crashes(#8311).
Titles no longer disappear and switching tabs no longer causes crashes
Fixes #8310 
Fixes #8311

fix(android): Bugs in tab strip items when changing styles dynamically

---

api-reports/NativeScript.api.md
e2e/ui-tests-app/app/tabs/frame-in-tabs-inner-page-1.xml
e2e/ui-tests-app/app/tabs/frame-in-tabs-inner-page-2.xml
e2e/ui-tests-app/app/tabs/frame-in-tabs-inner-page-3.xml
e2e/ui-tests-app/app/tabs/frame-in-tabs-inner-page-4.xml
e2e/ui-tests-app/app/tabs/frame-in-tabs.ts
e2e/ui-tests-app/app/tabs/frame-in-tabs.xml
e2e/ui-tests-app/e2e/suites/tab-navigation/tabs/tabs-tests.e2e-spec.ts
nativescript-core/ui/core/view-base/view-base.d.ts
nativescript-core/ui/core/view-base/view-base.ts
nativescript-core/ui/frame/frame-common.ts
nativescript-core/ui/frame/frame.d.ts
nativescript-core/ui/page/page.ios.ts
nativescript-core/ui/tabs/tabs.ios.ts

When there is an animation for transitioning from one tab to another and the tab contains a frame inside, `loadView` is triggered which [causes the animation to stop](https://stackoverflow.com/a/47031524/613113)
When an animation is running we are calling the `callLoaded` inside the `loadView` in a setTimeout for deferred execution
Fixes  #7827.

fix(tabs): delay loadView when animation runs

---

nativescript-core/ui/core/control-state-change/control-state-change.ios.ts

The extended `ObserverClass` is only allocated but never initialized. The iOS runtime applies some heuristics to such objects trying to automatically initialize them when used. The [new iOS V8 based runtime](https://github.com/NativeScript/ns-v8ios-runtime) no longer does that and the application will crash if we try to use such objects.
Ensure that the allocated instance is initialized.

fix(ios): Ensure ObserverClass is initialized

---

api-reports/NativeScript.api.md
nativescript-core/ui/core/view-base/view-base.d.ts
nativescript-core/ui/core/view-base/view-base.ts
nativescript-core/ui/page/page.ios.ts
nativescript-core/ui/tabs/tabs.ios.ts

The PR contains two fixes:
- Proper animation freeze fix as the delay should be on the **requestLayout** method, but not on the **callLoaded** method 
- Property set the selected item in the tabstrip when the selectedIndex is changed programmatically
Fixes #7827, #8327.

Tabs animation and selected index fixes

---

nativescript-core/ui/bottom-navigation/bottom-navigation.ios.ts

There's a bug when setting the item color on ios 13 if there's no background set to the tabstrip -  https://books.google.bg/books?id=99_BDwAAQBAJ&q=tabBar.unselectedItemTintColor 
To fix the above issue we are applying the selected fix only for the case when there is no background set. In that case, we have the following known issue:
-  we will set the same color to all unselected items, so you won't be able to set different colors for the different not selected items
Fixes #8309.
iOS: You cannot set different text colors for different not selected items in the TabStrip if there is no background set to the tabs. 
The above background cannot be achieved in iOS 13 because of a bug, and to avoid different behavior on different versions we've added the above restriction. …

Bottom nav color ios fix

---

api-reports/NativeScript.api.md
nativescript-core/ui/text-field/text-field-common.ts
nativescript-core/ui/text-field/text-field.d.ts
nativescript-core/ui/text-field/text-field.ios.ts

This issue has been complained about in a variety of development circles even outside NativeScript and something we recently experienced as a problem on an app we were building.
Here's a few extensive discussions on the topic all of which offer several solutions:
* https://stackoverflow.com/questions/45452170/ios-11-disable-password-autofill-accessory-view-option
* https://github.com/expo/expo/issues/2571
None worked as reliably and bulletproof as the suggestion made in this answer:
https://github.com/expo/expo/issues/2571#issuecomment-473347380
When an app desires to completely avoid the auto iOS strong password suggestion handling, developers can now specify `secureWithoutAutofill="true"` vs. the standard `secure="true"` property.
Currently developers may use TextField as follows which …

feat(ios): textfield option to disable iOS autofill strong password handling

---

nativescript-core/ui/styling/background.android.ts

It seems that keeping the cache solves the problem with `newDrawable(android.content.res.Resources) on null object`. However, it is not clear why we were clearing it from the cache. 
Fixes  #7954, #7867.

fix: do not clear androidView._cachedDrawable

---

api-reports/NativeScript.api.md
e2e/ui-tests-app/app/bottom-navigation/dynamic-color-change-page.css
e2e/ui-tests-app/app/bottom-navigation/dynamic-color-change-page.ts
e2e/ui-tests-app/app/bottom-navigation/dynamic-color-change-page.xml
e2e/ui-tests-app/app/tabs/dynamic-color-change-page.css
e2e/ui-tests-app/app/tabs/dynamic-color-change-page.ts
e2e/ui-tests-app/app/tabs/dynamic-color-change-page.xml
e2e/ui-tests-app/e2e/suites/tab-navigation/bottom-navigation/bottom-navigation.e2e-spec.ts
e2e/ui-tests-app/e2e/suites/tab-navigation/tabs/tabs-tests.e2e-spec.ts
nativescript-core/ui/bottom-navigation/bottom-navigation.android.ts
nativescript-core/ui/bottom-navigation/bottom-navigation.ios.ts
nativescript-core/ui/tab-navigation-base/tab-navigation-base/tab-navigation-base.d.ts
nativescript-core/ui/tab-navigation-base/tab-navigation-base/tab-navigation-base.ts
nativescript-core/ui/tab-navigation-base/tab-strip-item/tab-strip-item.ts
nativescript-core/ui/tab-view/tab-view.android.ts
nativescript-core/ui/tabs/tabs.android.ts
nativescript-core/ui/tabs/tabs.ios.ts

Fixed dynamically setting `iconSource` of **TabStripItem** in Tabs/Bottom Navigation and `selectedItemColor/unSelectedItemColor` of **TabStrip**

fix(tabs): dynamic styling fixes

---

tests/app/ui/text-field/text-field-tests.ts

A duplicate snippet (for markdown generation) was crashing the DOCS build.
Related to [this PR here](https://github.com/NativeScript/NativeScript/pull/8347/files)

fix: remove duplicate snippet

---

nativescript-core/css/parser.ts
tests/app/ui/styling/style-tests.ts

Currently NativeScript doesn't correctly parse escape sequences in CSS selectors. There was an issue and PR (#7688, #7689) about this problem previously but only escaping a slash was implemented. My PR fully supports escape sequence from the [spec](https://www.w3.org/TR/CSS21/syndata.html#characters). This includes escaping any character or Unicode sequence.

fix(css): parse css selectors with escape sequences (for real)

---

nativescript-core/css/css-tree-parser.ts
unit-tests/css-tree-parser/css-tree-parser.ts

- [ x ] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/CONTRIBUTING.md#commit-messages.
- [ x ] You have signed the [CLA](http://www.nativescript.org/cla).
- [ x ] All existing tests are passing: https://github.com/NativeScript/NativeScript/blob/master/DevelopmentWorkflow.md#running-unit-tests.
- [ x ] Tests for the changes are included - https://github.com/NativeScript/NativeScript/blob/master/WritingUnitTests.md.
The CSS parser is failing for empty rules such as:
```css
Button.-primary {
font-size: 18;
;
color: red;
}
```
The CSS parser should ignore such empty rules without failing.

fix: the css parser should handle empty nodes

---

tests/app/ui/tab-view/tab-view.md

There is a small typo in tests/app/ui/tab-view/tab-view.md.
Should read `corresponding` rather than `coresponding`.

docs: Fix simple typo, coresponding -> corresponding

---

api-reports/NativeScript.api.md
nativescript-core/data/observable/observable.d.ts
nativescript-core/data/observable/observable.ts

Right now when unknown properties are added/set on a View, css attribute selectors do not update the styling.
A new `setProperty` method has been added to Observable that will fire a `propertyChange` and a `${propertyName}Change` event - which will get picked up by the css runtime and styles will update.
The reason I've opted for a new method is because the `set` method of the Observable is overwritten in Views - adding a new method allows triggering the correct events.
Ref: #6122, #7914

feat: setProperty on Observable

---

nativescript-core/ui/editable-text-base/editable-text-base.android.ts

Do not clear key listener when editable is false This prevents the input type to be changed.
Instead, we can set focusable, clickable to false.
This allows to change input Type i.e (secure) at run time when editable is false.
Reference issue: https://github.com/NativeScript/NativeScript/issues/8523
In android platform, In TextField if editable is set to false. We cannot change or toggle secure property. This occurs because we are setting KeyListener to false. Instead we can set Focusable, clickable to false.
Now, one can toggle between secure property, even if editable is set to false.

fix(android/TextField): set focusable, clickable to false if not editable

---

package.json

We need to do a bit more testing with #8591 before we merge it - as there may be other side effects of typescript 3.9.3.

fix(core): pin typescript to 3.8.3 to avoid __exportStar issue

---

nativescript-core/ui/text-base/text-base.ios.ts

If the value of the text field is changed at runtime, the configured letter spacing is not respected.
Letter spacing is respected if text in text field is changed at runtime.
Fixes/Implements/Closes https://github.com/NativeScript/NativeScript/issues/4892

fix(text-base): apply letter spacing in ios text field

---

nativescript-core/ui/styling/style-properties.ts
nativescript-core/ui/text-base/span.ts
nativescript-core/ui/text-base/text-base-common.ts
nativescript-core/ui/text-base/text-base.android.ts
nativescript-core/ui/text-base/text-base.ios.ts

Currently there's no way to align vertically the Spans in a FormattedString
Spans in FormattedString support the vertical-align CSS property.
Implements #4795.

feat(text-base): Add Span vertical-align support

---

nativescript-core/ui/text-base/text-base.ios.ts

Updating the color property on a button in iOS does not change its text color.
Looks like the NSForegroundColorAttributeName takes precedence over any color later applied by setTitleColorForState.
Updating the color property on a button in iOS does change its text color.
Fixes/Implements/Closes https://github.com/NativeScript/nativescript-angular/issues/1453

fix(text-base): update text color for ios

---

e2e/ui-tests-app/app/fonts-tests/text-field-page.xml
e2e/ui-tests-app/package.json
nativescript-core/ui/text-base/text-base.ios.ts

closes https://github.com/NativeScript/NativeScript/pull/8626
closes https://github.com/NativeScript/NativeScript/issues/4892
@dosomder `setValueForKey` as well as `setObjectForKey` do fix the issue, nice work on the original PR. Sticking with `setValueForKey` since it's typesafe and works same 👍

fix(text-base): letter spacing for textfield

---

nativescript-core/ui/core/view/view.android.ts
nativescript-core/ui/frame/frame.android.ts

Currently, 'onBackPressed' callback will never get called in the case of a frame root.
Developers will be able to handle back press for frame root.

feat: Implementing 'onBackPressed' for frame-root. Useful for meddling with tab-navigated apps

---

e2e/ui-tests-app/app/app.css
e2e/ui-tests-app/app/fonts-tests/button-page.ts
e2e/ui-tests-app/app/fonts-tests/button-page.xml
nativescript-core/ui/text-base/text-base.ios.ts

Updating the color property on a button in iOS does not change its text color. This seems to only happen if the letter spacing property is also set. On Android the issue does not happen.
Color is changed properly.
Previous PR: https://github.com/NativeScript/NativeScript/pull/8617
Playground demo: https://play.nativescript.org/?template=play-js&id=r7ubMC&v=3

fix(text-base): apply dynamic text color change on button for ios

---

e2e/ui-tests-app/app/main-page.ts
e2e/ui-tests-app/app/screen-qualifiers/main-page.ios.xml
e2e/ui-tests-app/app/screen-qualifiers/main-page.land.xml
e2e/ui-tests-app/app/screen-qualifiers/main-page.minWH120.port.xml
e2e/ui-tests-app/app/screen-qualifiers/main-page.minWH360.ts
e2e/ui-tests-app/app/screen-qualifiers/main-page.minWH360.xml
e2e/ui-tests-app/app/screen-qualifiers/main-page.ts
e2e/ui-tests-app/app/screen-qualifiers/main-page.xml
nativescript-core/module-name-resolver/module-name-resolver.ts
nativescript-core/module-name-resolver/qualifier-matcher/qualifier-matcher.d.ts
nativescript-core/module-name-resolver/qualifier-matcher/qualifier-matcher.ts

A dirty hack for taking care qualifier-based pages issues during hot module reload.
Live-sync fails to load script and style files <file-name>.<extension> (e.g. js, css) for <file-name>[.<qualifier>]*.xml files.
Reload will work.
Closes #8622 .
This way of making module-resolve reload these files is quite dirty, so I hope there'll be a better alternative of extracting qualifiers from file paths.

fix: #8622

---

nativescript-core/ui/enums/enums.ts

add "hidden" to Visibility enum and remove the unused "collapsed" value
closes #8653
Setting a view's visibility via JavaScript/TypeScript to enums.Visibility.hidden crashes the app.
logging enums.Visibility to the console results in:
```
{
"visible": "visible",
"collapse": "collapse",
"collapsed": "collapsed"
}
```
collapsed is not a valid value for the visibility property.
Setting the visibility of a view programatically to hidden (using enums.Visibiliy.hidden) hides the view as expected and does not crash the app.
loggin enums.Visibility to the console correctly shows:
```
{
"visible": "visible",
"collapse": "collapse",
"hidden": "hidden"
}
```
Fixes #8653.

fix(enums): add Visibility.hidden

---

nativescript-core/ui/core/view/view.d.ts

Replace the 'deafault' with 'default'.
Fixes NativeScript/NativeScript#8668

fix(nativescript-core/ui): Fix syntax error in comments for property of View, originX and originY. 

---

api-reports/NativeScript.api.md
nativescript-core/image-source/image-source-common.ts
nativescript-core/image-source/image-source.android.ts
nativescript-core/image-source/image-source.d.ts
nativescript-core/image-source/image-source.ios.ts
tests/app/image-source/image-source-tests.ts

- [ x] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/CONTRIBUTING.md#commit-messages.
- [ x] You have signed the [CLA](http://www.nativescript.org/cla).
- [ x] All existing tests are passing: https://github.com/NativeScript/NativeScript/blob/master/DevelopmentWorkflow.md#running-unit-tests.
- [ x] Tests for the changes are included - https://github.com/NativeScript/NativeScript/blob/master/WritingUnitTests.md.
There was no manner in which to resize an image. When sending images to a backend such as a social feed you typically don't want to send the full resolution image as these days mobile cameras can create huge 40 megapixel images. 
This provides an easy way to resize an image. Simply get an ImageSource and call resize(maxSize) on it and …

feat: ImageSource resize method

---

nativescript-core/ui/text-view/text-view.ios.ts

iOS TextView reloads text every time the TextView is focused
Only reload text if necessary (i.e. previously was the hint shown)
Fixes/Implements/Closes https://github.com/NativeScript/NativeScript/issues/8620

fix(text-view): only reload text if hint is showing on ios

---

e2e/ui-tests-app/app/list-view/main-page.ts
e2e/ui-tests-app/app/list-view/parents-expression-page.ts
e2e/ui-tests-app/app/list-view/parents-expression-page.xml
nativescript-core/ui/core/bindable/bindable.ts

Reference '$parents' or '$parent' can be undefined when included in expressions that are nested inside a ListView or a Repeater.
Playground Sample: https://play.nativescript.org/?template=play-js&id=TERk3c&v=11
**Note:** A component sample called 'parents-expression' is included inside ui-tests-app list-view section.
Parent referenced expression-values will be loaded properly using an 'update' call just like core already does with sourceProperties.
Fixes #8666 #6981 #5054

fix: #8666 #6981 #5054

---

e2e/ui-tests-app/app/scroll-view/main-page.ts
e2e/ui-tests-app/app/scroll-view/scroll-enabled-page.ts
e2e/ui-tests-app/app/scroll-view/scroll-enabled-page.xml
tns-core-modules-widgets/android/widgets/src/main/java/org/nativescript/widgets/HorizontalScrollView.java
tns-core-modules-widgets/android/widgets/src/main/java/org/nativescript/widgets/VerticalScrollView.java

Android property 'isScrollEnabled' does not apply to scroll view if changed while gesture is underway.
Android property 'isScrollEnabled' will apply to scroll view if changed while gesture is underway.
Fixes #8545 .
This fixes issues of implementations related to moving views inside a ScrollView (e.g. BottomSheet).
Here is a sample from @rigor789  that was done using android native touch listener: https://play.nativescript.org/?template=play-vue&id=v1t5Pe&v=2
With this fix, there is the possibility of implementing such features using pure NativeScript. :)

fix: Android 'isScrollEnabled' not applied to scroll view if changed during gesture

---

nativescript-core/utils/native-helper.android.ts

See #8713 
We now check whether the view has focus when the argument is given to ad.dismissSoftInput(nativeView?), when the given view is not focused, we don't do anything.
Fixes/Implements/Closes #8713 
I did not create a test for this change, as I did not see any existing tests for this functionality.
I also had 3 failing tests on the current master that are unrelated to this change.

fix(android/utils): add check in ad.dismissSoftInput(nativeView?) to make sure the dismissed nativeView has focus at that moment

---

nativescript-core/ui/frame/frame.ios.ts

fix(ios): actionbar show/hide should trigger page layout

---

e2e/ui-tests-app/app/main-page.ts
e2e/ui-tests-app/app/segmented-bar/android-enabled-page.ts
e2e/ui-tests-app/app/segmented-bar/android-enabled-page.xml
e2e/ui-tests-app/app/segmented-bar/clean-page.xml
e2e/ui-tests-app/app/segmented-bar/main-page.ts
e2e/ui-tests-app/app/segmented-bar/main-page.xml
nativescript-core/ui/segmented-bar/segmented-bar.android.ts

Setting property 'isEnabled' to false does not disable SegmentedBar in Android.
Setting property 'isEnabled' to false disables SegmentedBar in Android.
**Note:** Most of TabHost's public methods (including getTabWidget) are getting deprecated in Android API 30.
So far, no alternative has been released by Google on how to manage TabHosts.

fix: Setting property 'isEnabled' to false does not disable SegmentedBar in Android

---

packages/core/ui/frame/fragment.transitions.android.ts
packages/core/ui/frame/frame-common.ts
packages/core/ui/frame/index.android.ts

So this is a long coming fix for me in all my apps.
Kind of in the same vibe as https://github.com/NativeScript/NativeScript/pull/8561
Until now when transitioning between fragment we were using `replace` which means that moving to a new fragment the current fragment was destroyed and re created on back.
This was bad for maps and any opengl rendered views.
Here is an example of what it looked like before
This PR changes that behavior by using `add` and `remove`.
I hacked the transition life handlers a bit the get the entry we are moving to and the entry we are moving from.
Another plus of this is that back navigations should be faster as we dont recreate the views.
We will also keep the positions in any scroll view!!!
Here is what it looks like now:

[android] dont use replace transaction anymore.

---

packages/webpack/transformers/ns-transform-native-classes.ts

With TS 3.9+ when transpiling TS to ES5 if a property has a get/set defined, it marks the properties as `enumerable: false`. ([TS commit reference](https://github.com/microsoft/TypeScript/commit/5c85febb0ce9d6088cbe9b09cb42f73f9ee8ea05)) This prevents v8/JSC to correctly access them. 
The added regex patches the output of the transpile and marks all properties as `enumerable: true`

fix(webpack/transform): Change NativeClass properties to enumerable

---

packages/webpack/helpers/apply-css-loader.js
packages/webpack/package.json

Now that everything is using ES modules, the `exports` object no longer exists.
`css-loader` adds the `___CSS_LOADER_EXPORT___` variable to the module, and then exports it. This allows us to hook into it, and apply the css to a NativeScript app. 
This fixes Vue apps in NativeScript 7. See https://github.com/nativescript-vue/nativescript-vue/issues/715
I believe `require("@nativescript/core/ui/styling/style-scope")` is no longer needed - because globals are handled differently (testing the change in an app works fine) - but @NathanWalker please take a look!
The change has been released under `3.0.1-rc.0`.

fix(webpack): apply-css-loader not applying css

---

package.json

There is no `rc7` tag for the `nativescript` package.

fix: invalid cli tag version

---

packages/core/application/application-common.ts
packages/core/application/index.d.ts

With es2017 `@nativescript/theme` wont work because of an error like that 
```
Cannot set property systemAppearanceChanged of #<Object> which has only a getter
```
Now i think it is best to not "override" that method but to have a boolean to disable

feat: boolean to disable systemAppearanceChanged (theme)

---

packages/core/index.d.ts
packages/core/index.ts
packages/core/ui/index.ts
workspace.json

A few properties are missing from the barrel.
This adds the additional getter/setters for plugin usage:
```
import { 
letterSpacingProperty, 
textAlignmentProperty, 
textDecorationProperty, 
textTransformProperty, 
whiteSpaceProperty, 
lineHeightProperty 
} from '@nativescript/core';
```
/cc @PeterStaev

feat(core): export additional properties for plugin usage

---

packages/core/globals/index.ts

This PR fixes a big issue which appeared with N 7 / esm / webpack
With webpack import / require order is not respected : https://github.com/webpack/webpack/issues/1343
Now in [bundle-config-loader](https://github.com/Nativescript/NativeScript/blob/65a3302a048fb32da78968256c16fc63a5706e3d/packages/webpack/bundle-config-loader.ts#L55) we rely on `require` to load `bundle-entry-points` thus calling `initGlobals` and making tslib functions global.
Because it uses `require` it actually end up at the end of your `main.js` (simply look at a generated bundle.js)
To keep that call up we need to use `import` 
But that is not enough!
in `bundle-entry-points` we use 'require' on 'globals'. And using `import` is not enough either because we call a method on it which will end up after all imports!
The …

fix bundle-config-loader

---

package.json
packages/core/config/config.interface.ts

`profiling` is nested in the `android` key - and is ignored.
no `cssParser` property in config.
`profiling` is now at the proper root level, and is picked up by core (after https://github.com/NativeScript/nativescript-cli/commit/9641bea992e05978dbb64d28dc7d60bf14ea2f76 is released) 
`cssParser` is now read from the config.

fix: add missing configuration keys and move profiling out of android

---

packages/core/ui/frame/fragment.transitions.android.ts

When navigating with a `flip*` transition, the `duration` and `curve` are not honoured. Duration is hard-coded to 3000 which results in a low transition. This may have been accidentally left in during testing.
Hard-coded line is removed, the transition now honours the passed options.

fix(android-transitions): remove hard-coded flip transition duration/curve

---

packages/core/ui/text-view/index.ios.ts

fix(ios/textview): switch order of _setNativeText and _refreshColor in showText-method
The color should be refreshed after setting the text to keep the styles.
Fixes #8764
Fixes #8764 .

fix(ios/textview): switch order of _setNativeText and _refreshColor in showText-method

---

packages/core/ui/date-picker/index.ios.ts
packages/core/ui/time-picker/index.ios.ts
packages/types-ios/src/lib/ios/objc-x86_64/objc!UIKit.d.ts

TimePicker/DatePicker crashes on iOS 14
Does not crash
Fixes/Implements/Closes #8862

fix(ios): time-picker and date-picker for iOS 14

---

packages/core/ui/text-view/index.ios.ts

just like textfields. Fixes components extending this one

fix: delegate should be set on nativeTextViewProtected

---

packages/core/package.json
packages/core/ui/styling/css-selector/index.ts

closes https://github.com/NativeScript/NativeScript/issues/8778
closes https://github.com/NativeScript/NativeScript/issues/8872
`--env.production` flag causes css-selector to be imported at top and needs globals setup first.

fix(core): global handling with env.production flag

---

packages/core/ui/date-picker/date-picker-common.ts
packages/core/ui/date-picker/index.d.ts
packages/core/ui/date-picker/index.ios.ts
packages/core/ui/time-picker/index.d.ts
packages/core/ui/time-picker/index.ios.ts
packages/core/ui/time-picker/time-picker-common.ts

This is my suggestion for the discussion at https://github.com/NativeScript/NativeScript/pull/8877#issuecomment-698830203
I will add the same property to the datetime element after I have gotten feedback

fix(ios): preferredDatePickerStyle property

---

packages/core/data/observable-array/index.ts

In javascript you can call splice with an index > length. The result is a push.
But when you do that ObservableArray index will be wrong and thus user logic will fail.
Example:
```ts
// obsarray = [0];
obsarray.splice(2, 0, 1);
// this works, the inner array is now [0,1]
// however 'change' is called with index = 2
// when the use tries to do obsarray.getItem(eventData.index) -> crash
```
We have that issue with `svelte-native` and the `spans` `ObservableArray` of `FormattedString`

fix(core): Observable splice index > length 

---

packages/core/utils/index.ios.ts
packages/core/utils/native-helper.d.ts
packages/core/utils/native-helper.ios.ts

On iOS, `Utils.openFile(somePath)` doesn't work.
On iOS, `Utils.openFile(somePath)` works as expected.
**NOTE**: This is published under @nativescript/core "rc" tag now so if anyone needs this right away you can use the rc. (specifically under `7.0.8-rc.0`)
closes https://github.com/NativeScript/NativeScript/issues/8913

fix(ios): Utils.openFile

---

packages/core/globals/index.d.ts

When using @nativescript/unit-test-runner the following typing's issue will occur:
```
node_modules/@nativescript/core/globals/index.d.ts:3:10 - error TS2315: Type 'Observable' is not generic.
3  events: Observable<any>;
```
Runs without error.

fix(core): global index typing fix for unit testing framework

---

packages/core/data/observable-array/index.ts

Otherwise it will crash in ListView for iOS for example as it tries to animate an item with a negative row index. See issue here https://github.com/NativeScript/NativeScript/pull/8900#issuecomment-701539011

Fix to ensure index remains > 0 on splice

---

packages/core/package.json

For some reason we need to have the three of those for it to work correctly
Fixes https://github.com/NativeScript/NativeScript/issues/8925

fix: ensure globals do not get tree shaked

---

packages/webpack/helpers/angular-config-parser.js
packages/webpack/templates/webpack.angular.js
packages/webpack/templates/webpack.config.spec.ts

Handling production, staging, qa or any other environment configurations is not intuitive or consistent with typical Angular handling.
User's can now define `configurations` per project via `angular.json` (in standard/flat projects) or `workspace.json` (if using large Nx workspaces).
For example:
```
"projects": {
"mobile": {
"root": "",
"sourceRoot": "src",
"projectType": "application",
"prefix": "foo",
"configurations": {
"production": {
"fileReplacements": [
{
"replace": "src/environments/environment.ts",
"with": "src/environments/environment.prod.ts"
}
]
}
},
```
Usage:
```
ns run ios --env.configuration=production --env.projectName=mobile
```
```
"projects": {
"nativescript-mobile": {
"root": "apps/nativescript-mobile/",
"sourceRoot": "apps/nativescript-mobile/src",
"projectType": …
```

feat(webpack): angular configuration support for environment handling

---

packages/core/ui/core/view/view-helper/index.ios.ts

iOS 10 seems to have an issue with reallocing UILayoutGuide after a init.  So on the second pass thru this function that app will crash on iOS 10 with an error about `init` not being a function. 
I suspect there might be a issue with Allocation size of the object on iOS 10, and bears some detailed debugging.  But at this point using the new() works around the issue so that the app won't crash on iOS 10.

Fix: Fix iOS 10 Issue with UILayoutGuide

---

apps/automated/src/data/observable-array-tests.ts
packages/core/data/observable-array/index.ts
packages/core/ui/text-base/formatted-string.ts

Fixes the automated tests from the changes done in PR #8900 & #8921 which broke two of the tests.
- Those PR's also created a couple corner cases on deletion, which are now fixed.
- Added `Length` growing array (never worked, but now does, so now more like a real array)
- Added additional tests to catch the corner cases in the future.

fix: fix Observable-Array, its tests and a typo

---

.github/ISSUE_TEMPLATE/bug_report.md
packages/core/ui/frame/index.android.ts

Apps that have Bottom Navigation nested inside Frame & Page throw exception on exit.
Exception thrown on exit is solved.
Closes #8828

fix: BottomNavigation error on back press (application exit)

---

packages/core/ui/list-view/index.ios.ts

iOS 14 broke the default transparency of ListViewCell. UITableViewCell now adds a default UIBackgroundConfiguration unless backgroundColor is set on the cell. Because of this, ListViewCell are created with a white background instead of the expected transparent background.
New instances of ListViewCell are now properly transparent on iOS14. The fix doesn't break previous versions of iOS.

fix(core): ListViewCell.initWithEmptyBackground

---

apps/automated/src/test-runner.ts

Tests that are created with `createTestCase` aren't running because since es6 classes methods are no longer properties of the object.
All tests are running

fix(tests): should run all unit tests

---

packages/core/ui/tabs/index.ios.ts

iOS 10.3 (and possibly other version) the hack for Animated sliding is crashing out on v8 engine.   Swapped hack for a different hack that passed all the same tests.
No Crashes.  :-)

fix: ios10 tab crash

---

apps/automated/src/ui/date-picker/date-picker-tests.ts
apps/automated/src/ui/time-picker/time-picker-tests.ts
packages/core/ui/tabs/index.ios.ts

iOS 14 removed support for text color on Date/Time except for the Wheel.   Tests were trying to read the color attribute directly on iOS 14 to compare it to what was set; which of course then failed as the Date/Time items are not using the wheel.
Fixes both tests to detect if on iOS 14, and then ignore that test.

fix: color date/time ios14 tests

---

apps/automated/src/ui/list-view/list-view-tests.ts
packages/core/ui/list-view/index.android.ts

`public getView(index: number, convertView: android.view.View, parent: android.view.ViewGroup): android.view.View` never checks if `convertView` is of the right type for the template. This usually isn't an issue because android calls `getItemViewType(index: number)` to check if the view is of the correct type (template). If for some reason the items have changed mid-execution, though, `getItemViewType(index: number)` will return a different template from what the view actually is.
Consider this scenario (listview where only 2 items are visible):
```
red
green
green
green
```
While rendering `red`, items change to
```
green
green
green
green
```
You'll see the wrong representation because it should never change view types, but it did.
```
red // android believes this is a green view!
green …
```

fix(list-view): handle reusing wrong view

---

packages/core/data/observable/index.d.ts
packages/core/data/observable/index.ts

if not set it will be set to this.
This always bugged me to have to set this all the time. It seems better that way to me

fix: make object optional in notify

---

apps/automated/src/timer/timer-tests.ts
packages/core/timer/index.android.ts

setInterval on Android will keep delaying if busy work is done during the callback
`setInterval(..., 1000)` will almost never call 10 times every exact 10s.
setInterval now works like the web, calling every x ms, which means sometimes it'll call more/less often depending on the amount of work being done.
`setInterval(..., 1000)` will almost always call 10 times every 10s (exception is if work took longer than 1000ms to be called)

feat(android-timer): setInterval closer to web spec

---

packages/core/application/application-interfaces.ts
packages/core/application/index.android.ts
packages/core/application/index.d.ts
packages/core/application/index.ios.ts
packages/core/ui/frame/index.android.ts

When you bootstrap the app, the root view MUST be created synchronously.
When bootstrapping the app, you can set the root view to `null` which will ensure the app will start without a root view (blank screen). It's then up to the developer (usually flavor) to set this root view.
In the Angular context, this is now possible:
1. on launch, begin AppModule bootstrap
2. set the rootview to null
3. schedule a macroTask to check if bootstrap is done
3.1. if it is, set the rootView (no flashes)
3.2. if it isn't, set the rootView as a temporary view (user provided splash screen)
4. on bootstrap complete, set root view from AppModule's rootView

feat: allow app to start without a root view

---

packages/core/ui/core/view/index.ios.ts
packages/core/ui/core/view/view-common.ts
packages/core/ui/core/view/view-helper/index.ios.ts

I added a new property to completely ignore safearea computation. It gets important with components like bottomsheets.
Without it i can only get unwanted view "padding" as seen in the next screenshot.
And there is no real way right now to simply "ignore" that top safe area (because the view controller has a  safe area).
By setting that new property (which has no consequence when not set) i get correct "p
adding"
I also think this is the property which should be set on all ListView cells to totally ignore safearea inside listviews

feat: ios added ignoreSafeArea property

---

packages/core/platform/index.android.ts
packages/core/platform/index.d.ts
packages/core/platform/index.ios.ts

We somehow renamed `Platform.screen` & `Platform.device` to `Platform.Screen` and `Platform.Device` in the Mono-Repo transition.   This breaks plugins and applications, including all versions of NS-Theme's 2.x.   This also breaks all examples and the current documentation.
Adds a simple compatibility classes so that `Platform.screen` and `Platform.device` both point to the upper case version, to allow every plugin and use of this to work.   The new name Platform.Screen and Platform.Device still work as we are using them in other places...

fix: Add old names to platform for compatibility

---

packages/core/ui/core/view-base/index.d.ts
packages/core/ui/core/view-base/index.ts
packages/core/ui/core/view/index.android.ts

I use `android:windowSoftInputMode="stateHidden|adjustPan"`  however when i open a modal window the softInputMode is set to `adjustResize`. This PR makes the android `DialogFragment` follow your default activity setting.
Also added an android modal parameter to set a custom windowSoftInputMode

fix: android modal not following activity windowSoftInputMode

---

apps/ui/src/progress-bar/activity-indicator-page.xml
packages/core/ui/activity-indicator/index.android.ts

Changing color to an ActivityIndicator applies the new color to all other ActivityIndicators in the same page.
That only applies to Android.
Each indicator has independent color by calling `mutate()` on indicator drawable instance at the creation of view.
Fixes/Closes #9021 .

fix(core-android): ActivityIndicator changed transferred its color to other ActivityIndicators of the same page

---

packages/core/ui/page/page-common.ts

I am not sure why i dont see the issue in all apps but the issue is definitely there:
* `Page` imports `Frame`
*  `Frame` imports `Page`
I ended up in a case  where i got `Cannot access … before initialization` because of that.
By using `frame.constructor.name === 'Frame'` now `Frame` is just used as a type in `page-common` and thus we dont get a circular referecence anymore

fix: prevent circular reference && Cannot access … before initialization

---

packages/core/ui/bottom-navigation/index.android.ts

Android BottomNavigation was super fragile, prone to bugs and race conditions due to poor fragment handling.
Android BottomNavigation is stable and reliable.
closes https://github.com/NativeScript/NativeScript/issues/8132
closes https://github.com/NativeScript/NativeScript/issues/7901
closes https://github.com/NativeScript/NativeScript/issues/9051
closes https://github.com/NativeScript/NativeScript/issues/8251

fix(android): BottomNavigation fragment child already has a parent

---

packages/core/utils/native-helper.ios.ts

Using `Utils.ios.getVisibleViewController` from different view controller contexts can crash with maximum call stack exceeded.
`Utils.ios.getVisibleViewController` works as expected under all circumstances.
closes https://github.com/NativeScript/plugins/issues/39

fix(ios): getVisibleViewController maximum call stack exceeded

---

packages/webpack/host/resolver.ts

When webpacking in Angular; it requires the plugins to have the name "nativescript", "@nativescript", "tns" somewhere in it.  If it doesn't have it -- it will not consider it a plugin to do any .ios. / .android. file renaming causing the build to fail.
Makes angular be consistent with **all** the other flavors, and now does NOT care about the package name in its check to see if it is a file it needs to rename.  
It does add about between a -10% to a +5% slowdown to just the WebPack portion of the build depending on the size of the application. (No other speed or size impacts)   In smaller apps; the webpacking is now faster.   In apps that take about 30 seconds for just the webpacking, it adds an additional second.

Fix: Angular no longer has issues with plugins that aren't named "nativescript"

---

packages/core/image-source/index.ios.ts

Looks like the gc isn't cleaning up this fast enough when used in a loop e.g NativeScript/plugins#71

fix(ios): force release of nsdata after saving image

---

packages/core/ui/text-field/index.ios.ts

This fixes iOS behavior to correctly resize on text change.
Was already working on Android

fix: ios textfield resizing (auto width) on text change

---

.eslintrc.json
.prettierignore
package.json

* add `eslint-plugin-prettier` so that eslint can format code too
* fixed eslint config file:
- wrong “prettier” extend
- added config for eslint/prettier
* allow eslint/prettier to format JSON files except package.json files (which are formatted by npm)

fix: some eslint fixes

---

apps/ui/src/issues/issue-7469-page.css
apps/ui/src/issues/issue-7469-page.ts
apps/ui/src/issues/issue-7469-page.xml
apps/ui/src/issues/main-page.ts
packages/core/ui/core/view-base/index.d.ts
packages/core/ui/core/view-base/index.ts

Views and view trees are destroyed when removed from the view tree.
Views can be marked as `reusable` and will not be destroyed when removed from view tree. Removing these nodes require the developer to do: 
```
view.destroyNode();
// which calls
view.reusable = false;
view._tearDownUI();
```
For implementation details on how frameworks should deal with it, see my work in `nativescript-angular`: https://github.com/edusperoni/nativescript-angular/tree/reusable-views
Implements #7469.
Rewrite of #8184
-------
What happens when a reusable view with children gets removed? The current implementation does not call _tearDownUI on children, but we should still suspendNativeUpdates down the chain (`this._suspendNativeUpdates(SuspendType.UISetup);`).
Maybe we should we create a new SuspendType …

feat: reusable views

---

packages/core/ui/page/index.ios.ts

I have a plugin `@nativescript-community/system-ui` which allows to change status bar background color.
without `updateWithWillAppear` there was no way for my plugin to rollback the status bar color once i closed a modal page which was changing it.
the `updateWithWillDisappear` allows to have smoother modal close by changing the status bar color as soon as the modal close animation starts
My plugin can hook those methods through class mixins
This is mostly used by fullscreen modals.
This PR mostly dont change behavior. I just added `updateStatusBar` from `updateWithWillAppear` to ensure the status bar style is also updated in the modal close case.
Working on that i saw that N is not firing page navigation events for modals. I would raise the question should we not bring it back? I feel it …

Ios modal status bar

---

packages/core/ui/frame/index.ios.ts

Sometimes the application crashes when the user back the page with iOS back swipe.
This commit adds a new check to verify if the new page is available before checking the frame.
It seems to fix random crashes when navigating on iOS device.
Fixes #9096

fix(ios) Navigation via swipe leads to crash

---

packages/core/ui/styling/background.android.ts

When not using border radius or border colors it is much faster, it is much faster to set only backgroundColor.
In my profiling tests the creation of the border drawable was really slow.

Faster background color

---

packages/core/__tests__/observable/observable-array.ts
packages/core/data/observable-array/index.ts

Fix for when using splice on ObservableArray and specifying the start only. Passing `undefined` as the deleteCount to Array doesn't work as expected.
- [x ] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#commit-messages.
- [ x] There is an issue for the bug/feature this PR is for. To avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it.
- [ x] You have signed the [CLA](http://www.nativescript.org/cla).
- [ x] All existing tests are passing: https://github.com/NativeScript/NativeScript/blob/master/tools/notes/DevelopmentWorkflow.md#running-unit-tests-application.
- [ x] Tests for the changes are included - …

fix: ObservableArray splice with start only

---

packages/core/ui/frame/frame-common.ts
packages/core/ui/frame/frame-helpers.ts
packages/core/ui/page/page-common.ts

Fixes the `page.frame` getter in some cases where the Frame has been extended with a custom implementation.

fix(page): frame getter for custom Frames

---

packages/core/ui/page/index.ios.ts

On iOS if you were to use a frame modally, the deep(backStack >0) `navigatingFrom` events were not fired.
The reason is pretty simple, it was seen as modal and thus no event (yet `navigatingTo` was fired...)
That PR simply bypass the check if frame backstack length is > 0. That way we get the events for deep navigation but we still "skip" it when closing the modal itself.

fix: allow navigationFrom event for deep navigation within modal frame

---

packages/core/global-types.d.ts

Global types conflict with node types as used in various integrations differently. This was particularly problematic for Vue 3 and works well for all integrations with this removed.
```
node_modules/@nativescript/core/global-types.d.ts:157:11 - error TS2430: Interface 'NodeRequire' incorrectly extends interface 'Require'.
157 interface NodeRequire {
~~~~~~~~~~~
node_modules/@nativescript/core/global-types.d.ts:157:11 - error TS2430: Interface 'NodeRequire' incorrectly extends interface 'Require'.
The types returned by 'context(...)' are incompatible between these types.
Property 'id' is missing in type 'RequireContext' but required in type '__WebpackModuleApi.RequireContext'.
157 interface NodeRequire {
~~~~~~~~~~~
node_modules/@types/webpack-env/index.d.ts:23:9
23         id: string;
~~ …
```

fix(core): conflicting node global types

---

packages/core/ui/dialogs/dialogs-common.ts
packages/core/ui/dialogs/index.android.ts
packages/core/ui/dialogs/index.d.ts

Right now, you can't change the theme for android dialogs.
A theme attribute has been added to change the theme of android dialogs. Available themes are: https://developer.android.com/reference/android/R.style

feat: Add possibility to choose theme in android dialogs

---

packages/core/xhr/index.ts

App breaks on unknown xhr event wiring.
App no longer breaks on unknown xhr event wiring.
closes https://github.com/NativeScript/NativeScript/issues/9245

fix(xhr): remove unnecessary throw when event not supported

---

packages/core/ui/core/properties/index.ts

In NativeScript 6, we were able to override the entire property itself.   Unfortunately when moving to NS 7, you can no longer override the property once it has been created.   This breaks a plugin that I frequently use  (Since NS 2) in my apps, that needs to override the some properties valueChanges and valueConverter functions.   
This adds a new "function"  `overrideHandlers`  to several of the property types which allows you to pass in the same options as at creation time, and if any of them exist in the new options array it replaces the existing property handler.  
I have opened a RFC here to replace the property system in NS 8(?) (https://github.com/NativeScript/rfcs/discussions/29) as this is really more of a hack so that we don't have to make any breaking changes to the property …

feat: allow property overrides at runtime

---

packages/core/ui/core/properties/index.ts
packages/core/ui/editable-text-base/editable-text-base-common.ts
packages/core/ui/editable-text-base/index.android.ts
packages/core/ui/text-field/index.android.ts

Passing in a number value for the Android Keyboard type is supposed to be supported, however it wasn't converting the "string" value to a number.
It will now convert the number to a string.

fix(android): KeyboardType now respects numbers

---

packages/webpack5/package.json
packages/webpack5/src/configuration/base.ts

Undesirable warnings display during webpack build.
For example:
```
WARNING in ./node_modules/@angular/core/fesm2015/core.js 29714:15-102
System.import() is deprecated and will be removed soon. Use import() instead.
For more info visit https://webpack.js.org/guides/code-splitting/
```
Clean build output.

feat(webpack): filter common undesirable warnings by default

---

nativescript-core/ui/bottom-navigation/bottom-navigation.android.ts

background the app, go to settings, change to light / dark theme, resume the app, the app crashes with:
```
System.err: An uncaught Exception occurred on "main" thread.
System.err: Calling js method onStart failed
System.err: Error: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.View android.widget.LinearLayout.getChildAt(int)' on a null object reference
System.err: 
System.err: StackTrace:
System.err: push.../node_modules/@nativescript/core/ui/bottom-navigation/bottom-navigation.js.BottomNavigation.updateAndroidItemAt(file: node_modules/@nativescript/core/ui/bottom-navigation/bottom-navigation.android.js:580:0)
```
Android apps can change device dark/light theme anytime with no crash.

fix(bottom-navigation): android light/dark theme change on device crash

---

packages/core/utils/native-helper.d.ts
packages/core/utils/native-helper.ios.ts

Fixes incorrect declaration of ```Utils.ios.collections.jsArrayToNSArray``` and ```Utils.ios.collections.nsArrayToJSArray``` where accepted and returned ```string[]``` regardless of type of the input parameter.

fix(ios): incorrect declaration of 'jsArrayToNSArray' and 'nsArrayToJSArray'

---

packages/core/core-types/index.d.ts
packages/core/core-types/index.ts

`Enums` could not be used exactly as they were in 7.0.
`Enums` can be used as normal as they were in 7.0 and a proper deprecation is displayed to move to `CoreTypes`.
closes https://github.com/NativeScript/NativeScript/issues/9298

fix(core): Enums deprecation adjustment

---

package.json

`npm run clean` will delete most editor files in the `.vscode`, and completely remove the `.idea`.   Under an intellij editor, this removal causes the editor to become unstable and crash or lockup.   So it is not recommended to clean the `.idea` folder.
Tells the git clean command to ignore the .idea and .vscode folders during a clean.

fix: npm clean to ignore .idea / .vscode

---

packages/webpack5/__tests__/configuration/__snapshots__/angular.spec.ts.snap
packages/webpack5/__tests__/configuration/__snapshots__/base.spec.ts.snap
packages/webpack5/__tests__/configuration/__snapshots__/javascript.spec.ts.snap
packages/webpack5/__tests__/configuration/__snapshots__/react.spec.ts.snap
packages/webpack5/__tests__/configuration/__snapshots__/svelte.spec.ts.snap
packages/webpack5/__tests__/configuration/__snapshots__/typescript.spec.ts.snap
packages/webpack5/__tests__/configuration/__snapshots__/vue.spec.ts.snap
packages/webpack5/package.json
packages/webpack5/src/configuration/base.ts
packages/webpack5/src/index.ts

The current webpack 5 & babel loader does not actually support things the NativeScript v8 engine actually supports. (see notes).   Certain ES code will break webpack and/or babel:
```
// Android & iOS
class C {  
static x = 'x'; 
};
// ios only (as the android runtime isn't new enough yet in NS 8.0)
class C {
#x() { return 42; }
x() {
return this.#x();
}
}
```
Both of these class types will now be accepted by webpack and run on the actual devices since the actual v8 engine supports them.
1. Please note; if you look at the official https://kangax.github.io/compat-table/es6/ you will see other things where Babel 7 doesn't fully support some of the later ES syntax as the v8 engine we are using as shown here  http://nativescript.rocks/compat/esnext/ 
2. This updates the master template to …

fix: webpack5 ES incompatibilities using JS

---

packages/core/platforms/android/native-api-usage.json

If using limited metadata builds, the application will crash on startup on Android because of the new accessibility changes.
Application will no longer crash as we are adding the new class it needs to include metadata in the metadata exceptions list.

fix: Accessibility breaks limiting metadata on Android

---

packages/core/ui/text-base/index.android.ts
packages/core/ui/text-base/index.ios.ts

This PR adds move the generation of the native `FormattedString` to a class method so that it can be overriden by subclasses and plugins.
This is used, for example, by my `@nativescript-community/text` to override the default implementation for all `TextBase`  to make it faster and add more functionnalities.

fix: allow subclass to override createFormattedTextNative

---

apps/automated/package.json
apps/toolbox/package.json
apps/ui/package.json
packages/core/trace/index.d.ts
packages/core/trace/index.ts
packages/core/ui/core/view-base/index.ts

webpack loader can cause build failure due to protected `class` getter/setters in view-base.
```
ERROR in ./node_modules/@nativescript/core/ui/core/view-base/index.js 199:8
Module parse failed: Unexpected token (199:8)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|         return this._isLoaded;
|     }
>     get class() {
|         return this.className;
|     }
@ ./node_modules/@nativescript/core/ui/index.js 10:0-104 10:0-104 10:0-104 10:0-104 10:0-104 10:0-104
@ ./node_modules/@nativescript/core/bundle-entry-points.js 5:0-44 6:53-66
@ ./app/__@nativescript_webpack_virtual_entry_typescript__ 2:0-49
```
Builds successfully.
This PR also includes:
* typings correction to …

fix(core): protected class getter webpack issue

---

packages/core/ui/layouts/root-layout/index.android.ts

When there is no tap event on a view that is added dynamically via RootLayout, tap events are passing through the views underneath it on Android
Dynamic views added via RootLayout catches tap events and doesn't let it pass through views underneath it
Fixes/Implements/Closes #9340.

fix(layouts): prevent android touch event to pass through views underneath

---

packages/core/platform/index.android.ts
packages/core/platform/index.ios.ts

Returning to the app after language/region change will correctly reflect w/o restarting the app

feat: don't cache device language & region

---

packages/core/accessibility/font-scale.android.ts
packages/core/accessibility/font-scale.ios.ts
packages/core/application/index.d.ts
packages/core/index.d.ts
packages/core/index.ts

The `fontScaleChanged` event was wired up, but not exposed as part of the `Application` events. This PR adds `fontScaleChanged` to `Application` so you can use it as follows:
```typescript
Application.on(Application.fontScaleChangedEvent, (args) => {
console.log('fontScaleChangedEvent newValue', args.newValue);
});
```

fix(a11y): add missing application event for `fontScaleChanged`

---

packages/core/data/observable/index.d.ts
packages/core/index.d.ts

A few flavor integrations used this but in particular the typings were missing for them.

fix(core): typings for Utils.queueMacrotask and static methods on Observable

---

packages/core/ui/action-bar/index.ios.ts
packages/core/ui/frame/index.ios.ts
packages/core/ui/page/index.ios.ts

Under various async conditions of initializing an application on boot (for example the new Angular 12 integration coming soon provides more flexibility around boot conditions), these areas of core were frail and subject to crashes.
Guards the unstable areas to ensure smooth handling on boot or init of page/frame under more versatile conditions.

fix(core): guard unstable init contexts under async conditions

---

packages/core/ui/text-base/index.android.ts

needs to be set on `nativeTextViewProtected` for text-base components
fixes https://github.com/nativescript-community/ui-material-components/issues/304

fix(android): accessibilityIdentifier

---

packages/webpack5/src/configuration/angular.ts

angular loads the template directly from disk
angular uses webpack resolver to load the template
@rigor789 can you please update the snapshots for me? for some reason the tests always fail on windows so I can't update them
Fixes #9458.

fix(webpack5): allow platform specific template files

---

packages/core/application/index.android.ts
packages/core/application/index.d.ts

Sorry, I did not find the tests folder.
You can use this interface below to get registered broadcastReceiver, then you can get result code in onReceiveCallback when you are using registerBroadcastReceiver.
```
Application.android.getRegisteredBroadcastReceiver(intentFilter: string)
```
#9466

feat(android): provide ability to get registered broadCastReceiver #9466

---

packages/webpack5/__tests__/configuration/__snapshots__/typescript.spec.ts.snap
packages/webpack5/__tests__/configuration/typescript.spec.ts
packages/webpack5/src/configuration/typescript.ts

With webpack5, typescript projects do not load filenames that end with a `d` e.g. `tested.ts`
Per the [regex lookbehind proposal](https://github.com/tc39/proposal-regexp-lookbehind)
> Patterns normally match starting from the leftmost sub-pattern and move on to the sub-pattern on the right if the left sub-pattern succeeds. When contained within a lookbehind assertion, the order of matching would be reversed. Patterns would match starting from the rightmost sub-pattern and advance to the left instead. For example, given /(?<=\$\d+\.)\d+/, the pattern would first find a number and ensure first that it is preceded by . going backward, then \d+ starting from ., and lastly $ starting from where \d+ within the assertion begins. The backtracking direction would also be reversed as a result of …

fix(webpack5): change typescript declaration file filter regex

---

packages/core/ui/core/view/index.android.ts

on android setting a length to 0 will treat it as "auto"
length 0 will be treated as 0, where null/undefined will be treated as auto.
Fixes #9484.

fix(android): allow 0-length properties

---

packages/webpack5/src/bin/index.ts
packages/webpack5/src/configuration/base.ts
packages/webpack5/src/plugins/WatchStatePlugin.ts

When something is broken within WebPack compilation, the NativeScript WebPack CLI will simply ignore those and let the NativeScript CLI continue with the build as if nothing happened...
When the WebPack build fails, also the NativeScript build should fail.

fix(webpack): compilation errors should no longer ignored

---

apps/ui/src/modal-view/nested-modal-tab.xml
apps/ui/src/modal-view/nested-modal.ts
apps/ui/src/modal-view/nested-nested-frame.ts
apps/ui/src/modal-view/nested-nested-frame.xml
apps/ui/src/modal-view/nested-nested-modal.xml
packages/core/ui/core/view/index.android.ts

Android dialogs/fragments handled inside nested views can crash.
Android dialogs/fragments handled inside nested views no longer crash.

fix(android): nested dialogs

---

packages/webpack5/__tests__/configuration/__snapshots__/angular.spec.ts.snap
packages/webpack5/src/configuration/angular.ts

fix(webpack5): angular scss rule not ignoring regular scss

---

packages/core/ui/frame/index.android.ts

On an edge case where the rootView is not set, `onSaveInstanceState` will crash the app.
No longer crashes as we check if the rootView exists before using it.
Fixes https://github.com/NativeScript/angular/issues/8.

fix: onSaveInstanceState should not crash when no rootView is set

---

packages/core/abortcontroller/abortsignal.ts
packages/core/abortcontroller/index.ts
packages/core/globals/index.ts

This PR adds the `AbortController` polyfill.
Now it is not yet used by the fetch polyfill. Also i think it is a good time we think about creating a `ProvidePlugin` for our webpack to control those polyfills instead of always "requiring" them

Abortcontroller polyfill

---

packages/core/core-types/index.ts
packages/core/ui/editable-text-base/editable-text-base-common.ts
packages/core/ui/editable-text-base/index.android.ts
packages/core/ui/editable-text-base/index.d.ts
packages/core/ui/editable-text-base/index.ios.ts

This is useful to make your app work correctly with password managers  and such.
It is important to note that it does not represent exactly the same thing on iOS/Android
* iOS: `textContentType` which is used for more that auto fill hint. It also helps the platform decide which keyboard to show
* Android: `setAutofillHints` : only for auto fill hint...
So i decided to choose the name of the most specific one.

feat: autofillType property for edit text base

---

packages/core/ui/frame/index.android.ts

After changing the system theme (toggle dark mode)
```
JS: activityPaused
JS: activityStopped
JS: saveActivityState
JS: [exitEvent] // this destroys the angular instance, probably the same for other flavors
JS: activityDestroyed
JS: activityCreated
JS: activityStarted
JS: activityResumed
```
normal exit:
```
JS: activityBackPressed
JS: [suspendEvent]
JS: activityPaused
JS: activityStopped
JS: [exitEvent]
JS: activityDestroyed
```
normal enter (after previous exit)
```
JS: activityCreated
JS: activityNewIntent
JS: [launchEvent] // this creates the angular/other flavors instance
```
```
JS: activityPaused
JS: activityStopped
JS: saveActivityState
// no exit event here!
JS: activityDestroyed
JS: activityCreated
JS: activityStarted
JS: activityResumed
```
Fixes/Implements/Closes #[Issue …

fix(android): do not call exitEvent on activity restart

---

packages/core/ui/core/view/index.ios.ts

This should not happen but it does. Did not manage to find the real source but it seems ok to test it here. Plus if it happens the measurement chain for that view will be broken

fix(core): prevent iOS views to be measured if no native view

---

packages/core/ui/button/index.ios.ts

Currently Button on iOS doesn't respond to background color changes
after it is created. This commit implements the backgroundColorProperty
to access the native UIButton's backgroundColor property.
Fixes NativeScript/NativeScript#9523

fix(ios): background color property on Button

---

packages/core/ui/styling/background.android.ts

On Android background-image: none would cause a crash.
No longer crashes.
closes https://github.com/NativeScript/NativeScript/issues/9546

fix(android): background-image 'none'

---

packages/core/ui/frame/index.android.ts

We currently check for `androidx.lifecycle.Lifecycle.State.STARTED`, which happens after CREATE, so when `_onAttachedToWindow` is called during activity created, it's not attached properly (like when suspending/resuming with a frame inside tabs/bottom nav)
Check for `androidx.lifecycle.Lifecycle.State.CREATED` instead. Also guards around `foregroundActivity` or `startActivity` not having a `getLifecycle` method and falls back to a default `androidx.lifecycle.Lifecycle.State.CREATED` (this may happen on some edge cases like: app has multiple activities and foreground is not a `androidx.fragment.app.FragmentActivity` and `startActivity` was either destroyed or is not also a `androidx.fragment.app.FragmentActivity`)

fix(android): only attach if activity is CREATED

---

packages/core/ui/text-field/index.ios.ts

On iOS if we type a few character and use the auto-fill function it will concat the strings instead of replacing to the suggested one.
Video example in the issue: https://github.com/NativeScript/NativeScript/issues/9486
After typing the the start of an e-mail and tap on auto-fill, it will replace the text.
**Note:**
The solution is based on the string's delta, which means if we copy and paste a text to a textfield, it will behave like we used auto-fill and replace the text in the view model.
Fixes #9486

fix: replace autofill string in textfield

---

packages/core/css/parser.ts
packages/core/ui/styling/style-properties.ts

The parser now returns a `Color` directly.  We need to test for it and not try to create an new instance of `Color`

fix: background failing when parsing color #9559

---

packages/webpack5/__tests__/configuration/__snapshots__/javascript.spec.ts.snap
packages/webpack5/__tests__/configuration/__snapshots__/typescript.spec.ts.snap
packages/webpack5/src/configuration/javascript.ts
packages/webpack5/src/configuration/typescript.ts

In plain flavors (TypeScript and JavaScript), having scss files starting with `_` are not ignored from the require.context causing build errors because they are treated as root stylesheets.
Files starting with an `_` are now properly ignored from the `require.context()` that maps out all the files in the app and will no longer cause build errors due to treating these stylesheets as root ones.

fix(webpack): exclude files starting with _ from require.context

---

packages/core/utils/index.android.ts
packages/core/utils/index.d.ts

`Open File...` title is hard coded.
You can change the default `Open File...` title
Implements #9293

feat: android openFile dialog title

---

packages/webpack5/package.json

When installing `@nativescript/webpack@5` the following warnings are shown
```
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
```
The deprecated packages have been updated so no warnings are shown.

chore(webpack5): update react-refresh

---

packages/webpack5/__tests__/configuration/__snapshots__/angular.spec.ts.snap
packages/webpack5/__tests__/configuration/__snapshots__/base.spec.ts.snap
packages/webpack5/__tests__/configuration/__snapshots__/javascript.spec.ts.snap
packages/webpack5/__tests__/configuration/__snapshots__/react.spec.ts.snap
packages/webpack5/__tests__/configuration/__snapshots__/svelte.spec.ts.snap
packages/webpack5/__tests__/configuration/__snapshots__/typescript.spec.ts.snap
packages/webpack5/__tests__/configuration/__snapshots__/vue.spec.ts.snap
packages/webpack5/src/configuration/base.ts
packages/webpack5/src/configuration/javascript.ts
packages/webpack5/src/configuration/typescript.ts

webpack 5 includes nativescript-hot-loader and the hmr runtime regardless if it's being used or not (which have a nasty side effect of removing sourcemaps for code coverage)
Those are only added when env.hmr is true

fix(webpack): respect hmr flag

---

packages/webpack5/src/configuration/angular.ts

This fixes angular JIT compilation
Because we're pushing instead of unshifting the NativeClass transformer, angular fails to build in JIT mode
Prepend NativeClass transformer so it always runs first

fix(webpack): prepend NativeClass transformer in angular config

---

apps/toolbox/src/pages/root-layout.ts
packages/core/ui/layouts/root-layout/index.android.ts

Gradient background color for root layout's shade cover is only supported on iOS
Add support for gradient background color for root layout's shade cover on Android

feat(layouts): rootlayout gradient shadecover android

---

packages/webpack5/__tests__/configuration/__snapshots__/angular.spec.ts.snap
packages/webpack5/package.json
packages/webpack5/src/configuration/angular.ts
packages/webpack5/src/helpers/index.ts
packages/webpack5/src/helpers/tsconfig.ts

throws when no @angular-devkit/build-angular is installed and uses ESNext always
shows warning instead, reads tsconfig and adds --env.disableAOT flag

feat: disable aot, optional angular dep and tsconfig utils

---

packages/core/ui/frame/fragment.android.ts
packages/core/ui/frame/fragment.transitions.android.ts
packages/core/ui/frame/index.android.ts
packages/core/ui/frame/index.d.ts

Nested frames get into inconsistent states when destroyed and recreated.
We attempt to manually recreate the frames when android doesn't magically do it for us.
AndroidFragmentCallbacks now requires `onResume` as well
Migration steps:
specify `onResume` on custom fragment implementations

fix(android): nested frames were sometimes not recreated

---

packages/core/module-name-resolver/qualifier-matcher/index.ts

Screen qualifier matcher does not support multiple qualifiers for a file.
Screen qualifier matcher will support multiple qualifiers for a file.
Fixes/Closes #9706

fix: Qualifier matcher did not support multiple qualifiers for a single file

---

packages/core/application/index.android.ts
packages/core/application/index.ios.ts
packages/core/index.ts

Since application instances are now created during the call of `Application.run`, core `index.ts` of NativeScript will always export `Application.android` and `Application.ios` as undefined.
This was tested with a JavaScript app on android device.
I believe the reason is that these properties are exported inside a constant named `Application`, therefore imported properties are never updated when changed.
Here is the root of the problem:
```js
export const Application = {
launchEvent,
displayedEvent,
uncaughtErrorEvent,
discardedErrorEvent,
suspendEvent,
resumeEvent,
exitEvent,
lowMemoryEvent,
orientationChangedEvent,
systemAppearanceChangedEvent,
systemAppearanceChanged,
fontScaleChangedEvent,
getMainEntry,
getRootView,
resetRootView: _resetRootView,
getResources,
setResources, …
```

fix(8.2-alpha): `Application.android` and `Application.ios` were undefined in startup

---

packages/core/ui/core/bindable/bindable-expressions.ts

This is an addition to my work for vanilla NS expression parsing. It contains few tweaks regarding binding contexts.
1) Expression parser cannot parse indentifiers that belong to global.
2) Converter callbacks use object they are declared into as a context.
1) Expression parser will now check if an identifier belongs to global.
2) Converter callbacks will have current binding context or the instance they were called from as function context just like the old way.
Hello World app sample with an example of supporting `global`:
```xml
<Page xmlns="http://schemas.nativescript.org/tns.xsd" navigatingTo="navigatingTo">
<ActionBar title="My App" icon="" />
<StackLayout class="p-20">
<Label text="Tap the button" class="h1 text-center" />
<Button text="TAP" tap="{{ onTap }}" class="-primary" /> …
```

feat(8.2-alpha): Addition of "global" context for expressions inside XML

---

apps/automated/src/http/http-string-worker.ts
apps/toolbox/src/app.css
apps/toolbox/src/main-page.xml
apps/toolbox/src/pages/touch-animations.ts
apps/toolbox/src/pages/touch-animations.xml
packages/core/application/index.android.ts
packages/core/application/index.d.ts
packages/core/application/index.ios.ts
packages/core/index.ts
packages/core/package.json
packages/core/ui/action-bar/index.android.ts
packages/core/ui/button/index.android.ts
packages/core/ui/core/view-base/index.d.ts
packages/core/ui/core/view-base/index.ts
packages/core/ui/core/view/index.android.ts
packages/core/ui/core/view/index.d.ts
packages/core/ui/core/view/view-common.ts
packages/core/ui/frame/fragment.transitions.android.ts
packages/core/ui/gestures/gestures-common.ts
packages/core/ui/gestures/index.d.ts
packages/core/ui/gestures/touch-manager.ts
packages/core/ui/index.ts
packages/core/ui/styling/background-common.ts
packages/core/ui/styling/background.android.ts
packages/core/ui/styling/background.d.ts
tools/assets/App_Resources/Android/src/main/AndroidManifest.xml

No easy way to add dynamic touch down/up animations for nice interactivity in the UI.
Introduces a `TouchManager` with an easy api to enable rich interactivity throughout the UI.
Also adds `touchAnimation` and `ignoreTouchAnimation` properties to views. This allows each view to opt into and define/control it's own touch down/up animations.
`TouchManager.enableGlobalTapAnimations = true` can also be used alongside `TouchManager.animations.{up|down}` animations to define consistent reusable animations for the entire UI by auto detecting and attaching to any view with a `tap` binding.

feat(ui): TouchManager for ease in adding interactivity

---

packages/core/ui/builder/binding-builder.ts

This is a change that came up due to expression parser rework and its new features.
NativeScript Core cannot parse XML expression with template literal syntax and nested indentifiers.
Example:
```xml
<Page actionBarHidden="true" xmlns="http://www.nativescript.org/tns.xsd">
<GridLayout>
<Label text="{{ 'Hello' + username }}"/> 
<Label text="{{ `Hello ${username}` }}"/> 
</GridLayout>
</Page>
```
Template literal syntax that includes identifiers will be parsed as expression.

fix(core 8.2): Parse template literal syntax with nested identifiers as expression

---

packages/core/ui/core/view/index.ios.ts

if the safeareainsets change, the children view's safeareainsets are not updated and will layout wrongly
forces the layout before layouting the children

fix(ios): force layout of view when changing the safe area insets

---

apps/ui/src/tab-view/tab-view-icon-local-page.ts
apps/ui/src/tab-view/tab-view-icon-page.ts
packages/core/ui/tab-view/index.android.ts
packages/core/ui/tab-view/index.d.ts
packages/core/ui/tab-view/tab-view-common.ts
packages/types-android/src/lib/android/org.nativescript.widgets.d.ts
packages/ui-mobile-base/android/widgets/src/main/java/org/nativescript/widgets/TabIconRenderingMode.java
packages/ui-mobile-base/android/widgets/src/main/java/org/nativescript/widgets/TabLayout.java
packages/ui-mobile-base/android/widgets/src/main/java/org/nativescript/widgets/TabStrip.java

On Android, the TabView always renders icons without any tinting.
This is similar to the `alwaysOriginal` option of the `iosIconRenderingMode` on iOS
There is a new option, `androidIconRenderingMode` which provides `alwaysOriginal` (default) and `alwaysTemplate` options.
These options behave similar to iOS, however the default on Android is `alwaysOriginal` where as iOS defaults to `automatic` which prefers templates.
https://user-images.githubusercontent.com/8206108/136665172-1d956412-06c9-4a64-ac3b-a43268f575cc.mov

feat: tab view android icon rendering mode

---

packages/core/application/index.android.ts
packages/core/application/index.d.ts
packages/core/application/index.ios.ts
packages/core/index.d.ts
packages/core/index.ts

Currently default frame refresh rates are used on iOS.
On supported devices users can now dynamically optimize frame refresh rates in accordance to:
see: https://developer.apple.com/documentation/quartzcore/optimizing_promotion_refresh_rates_for_iphone_13_pro_and_ipad_pro
```
Application.setMaxRefreshRate({
min: 80,
max: 120,
preferred: 120
});
```
Can be called to dynamically adjust frame refresh rates on newer devices to optimize high impact animations. Other adjustments can be made according to docs under various conditions.
No breaking changes - this was already being setup on app boot with default settings; this just allows user to set it themselves where needed.

feat(ios): allow dynamic ProMotion frame refresh rate changes

---

packages/core/config/config.interface.ts
packages/webpack5/__tests__/helpers/platform.spec.ts
packages/webpack5/scripts/jest.setup.ts
packages/webpack5/src/helpers/config.ts
packages/webpack5/src/helpers/platform.ts

`main` in `nativescript.config.ts` is ignored.
`main` in `nativescript.config.ts` is read and used instead of `package.json`'s `main` when set.
implements #9658
Possibly breaking if a project has a `main` field set in the `nativescript.config.ts` - since after this lands, this value will be used instead of `package.json` `main`. 
The impact is likely very small, the steps to migrate:
1. (Option A) remove `main` from `nativescript.config.ts` if set
2. (Option B) update `main` to the correct path in `nativescript.config.ts` if set incorrectly

feat(webpack): read nativescript.config.ts main if set before package.json

---

packages/core/utils/native-helper.android.ts

Hiding the keyboard on iOS loses focus; this makes Android match when no view argument is provided.

fix(android): when hiding the keyboard make view lose focus to match ios behavior

---

packages/core/accessibility/accessibility-service.android.ts

App crashes on api <19
App works on api <19

fix(android): api17 crash on a11y service

---

packages/core/ui/core/bindable/bindable-expressions.ts
packages/core/ui/core/bindable/index.ts

The follow additions are included in this patch:
- Better error reporting for binding expression parsing failure
- Added missing optional chaining support for callbacks
- Using a safer approach to recognize converters
- Fixed an issue that caused a circular reference for `$value` key in certain cases of two-way binding
- Re-added lost converters feature according to docs: `Since the usual operation is converting data from model to view, if a function is provided as converter, it acts as a toView function.`
- If a property caller is undefined (e.g. caller.property1.property2), parser will return undefined instead of throwing error. This is similar to old behaviour and is an attempt to fix issues similar to #9785 
@felixkrautschuk This patch includes changes that should help with your …

feat: Binding expression parser additions and improvements

---

apps/toolbox/src/app.css
apps/toolbox/src/main-page.xml
apps/toolbox/src/pages/switch.ts
apps/toolbox/src/pages/switch.xml
packages/core/ui/switch/index.android.ts
packages/core/ui/switch/index.ios.ts
packages/core/ui/switch/switch-common.ts

Switches cannot be styled using the `:checked` pseudo selector.
Switch color behavior differs between iOS and Android.
Android Switch colors are muted and not same as set.
Switches can now be styled with the `:checked` selector.
Switches now have the same behavior across iOS and Android.
Switch colors are exactly as set (no color filters etc applied).
```css
.switch-demo-page Switch.custom-switch {
color: #ddd;
background-color: #65adf1;
}
.switch-demo-page Switch.custom-switch:checked {
color: #111;
background-color: #65adf1;
}
.switch-demo-page Switch.custom-switch:disabled {
color: #777;
background-color: #ddd;
}
.switch-demo-page Switch.custom-switch:disabled:checked {
color: #ddd;
background-color: #777;
}
```
Switch `color` now affects both unchecked and checked …

feat(switch): :checked pseudo and color fixes

---

packages/core/ui/text-field/index.android.ts

Binding the `keyboardType` to `false/true` prevents the `secure` text-field from working.
Setting the keyboardType to a boolean should not set the `inputType`.

fix: android boolean keyboardType should not set inputType

---

apps/toolbox/src/pages/a11y.ts
apps/toolbox/src/pages/a11y.xml
apps/toolbox/src/pages/sample-modal.ts
apps/toolbox/src/pages/sample-modal.xml
packages/core/ui/core/view/view-common.ts

Closing a modal will not tear down the views from the modal (GC might eventually, but not reliably)
Closing a modal will fire the `closeCallback` and then tear down the views explicitly.

fix: tear down views after a modal is closed

---

packages/core/ui/core/view/index.ios.ts

On iOS, views with `background-image: none` are redrawn multiple times while they shouldn't. Even if you just set a `background-color`, `background-image` is automatically set to `none` (I don't know what is setting this value though).
Views are redrawn only if the view has a background-image, a non-uniform border or a border radius.
I identified this problem because my app crashed because of a constantly redrawn background. This PR does not fix the problem in my app (I made other app-specific changes) but I thought that the change is still needed for better performance.
I also could not run the tests (I think the README is outdated because the `tests` folder does not exist).

fix: Do not redraw on iOS if background image is 'none'

---

packages/core/ui/builder/binding-builder.ts
packages/core/ui/core/bindable/bindable-expressions.ts

- Refactoring converter and function calls parsing mechanism
- Added missing exponentiation operator
- Fixed content inside template literals returning malformed value
- Support for using converters without using`()` just like in old NS
- Null-safety for parent properties whose value is null or undefined (similar to the Polymer way)

ref(core): Improved converter and function call parsing mechanism for XML expressions

---

apps/toolbox/src/pages/a11y.xml
packages/core/accessibility/index.android.ts
packages/core/global-types.d.ts
packages/core/platforms/android/res/values/ids.xml
packages/core/ui/core/view/index.android.ts
packages/core/ui/core/view/index.ios.ts
packages/core/ui/core/view/view-common.ts
packages/core/ui/text-base/index.android.ts
packages/webpack5/__tests__/configuration/__snapshots__/angular.spec.ts.snap
packages/webpack5/__tests__/configuration/__snapshots__/base.spec.ts.snap
packages/webpack5/__tests__/configuration/__snapshots__/javascript.spec.ts.snap
packages/webpack5/__tests__/configuration/__snapshots__/react.spec.ts.snap
packages/webpack5/__tests__/configuration/__snapshots__/svelte.spec.ts.snap
packages/webpack5/__tests__/configuration/__snapshots__/typescript.spec.ts.snap
packages/webpack5/__tests__/configuration/__snapshots__/vue.spec.ts.snap
packages/webpack5/src/configuration/base.ts
packages/webpack5/src/index.ts

Using `automationText` for e2e testing interferes with a11y.
Adds a new `testID` property matching what the [React Native community adopted](https://reactnativetesting.io/component/testing.html#testing-text), also [reference api here](https://reactnative.dev/docs/view#testid) which helps discern e2e testing id's apart from anything specific to a11y.

feat: testID property for use with e2e testing without interfering with a11y

---

packages/core/ui/core/view/view-common.ts
packages/core/ui/layouts/root-layout/index.d.ts
packages/core/ui/layouts/root-layout/root-layout-common.ts

RootLayout popup views will not update or close during live-sync.
RootLayout popup views will close during live-sync.
During my work on this, I took the liberty to do few more important improvements.
1) Method `closeAll` of `RootLayout` will now use Promise.all so that developers can await for all simultaneous popup dismissals.
2) Fixed a small issue that caused live-sync not to reload changes in current page if a `Modal` was shown atop of it. This was a minor bug that occured during early NativeScript 6 updates.
3) Regarding error handling, promise-based methods of `RootLayout` have also gotten few improvements.
The old approach was using try clauses inside promises which caused a promise never to reject in case of error.
There were few trace messages in case trace was enabled but that …

fix: Close popup views on live-sync

---

packages/core/ui/gestures/index.android.ts

native `recognizer` should be reported as `android` and not `ios`

fix(core): android gesture events fix

---

packages/core/utils/utils-common.ts

Calling `Utils.queueGC()` would not throttle or debounce properly.
Calling `Utils.queueGC()` behaves properly now.

fix: queueGC debounce and throttle with reuse of different settings

---

packages/core/ui/styling/style-properties.ts

Using `hsl` colors on borderColor would parse incorrectly.
Using `hsl` colors on borderColor will now parse correctly.

fix(css): borderColor parse handling for hsl color values

---

packages/core/ui/core/view/view-common.ts
packages/core/ui/layouts/root-layout/root-layout-common.ts

This is a performance improvement for RootLayout live-sync. It's also a cleaner approach.
Using the old approach, parents of RootLayout could also close popups during live-sync. Now, RootLayout will handle its own views.

perf: Improved live-sync functionality for RootLayout

---

packages/core/ui/styling/background.android.ts

Android app boot might fail if listeners are wired prior to bootstrap.
Android app boot is more resilient under these conditions.

fix(android): ensure android application is created before setting listeners

---

packages/core/ui/core/view/index.android.ts

This is a simple change allowing views to force the layout change listener to be set without having an event added.
I have some plugins needing this. Thought it would be an easy and good thing to have in the core

fix(core): allow View subclass to force onLayoutChangeListener

---

packages/core/ui/editable-text-base/index.android.ts

This fixes a and issue with `EditableTextBase` and `ad.dismissSoftInput`
If `ad.dismissSoftInput` is called with a null parameter it will actually try to focus the first possible EditText( do we really want that?)
The issue is that the timeout `dismissSoftInput` from `EditableTextBase` could be calling `ad.dismissSoftInput` with a null parameter and thus focus another EditText when you just wanted to dismiss the keyboard
It has been reported multiple times in Discord

Textfield focus fix

---

packages/core/application/index.android.ts
packages/core/core-types/index.ts
packages/core/ui/button/index.ios.ts
packages/core/ui/label/index.ios.ts
packages/core/ui/styling/style/index.ts
packages/core/ui/text-base/index.android.ts
packages/core/ui/text-base/index.d.ts
packages/core/ui/text-base/index.ios.ts
packages/core/ui/text-base/text-base-common.ts
packages/core/ui/text-view/index.android.ts
packages/core/ui/text-view/index.ios.ts
packages/core/ui/text-view/text-view-common.ts

This adds `maxLines` property for all `text-base` components.
It supports number + 'none' as specified. It also works correctly with `whiteSpace`

feat(core): maxLines support for all text components

---

packages/core/ui/proxy-view-container/index.ts

If you set `reusable = true` on a ProxyViewContainer, the children are never re-added to the native visual tree
reusable ProxyViewContainers will now temporarily set the reusable flag on it's children so that they're not destroyed on _tearDownUI and correctly call _addViewToNativeVisualTree during _setupUI

fix: ensure reusable ProxyViewContainer re-adds native children

---

packages/core/ui/styling/background.ios.ts

In iOS:
- Border radius is miscalculated for drop-shadow
- Gradient background border radius is miscalculated when there is drop-shadow
I found those problems while using an iPad. Box-shadow radius was probably miscalculated because of a scale factor that may be higher than 1.
Border radius will be properly calculated for view box-shadow and sublayers. It seems that `toDeviceIndependentPixels` works better and returns the same value as the rest of applied view border-radiuses.
This change will also attempt to apply corner radius to all sublayers. Sublayers will usually consist of a gradient layer and a border layer.
There are also cases that border layer has sublayers but there is a need for a whole refactor to make those look good, that is why we apply radius to top-level layers for now. …

fix: Apply proper border radius to box shadow and view sublayers

---

apps/automated/src/ui/lifecycle/lifecycle-tests.ts
packages/core/package.json
packages/core/ui/animation/animation-interfaces.ts
packages/core/ui/core/view-base/index.ts
packages/core/ui/core/view/index.ios.ts
packages/core/ui/core/view/view-helper/index.ios.ts

Native iOS views are not disposed and cannot be recreated when their view instances are re-added to the view tree.
This PR was initially created for the sole purpose of destroying old native views (until more problems showed up in the process).
This is based on Martin's @farfromrefug  PR #9671 which was reverted because of few problems.
@rigor789 If I'm not mistaken, the most common error case was this one:
```
***** Fatal JavaScript exception - application has been terminated. *****
NativeScript encountered a fatal error: Uncaught TypeError: Cannot set property 'delegate' of null
at
onUnloaded(file: src/webpack:/node_modules/@nativescript/core/ui/text-field/index.ios.js:114:0)
at (file: src/webpack:/node_modules/@nativescript/core/ui/core/view-base/index.js:321:0)
at …
```

fix(ios): proper disposal and recreation of iOS native views

---

packages/core/application/application-common.ts
packages/core/application/index.android.ts
packages/core/application/index.ios.ts
packages/core/ui/frame/index.android.ts

This fixes a bug with my recent addition of `backgroung/foreground` events.
It also adds getters `inBackground` and `suspended` in `application-common` to query the current value for both iOS/Android

fix(core): android wrong background state + current value accessors

---

packages/core/ui/tab-view/index.ios.ts

TabView properties `tab-text-color` and `tab-text-font-size` are not working on iOS 15.
TabView properties `tab-text-color` and `tab-text-font-size` will also work on iOS 15.
Related feedback: https://developer.apple.com/forums/thread/682528
Fixes/Implements/Closes #9844 .

fix(TabView): item styling improvements for iOS 15+

---

packages/core/ui/frame/frame-common.ts

Navigation history is not maintained after live-sync.
This was tested in plain NativeScript and has caused a bit of trouble for some time now during development.
It's related to #9837 and #9839.
Navigation history will be maintained after live-sync.

fix(live-sync): navigation history is now maintained

---

packages/core/ui/layouts/root-layout/root-layout-common.ts

We currently don't have any way to detect if the view has been closed if it was closed by tapping the shade cover. This makes it difficult to do any manual clean up (if needed) when the view is closed via the shade cover.
The changes in the PR adds an `opened` and `closed` event on the `view` that we can listen to..
```
view.on('opened', () => {
// opened
});
view.on('closed', () => {
// closed
});
```

feat(layouts): add opened and closed events for RootLayout

---

packages/core/utils/index.android.ts
packages/core/utils/index.ios.ts

Webpack cannot locate `dataDeserialize` and `dataSerialize` exports.
Webpack will locate `dataDeserialize` and `dataSerialize` exports.

fix: export 'dataSerialize' (imported as 'dataSerialize') was not found

---

packages/core/image-source/index.android.ts
packages/core/image-source/index.ios.ts

Since NS 6, font icons used with Image, ActionItem, and few more elements have bad sizing between the 2 platforms.
It seems there's been a mistake since the implementation of this feature and font size is multiplied with display density 'twice'.
Font icons used with Image, ActionItem, and few more elements will have proper size in both platforms.
Note: In iOS, there was a pixel conversion that was wrong and also didn't run so it was dead and was consequently removed.
Fixes #8391.

fix: Incorrect font icon size conversion to device pixels.

---

packages/core/image-source/index.android.ts

The font icon size that works as a fallback value is incorrect.
The font icon size that works as a fallback value will be incorrect.

fix(core): Font icons had incorrect fallback size in android

---

packages/core/connectivity/index.android.ts

On some android phones, (Google Pixel 5 & Galaxy s20+ running android 12) the final state reported when subscribing to ````Connectivity.startMonitoring```` would report incorrectly report no connectivity.
This happened when the app was in the foreground, and the phone was locked and then unlocked ( i.e. hit power button)
This was because the call to the methods on ConnectivityManager.getActiveNetwork returned null, the documentation seems to suggest that calling any of the syncronus methods on ConnectivityManager is not advised during these callbacks.
https://developer.android.com/reference/android/net/ConnectivityManager.NetworkCallback
The new behaviour is to rely on the network capabilities passed to the callback to determine the status, or to report no connectivity when lost is …

fix(android) Connectivity reporting none on resume

---

packages/core/ui/switch/index.android.ts

Various framework integrations, like Angular, may invoke view change detection cycles on property bindings at times when the `nativeView` is not available resulting in errors like:
```
JS: ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'getTrackDrawable' of undefined
JS: TypeError: Cannot read property 'getTrackDrawable' of undefined
JS:     at Switch.setNativeBackgroundColor (file: src/webpack:/app/node_modules/@nativescript/core/ui/switch/index.android.js:48:0)
JS:     at Switch._onCheckedPropertyChanged (file: src/webpack:/app/node_modules/@nativescript/core/ui/switch/index.android.js:61:0)
```
`Switch` is now resilient to this.

fix(android): race condition on offBackgroundColor view change detection

---

packages/core/color/color-common.ts

Methods `rgbToHsv` and `rgbToHsl` generate wrong output.
Methods `rgbToHsv` and `rgbToHsl` generate correct output.
@farfromrefug this is a continuation for https://github.com/NativeScript/NativeScript/commit/5452b8973520b7657ee59499b8e413e3c54b2817
The problem is that r, g, b variables were missing division in switch statement cases.
With this patch, function arguments are re-assigned and perform division on top. Let me know if we are good with this change.
Fixes/Implements/Closes #9918 .

fix: Output from rgbToHsv and rgbToHsl was incorrect

---

packages/core/ui/page/index.ios.ts

The iOS app is leaking always after using the 'showModal' navigation to present any Page. According to the debugging, the entire page presented is leaking.
The page presented by the 'showModal' navigation is being disposed of memory.

fix(core): iOS app memory leak after using 'showModal' passing any Page as parameter

---

packages/core/ui/label/index.ios.ts

Right now, iOS labels include all the lines on the height measurement and do not respect the value specified by the `numberOfLines` property.
The new behavior respects the `numberOfLines` property and properly measures the label height. When the user doesn't specify a custom value for the property it'll be zero and thus all the lines will be considered in the measurement, just as before.
Fixes #6037

fix(ios): label measure correct height when using custom numberOfLines

---

packages/core/ui/styling/font.ios.ts

a new `UIFont` is constructed whenever a view is instantiated (that displays text).
a new `UIFont` is created only when necessary, otherwise a single UIFont instance is reused.

perf: cache UIFont construction based on FontDescriptor

---

packages/core/ui/core/view/view-helper/index.ios.ts

Inside the **shrinkToSafeArea(view, frame)** method the NativeScript trace is writing the entire IOSHelper source code into the log. See the below example:
```
Layout: class IOSHelper {
static getParentWithViewController(view) {
while (view && !view.viewController) {
view = view.parent;
}
// Note: Might return undefined if no parent with viewController is found
...
...
...
} :shrinkToSafeArea: {"left":0,"right":828,"top":176,"bottom":342}
``` 
Inside the **shrinkToSafeArea(view, frame)** method the NativeScript trace should log something like below:
```
Layout: SectionedTable<SectionedTable> :shrinkToSafeArea: {"left":0,"right":828,"top":368,"bottom":589}
```

fix(core): trace log using a wrong parameter

---

packages/core/ui/frame/frame-common.ts

the event has no real use if we dont get access to `resolvedPage`

fix(core): Frame `navigatingToEvent` event fix

---

packages/webpack5/src/helpers/host.ts

Usage of unit test runner v3+ with Node 18 would fail.
Usage of unit test runner v3+ with Node 18 will operate normally.

fix(webpack): unit test runner with node 18+

---

packages/core/ui/gestures/index.ios.ts

we convert the position to DIP, but the position is already in DIP
we return the position as is
tapData.getX() and tapData.getY() will now return correctly in DIP, so any extra conversions (like calling toDevicePixels) twice must be changed.

fix: do not convert tap data to device pixels twice

---

packages/webpack5/src/configuration/angular.ts

This is needed because otherwise the webpack build will correctly transpile the class to es5 but you're unable to use imported symbols in it:
Example:
```
// JIT + current config:
console.log(_nativescript_core__WEBPACK_IMPORTED_MODULE_8__.GridLayout);
// AOT + current config
console.log(GridLayout);
// AOT + new config
console.log(_nativescript_core__WEBPACK_IMPORTED_MODULE_8__.GridLayout);
```

fix(webpack5): NativeClass decorator should run after angular transformers in AOT mode

---

packages/core/platform/index.android.ts

In android, platform module exposes a `Device` instance that includes `language` and `region` properties.
These getters expose data based on `java.util.Locale` which exposes data from jvm.
Also, `@nativescript/localize` plugin modifies default locale in `java.util.Locale`, resulting in getting a different value from `Device.language` afterwards.
This patch will expose language and region values from android system configuration, as `java.util.Locale.getDefault()` should be more application-specific than device-specific.

ref: Get android device language and region from system configuration

---

apps/automated/src/data/observable-array-tests.ts
apps/automated/src/data/observable-array.md
packages/core/data/observable-array/index.ts

ObservableArray works as an object wrapper that supports some Array methods.
Additionally, methods like `filter` or `map` will return the nested array itself which reduces the worth of wrapper itself.
ObservableArray becomes iterable using `Symbol.iterator` symbol. As a result, it becomes compliant with spread operator and can be used as an argument in `Array.from` and `Array.prototype.concat` methods.
Also, some changes have been made to make ObservableArray more usable.
Since we make use of `getItem` and `setItem` methods for indexing, it's a good chance to add more advanced functionality.
These methods will now support negative indexing, similar to `Array.prototype.at`.
For instance:
```js
var obsArray = new ObservableArray(1, 2, 3);
var item = obsArray.getItem(-1); // Get last item …
```

feat(core): An iterable ObservableArray

---

packages/core/fps-meter/fps-native.android.ts
packages/core/utils/mainthread-helper.android.ts

The following methods are implemented using the ndk which in turn should help lower the overhead when used frequently... 👀  (raf) . [This pr](https://github.com/NativeScript/android-runtime/pull/1713) is required for it to be functional.

feat: runOnMain, postFrameCallback & removeFrameCallback

---

packages/core/ui/text-base/formatted-string.ts

Span items throw `is not a valid View instance` markup error. This is related to few ObservableArray changes in 8.3.
Span items will render without problems.

fix(core): FormattedString.spans threw error in markup.

---

packages/core/data/observable-array/index.ts

With the change in 8.3 to ObservableArray to push very subtile, adding typings lets the compiler find the issues in a code base.
Also updated/corrected typings for find, splice, unshift
Type Checks will fail if incorrect param passed to push etc.

fix(core): Correct typings in ObservableArray

---

packages/core/file-system/file-system-access.android.ts
packages/core/file-system/file-system-access.d.ts
packages/core/file-system/file-system-access.ios.ts
packages/core/file-system/index.d.ts
packages/core/file-system/index.ts

This PR adds a new `knowFolders` `externalDocuments`. On iOS it will return `documents` but on android it returns the documents folder on external storage.
I added a note to the fact that it requires permissions

feat: `knownFolders.externalDocuments()`

---

packages/core/ui/frame/index.android.ts

The FragmentCallbacksImplementation is having memory leak on Android apps on navigations and when the app enters in foreground.
The memory leak can be verified on the Chrome Dev Tools.
The FragmentCallbacksImplementation is being disposed properly.

fix(core): FragmentCallbacksImplementation memory leak on Android

---

apps/automated/src/data/observable-array-tests.ts
packages/core/data/observable-array/index.ts

ObservableArray constructor does not accept multiple arguments because of TypeScript type incompatibility.
Current declaration:
```ts
constructor(args?: T[] | number);
```
Concept:
```ts
const array: ObservableArray<number> = new ObservableArray(1, 2, 3);
```
ObservableArray constructor will accept multiple arguments.
This was achieved by adding few constructor declarations.
Using multiple types with union operator didn't work so I followed the same approach that was used back in NativeScript 6.x.x: https://github.com/NativeScript/NativeScript/blob/cea2e317c8f83ad4866599527638bf00eb6b6b93/nativescript-core/data/observable-array/observable-array.d.ts#L66
The test for the corresponding case was modified in such a way that the TS argument type will also be checked upon execution.

fix(core): Added ObservableArray constructor declarations to support multiple arguments

---

packages/core/ui/core/view/view-helper/index.ios.ts

This reverts commit aee1d0565105158e84b6a752cc05ee0dc0577943.
The original PR https://github.com/NativeScript/NativeScript/pull/9931 resolved some isolated cases but has some undesired side effects.
This returns behavior to original and we will redress this differently in subsequent PR.
cc/ @CatchABus

revert "fix(ios): not responding after rotation (#9931)"

---

packages/core/ui/core/view/view-helper/index.ios.ts

The iOS app isn't responding after rotation. The issue is only reproducible on the iOS phone. Cannot be reproduced on an iOS tablet.
The issue can be reproduced immediately (after the first rotation) on the nested tabs scenario.
See #9931 for more details by @dgmachado. He has provided a sample and precious information.
If needed, NS view controllers will modify their own insets when they layout subviews. This seemed to cause problems in a rotation scenario due to wrong checks inside core during children insets calculation.
Application will operate normally after rotation without problems.
Fixes #9931

fix(ios): app stopped responding after screen rotation

---

packages/core/ui/core/view/view-helper/index.ios.ts
packages/core/ui/page/index.ios.ts

During additional safe area inset calculation, view controllers also included the old additional safe area inset values. Subtracting them from `currentInsetsTop` and `currentInsetsTop` helps calculate proper values for additional insets and fixes problems like tabs infinite loop during rotation.
See https://github.com/NativeScript/NativeScript/pull/9931 for more details by @dgmachado. He has provided a sample and precious information.
Application will properly calculate insets and operate normally after rotation without problems.
Fixes https://github.com/NativeScript/NativeScript/pull/9931

fix(ios): additional safe area insets were miscalculated if already set

---

packages/core/ui/index.ts
packages/core/ui/styling/font-common.ts
packages/core/ui/styling/font.android.ts
packages/core/ui/styling/font.d.ts
packages/core/ui/styling/font.ios.ts

Change font style, weight, scale constructor parameters to optional.
Export `FontStyle` and `FontWeight`.
Creating new font instance requires redundant parameters:
```ts
new Font('material-symbols-outlined', 28, 'normal', 'normal')
```
Style, weight and scale parameters are optional:
```ts
new Font('material-symbols-outlined', 28)
```

feat(core): make font style, weight, scale params optional

---

packages/core/ui/frame/fragment.transitions.android.ts

Android navigation crash when receiving unexpected value on the Entry struct. The entry.resolvedPage is coming null in a Test App and I suppose the root case is that there's memory leak happening on the navigation.
Fix the Android navigation crash just ignoring the expected value received. It's a defensive programming and that fixes the this crash issue.

fix(core): Fix Android navigation crash

---

packages/core/ui/gestures/index.ios.ts

on iOS, depending on the time you hold down the finger, it'll fire both longpress and tap events.
Only tap OR longpress events will be fired. (tap requires longpress to fail, if bound)
Reproduction: https://stackblitz.com/edit/nativescript-stackblitz-templates-s1wsjp

fix(core): handle tap and longpress gesture conflict on iOS

---

packages/core/global-types.d.ts

Using `WeakRef` API `deref` would not pass type checks.
Using `WeakRef` API `deref` will now pass type checks.

fix(core): WeakRef typings to include deref

---

packages/core/ui/builder/binding-builder.ts

There are times method `isExpression` modifies expression in case there is a parent reference inside while there is no need for such a thing.
This was initially added here: https://github.com/NativeScript/NativeScript/commit/e7156b53bd2cca7eb1f15f6b24a13ab3bdb10495#
On top of that, it performs extra regex calls to test expression in a totally wrong way, resulting in an error with this format when there is a parent inside:
```sh
Binding: Property: '`test-${activeAlerts | parentsMatch' is invalid or does not exist. SourceProperty: '`test-${activeAlerts | $parents['ListView'].fooConverter}`'
```
The code block responsive for this gets removed. All tests are passing and expressions with parent work as they should.

fix(core): property parentsMatch is invalid or does not exist

---

packages/core/ui/segmented-bar/index.ios.ts

It seems that setting title to `SegmentedBarItem` using binding methods like Angular interpolation will cause SegmentedBar to crash on iOS.
SegmentedBar will stop crashing. It seems that if we prevent update using a native view validity check, title will still be updated properly.
Fixes/Closes #10009

fix(core): segmented bar crashes on iOS

---

packages/core/platforms/ios/src/UIView+NativeScript.h
packages/core/platforms/ios/src/UIView+NativeScript.m
packages/core/ui/text-base/index.ios.ts
packages/types-ios/src/lib/ios/objc-x86_64/objc!UIKit.d.ts
packages/types-minimal/src/lib/ios/objc-x86_64/objc!UIKit.d.ts

One cannot set `lineHeight` or `letterSpacing` to Labels that consist of spans.
This a feature that got broken in #9761 
`lineHeight` or `letterSpacing` will apply to spans.

fix(ios): properties lineHeight and letterSpacing did not apply to spans

---

packages/core/ui/action-bar/index.ios.ts

calling actionbar.ios on an unloaded page results in an error/crash
actionbar.ios returns null if page is not loaded.

fix: prevent possible crash when accessing actionbar.ios

---

packages/core/ui/text-base/index.android.ts

In android, text transform capitalize is capitalizing after apostrophe. That is because regular expression checks for letters after single quote and performs upper-case.
Regex has been modified so that it performs this operation only on single quotes who are followed by white-space.
Fixes/Implements/Closes #9940.

fix(android): text transform capitalize is capitalizing after apostrophe

---

packages/core/data/observable/index.ts

Here is a small scenario. I have this `Page` event callback.
```js
function onNavigatedTo(args) {
// For a reason, I wish to navigate elsewhere
Frame.topmost().navigate({moduleName: "I accidentally put an invalid path"});
}
```
There is faulty code inside it that returns a blank page and throws error in console.
```sh
Error: Failed to load component from module: I accidentally put an invalid path
```
So far so good. What if I want to use an asynchronous callback though? Let's say that I would like to use async-await because I like it more than promises.
My callback will look like this:
```js
async function onNavigatedTo(args) {
var response = await axios.get(...);
// For a reason, I wish to navigate elsewhere
Frame.topmost().navigate({moduleName: "I accidentally put an invalid path"});
} …
```

fix(core): Errors get swallowed if thrown inside async event functions

---

packages/core/platforms/ios/src/UIView+NativeScript.m
packages/core/ui/text-base/index.ios.ts

In iOS, event `linkTap` is not emitted at all times or happens to emit for wrong tap point.
Issues:
1) Tap point calculations return wrong result if text alignment is not set to center
2) Tap point calculations return wrong result if label is multi-line
3) One can trigger `linkTap` event even if tap occurs outside text bounding area
4) One can trigger `linkTap` event even if tap occurs on a blank point inside text bounding area (method `characterIndexForPointInTextContainerFractionOfDistanceBetweenInsertionPoints` returns first or last character index when no character is found, depending on tap horizontal position)
An accurate `linkTap` event for iOS that meets the requirements to emulate android native tap for `SpannableStrings`.
It was essential to include paragraph style alignment for …

fix(ios): Tapping on span does not emit linkTap event

---

packages/core/ui/web-view/index.android.ts

Android WebView does not handle links with mailto or tel schemes.
WebView for iOS already supports this.
Example:
```html
<a href="mailto:webmaster@example.com">Contact Us</a>
```
Android WebView will handle any scheme provided there is an app that can handle it.
We make use of existing `openUrl` for this which is pretty convenient.

fix(android): Webview href schemes threw 'net::ERR_UNKNOWN_URL_SCHEME'

---

packages/core/ui/html-view/html-view-common.ts
packages/core/ui/html-view/index.android.ts
packages/core/ui/html-view/index.d.ts
packages/core/ui/html-view/index.ios.ts

`HtmlView` has selectable text and there is no way to turn it off.
Added `selectable` property with default value equals `true`.

feat(core): selectable property for HtmlView

---

packages/core/ui/styling/css-selector/index.ts

When app is set with force light mode settings, the styling on modal page is not working if having .ns-light identifier.
Please find the sample app and screen recording attached. (run npm i first)
Steps to reproduce:
1) Tap on 'MODAL' actionbar item to show a modal page.
2) Notice the 'Testing: 1' label on the modal page is in grey color even though on app.android.css, the Label type is styled as red color. 
https://user-images.githubusercontent.com/5738416/198552563-16423b62-1484-449c-8769-ea779b7673a1.mov
The css is being applied properly. 
Sample app:
[testPopoverModal.zip](https://github.com/NativeScript/NativeScript/files/9887022/testPopoverModal.zip)

fix(core): CSS style not working properly in Android modal pages

---

packages/webpack5/src/bin/index.ts

Webpack compiler is not closed, this breaks features that rely on the compiler shutdown hook (for example, caching). 
Now the compiler is closed after running, same behaviour as the webpack CLI.
https://github.com/webpack/webpack/blob/main/lib/webpack.js#L146-L150
Relevant comment about this: https://github.com/webpack/webpack/issues/12345#issuecomment-756099417

fix(webpack): close compiler after run

---

packages/core/accessibility/accessibility-service.android.ts
packages/core/accessibility/index.android.ts
packages/core/connectivity/index.android.ts
packages/core/file-system/index.ts
packages/core/fps-meter/fps-native.android.ts
packages/core/platform/index.android.ts
packages/core/tsconfig.lib.json
packages/core/ui/action-bar/index.android.ts
packages/core/ui/animation/index.android.ts
packages/core/ui/button/index.android.ts
packages/core/ui/core/view/index.android.ts
packages/core/ui/editable-text-base/index.android.ts
packages/core/ui/html-view/index.android.ts
packages/core/ui/list-picker/index.android.ts
packages/core/ui/page/index.android.ts
packages/core/ui/segmented-bar/index.android.ts
packages/core/ui/styling/font.android.ts
packages/core/ui/text-base/index.android.ts
packages/core/ui/time-picker/index.android.ts
packages/core/utils/index.android.ts
packages/core/utils/index.d.ts
packages/core/utils/layout-helper/index.android.ts
packages/core/utils/utils-common.ts

I refactored it all so that we always use the same variable and stop constantly accessing `android.os.Build`
On change i made also was to not use lazy. I did not see any issue locally but maybe i missed something. I dont know why we were using it here

chore(core): refactor android sdk version use

---

packages/core/application-settings/index.android.ts

`ApplicationSettings.getNumber` does not return the precise value of a stored number. That is because `setNumber` uses `SharedPreferences.putFloat` inside and float is 32-bit.
To reproduce
```js
ApplicationSettings.setNumber("timestamp", 1668478505);
console.log(ApplicationSettings.getNumber("timestamp")); // Returns 1668478464
```
`ApplicationSettings.setNumber` will store the precise value and return it as double.
Issue: https://discord.com/channels/603595811204366337/828973479343947787/1041908934266589195

fix(android): ApplicationSettings not returning precise stored numbers

---

apps/toolbox/src/main-page.ts
apps/toolbox/src/main.ts
apps/toolbox/src/pages/box-shadow.ts
apps/toolbox/src/pages/webview.xml
packages/core/index.d.ts
packages/core/index.ts
packages/core/utils/index.android.ts
packages/core/utils/index.d.ts
packages/core/utils/index.ios.ts
packages/core/utils/native-helper.android.ts
packages/core/utils/native-helper.d.ts
packages/core/utils/native-helper.ios.ts

Various commonly needed utilities required developers to create themselves.
New convenient utilities have been added:
* `Utils.dismissKeyboard()`: dismiss any visible keyboard 
* `Utils.copyToClipboard(value)`: copy any string value to device clipboard
* `Utils.ios.setWindowBackgroundColor('blue')`: iOS set window background (shown behind modals)
* `Utils.android.getCurrentActivity()`: get current activity - previously would often check foregroundActivity and startActivity - this fallbacks automatically
* `Utils.android.getResource(name, type?)`: get an android resource by it's name with optional explicit type. This also uses the explicit package name unlike getId.

feat(utils): dismissKeyboard, copyToClipboard, setWindowBackgroundColor, getCurrentActivity and getResource

---

packages/core/utils/native-helper.ios.ts

`dataSerialize` method fails on iOS when there's an array with null/undefined elements and when objects have null/undefined prop values. 
With this PR the null elements are filtered out of arrays and dictionaries.
This PR also fixes a slight oversight with `data.map(serialize)`, since this syntax causes the second argument to be the element index instead of `wrapPrimitives`, causing the first element not to be wrapped and all the others to be.
```ts
dataSerialize([ null, undefined ]);
// Error: *** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[0] Error: *** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[1]
dataSerialize({ someProp: null, otherProp: undefined });
// Error: *** -[__NSPlaceholderDictionary …
```

fix(ios/utils): filter out null values from dataSerialize

---

packages/core/ui/list-view/index.ios.ts

`ListView` gets set to null in some cases on iOS. This caused the template to break and white screen.  
The onUnloaded() has been removed as it was the reason ListView was returning null.

fix(listview): remove ios delegate set to null

---

packages/core/platforms/ios/native-api-usage.json

Enabling metadata filtering crashes a simple app on latest xcode/IOS 16.
Adds an extra entry to allow enabling of metadata filtering in IOS 16.

fix(core): update metadata filtering for IOS 16

---

packages/core/ui/core/view/view-helper/index.ios.ts
packages/core/ui/page/index.ios.ts

Sometimes `additionalSafeAreaInsets` are correctly set in a layout pass but should be reset back to zero if the size if a sibling view changes. This doesn't happen and causes the safezone to be incorrectly calculated for the view that had the `additionalSafeAreaInsets` set.
`additionalSafeAreaInsets` is set back to null if the newly calculated additional insets are zero.

fix(core/ios): reset additional insets if they're zero

---

packages/core/ui/styling/background.ios.ts

Without these changes the border with box-shadow was not visible, now the border is clearly visible. The problem when it is a number is that it enters here: https://github.com/NativeScript/NativeScript/blob/main/packages/core/ui/styling/style-properties.ts#L78 and the resulting number is much greater than the edge and the view is lost
Without changes
With changes:

fix(core/ios): box shadow value border radius

---

packages/core/ui/page/index.ios.ts

My previous change was specifically to re-layout the views once the safe area insets change. The issue is that `viewSafeAreaInsetsDidChange` fires before `viewDidLayoutSubviews`. This shouldn't be a problem, as we're just doing an extra layout pass, but for some reason is.
We wait for the first `viewDidLayoutSubviews` to run before dispatching layout calls on `viewSafeAreaInsetsDidChange` 
Fixes #10149.

fix: don't run layout on viewSafeAreaInsetsDidChange until the first viewDidLayoutSubviews

---

packages/core/ui/frame/index.ios.ts

Frame usage within a modal would cause content to be blank until fully opened.
Frame usage within a modal now works as expected.
closes https://github.com/NativeScript/NativeScript/issues/10115

fix(ios): prevent transitionCoordinator usage during modal presentation

---

apps/automated/src/ui/web-view/web-view.md
tools/notes/DevelopmentWorkflow.md

There are small typos in:
- apps/automated/src/ui/web-view/web-view.md
- tools/notes/DevelopmentWorkflow.md
Fixes:
- Should read `describe` rather than `decribe`.
- Should read `control` rather than `controll`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

docs: Fix a few typos

---

packages/core/platforms/ios/src/NativeScriptUtils.m

Building for Catalyst would throw error on invalid api.
Building for Catalyst works.

fix(mac): utils for mac catalyst

---

packages/core/utils/index.android.ts

Method `openUrl` fails to handle certain http/https schemas (e.g. YouTube links).
This patch partially reverts changes in #10148 as they triggered this problem.
We could start adding checks for http/https schemas but we really don't have to make it too complicated.
@prabudevarrajan You should face no problems as your change in `WebView` is sufficient for fixing your bug. You can also try and let us know.
Fixes: https://discord.com/channels/603595811204366337/603595811720527881/1060924012919799888

fix(android): Method openUrl failed to handle urls

---

packages/core/core-types/index.ts
packages/core/ui/editable-text-base/index.android.ts
packages/core/ui/editable-text-base/index.ios.ts

Add new autoFillTypes:
* for `oneTimeCode` on android i chose `AUTOFILL_HINT_2FA_APP_OTP` but there is also sms and email otp. Not 100% sure which one to choose
* `UITextContentTypeNewPassword` was added in iOS 12. Do we need a check for ios version?

feat(core): new autoFillTypes

---

packages/core/application/index.ios.ts

Embedding NativeScript into existing native project will use the wrong root window.
Embedding NativeScript into existing native project will use the correct root window.
@tdermendjiev

fix(ios): embedder usage of window

---

packages/core/data/observable/index.ts
packages/core/ui/button/index.ios.ts
packages/core/ui/core/view/index.android.ts
packages/core/ui/core/view/index.ios.ts
packages/core/ui/list-picker/index.ios.ts
packages/core/ui/scroll-view/index.android.ts
packages/core/ui/scroll-view/index.ios.ts
packages/core/ui/scroll-view/scroll-view-common.ts
packages/core/ui/search-bar/index.ios.ts
packages/core/ui/text-field/index.ios.ts
packages/core/ui/text-view/index.ios.ts
packages/core/ui/web-view/index.ios.ts

Various TypeErrors, crashes and unstable behavior would result from inconsistent handling of loaded/unloaded events.
For example, a `ListView` bound to an Array where the items were programmatically changed which would fire a render of the list would cause `undefined` errors due to unloaded firing on a TextField tearing down the delegate used inside.
These conditions are now stable and more performant due to unnecessary repetitive setup/teardown.

fix(core): improve loaded/unloaded handling to be stable and consistent

---

packages/webpack5/src/plugins/PlatformSuffixPlugin.ts

In this sintax there is the need to escape the backslash in order to escape the . of the regex. In this way '.android.' will be replaced, and not *android* (* stands for character before and after android)
`./shared/androidTestClass.ts` will be replaced with `./shared.estClass.ts` (here is the bug)
`./shared/testClass.android` will be replaced with `./shared/testClass.ts` (as it should be)
`./shared/androidTestClass.ts` will remain `./shared/androidTestClass.ts` (so it's right)
`./shared/testClass.android` will be replaced with `./shared/testClass.ts` (as it was before)
The same is applied to `ios`.
Fixes/Implements/Closes #10168.

fix(webpack): fix regex for PlatformSuffixPlugin

---

packages/core/ui/core/view/index.ios.ts

A race condition exists when showing a view modally on ios if that view has been assigned width and height.  In `_showNativeModalView` (@nativescript/core/ui/core/view/index.ios.ts, 459) `const controller` is assigned the value `this.viewController`. In the `handler` callback created on line 481, the width/height from the view are assigned to the `preferredContentSize` of the `controller`. However at the conclusion of `_showNativeModalView`, the `controller` variable is released, creating a race condition for the handler.
Making the perferredContentSize assignment on `this.viewController` instead of `controller` avoids a race condition.

fix (ios-view): resolves race condition when setting preferredContentSize on view controller

---

packages/core/ui/styling/background.ios.ts

Under various view navigation conditions, anything from background-image css handling to processing of the nativeView can trigger with view bindings at times which lead to race conditions when the nativeView would have been destroyed and crashes such as:
```
Unhandled Promise rejection: Cannot read property 'frame' of null ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Cannot read property 'frame' of null TypeError: Cannot read property 'frame' of null
at uiColorFromImage (file: node_modules/@nativescript/core/ui/styling/background.ios.js:317:0)
at file: node_modules/@nativescript/core/ui/styling/background.ios.js:167:0
```
iOS stability across broader diverse project/layout binding setups. Under all these types of cases, the existence of `nativeView` does not matter at all and …

fix(ios): race conditions with nativeView

---

packages/core/ui/list-view/list-view-common.ts
packages/core/ui/repeater/index.ts

ListView and Repeater don't seem to provide template support for external renderers.
ListView and Repeater will provide template support for external renderers.
By default, we'll be treating `itemTemplate` property as a function according to `Template` interface. This helps ensure that external renderers that rely on vanilla {N} API can make use of single list templates.
Even core itself has an identical handling inside `Builder` module:
https://github.com/NativeScript/NativeScript/blob/main/packages/core/ui/builder/index.ts#L79
@farfromrefug I doubt this has any impact on current functionality or how other frameworks use `ListView` but please feel free to leave comments on this.

fix(core): Added item template handling for external renderers

---

packages/core/ui/styling/style-scope.ts

View properties of type `Property` do not get unset if they're updated from a css class selector that no longer targets view.
This is more apparent on ListViews where views are being recycled. View has a css class until it doesn't have it anymore so when class is unset, its effect to the view is still there.
Everything works fine for type `CssProperty`.
View properties of type `Property` will get unset if they're updated from a css class selector that no longer targets view.
This fix is a continuation of #6889

fix(core): Unset values for css properties of type Property

---

packages/core/application/index.ios.ts

When NS app is embedded main window should not be updated because it belongs to the parent app.

Disable setting main window content in ios

---

.github/workflows/apps_automated.yml
apps/automated/.npmrc
tools/scripts/run-automated.js

The CI action for the Automated app fails with a bunch of errors like these ones:
```
ERROR in ./src/main.ts 8:0-69
Module not found: Error: Can't resolve '@nativescript/core' in '/Users/runner/work/NativeScript/NativeScript/apps/automated/src'
```
(example build: https://github.com/NativeScript/NativeScript/actions/runs/4204462364/jobs/7311437908)
The workflow has been updated to use latest version of each action (bundled in here, but unrelated to the failing workflow).
We are setting the `install-links=false` flag to force linking `file:` referenced packages.
---
Background of the issue:
- npm 9.0 changed `install-links` value to be `true` by default
- GitHub Actions updated the macos environment from npm 8.9 to 9.3.1 recently
About the `install-links` flag from the NPM docs:
> When set …

ci: fix automated app CI workflow

---

packages/core/ui/frame/frame-common.ts
packages/core/ui/frame/index.android.ts
packages/core/ui/page/index.ios.ts

When I attempt to update some inheritable properties programmatically, they won't propagate from Frame to Page during initialization.
The reason seems to be the fact that we append page to frame using `_addView` before setting new frame entry.
Methods like `eachChildView` and `_childrenCount` rely on current entry resolved page and this is the actual problem.
For example, this is a description of how things currently work on iOS:
- Method `viewWillAppear` in Frame view controller will perform an `_addView` call
- Method `viewDidAppear` will assign new current entry
Property `currentPage` is a getter that returns the resolved page of current entry, and this getter is used by `eachChildView` and `_childrenCount`. Since current entry won't be updated until `viewDidAppear` call, we end up …

fix(core): Frame to Page property propagation

---

apps/automated/src/test-runner.ts
apps/automated/src/ui/animation/css-animation-tests.ts
apps/automated/src/ui/animation/test-page.css
packages/core/jest.setup.ts
packages/core/ui/styling/css-animation-parser.d.ts
packages/core/ui/styling/css-animation-parser.spec.ts
packages/core/ui/styling/css-animation-parser.ts

The `animation` shorthand is parsed incorrectly, requiring using the extended individual animation properties instead.
The `animation` shorthand is parsed correctly according to spec.
Duplicate keyframes are now properly merged together.
Tests are added for both the shorthand parsing and keyframe parsing.

fix: CSS animation parsing

---

apps/automated/src/application/application-tests-common.ts
apps/automated/src/globals/globals-tests.ts
apps/automated/src/livesync/livesync-tests.ts
apps/automated/src/main.ts
apps/automated/src/xml-declaration/xml-declaration-tests.ts
apps/ui/src/main.ts
apps/ui/src/perf/properties/tests.ts
packages/core/application/index.ios.ts
packages/core/fps-meter/fps-native.android.ts
packages/core/global-types.d.ts
packages/core/globals/index.ts
packages/core/profiling/index.ts
packages/core/tsconfig.lib.json
packages/core/ui/animation/index.ios.ts
packages/core/ui/frame/index.android.ts
packages/core/xml/index.ts

this changes the way we declare global variables so that it works again as explained here https://stackoverflow.com/questions/59459312/using-globalthis-in-typescript
tsc now picks up the typings and so most fo the any cast are not needed anymore

fix: global declarations fix

---

packages/core/config/config.interface.ts

https://github.com/NativeScript/nativescript-cli/pull/5721 https://github.com/NativeScript/nativescript-cli/issues/5723
`NativeScriptConfig` did not support the strongly typed `SPMPackages` option.
`NativeScriptConfig` now supports the new strongly typed `SPMPackages` option.
https://github.com/NativeScript/nativescript-cli/pull/5721
https://github.com/NativeScript/nativescript-cli/issues/5723

feat(ios): Swift Package Manager support in config

---

apps/automated/src/accessibility/accessibility-properties-tests.ts
apps/automated/src/test-runner.ts
apps/automated/src/ui/styling/style-properties-tests.ts
packages/core/accessibility/accessibility-css-helper.ts
packages/core/accessibility/accessibility-properties.ts
packages/core/ui/core/view/index.d.ts
packages/core/ui/core/view/view-common.ts
packages/core/ui/styling/style-properties.d.ts
packages/core/ui/styling/style-properties.ts
packages/core/ui/styling/style/index.ts
packages/core/ui/text-base/index.ios.ts

As of NativeScript 8.5, we added missing support for scaling font size on iOS using accessibility settings by default.
This caused problems for a number of developers as they don't want this feature or want to put limits to it.
This PR adds the following new properties for iOS:
- iOSAccessibilityAdjustsFontSize (default: false)
- iOSAccessibilityMinFontScale
- iOSAccessibilityMaxFontScale
All of them are inherited css properties and inline properties at the same time.
Assigned one to root view is enough for affecting entire view tree.
This PR ensures accessibility font scale is disabled by default on iOS.
It has minor to almost no impact as scaling was not available before 8.5.

feat(ios): Added new a11y properties for managing font scale

---

packages/core/ui/layouts/root-layout/index.d.ts
packages/core/ui/layouts/root-layout/root-layout-common.ts

RootLayout view and shade cover don't animate in parallel.
This fixes animation problems caused by #10228, makes few of checks more obvious, and adds a bit more of a missing promise functionality for method `openShadeCover`.
Method `openShadeCover` return type changes from `void` to `Promise<void>`.

fix(core): RootLayout view and shade cover should animate in parallel

---

apps/toolbox/src/pages/forms.ts
apps/toolbox/src/pages/forms.xml
packages/core/ui/editable-text-base/editable-text-base-common.ts
packages/core/ui/editable-text-base/index.android.ts
packages/core/ui/editable-text-base/index.d.ts
packages/core/ui/text-field/index.ios.ts

Formatting text, which updates input on the fly in the text input area, while typing on the keyboard was tricky to do properly. 
Adds a new `valueFormatter` option providing the ability to do all sorts of on-the-fly auto formatting with text entry.
https://github.com/NativeScript/NativeScript/issues/10249
https://user-images.githubusercontent.com/457187/230701381-5f7290a5-bbb6-4f15-8182-528129a01841.mov
https://user-images.githubusercontent.com/457187/230701388-0abeddf7-97c0-4256-b890-5fd3131354f1.mov

feat(text): valueFormatter for easy and flexible input auto-formatting

---

packages/core/global-types.d.ts

8.5 introduced strong typing on the Application event args, but the typings in the UnhandledErrorEventData type do not match what is returned in the handler from native.
Updated to match reality. So existing code compiles with 8.5.
Will cause code written against the incorrect typing to not compile, but code would not have worked anyway.

fix(core): unhandled error typings

---

packages/core/platform/index.d.ts

Currently, both `Device.sdkVersion` and `Device.osVersion` return a number in Android. The typings state that this should be a string so expressions like `if (Device.sdkVersion >= 23) {...}` are not possible.
I added `number | string` to the IDevice interface declaration so these expressions are allowed without the need to add `@ts-ignore`. I also updated the JSDoc to reflect this change.

fix(core/platform): fixed types for sdkVersion and osVersion

---

packages/core/ui/core/view/index.ios.ts
packages/core/ui/layouts/layout-base.ios.ts
packages/core/ui/list-view/index.ios.ts

Occasionally varied view binding conditions can cause race conditions on property setters which could end up trying to access the `nativeView` when it is not ready or not created yet.
iOS will be resilient under these conditions.

fix(ios): resilience to nativeView access under edge cases

---

packages/core/utils/native-helper.ios.ts

In some cases a snapshot might end up being a transparent (empty) image.
The snapshot ensures the layers opacity is non-zero for the snapshot.

fix(shared-transition): iOS snapshot opacity

---

apps/automated/src/test-runner.ts
apps/automated/src/ui/styling/style-properties-tests.ts
apps/automated/src/ui/text-base/text-base-tests.ts
packages/core/ui/text-base/formatted-string.d.ts
packages/core/ui/text-base/formatted-string.ts
packages/core/ui/text-base/index.ios.ts
packages/core/ui/text-base/span.d.ts
packages/core/ui/text-base/span.ts

iOS a11y font scale does not affect FormattedStrings and Spans.
iOS a11y font scale will affect FormattedStrings and Spans.
Fixes #10272 .

fix(ios): FormattedString and Span a11y font scale

---

packages/core/ui/core/view/index.ios.ts
packages/core/ui/layouts/layout-base.ios.ts
packages/core/ui/list-view/index.ios.ts

`this.nativeViewProtected` is faster than `this.ios`

chore: refactor

---

packages/core/ui/layouts/root-layout/root-layout-common.ts

When animating shadeCover for root layout, the exit animation doesn't work if translate or scale values are 0.
The exit animations work as intended when the translate or scale values are 0.
Fixes/Implements/Closes #10289.

fix(root-layout): Use isNumber to check for translate and scale values

---

packages/core/ui/dialogs/index.ios.ts

A dialog will not show up on iOS when invoked shortly after a modal has been closed, as the view controller will be playing the dismiss animation and will dismiss the dialog along with it.
Do not use UIControllers that have the `beingDismissed` flag as the `sourceView` for dialogs.
Alternatively, we could use an async approach like this:
```ts
function getViewController(): Promise<UIViewController> {
let viewController = ios.rootController as UIViewController;
while (viewController && viewController.presentedViewController) {
viewController = viewController.presentedViewController;
}
if (viewController.beingDismissed) {
const dismiss = new Promise<void>((resolve) => viewController.dismissViewControllerAnimatedCompletion(false, () => resolve()));
return dismiss.then(() => …
```

fix(dialogs/iOS): do not use view controllers that are being dismissed

---

packages/core/ui/animation/index.android.ts
packages/core/ui/animation/index.ios.ts

Currently any in-flight animation can be auto cancelled by any number of user interactions - navigation, tap to interact with screens, or explicit cancels. All will reject the promise of which don't need to be caught but still cause numerous uncaught errors. These can manifest into UI bugs when uncaught under various conditions.
```ts
Error: Animation cancelled. Error: Animation cancelled.
at Animation._rejectAnimationFinishedPromise (file: src/webpack:/myp/node_modules/@nativescript/core/ui/animation/animation-common.js:102:0)
at AnimationDelegateImpl.animationFinishedCallback [as _finishedCallback] (file: src/webpack:/myp/node_modules/@nativescript/core/ui/animation/index.ios.js:158:0)
at AnimationDelegateImpl.animationDidStopFinished (file: …
```

fix(animation): avoid uncaught reject on cancel

---

packages/core/utils/ios/index.ts

Snapshotting of shared elements during a shared transition won't always set their opacity back to original before animating leading to unexpected shared element transition.
The snapshot opacity is set back properly on next tick before animation starts. Note: this was affected by the recent async/await share element callbacks.

fix(shared-transitions): layer opacity set back to original on next tick

---

apps/automated/src/application/application-tests.android.ts
apps/automated/src/application/application-tests.ios.ts
packages/core/application/application-common.ts
packages/core/application/application-shims.ts
packages/core/ui/transition/shared-transition-helper.ios.ts

https://github.com/NativeScript/NativeScript/commit/f64355ba7a53cddf7c0a147ea7678f0fe6de6fba introduces breaking changes to 2 APIs on Application class, `orientation` as a getter only and `systemAppearance` as a getter only.
This allows the barrel refactor to proceed without breaking changes, maintaining existing behavior of `Application.orientation()` as a function and `Application.systemAppearance()` as a function.

refactor: Application barrel changes without breaking changes

---

packages/core/ui/transition/shared-transition-helper.ios.ts

Occasionally when using interactive options for dismissing shared transition, the state may get reset early and cause an error.
Interactive shared transition dismissals will be stable under broader conditions.

fix(shared-transition): race condition with interactive updates

---

packages/core/application/application.android.ts

Accessing `Android.application.context` can lead to crashes if called too early:
```
TypeError: Cannot read properties of undefined (reading 'getApplicationContext')
```
Accessing `context` early will be `undefined` but will not crash (if the caller handles it correctly) - this matches behavior prior to 8.5.4.

fix: early access to context and packageName

---

packages/core/application/application.android.ts

In some cases when trying to access the native application, an error is thrown:
```
Error: java.lang.ClassNotFoundException: androidx.appcompat.app.AppCompatActivityThread
```
The native application is correctly found/resolved.
fixes #10325
_Note: This line was likely changed by accident in my #10286 PR as I don't recall making this change, or a reason to do so._

fix(Application): getNativeApplication wrong ActivityThread

---

packages/core/connectivity/index.android.ts
packages/core/global-types.d.ts

On SDK <28 the app crashes when startMonitoring is called with:
```
ReferenceError: androidApp is not defined
```
The app no longer crashes, and calls the correct Application method to register a broadcast receiver.
Bonus: added generic type to `zonedCallback` to not need a `@ts-ignore` comment due to the wrapped function type being changed to `Function`.
fixes #10323

fix(Connectivity): androidApp is not defined on SDK <28

---

packages/core/application/application.android.ts

new native classes are attempted to be initialised in workers, causing workers to crash.
native classes are initialised once on the main app thread and reused as necessary in workers.
fixes: #10334

fix(application): wrap native classes in initialisers

---

packages/core/application/application-common.ts

#10286 didn't account for usage of the AndroidApplication in the following scenario:
```ts
AndroidApplication.on(AndroidApplication.activityCreatedEvent, () => {});
```
These are now exposed statically on the AndroidApplication to restore/remove the breaking change.
They are marked as deprecated as the preferred way to write these would be:
```ts
Application.android.on(Application.android.activityCreatedEvent, () => {});
```
to simplify usage/code across the board.

fix(application): restore AndroidApplication.on etc.

---

apps/toolbox/src/pages/datepicker.ts
apps/toolbox/src/pages/datepicker.xml
packages/core/ui/date-picker/index.android.ts
packages/core/ui/date-picker/index.ios.ts

When using data bindings with `date`, `minDate` and `maxDate` crashes could occur with null/undefined values.
These properties are now resilient to dynamic data binding conditions.
closes https://github.com/NativeScript/NativeScript/issues/8885

fix(datepicker): max, min and date value binding handling

---

packages/core/ui/page/index.d.ts

Compiling a project with Typescript strict mode enabled will file the compile will throw an error for:
```ts
this.page.on(Page.navigatedToEvent, (data: NavigatedData) => {});
```
because it cannot resolve the overloads for Page.on
Making `Page.navigatedToEvent` etc. constants with the correct event name string resolves the error.

fix(core): fix Page event overload resolution

---

packages/core/ui/transition/shared-transition-helper.ios.ts
packages/core/ui/transition/shared-transition.ts

When setting up page navigation shared transitions, sometimes you want to use transparent backgrounds on the page to bring more dynamic possibilities into the animation. Currently there was no way to specify custom `pageOut` animatable properties to adjust how the transition animates between the *outgoing* page and incoming.
Adds a new `pageOut` property which will be applied *to the outgoing page* to provide versatility in animated options.
Given settings as follows:
```ts
SharedTransition.custom(new PageTransition(), {
pageStart: {
opacity: 0,
x: 0,
y: -50,
},
pageEnd: {
opacity: 1,
x: 0,
y: 0,
},
pageReturn: {
opacity: 0,
x: 0,
y: -50,
},
pageOut: {
opacity: 0,
y: -50
}
});
```
You can now achieve page transition effects like this (just one page navigating to another with a …

feat(shared-transition): pageOut option for more dynamic page animations

---

packages/core/css/system-classes.ts

If we call recreate on an activity the `setRootViewCSSClasses` is called again on the `rootView`. This would cause duplicate system css entries which could make theming fail. This fix ensure every system css entry is inserted only once

fix: prevent duplicate system classes

---

packages/webpack5/src/transformers/NativeClass/index.ts

Fixes TS 5+ where it now uses __esDecorate by default where we need __decorate (set by experimentalDecorators)

fix(webpack): force experimentalDecorators on NativeClass

---

packages/webpack5/__tests__/configuration/__snapshots__/base.spec.ts.snap
packages/webpack5/__tests__/configuration/base.spec.ts
packages/webpack5/src/configuration/base.ts

Passing `--env.sourceMap=hidden-source-map` generates the source maps deep in the platforms folder right next to the bundle/vendor chunks. This isn't quite right because the purpose of hidden source-maps is to not ship them with the app. Right now, the user would have to run a build with hidden-source-maps, take the source-maps, and then re-build without source-maps to not ship them with the app.
When using `--env.sourceMap=hidden-source-map` we automatically set the output path for the sourceMaps to `platforms/{platformName}-sourceMaps/`:
```bash
platforms/ios-sourceMaps/...
platforms/android-sourceMaps/...
```

feat(webpack): place hidden sourceMaps in platforms folder

---

packages/core/ui/scroll-view/index.android.ts
packages/core/ui/scroll-view/index.ios.ts
packages/core/ui/scroll-view/scroll-view-common.ts

There is a case that `ScrollView` scroll event listeners fail to register if a `removeEventListener` call occurs prior.
e.g.
```js
view.off('scroll', onScroll);
view.on('scroll', onScroll); // This won't work because of line above
```
This occurs mostly on iOS because we don't unset property `_delegate` when detaching delegate.
PR will take care of this and improve few other things for both platforms.
Scroll listeners will register without problems.

fix(core): Scroll listener register failure after unregister

---

apps/toolbox/src/pages/labels.xml
packages/core/core-types/index.ts
packages/core/ui/button/index.ios.ts
packages/core/ui/index.ts
packages/core/ui/label/index.ios.ts
packages/core/ui/styling/style/index.ts
packages/core/ui/text-base/index.android.ts
packages/core/ui/text-base/index.d.ts
packages/core/ui/text-base/text-base-common.ts

`text-overflow` was not supported. This means most buttons would truncate awkwardly like this by default:
Adds support for standard CSS `text-overflow` to combine with `white-space` to achieve different truncation on text with labels and buttons. This allows you to set `text-overflow: ellipsis` to allow desired truncation:
ref: https://github.com/NativeScript/tailwind/pull/189
closes https://github.com/NativeScript/NativeScript/issues/5487

feat(css): support for text-overflow

---

apps/automated/src/main.ts
packages/core/application/application.d.ts
packages/core/application/application.ios.ts

In order to add delegate handlers, users must replace the Application.ios.delegate with their own - accounting for existing delegates if any (ie. from plugins).
To simplify adding delegate handlers, users no longer need to replace the delegate, and can just add/register them via the new api:
```ts
Application.ios.addDelegateHandler('applicationDidBecomeActive', (application: UIApplication) => {
console.log('applicationDidBecomeActive', application);
});
```
The types should automatically be inferred for the handler function.
Implementation loosely based off of https://github.com/nativescript-community/universal-links/blob/master/src/universal-links/index.ios.ts#L6-L31

feat(ios): addDelegateHandler to add App Delegate handlers

---

packages/core/ui/core/view/index.ios.ts
packages/core/ui/styling/background.ios.ts

iOS shadow layers do not respect origin point.
iOS shadow layers will respect origin point. This is a fix for https://github.com/NativeScript/NativeScript/pull/10374#issuecomment-1709232617

fix(ios): Shadow layer origin point update

---

packages/webpack5/__tests__/configuration/__snapshots__/angular.spec.ts.snap
packages/webpack5/__tests__/configuration/__snapshots__/base.spec.ts.snap
packages/webpack5/__tests__/configuration/__snapshots__/javascript.spec.ts.snap
packages/webpack5/__tests__/configuration/__snapshots__/react.spec.ts.snap
packages/webpack5/__tests__/configuration/__snapshots__/svelte.spec.ts.snap
packages/webpack5/__tests__/configuration/__snapshots__/typescript.spec.ts.snap
packages/webpack5/__tests__/configuration/__snapshots__/vue.spec.ts.snap
packages/webpack5/src/configuration/base.ts

In release builds, Terser strips quotes from props, and in some cases causes boot crashes while parsing the bundle/vendor chunks. For example, if the app uses a `html-entities` package, the mapping from entities -> their html equivalent causes the app to crash on boot in minified/production builds.
Example:
```js
characters: {
Æ: '&AElig;',
'&': '&amp;',
Á: '&Aacute;',
Ă: '&Abreve;',
Â: '&Acirc;',
А: '&Acy;',
𝔄: '&Afr;', // <-- this fails
```
```
***** Fatal JavaScript exception - application has been terminated. *****
2023-09-13 22:14:29.640530-0700 app[1:1] NativeScript encountered a fatal error: Uncaught SyntaxError: Invalid or unexpected token
at 
require(:1:232)
at __webpack_require__.f.require(file:///app/runtime.js:1:1468)
at (file:///app/runtime.js:1:692)
at …
```

fix(webpack): set keep_quoted_props: true in TerserOptions

---

packages/core/ui/core/view-base/index.ts

```
09-27 21:44:42.911  6331  6331 V 1000_StackLayouts: 389 <--- Cold Start
09-27 21:44:43.243  6331  6331 V 1000_StackLayouts: 332
09-27 21:44:43.521  6331  6331 V 1000_StackLayouts: 278
09-27 21:44:43.787  6331  6331 V 1000_StackLayouts: 265
09-27 21:44:44.018  6331  6331 V 1000_StackLayouts: 231
09-27 21:44:44.256  6331  6331 V 1000_StackLayouts: 237
09-27 21:44:44.502  6331  6331 V 1000_StackLayouts: 246
09-27 21:44:44.774  6331  6331 V 1000_StackLayouts: 271
09-27 21:44:45.027  6331  6331 V 1000_StackLayouts: 253
09-27 21:44:45.268  6331  6331 V 1000_StackLayouts: 241
```
Roughly 25-30% faster view rendering on android after this change:
```
09-27 21:43:28.150  6330  6330 V 1000_StackLayouts: 290 <--- Cold Start
09-27 21:43:28.412  6330  6330 V 1000_StackLayouts: 262
09-27 …
```

perf: cache default view paddings on android

---

packages/core/ui/core/view/index.ios.ts

iOS apps crash when trying to dispose native views that do not extend UIView (e.g. UITabBarItem) due to CALayers cleanup.
This trace was provided in discord:
```
[11:04:49.026] Debug: uncaughtErrorEvent - NativeScriptError: TypeError: Cannot set properties of undefined (setting 'mask')
***** Fatal JavaScript exception - application has been terminated. *****
NativeScript encountered a fatal error:
Uncaught TypeError: Cannot set properties of undefined (setting 'mask')
at
clearLayerMask(file: src/webpack:/app/node_modules/@nativescript/core/ui/styling/background.ios.js:279:0)
at clearBackgroundVisualEffects(file: src/webpack:/app/node_modules/@nativescript/core/ui/styling/background.ios.js:100:0)
at disposeNativeView(file: src/webpack:/app/node_modules/@nativescript/core/ui/core/view/index. …
```

fix(ios): Setting of property mask on 'undefined' during view disposal

---

packages/core/ui/styling/css-shadow.spec.ts
packages/core/ui/styling/css-shadow.ts
packages/core/ui/styling/css-stroke.spec.ts
packages/core/ui/styling/css-stroke.ts
packages/core/ui/styling/css-utils.ts
packages/core/utils/index.d.ts

box-shadow shorthand 'none' would work but throw a benign error in parsing.
The value 'none' now applies normally as 'empty'.
closes https://github.com/NativeScript/NativeScript/issues/10403

fix(core): box-shadow 'none' handling 

---

packages/core/ui/core/view/index.ios.ts
packages/core/ui/styling/background.ios.ts

On iOS, shadow layer position gets messed up if translate transformation is applied to view.
On iOS, shadow layer position aligns with view position when translate transformation is applied to view.
To achieve this, we set shadow layer position to match view's `center` coordinates.

fix(ios): Proper shadow position after translate transform

---

packages/core/ui/frame/frame-common.ts
packages/core/ui/frame/index.android.ts
packages/core/ui/page/index.d.ts
packages/core/ui/page/index.ios.ts
packages/core/ui/page/page-common.ts

There is currently an issue on Svelte Native that's related to HMR removing page elements and throwing exception.
The reason is that even though `_removeView` unsets page parent, the page still keeps reference of parent using property `_frame` and parent Frame happens to check that property when trying to dispose entry views in Core.
This change will ensure page won't keep any reference to parent after disposal. Doing so helps avoid calling `_removeView` multiple times.
More specifically, it ends up meddling with the following check:
https://github.com/NativeScript/NativeScript/blob/main/packages/core/ui/frame/frame-common.ts#L201
Fixes #10361 https://github.com/halfnelson/svelte-native/issues/347

fix(core): Page frame reference not unset on native view disposal

---

packages/core/ui/core/view/index.android.ts

If a Dialog is currently being shown, and the app is sent to the background where the Activity is then destroyed, when the app is brought to the foreground the app will crash.
This is because when the activity is destroyed, the dialog is torn down, but this happens after state is saved and it crashes when the dialog is being restored.
( Easy to test by turning on the `Don't keep activities` developer option. )
The change is to cancel the dialog creation if being restored in a state where the creation of the dialog will crash.

fix(android): Do not try to rehydrate destroyed dialogs

---

packages/core/ui/styling/font-common.ts
packages/core/ui/styling/font.android.ts

Font variation settings property complains about defined axes being invalid.
Font variation settings property will parse axes as expected.

fix(core): Font variation settings parser invalid axis

---

package.json
packages/core/ui/styling/css-shadow.spec.ts
packages/core/ui/styling/css-utils.ts

Usage of shadow css with `unset` in shorthand would result in css parse error.
`unset` is no longer inadvertently parsed as a color.

fix(css): prevent shorthand parse error on 'unset' and 'inset'

---

apps/toolbox/src/app.css
apps/toolbox/src/pages/box-shadow.xml
packages/core/ui/styling/css-shadow.spec.ts
packages/core/ui/styling/css-shadow.ts
packages/core/ui/styling/css-stroke.spec.ts
packages/core/ui/styling/css-stroke.ts
packages/core/ui/styling/css-utils.ts

box-shadow: none had slightly different behavior between platforms (ios would create CALayers unnecessarily and Android would throw error).
This `none` condition is now handled the same across both and avoids any unnecessary work.
closes https://github.com/NativeScript/NativeScript/issues/10403

fix(css): box-shadow none handling

---

packages/core/ui/styling/font-common.ts
packages/core/ui/styling/font-interfaces.ts
packages/core/ui/styling/font.android.ts
packages/core/ui/styling/font.d.ts
packages/core/ui/styling/font.ios.ts
packages/core/ui/styling/style-properties.d.ts
packages/core/ui/styling/style-properties.ts
packages/core/ui/styling/style/index.ts
packages/core/ui/text-base/formatted-string.d.ts
packages/core/ui/text-base/formatted-string.ts
packages/core/ui/text-base/index.android.ts
packages/core/ui/text-base/index.ios.ts
packages/core/ui/text-base/span.d.ts
packages/core/ui/text-base/span.ts

Font variation settings does not work for labels and spans in iOS.
Font variation settings will work for labels and spans in iOS.
There are also few small performance improvements related to this feature, like avoiding to iterate NSArray using for...of loop and using NSMutableDictionary instead of JS object.

fix(ios): Font variation settings not applied to labels

---

packages/core/ui/core/view/index.ios.ts
packages/core/ui/styling/background.ios.ts

Box shadow does not consider z-index.
Box shadow will consider z-index.

fix(ios): Shadow does not consider z-index

---

packages/core/ui/editable-text-base/index.android.ts
packages/core/ui/scroll-view/index.android.ts
packages/core/ui/search-bar/index.android.ts
packages/core/ui/text-base/index.android.ts
packages/core/ui/text-base/index.d.ts
packages/core/ui/text-base/text-base-common.ts
packages/core/ui/text-field/index.android.ts

There are times when we want to change the interaction of android input elements programmatically. Right now, re-enabling interaction programmatically has no effect.
Android input interaction becomes programmatically toggleable without problems.
That goes for both `editable` and `isUserInteractionEnabled` properties.
Fixes #8498.
Fixes #8523 in an alternate way by letting programmatic change of `editable` to apply at the same time.

fix(android): Proper change of input interaction mode programmatically

---

packages/core/ui/styling/background.ios.ts
packages/core/utils/number-utils.ts

Non-uniform borders may have incorrect angle if drawn on one-side.
Non-uniform borders will draw properly regardless of being one-sided borders.
Fixes #10436.

fix(ios): Non-uniform borders incorrect angle

---

packages/core/ui/core/view-base/index.ts
packages/core/ui/frame/frame-common.ts
packages/core/ui/frame/index.android.ts
packages/core/ui/page/index.ios.ts

If an inheritable view or style property is changed programmatically, the new value does not propagate to pages in frame backstack.
UPDATED: The style scope needs update as well, as it might change parent and eventually need to update children.
Updating an inheritable property programmatically will propagate changes to pages in frame backstack when navigating to them.
Fixes #10435.

fix(core): Inheritable property changes backstack propagation

---

packages/core/accessibility/accessibility-properties.ts
packages/core/accessibility/font-scale-common.ts
packages/core/file-system/index.ts
packages/core/ui/content-view/index.ts
packages/core/ui/core/view-base/index.ts
packages/core/ui/dialogs/dialogs-common.ts
packages/core/ui/frame/frame-common.ts
packages/core/ui/gestures/touch-manager.ts
packages/core/ui/image/image-common.ts
packages/core/ui/layouts/dock-layout/dock-layout-common.ts
packages/core/ui/layouts/flexbox-layout/flexbox-layout-common.ts
packages/core/ui/layouts/stack-layout/stack-layout-common.ts
packages/core/ui/layouts/wrap-layout/wrap-layout-common.ts
packages/core/ui/page/page-common.ts
packages/core/ui/search-bar/search-bar-common.ts
packages/core/ui/slider/slider-common.ts
packages/core/ui/tab-view/tab-view-common.ts
packages/core/ui/text-base/text-base-common.ts
packages/core/ui/transition/shared-transition.ts
packages/core/utils/debug.ts
packages/core/utils/platform-check.ts

Simple refactor. We should only use those now and stop relying on global

chore: use `__ANDROID__` and `__IOS__` instead of the global variables

---

apps/automated/src/ui/time-picker/time-picker-tests.ts
apps/toolbox/src/pages/datepicker.ts
apps/toolbox/src/pages/datepicker.xml
packages/core/ui/time-picker/time-picker-common.ts

The `TimePicker` would not allow a value of 0 on hours or minutes due to invalid Property defaultValue setup.
The properties are now defaulted to null which ensures the Property valueChanged will initialize values properly in the event the set value is same as default property value.
closes https://github.com/NativeScript/NativeScript/issues/10457

fix(time-picker): properly handle 0 on hour and minutes with valueChanged

---

packages/core/ui/text-field/index.android.ts

`setSecureAndKeyboardType` needs to use `nativeTextViewProtected`  As a reminder in text base components there is `nativeViewProtected` and `nativeTextViewProtected`. The reason is that material components (and maybe other) differentiate the layout and the textfield itself inside one view. A while back i made a PR for the whole N to support those two getters. But we need to remain careful on which one we use everytime

fix(android): crash with material components

---

packages/ui-mobile-base/android/widgets/src/main/java/org/nativescript/widgets/FileHelper.java

it was failing if you were to pass `content://com.android.externalstorage.documents/document/primary%3ADownload%2Fcom.akylas.documentscanner_settings_2024-01-02.json`.
It was trying to write `com.akylas.documentscanner_settings_2024-01-02.json/com.akylas.documentscanner_settings_2024-01-02.json` instead of `com.akylas.documentscanner_settings_2024-01-02.json`. It seems the `getFile` method is wrong.
This is not the perfect fix but in the meaning it should always work

fix(android): crash on writeText on Android > 29

---

packages/core/file-system/file-system-access.android.ts

by creating a `new Error` we lose the original error stack

fix(android): return native error or we lose stack

---

packages/core/profiling/index.ts

Not sure why we started getting this, but i was getting a crash saying `Symbol` cant be converted to string (or concat with a string)

fix: profile decorator fix

---

packages/ui-mobile-base/android/widgets/src/main/java/org/nativescript/widgets/Async.java
packages/ui-mobile-base/android/widgets/src/main/java/org/nativescript/widgets/FileHelper.java

I discussed this with @triniwiz . I am not sure why we are doing those update operations. Any way in my apps (may be better to say on my testing android versions) those `update` operations throws with something like `update not supported`.
A simple try catch prevent that error while preserving the code for what it be there for.
@triniwiz  could be nice if you remembered and added a comment on why that code even exists

fix(android): prevent errors on filesystem operations while using `content://...`

---

.github/workflows/apps_automated_android.yml
.github/workflows/apps_automated_ios.yml

This change improve both Android and iOS CI builds. Now there are separate builds for Android and iOS which cuts the CI time dramatically.
Android CI build is moved to `ubuntu-latest` in order to take advantage of the newer faster GitHub runners that have nested hardware virtualization. This enables the Android Emulator to start faster.
iOS CI build is moved to the faster M2 runners of [FlyCI](https://www.flyci.net/). It now uses the default iOS Simulators that [are installed](https://github.com/actions/runner-images/blob/main/images/macos/macos-14-arm64-Readme.md#installed-sdks) in the runner.

Move Android build to Ubuntu. Use FlyCI for iOS.

---

packages/types-ios/src/lib/ios/interop.d.ts

Simple typings update for https://github.com/NativeScript/ios/pull/228
Maybe we should start publishing these types with `@nativescript/ios` and `@nativescript/android`?

feat: add interop type for stringFromCString

---

packages/core/ui/core/view/index.ios.ts

Right now, there are cases that iOS view frame size is not updated properly when updating `originX` or `originY` programmatically.
The iOS view frame size will be updated properly when updating `originX` or `originY` programmatically.

fix(ios): Unset cached frame before updating  origin point

---

packages/core/application/application.ios.ts

It seems we accidentally removed live-sync handling for plain js/ts iOS apps in a past update.
Re-added live-sync handling for plain js/ts iOS apps.
Fixes #10447

fix(ios): Added missing live-sync handling for plain js/ts apps

---

packages/core/ui/text-base/index.d.ts
packages/core/ui/text-base/index.ios.ts
packages/core/ui/text-base/text-base-common.ts

When you change a label, iOS might animate the change with a flicker
You can disable the animations globally (TextBase.iosTextAnimationFallback = false) or per view (iosTextAnimation="false")
cc @NathanWalker

feat: allow disabling on text animations on iOS

---

packages/webpack5/src/bin/index.ts

If the configuration loading fails, the build proceeds as if it was successful.
When configuration loading fails, the build will properly indicated an unsuccessful build via the exitCode.
fixes #10314
Note: marked as draft, in order to confirm new behavior first.

fix(webpack): set exitCode if the configuration failed

---

packages/webpack5/__tests__/configuration/__snapshots__/angular.spec.ts.snap
packages/webpack5/__tests__/configuration/__snapshots__/base.spec.ts.snap
packages/webpack5/__tests__/configuration/__snapshots__/javascript.spec.ts.snap
packages/webpack5/__tests__/configuration/__snapshots__/react.spec.ts.snap
packages/webpack5/__tests__/configuration/__snapshots__/svelte.spec.ts.snap
packages/webpack5/__tests__/configuration/__snapshots__/typescript.spec.ts.snap
packages/webpack5/__tests__/configuration/__snapshots__/vue.spec.ts.snap
packages/webpack5/__tests__/configuration/base.spec.ts
packages/webpack5/package.json
packages/webpack5/src/configuration/angular.ts
packages/webpack5/src/configuration/base.ts
packages/webpack5/src/helpers/dependencies.ts

Using `@nativescript/webpack@5.0.19` on a pre 8.7.0 version of core prints an error about missing inspector_modules.
We detect core version and only include android inspector_modules if core version is >=8.7.0.
Fixes #10511

fix: detect core version before including inspector_modules on android

---

packages/core/ui/core/view-base/index.ts
packages/core/ui/core/view/index.android.ts
packages/core/ui/core/view/index.ios.ts
packages/core/ui/layouts/layout-base-common.ts

We had reports that android ListView `itemTap` event stopped working at core 8.7 and later.
The problem seemed to be that ListView proxy views became focusable due to some a11y calls, thus breaking native item click listener. A thread in StackOverflow explains why ListView does not operate well if list items become focusable: https://stackoverflow.com/questions/11610023/click-is-not-working-on-the-listitem-listview-android
Views will become focusable or non-focusable only when needed.
This is a continuation of the previous fix related to WebView accessibility focus: https://github.com/NativeScript/NativeScript/commit/92b2ff83a038ece4ab4411cf983ee9e252bba141
@farfromrefug Let me know if there's room for any improvements.

fix(android): ListView tap not working after setting children as focusable

---

tools/workspace-scripts.js

Using 'npm start' (as in the documentation) shows a menu where you can pick from the various project build scripts and unit tests.  This menu still contains reference to the old Webpack package, and launching either of the options associated with it gives an error.  There is also no menu option to invoke the Webpack5 unit tests.
Removes the references to the old Webpack package from the NPS config file, and adds a reference to invoke the unit testing for the Webpack5 package.

fix: Remove reference in NPS config to old Webpack package, and add reference to Webpack 5 unit tests.

---

packages/core/ui/core/view/view-common.ts

Relates to #10531. These two PRs are independent and can be merged in either order.
Cleans up the code related to event-handling in ViewCommon.
It makes it a lot clearer that we're actually splitting event names both here *and again* in Observable! So in a follow-up PR after this and the related PR, we can investigate removing event name splitting altogether.
There's some unclear, redundant code.
I've made the code clear and readable.

fix(core): clean up event-handling in ViewCommon

---

packages/core/ui/core/view/index.d.ts
packages/core/ui/core/view/view-common.ts
packages/core/ui/gestures/gestures-common.ts

This PR is related to #10537, but can be merged independently. Whichever is merged first will cause minor conflicts with the other, but it's a simple rebase that I'd be happy to take care of.
Although listeners for gesture events are set up in the same way as any other events, there are subtle differences in how they get handled.
- Gesture events accordingly have a few bugs:
- You can add the same `eventName-callback-thisArg` gesture observer multiple times.
- Removing any gesture observer removes all of the same name, regardless of `callback-thisArg` identity.
- GesturesObserver reaches up into ViewCommon to remove itself from the observer map; that should instead be a responsibility of ViewCommon, as that's the agent that maintains and inserts into the map.
- Unlike with regular events, …

fix(core): handle GestureObservers the same as event listeners

---

apps/automated/src/data/observable-tests.ts
packages/core/data/observable/index.ts
packages/core/ui/core/bindable/index.ts
packages/core/ui/core/view/view-common.ts
packages/core/ui/gestures/gestures-common.ts
packages/core/ui/gestures/index.android.ts
packages/core/ui/gestures/index.d.ts
packages/core/ui/gestures/index.ios.ts

This PR is based onto the following PRs that are in review:
I'd suggest reviewing this by just selecting the commits from this PR, excluding the commits from those prior two PRs. As per the screenshot, you'd scroll to the bottom of the commits (most recent at the bottom), and select the same commits as I've indicated in blue. In other words, the first included commit should be `chore(core): drop support for plural events`.
Currently, it is possible to listen for plural events by passing a comma-delimited series of event names (which may optionally be surrounded by whitespace):
```js
observable.addEventListener("propertyChange,loaded");
// Adds listeners for the "propertyChange" and "loaded" events
observable.addEventListener("propertyChange  ,  loaded");
// Adds listeners for the …
```

fix(core): drop support for plural event/gesture names

---

packages/core/data/observable-array/index.ts
packages/core/data/observable/index.ts
packages/core/data/virtual-array/index.ts
packages/core/ui/action-bar/index.d.ts
packages/core/ui/button/index.d.ts
packages/core/ui/core/view/index.d.ts
packages/core/ui/frame/index.d.ts
packages/core/ui/image-cache/index.d.ts
packages/core/ui/list-view/index.d.ts
packages/core/ui/page/index.d.ts
packages/core/ui/placeholder/index.d.ts
packages/core/ui/scroll-view/index.d.ts
packages/core/ui/search-bar/index.d.ts
packages/core/ui/segmented-bar/index.d.ts
packages/core/ui/tab-view/index.d.ts
packages/core/ui/web-view/index.d.ts

The doc comments for Observable (and subclasses) are out of sync with the implementation.
The doc comments are in sync with the implementation.

chore(core): update doc comments for on(), once(), addEventListener() and removeEventListener()

---

packages/core/ui/core/view/view-common.ts

Using splice without second parameter was removing all elements after first argument index. This would break if a modal was closed just after opening a second one.
You would also end up with views (the modal ones) in an "undead" state

fix: prevent breaking modal stack

---

packages/core/ui/action-bar/index.ios.ts

When you change the title of a specific page during navigation, the ActionBar will toggle off then on shortly due to the fact that the page is only set on the frame after the navigation is completely finished
This issue is now fixed by passing the current page to the `_updateActionBar` function. This also fixes cases where you might have multiple navigations and the current page could impact the action bar display mode of future pages.

fix: provide correct page for action bar update on title change

---

packages/core/ui/core/view-base/index.ts

In some cases you might want to set a parent(mostly rootView) before `_setupAsRootView` so that the the view calling `_setupAsRootView` inherits CSS variables and classes from the parent.
This is especially done in plugins like bottomsheet or dialogs or popover.
The issue is that if you set parent before `_setupAsRootView` then `_addViewToNativeVisualTree` will be called which could break things like it does with RadSideDrawer https://github.com/nativescript-community/ui-material-components/issues/462.
This PR fixes that by just preventing `_addViewToNativeVisualTree` to be called from `_setupAsRootView` which makes sense to me.

fix: dont add to parent from `_setupAsRootView`

---

packages/core/config/config.interface.ts

Can only pass arguments to CLI to configure embedding options.
Enables ability to persist configuration easily for embedding use cases.
ref: https://github.com/NativeScript/nativescript-cli/pull/5803

feat(config): embed options for existing platform host projects

---

packages/core/ui/core/view/index.android.ts

It is a known android "issue" that you cant commit/show a fragment while in background. The reason is, as explained [here](https://medium.com/@113408/avoid-fragment-illegalstateexception-can-not-perform-this-action-after-onsaveinstancestate-ba76ae4f00fe) or [here](https://stackoverflow.com/questions/15729138/on-showing-dialog-i-get-can-not-perform-this-action-after-onsaveinstancestate), that `onSaveInstanceState` is already called so any operation before activity start would be with state loss. There are 2 solutions in this case:
* use `commitAllowingStateLoss`, `dismissAllowingStateLoss` ... but then you loose state ... This is what we are doing in N in many cases. We can do this with `show` too but we would need to override the `DialogFragment.show` method.
* delay the action until the …

fix(android): prevent error while opening modal from background

---

packages/webpack5/src/index.ts

TypeScript only recognises the function type of the single argument of `mergeWebpack`. The object type is ignored.
Fixes the union type by parenthesising the function type. 
Fixes #10573

#10573 (webpack) fix union type

---

packages/core/utils/ios/index.ts

When embedding via 'ns embed ios', the .swift symbols may not be available and are not needed. This can be revisited in the future with project settings for embedded projects.
When embedding apps into platform host projects, the factory would always attempt to be used.
When embedding apps into platform host projects, the factory is not needed.

fix(embed): use factory only when it's available

---

packages/core/ui/core/view/view-common.ts
packages/core/ui/gestures/gestures-common.ts

makes gestures case-insensitive again for now

fix: re-add lowercase gesture handling and add deprecation notice when using non-string events

---

packages/core/application/application.android.ts

When targetting API 34, calling registerBroadcastReceiver throws an error due to https://developer.android.com/about/versions/14/behavior-changes-14#runtime-receivers-exported
Error no longer thrown and we mark the broadcast as exported by default. The user can opt to make it not exported by passing the correct flag.

fix: targetSdk 34 registerBroadcastReceiver needs additional flags

---

packages/core/package.json

The current configuration excludes winter_cg-release.aar since it's not included in the files. This change now force includes everything *but* the `core.aar` which isn't needed as it's auto-generated by the CLI every time (we should probably remove it and .gitignore it)

fix(core): include everything but core.aar in android platforms

---

apps/automated/src/color/color-tests-common.ts
packages/core/color/color-common.ts

Color module does not currently parse 4-digit hex code. 4-digit hex code is a shorthand for some 8-digit (rgba) hex codes.
Color module will parse 4-digit hex code as expected.

fix(core): Four-digit hex color parse failure

---

packages/core/ui/core/view/index.android.ts

In the case of android, layout change event listeners cannot be manipulated using addEventListener/removeEventListener.
Layout change event listeners can be manipulated using addEventListener/removeEventListener.
Methods `on` and `off` call those internally.

fix(android): Layout change listeners are ignored when using addEventListener

---

packages/core/ui/layouts/root-layout/index.android.ts

When Android RootLayout shade cover color is null, it results in unhandled exception.
Added null checks for android shade cover color.

fix(android): RootLayout shade cover null color handling

---

packages/core/ui/styling/background.ios.ts

There are cases when iOS views display extra borders. That is because layer fill drawing does not work well with fractional coordinates.
iOS view colored borders will display properly.
Fixes/Closes #10548.

fix(ios): Proper drawing bounds for colored borders

---

packages/core/ui/styling/style-scope.ts

It seems we have 2 portions of dead code when setting view property values.
Sample:
```js
delete oldProperties[property];
if (property in oldProperties && oldProperties[property] === value) {
// Skip unchanged values
continue;
}
```
This ends up with a dead if block and core will attempt to re-apply the same values to view properties.
Even though this is getting caught in Observable, we do one more additional check even though it's always going to be `false`.
This PR corrects property set behaviour and deletes property from list once its existence has been confirmed, enabling core to proceed to value check.
This is trivial, yet it keeps code cleaner and functional.

perf(core): Avoid setting the same value to view properties

---

packages/core/ui/list-view/index.ios.ts

When using iOS ListView with `itemLoading` event and always pass a new cell view, there's a chance that cell will keep both old (reusable) and new view resulting in duplicate content.
By removing old native view at the right time, we avoid content duplication.
Fixes the problem we tried to solve in #10001

fix(ios): Proper cleanup of reused listview cell content

---

packages/core/ui/dialogs/dialogs-common.ts

Ever since #10201, Dialog buttons, labels, and inputs are affected by global scope CSS. That brings the drawback of not being able to style the dialog specifically. One good example example, some apps ended up with light-colored text not being distinct in light-mode Dialogs because of how these apps were styled in global scope.
Added `ns-dialog-item` css class to style nested dialog views.
Sample:
```css
Label {
color: #fff;
}
Label.ns-dialog-item {
color: #000;
}
```

feat(core): Added css class for styling dialog nested elements

---

.github/workflows/apps_automated_ios.yml

This PR replaces the use of FlyCI macOS runners with GitHub ones since FlyCI macOS runners will be discontinued effective Sep 30, 2024. 
[Read more about the discontinuation of the FlyCI macOS runners](https://flyci.net/blog/flyci-discontinue-macos-runners?utm_source=site_link&utm_medium=github&utm_campaign=discontinue-runners).

Replace FlyCI runners with GitHub runners

---

packages/core/ui/core/view/index.ios.ts

When opening a popover modal inside a "Proxy" view (like angular's ProxyViewContainer), the popover will fail to open with an error since the parent view has no native view.
We now loop over parents until we find a valid view.

fix: popover delegate should ignore non-native views

---

packages/webpack5/src/configuration/base.ts

This adds a new flag `env.uniqueBundle` which will be appended as a suffix to generated bundle names.
The cli then uses this id to set the main entry in the package.json in the resulting app.
There is a corresponding `nativescript-cli` PR [5814](https://github.com/NativeScript/nativescript-cli/pull/5814)

feat: allow the passing of a bundle suffix

---

packages/core/ui/core/view/view-helper/index.ios.ts
packages/core/ui/core/view/view-helper/view-helper-common.ts

In some cases a negative width/height can happen, when the child width is 0, but the margins are subtracted from it.
The width/height should never go negative.

fix(layout): prevent negative width/height values

---

packages/core/utils/index.ios.ts

Calls to `Utils.openUrl` do not do anything if the app is compiled with XCode 16.
`UIApplication.shared.openUrl` is [depreciated](https://developer.apple.com/documentation/uikit/uiapplication/1622961-openurl?language=objc), replaced with call to `openURL:options:completionHandler`

fix(ios): replace depreciated UIApplication.shared.openUrl method call

---

packages/core/platforms/ios/src/UIView+NativeScript.m
packages/core/ui/styling/style-properties.d.ts
packages/core/ui/text-base/index.android.ts

Line height value seems to be applied on texts as spacing.
Line height value will be applied on texts as height of the line box.
This feature seems to be prone to breaking frequently so I made sure to include comments.
The correct behavior was implemented in #8257, although the value was being miscalculated on the android side resulting in #8751.
Fixes #9830 #10641.

fix(core): Proper line-height calculation

---

packages/core/ui/action-bar/index.android.ts
packages/core/ui/button/index.android.ts
packages/core/ui/core/view/index.android.ts
packages/core/ui/core/view/index.d.ts
packages/core/ui/core/view/view-common.ts

This is a fix for a bug caused by #10451.
It seems some android views with background drawable will not render the drawable color filter (e.g. Material design bottom navigation bar).
From now on, we mark the views that need setting the drawable color and call `setBackgroundColor` as a default for the rest of them.
Getter `needsNativeDrawableFill` seems like a good way to distinguish those views and we might be able to use it on iOS if such a case arises.
See relevant discussion: https://discord.com/channels/603595811204366337/1019708793371770950/threads/1300825437882290177

fix(android): Background color is not applied to certain views

---

packages/core/platforms/ios/src/UIView+NativeScript.m
packages/core/ui/styling/style-properties.d.ts
packages/core/ui/text-base/index.android.ts

Reverts NativeScript/NativeScript#10642
@NathanWalker I revert these changes because due to a weird line height behavior on iOS.
I'm preparing a new PR with typography improvements that will include a better version of these changes.
Note: Additionally, css `line-height` accepts multipliers so the original {N} approach might be the most recommended approach.

Revert "fix(core): Proper line-height calculation"

---

packages/core/ui/frame/frame-common.ts
packages/core/ui/frame/index.d.ts

Frame ignores listeners defined in xml markup
Frame will now register listeners defined in xml markup.
This PR also removes an `androidOptionSelectedEvent` property which was garbage from an old PR.

fix(core): Frame ignored event listeners in xml markup

---

packages/core/ui/gestures/index.android.ts
packages/core/ui/gestures/index.ios.ts
packages/core/ui/gestures/touch-manager.ts

JSC fails to run a basic NativeScript add due to these imports,  probably a circular.

fix: circular imports

---

packages/webpack5/src/loaders/nativescript-hot-loader/hmr.runtime.ts

Hermes does not support async arrow functions yet.

fix: hmr for hermes engine

---

packages/core/ui/frame/frame-common.ts
packages/core/ui/frame/index.android.ts
packages/core/ui/frame/index.ios.ts

Upon disposal, iOS frame does not dispose its page views resulting in memory leaks or accessible native view references that have already been affected by GC.
That goes for current, executing, and backstack pages.
Frame will dispose all owning page views upon its disposal.

fix(ios): Added missing Frame backstack disposal handling

---

packages/core/ui/core/view/view-helper/index.ios.ts

In iOS 10 and earlier versions, custom implementation of `safeAreaLayoutGuide` causes memory leaks.
Custom `safeAreaLayoutGuide` and its constraints will be created once.

fix(ios): Safe area memory leak on iOS 10 and older versions

---

packages/core/ui/core/view/index.ios.ts

There is a case when iOS view transform gets broken if set before layout.
This was originally an 8.2 fix that is no longer needed since we have done improvements on iOS layout and it also fixes one thing but breaks another.
iOS view transform will properly apply even if set before layout.
Thanks goes to @farfromrefug for informing me about this some time ago.

fix(ios): Broken transform if set before any layout

---

apps/automated/src/ui/animation/animation-tests.ts
packages/core/ui/animation/index.ios.ts

Right now, core iOS animations do not consider rotate as an affine transform causing some features like spring animation to break.
This became apparent once I took a small look in @farfromrefug's #9892 (thanks 🙏 ) and noticed that some rotation logic was missing.
iOS will animate rotations the right way. Also, it fixes the broken spring case.

fix(ios): Corrected rotate animation execution

---

packages/core/ui/editable-text-base/index.android.ts
packages/core/ui/html-view/index.ios.ts
packages/core/ui/label/index.ios.ts
packages/core/ui/scroll-view/index.android.ts
packages/core/ui/search-bar/index.ios.ts
packages/core/ui/text-base/index.android.ts
packages/core/ui/text-base/index.ios.ts
packages/core/ui/text-base/text-base-common.ts
packages/core/ui/text-field/index.ios.ts
packages/core/ui/text-view/index.ios.ts

This PR enhances some points around TextBase Span interaction and view disposal.
More specifically:
- Added `linkTap` event support for other iOS views that nest spans
- Prevent android span from setting parent background color to itself since it doesn't react to changes of that property. Unless background color is specified to the span directly, it's going to be transparent
- Added few missing `nativeTextViewProtected` references
- Improved view disposal for classes that inherit from TextBase as they had leftovers after android activity recreation
- Removed 2 assignments of `userInteractionEnabled` from TextBase as they were unneeded and had conflicts with `isUserInteractionEnabled` property. Core already sets that property to true for the views that need it in `createNativeView` call
- …

feat(core): TextBase Span interaction and styling improvements

---

packages/core/ui/animation/index.ios.ts
packages/core/ui/core/view/index.ios.ts
packages/core/ui/styling/background.ios.ts

In iOS, background-color animation will also animate shadow container color resulting in unexpected visual results.
The iOS animator will also animate shadow container properties provided that they're not layer colors.
This PR also adds a missing shadow transform handling that's needed ever since #10675 took effect.

fix(ios): Prevent animator from animating colors on shadow layer

---

packages/core/ui/layouts/index.d.ts
packages/core/ui/layouts/index.ts
packages/core/ui/layouts/root-layout/index.android.ts
packages/core/ui/layouts/root-layout/index.d.ts
packages/core/ui/layouts/root-layout/index.ios.ts
packages/core/ui/layouts/root-layout/root-layout-common.ts
packages/core/ui/layouts/root-layout/root-layout-stack.ts

This PR adds flexibility for multiple RootLayouts and the `getRootLayoutById` function to retrieve one using its view `id`.
Core will keep a root layout stack just like it does with Frames.
Also, existing `getRootLayout` function will return the first RootLayout in the view tree.
Additionally:
- Improved error messages
- Fixed a problem that caused a shade cover with gradient not to switch to a colored one
- Added iOS view disposal support to get rid of native gradient layer when needed
- Now, shade cover will calculate its insert index based on existing popup views

feat(core): Added flexibility for using multiple RootLayouts

---

packages/core/ui/image/image-common.ts
packages/core/ui/layouts/absolute-layout/absolute-layout-common.ts
packages/core/ui/layouts/wrap-layout/wrap-layout-common.ts
packages/core/ui/list-view/index.ios.ts
packages/core/ui/list-view/list-view-common.ts

Some length property definitions are missing equality comparers.
Added missing comparers for these properties.

fix(core): Added missing length property equality comparers

---

packages/core/core-types/index.ts
packages/core/ui/animation/animation-interfaces.ts
packages/core/ui/animation/index.d.ts
packages/core/ui/styling/background-common.ts
packages/core/ui/styling/background.android.ts
packages/core/ui/styling/background.d.ts
packages/core/ui/styling/background.ios.ts
packages/core/ui/styling/clip-path-function.ts
packages/core/ui/styling/css-animation-parser.ts
packages/core/ui/styling/css-transform.ts
packages/core/ui/styling/style-properties.d.ts
packages/core/ui/styling/style-properties.ts
packages/core/ui/styling/style/index.ts

This PR performs some refactoring on the `style-properties` module.
More specifically:
- Added new `FixedLengthType` type. It's only used for `translate` css properties but can cover more needs in the future
- Corrected a few transform types in animation module
- Added `ClipPathFunction` class. This class will keep data related to `clip-path` shape functions
- Moved all transform-related functions from `style-properties` to a new `css-transform` module
- Removed `any` type casts and improved types in `css-transform` module
- Moved all `style-properties` functions to the top
- Removed duplicate code used for calculating shorthand css properties
- Added value converter and equality comparer for `clip-path` property

ref(core): Style properties module improvements and organization

---

packages/core/ui/layouts/layout-base-common.ts
packages/core/ui/layouts/layout-base.d.ts
packages/core/ui/layouts/layout-base.ios.ts
packages/core/ui/layouts/root-layout/index.android.ts

A throw could occur during layout introduced from this change which would bubble out to a v8 engine crash:
https://github.com/NativeScript/NativeScript/pull/10679/files#diff-ff996ba7476badc71c6c2ce6924be412385d3ea43a8785248a28159b3f7d203eR54
Just ignore inserting children if < 0. 
Notes: Usage of CollectionView surfaced this issue.

fix(core): ignore inserting child if < 0

---

packages/core/ui/core/properties/index.ts

Tailwind v4 introduced some calc values with `unset` which would break when processing.
Ensures `unset` is zeroed out properly before processing calc.
ref: https://github.com/NativeScript/tailwind/pull/194

feat(core): tailwind v4 support

---

packages/core/config/config.interface.ts

Swift packages attach by default to the main app target with no way to specify multiple target use.
When using iOS Widget/Extensions, you may want to use swift packages from those. This `targets` array can list any targets by name to add swift packages to.

feat(config): multi target support for swift packages

---

packages/core/ui/frame/frame-common.ts
packages/core/ui/frame/index.d.ts

Frame has incorrect types for navigation events. These types seem to be leftovers from a previous breaking change regarding those events.
Updated Frame navigation event types to describe the event payload accurately.
Also, added a missing property to `navigatedTo` event.

chore(core): Corrected Frame navigation event types

---

packages/core/ui/text-base/index.d.ts
packages/core/ui/text-base/text-base-common.ts

This PR adds missing inheritance support for some text-base properties according to MDN docs:
https://developer.mozilla.org/en-US/docs/Web/CSS/text-transform#formal_definition
https://developer.mozilla.org/en-US/docs/Web/CSS/text-shadow#formal_definition
https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-text-stroke#formal_definition
https://developer.mozilla.org/en-US/docs/Web/CSS/white-space#formal_definition

fix(core): Added missing inheritance support for text css properties

---

packages/core/ui/text-base/index.android.ts
packages/core/ui/text-base/index.ios.ts
packages/core/ui/text-base/span.d.ts
packages/core/ui/text-base/span.ts

There are cases when TextBase and Span background colors mismatch.
That is very apparent when tapping a button with spans and css `:pressed` pseudo-state.
Spans will be colorless (transparent) to display TextBase parent background color unless they or their `FormattedString` parents have a background color of their own.
This issue was partially fixed on android but also broke `FormattedString` color inheritance, so this PR fixes that too (see #10682).
Fixes/Closes #7379 .

fix(core): Corrected background color between Label and nested spans

---

packages/core/ui/core/properties/index.ts

Tailwind 4, for example, uses css calc expressions, some of which contain `infinity` values. These would not be processed properly.
The `infinity` value will now properly evaluate to get expected styling results.

feat(css): allow infinity values within css calc expressions

---

apps/toolbox/src/pages/image-handling.xml
packages/core/image-source/index.d.ts
packages/core/image-source/index.ios.ts
packages/core/ui/image/image-common.ts

When using `iosSymbolScale="large"` the icon may appear oddly small. This is expected behavior based on how iOS system icons are handled as their scale is relative, not absolute.
iOS system icon scale can be influenced by font-size and font-weight alongside scale to better control the desired size of the system icon.
For example, an Image like this:
```xml
<Image src="sys://steeringwheel.and.hands" iosSymbolScale="large" />
```
Would likely appear quite small, however we can now add font-size (as well as font-weight) to get a more appropriate size for desired usage:
```xml
<Image src="sys://steeringwheel.and.hands" iosSymbolScale="large" style="font-size: 45; font-weight: bold;" />
```
This can be applied via any css packages as well, like tailwind `text-7xl font-bold` would have same …

feat(image): ios system icons styling by font-size and font-weight 

---

packages/core/ui/core/view/index.d.ts
packages/core/ui/core/view/index.ios.ts
packages/core/ui/core/view/view-common.ts
packages/core/ui/page/index.ios.ts

Right now, the `layoutChanged` event is not emitted on iOS Pages.
This is a concept that allows the `layoutChanged` event to emit on iOS Pages.
Fixes/Closes #7085

fix(ios): Added layoutChanged event support to Page

---

apps/automated/src/test-runner.ts
apps/automated/src/ui/styling/css-keywords-tests.ts
packages/core/core-types/index.ts
packages/core/ui/core/properties/index.ts
packages/core/ui/core/view/index.android.ts
packages/core/ui/layouts/flexbox-layout/index.d.ts
packages/core/ui/styling/css-utils.ts
packages/core/ui/styling/font-common.ts
packages/core/ui/styling/font-interfaces.ts
packages/core/ui/styling/style-properties.ts
packages/core/ui/text-base/index.android.ts
packages/core/ui/text-base/text-base-common.ts

Core is missing support for several CSS wide keywords.
This PR adds support for the following CSS wide keywords:
- initial
- inherit (right now it works as initial for non-inherited properties)
- unset
- revert
Implements/Closes #628.

feat(core): Added basic support for CSS wide keywords

---

packages/core/data/observable/index.ts
packages/core/media-query-list/index.ts
packages/core/ui/core/view/index.android.ts
packages/core/ui/core/view/view-common.ts
packages/core/ui/scroll-view/scroll-view-common.ts
packages/core/ui/text-base/span.ts

Right now, `View` event listeners registered using `once` don't get removed upon being called.
`View` event listeners registered using `once` will behave as expected.

fix(core): Added missing parameter for once event listeners

---

packages/core/data/observable/index.ts
packages/core/utils/typescript-utils.d.ts

Currently, the `on`, `off`, and `once` methods in `@nativescript/core/data/observable/index.ts` use a generic `EventData` type for all event callbacks, regardless of the event name. This lacks type specificity, especially for "Change" events, which should use `PropertyChangeData`.
This PR introduces the `EndsWith` utility type to dynamically determine the callback data type based on the event name. If the `eventName` ends with "Change", the callback will use `PropertyChangeData`; otherwise, it will use `EventData`. This provides improved type safety and developer experience.

feat(observable): enhance event callback type specificity

---

packages/types-ios/src/lib/ios/objc-x86_64/objc!NativeScriptEmbedder.d.ts

`initShared` was missing from view factory types.
Ensures `initShared` is strongly typed.

fix: view factory types

---

packages/core/http/http-request/index.ios.ts

With Xcode 16.3 (iOS 18.4) simulators, network failures could occur.
Use `ephemeralSessionConfiguration` instead of `defaultSessionConfiguration`.

fix(http): xcode 16.3, ios 18.4 urlsession change

---

packages/core/http/http-request/index.ios.ts

iOS 18.4 "simulators only" have networking bug. Physical devices are fine.
Just mitigate for end users for these 18.4 simulators.
https://developer.apple.com/forums/thread/777999

fix(ios): 18.4 simulator networking case

---

packages/core/ui/list-view/index.ios.ts

On iOS, there are times `ListView` skips needed measure updates. That is because method `measure` is overridden and performs a check that causes defects.
See: https://github.com/NativeScript/NativeScript/blob/main/packages/core/ui/list-view/index.ios.ts#L396
Calling `_setCurrentMeasureSpecs` may indicate whether size changed but also updates previous measure spec values, resulting in skipping measure update in the `super.measure()` call.
iOS ListView will undergo measurements as expected.

fix(ios): listview incorrect measurement

---

packages/webpack5/package.json
packages/webpack5/src/bin/index.ts

- Fixes the following issues related to transient dep updates from [here](https://github.com/NativeScript/NativeScript/commit/eab726b5d69c9c9b2bf790498225aa2dcbc5521d)
Reference: https://github.com/vuejs/vue-loader/releases/tag/v17.0.1
```
Error: @vitejs/plugin-vue requires vue (>=3.2.13) or @vue/compiler-sfc to be present in the dependency tree.
at Object.<anonymous> (node_modules/vue-loader/dist/compiler.js:14:15)
```
Reference: https://github.com/tj/commander.js/releases/tag/v13.0.0
```
build error: too many arguments. Expected 0 arguments but got 11.
```

fix(webpack): build with dep updates

---

apps/automated/src/ui/tab-view/tab-view-root-tests.ts
packages/core/ui/frame/frame-common.ts
packages/core/ui/frame/frame-interfaces.ts
packages/core/ui/frame/frame-stack.ts
packages/core/ui/frame/index.d.ts
packages/core/ui/frame/index.ios.ts
packages/core/ui/gestures/index.ios.ts
packages/core/ui/page/index.ios.ts
packages/core/ui/tab-view/index.ios.ts

Right now, we have Page navigation events handling inside iOS page ViewController to handle cases like back button navigation or swipe back navigation.
Unfortunately, the handling is quite messy with a couple of hackish solutions resulting in events being emitted when they shouldn't (e.g. @NathanWalker iOS 18 TabView navigation between frame that were already loaded once).
This PR focuses on improving how these events are emitted and decouple TabView from nested Page logic. Navigation events are now safely emitted from page ViewController when needed.
Few things to note:
- Added missing Frame `navigatingTo` event trigger for back button/swipe back navigations
- Assign Frame's executing context during those navigations since the property is essential for blocking unexpected calls during …

feat(ios): Better handling for emitting navigation events

---

apps/automated/src/ui/view/view-tests.ios.ts
packages/core/ui/core/view/index.ios.ts
packages/core/ui/styling/background.ios.ts

This PR removes the background redraw check that was added in #10661, as it doesn't fully solve the problem.
If developers experience visual glitches on layouts, it's best to set `iosOverflowSafeArea` to false.
The safe area support has flaws that need to be revisited in the future.

chore(ios): Removed forced background update during safe area inset calculation

---

apps/automated/src/ui/animation/animation-tests.ts
packages/core/ui/animation/index.ios.ts

Changes in #10676 causes rotate animation to break as animating affine transform will animate rotation to closest value.
For example, 0 -> 300 will rotate backwards since it's closer and 0 -> 360 won't rotate the view at all.
Reverted changes of #10676
Fixes #10764

Revert "fix(ios): corrected rotate animation (#10676)"

---

packages/core/ui/core/properties/index.ts
packages/core/ui/core/view/index.android.ts
packages/core/ui/image/index.ios.ts
packages/core/ui/search-bar/index.android.ts
packages/core/ui/search-bar/index.ios.ts
packages/core/ui/styling/style-properties.d.ts
packages/core/ui/text-base/index.android.ts
packages/core/ui/text-field/index.ios.ts

This PR gets rid of type errors related to some computed `setNative` methods.
Since we use symbols to define methods with a single argument, TypeScript may complain about union string types for prototype's `[prop: symbol]`.
Things can get a bad turn if some methods use `any` as an argument type or unions/enums end up in conflict with string type.
To solve this, the following actions have been performed:
- Replaced argument `any` with the corresponding type
- Replaced string enum with string type
- Switched order of some computed method declarations to get rid of union type conflicts
A small example to understand the conflict:
```ts
[testIDProperty.setNative](value: string) {
this.setAccessibilityIdentifier(this.nativeViewProtected, value);
}
// This throws error as TS with cause enum to …
```

chore(core): Got rid of setNative type errors

---

packages/core/ui/transition/page-transition.android.ts

Different timing conditions during shared element transitions can cause the following error:
```
java.lang.IllegalArgumentException: A shared element with the target name 'image-1234567890' has already been added to the transaction.
androidFragmentTransactionCallback file: @nativescript/core/ui/transition/page-transition.android.js:245:0
```
Prevention to a target already being added to the transaction.

fix(android): shared element with target name already added to transaction

---

packages/core/ui/dialogs/index.ios.ts

Dialogs don't confirm when using keyboard enter/return on iOS
Keyboard enter confirms and closes dialogs

feat(dialogs): allow using keyboard enter/return to confirm on iOS
