NativeScript/NativeScript

- gruntfile.js
- package.json
When there are errors that are not breaking the typescript compilation, the grunt build passes making these errors hard to find in the output.
> Set grunt to break on all TypeScript compilation errors

- ui/list-view/list-view.ios.ts
Use this code in ListView.itemLoading event if you want to control the
inset:
```JavaScript
function listViewItemLoading(args) {
if (args.ios) {
args.ios.separatorInset = UIEdgeInsetsZero;
args.ios.preservesSuperviewLayoutMargins = false;
args.ios.layoutMargins = UIEdgeInsetsZero;
}
}
```
> separator is no longer forced to the edge

- application/application-common.ts
- application/application.android.ts
- application/application.d.ts
- application/application.ios.ts
- apps/tests/app/app.ts
- ui/frame/frame.android.ts
Fix for #233 & #244.
Example:
```TypeScript
import application = require("application");
application.mainModule = "app/mainPage";
application.on(application.launchEvent, function (args: application.ApplicationEventData) {
console.log("launchEvent, iOS: " + args.ios + ", Android: " + args.android);
});
application.on(application.uncaughtErrorEvent, function (args: application.ApplicationEventData) {
console.log("uncaughtErrorEvent, iOS: " + args.ios + ", Android: " + args.android);
});
application.on(application.suspendEvent, function (args: application.ApplicationEventData) {
console.log("suspendEvent, iOS: " + args.ios + ", Android: " + args.android);
});
application.on(application.resumeEvent, function (args: application.ApplicationEventData) {
console.log("resumeEvent, iOS: " + …
```
> application module events added

- ui/list-view/list-view.ios.ts
- Fix crash due to asserts in scrollToRowAtIndexPathAtScrollPositionAnimated for ListView's UITableView instance.
- Fix a case where the UITableView fails to calculate its layout when the page, it is displayed in, is navigated to, from and back to.
> Fix some crashes for ListView's iOS UITableView

- ui/list-view/list-view.ios.ts
This is broken and unneeded in the new ios runtime.
Related: https://github.com/NativeScript/ios-runtime/issues/178
> Remove class override of ListViewCell

- apps/tests/TKUnit.ts
- apps/tests/http-tests.ts
- declarations.d.ts
- http/http.ts
The angular 2 code uses the `onload`/`onerror` events and explicitly sets `responseType`, so I added support for those. `responseType` is a pretty complex feature, so right now we only support `text` and raise an error if the user sets something else.
Bonus: modified TKUnit and wrapped test functions in a try/catch block thus failing the tests on exceptions instead of crashing the app.
> XHR compatibility updates

- declarations.d.ts
The Angular http service needs it, and we already have it implemented.
> Expose the response property on XMLHttpRequest in the d.ts file

- timer/timer.android.ts
- timer/timer.ios.ts
- ui/core/view.d.ts
Fixes a broken interface implementation error in the public d.ts.
> Move View._applyXmlAttribute outside @private block.

- package.json
That will make its name easily understandable. It will be used as a plugin in the future.
> Rename the tns-core package to tns-core-modules.

- gruntfile.js
The __extends function is declared in the runtimes. Thus, the one
that the TypeScript compiler generates is reduntant and only
causes unnecessary marshaling delay.
> Stop __extends function output

- globals/globals.ts
Removing __extends function generation by setting the
noEmitHelpers flag we removed the __decorate as well.
While the __extends exists in the runtimes, __decorate
is an EcmaScript-related functionality, hence its place
is in the modules.
> Add the __decorate function

- apps/action-bar-demo/pages/action-bar-hidden.ts
- apps/action-bar-demo/pages/data-binding.ts
- apps/action-bar-demo/pages/navigation-button.ts
- apps/action-bar-demo/pages/page-title-icon.ts
- apps/tests/TKUnit.ts
- apps/tests/pages/background-test.ts
- apps/tests/ui/list-view/list-view-tests.ts
- apps/tests/xml-declaration/inherited-base-page.ts
- apps/tests/xml-declaration/inherited-page.ts
- apps/tests/xml-declaration/inherited-page.xml
- apps/tests/xml-declaration/xml-declaration-tests.ts
- apps/ui-tests-app/pages/background.ts
- ui/core/view-common.ts
- ui/core/view.d.ts
- ui/page/page-common.ts
- ui/styling/visual-state.ts
- ui/tab-view/tab-view.android.ts
Didn't work when the page is not an instance of Page, but an inherited class instead.
No longer using getAncestor(view, "Page") to look for a pagey parent.
Replaced that with a View.page property. Removed getAncestor as its type
name-based implementation seems unreliable.
Areas for improvement -- I don't like the double typecast that's needed to get a page from a `pageLoaded` event args object:
```typescript
var page = <pages.Page>(<view.View>args.object).page;
```
But I can't declare the `page` property as returning a `Page` type object since we'd have a circular import between the page and view modules. Probably the best option would be to declare a `PageLike` interface in a separate module, have `Page` implement it, and use that as the `View.page` type. Thoughts?
> Fix applying app CSS to template children when using custom pages.

- ui/animation/animation.ios.ts
Before the fix, if an iOS animation object has some of its animations finished and some cancelled, that._cancelledAnimations and that._finishedAnimations will both be smaller than that._mergedPropertyAnimations.length and thus _animationFinishedPromise will never be resolved nor rejected. This PR tries to fix this bug.
> fix the issue that an iOS animation promise may never be resolved nor rejected

- apps/tests/xhr-tests.ts
- xhr/xhr.ts
In order to follow the spec the XHR statusText property should
return just the status text without the status code. Adding
tests to guard this behavior.
> Fix XHR statusText property to return just the text

- apps/tests/ui/page/page-tests-common.ts
- apps/tests/ui/page/test-page-declarative-css.css
- apps/tests/ui/page/test-page-declarative-css.xml
- apps/tests/ui/page/test-page-module-css.css
- apps/tests/ui/page/test-page-module-css.ts
- ui/frame/frame-common.ts
frame-common.ts is missing the code to automagically load the page.css file if it exists on a page that is created via the JavaScript createPage() function.  The expected behavior is that the page.css file is always loaded if it exists, no matter how the page is created.
> frame-common.ts is missing the code to automagically load the page.css

- ui/gestures/gestures.android.ts
- ui/gestures/gestures.ios.ts
Nothing major; While perusing the source code I found this simple misspelling in the _detach function in the gestures files.    Would be worth fixing before it becomes a fixed point in time and space.
> Fix the 9 misspellings of _detach in the two Gestures files.

- ui/dialogs/dialogs.android.ts
- ui/dialogs/dialogs.d.ts
- ui/dialogs/dialogs.ios.ts
If the user wants to display only action sheet buttons w/o any text and
he sends null as message, the empty string causes an empty title to be
shown above the buttons. Having null instead, completely eliminates the
empty space.
> Dialog action fix

- CrossPlatformModules.csproj
- apps/tests/xml-declaration/custom-code-file.ts
- apps/tests/xml-declaration/custom-css-file.css
- apps/tests/xml-declaration/xml-declaration-tests.ts
- ui/builder/component-builder.ts
- ui/frame/frame-common.ts
Implemented #675
Example:
```XML
<Page codeFile="~/custom-code-file"
cssFile="~/custom-css-file.css" loaded="loaded">
<Label cssClass='MyClass' />
</Page>
```
```TypeScript
export function loaded(args) {
console.log("Custom code file loaded!")
}
```
```CSS
.MyClass {
background-color: green;
}
```
> CSS and XML code files now can be specified in XML

- ui/html-view/html-view.android.ts
- ui/html-view/html-view.ios.ts
This makes the <HtmlView> clickable and automatic parsing.
Please note; their is one **possible negative** to this code; on iOS to allow the clicking ability the label has to allow selection, so the user can actually select text (i.e. you can actually select & copy the "Go to") in the label.   However, for the minor drawback; you can now do:
\<HtmlView html="Go to http://www.master-technology.com or email me at me@somewhere"/> and both links will just work.   :grinning:  (And \<a href="...">Link Text\</a> now also works... on both platforms)
> Link click detection

- ui/builder/component-builder.ts
- ui/builder/special-properties.ts
- ui/layouts/absolute-layout/absolute-layout-common.ts
- ui/layouts/dock-layout/dock-layout-common.ts
- ui/layouts/grid-layout/grid-layout-common.ts
Setters registered by the respective modules on import.
As requested by @ligaz [here](https://github.com/NativeScript/NativeScript/pull/702#issuecomment-139123742). 
@enchev's [PR](https://github.com/NativeScript/NativeScript/pull/706) needs to be merged first
> Move layout special properties sets out of the component builder.

- apps/tests/ui/style/style-tests.ts
- ui/styling/style-scope.ts
1. Changed code to lowercase the declaration property
2. Minimize the data pushed to each rule (by about half)
Benchmark on v8 shows this new code is about a 1/3 faster than the original code.  (Not to mention it should cause less memory pressure as it saves memory per css rule).
This is to fix #623
> Changed createSelectorsFromSyntaxTree to use a loop rather than filter.

- file-system/file-system-access.android.ts
Due a bug in the Android runtime when a Java method returns `null` value it was propagated as `undefined` in JavaScript. This is no longer the case. As a result, the current loop check never holds `true`. The proposed workaround is to use `isNullOrUndefined` instead of `isUndefined`. Another, yet simpler solution is to use `line === null` check.
> use isNullOrUndefined instead of isUndefined

- apps/tests/layouts/dock-layout-tests.ts
- apps/tests/layouts/grid-layout-tests.ts
- apps/tests/layouts/stack-layout-tests.ts
- apps/tests/ui/scroll-view/scroll-view-tests.ts
- apps/tests/ui/style/style-properties-tests.ts
- data/observable/observable.d.ts
- data/observable/observable.ts
- gruntfile.js
- package.json
- ui/animation/animation.ios.ts
- ui/builder/component-builder.ts
- ui/button/button.android.ts
- ui/date-picker/date-picker.android.ts
- ui/list-picker/list-picker.android.ts
- ui/list-view/list-view.android.ts
- ui/search-bar/search-bar.android.ts
- ui/switch/switch.android.ts
- ui/time-picker/time-picker.android.ts
- utils/utils.d.ts
Fixed a bunch of errors all over the place:
- not using extra properties in object literals
- not using `delete` on module level vars.
------
We are also using the `--moduleResolution classic` compiler option to avoid the Node.js-like behavior of looking in `node_modules` instead of the current dir. Ideally (in the future) we should use only relative imports like `../ui/builder/...` instead of `ui/builder/...` and remove that compiler option.
> Typescript 1.6

- node-tests/test-xml.ts
- xml/xml.ts
This patch adds two features -- during parsing of the XML it will now parse &amp;#xZZZZ;  and &amp;#YY; properly.       The place you normally notice this as being broken (and it totally is) is when you add any symbolic font that uses characters symbols that can't easily be accessed like Fonttastic or Google Material Icons.  In the current version of NS you currently can't use these fonts without remapping the font with a font program/service to move the glyphs from the FF00 range down to the normal text range.    With this patch, you can now access them just like you would in HTML.  &amp;#xFF00; would show that glyph.   (This is a VERY easy issue to run into with fonts)
Second it adds several hundred valid entity &names; html entities like &amp;copy; &amp;trade; &amp;euro; etc...
> Fixes the XML Entities issues on Android 

- ui/core/view.ios.ts
In iOS we now set `bound` along the `frame` property on the native views.
The easiest way to reproduce this is to display an UI similar to:
```
<GridLayout width="50" height="50">
<Image src="res://img" rotate="25" backgroundColor="red" />
</GridLayout>
```
The image will be rotated but will also somewhat scale since the transform was not reapplied after the frame was set. After applying this fix, the image will appear correctly rotated.
> Transformations such as scale, translate, rotate won't be incorrectly affected by the layout

- ui/web-view/web-view.android.ts
This PR fixes that UTF-8 characters (such as the Nordic `åäöæø`) does not show correctly in a Web-view, if content is loaded from local file or local html string.
content-type is changed from `text/html` to `text/html; charset=utf-8` as this is needed for newer Android (where older just rely on the mime-type `utf-8`)
> web-view loads local data with UTF-8

- declarations.d.ts
- weakmap.d.ts
Exclude in es6-shim compiles (Angular) to avoid name clashes.
> Separate WeakMap to its own d.ts file.

- .gitignore
- css-value/index.js
- css-value/package.json
- css/index.js
- css/lib/parse/index.js
- css/package.json
Upgraded the CSS parse libs and made them use the same file structure as upstream. That should fix a problem in the Angular codebase that requires a submodule of the css lib directly: `css/lib/parse/index`
> Css upgrade

- css-value/reworkcss-value.d.ts
- ui/styling/background-common.ts
Using a JS hack. I got beat by the TS compiler `export =` feature
> css-value parse fix to match the new parse function export.

- ui/core/bindable.ts
- ui/styling/stylers-common.ts
By late-importing `application` in `bindable` and `stylers-common`.
It all started in [this issue](https://github.com/NativeScript/NativeScript/issues/948).
Note that requiring `ui/core/view` early on may still break if "globals" hasn't been imported since it requires that the `moduleMerge` function be available.
> Break a circular import view-application-view.

- ui/page/page-common.ts
- ui/page/page.d.ts
Now you can do:
```JavaScript
var p = new Page();
var ai = new ActivityIndicator();
ai.busy = true
p.content = ai;
p.showModal();
setTimeout(function () { p.closeModal(); }, 1000);
```
> added simple showModal() overload

- apps/tests/testRunner.ts
- apps/tests/xhr-tests.ts
- xhr/xhr.ts
Fixing problems I'd stumbled upon while building an HTTP demo with Angular:
- Add `addEventListener`/`removeEventListener` methods for `load` and `error` events only. Raise events accordingly.
- Ignore request body in `send()` if the method is a `GET` since that causes an error on Android. Browsers seem to ignore it too.
> XHR events and an Android bugfix

- es6.d.ts
- ui/animation/animation.android.ts
When android animation is interrupted by a second animation, the first animation will not try to set the animated properties on the view.
Currently the first animation sets the properties on the view while the second animation is still playing causing a flickering.
> Android animations flicker when interrupted by a second animation

- css/package.json
- gruntfile.js
- js-libs/easysax/package.json
- js-libs/esprima/package.json
Include d.ts files in tns-core-modules package.
- Generate a combined tns-core-modules.d.ts file for user projects. (Will
be included in tsconfig.json files by the `tns` tool automagically.)
- Test the integrity of the generated combined file by compiling it.
- Remove all traces of the obsoleted tns-definitions package.
/cc @ErjanGavalji @tailsu @ligaz
> tns-core-modules + d.ts = ☺☺☺

- package.json
I forgot it in my previous PR. `nativescript-dev-typescript` works without it, but it would be best if we keep it in our `package.json`.
> Add the typings hint to nativescript-dev-typescript.

- gruntfile.js
- package.json
Builds the modules in bin/dist/modules and updates an app's
node_modules/tns-core-modules dir.
grunt update-external-app --path=/some/path/myapp1
/cc @nsndeck
> Grunt: add an update-external-app task

- gruntfile.js
- package.json
Skip the rest of the apps and finish ~20 seconds faster.
```bash
$ time grunt --stack --test-app-only=1 --runtslint=0
...
21.52user 1.19system 0:19.81elapsed 114%CPU (0avgtext+0avgdata 655360maxresident)k
0inputs+36632outputs (0major+567166minor)pagefaults 0swaps
$ time grunt --stack --test-app-only=0 --runtslint=0
...
44.02user 2.99system 0:42.32elapsed 111%CPU (0avgtext+0avgdata 656340maxresident)k
0inputs+52440outputs (0major+1281229minor)pagefaults 0swaps
```
ping @ErjanGavalji
> Add an option to build the test app only

- ui/dialogs/dialogs.android.ts
- ui/dialogs/dialogs.d.ts
All the dialogs also suffer on Android from the click outside and then not having the promise resolved or rejected.   
This code does two different things:
1. The promises to be resolved if clicked outside of dialog.
2. The ability to disable the click outside to cancel.  (This might be worth setting as default on the login dialog)
> This will now allow the dialog to call the resolve function when cancelled by clicking outside.

- apps/tests/ui/list-view/list-view-tests.ts
- apps/tests/ui/repeater/repeater-tests.ts
- apps/tests/xml-declaration/template-builder-tests/simple-template-test.xml
- apps/tests/xml-declaration/template-builder-tests/template-view.ts
- apps/tests/xml-declaration/xml-declaration-tests.ts
- tsconfig.json
- ui/builder/builder.d.ts
- ui/builder/builder.ts
- ui/builder/template-builder.d.ts
- ui/builder/template-builder.ts
- ui/core/view.d.ts
- ui/list-view/list-view-common.ts
- ui/list-view/list-view.d.ts
- ui/repeater/repeater.d.ts
- ui/repeater/repeater.ts
This will allow more flexible `itemTemplate` to be used in the Repeater and ListView including factory functions written in pure JavaScript or originating from other framework such as Angular.
This may be perceived as a breaking change, since the template builder will now return a `function` instead of `string`. These strings however, usually round-trip back to "ui/builder".parse, and the parse now has overload to accept both `string` and `function` types.
It is recommended in future to use `"ui/core/view".Template` for `itemTemplate` properties in child controls, but ours will still accept strings so they can be as backward compatible as possible.
Some existing controls that expose `itemTemplate` string property, that are not updated after this change, may get `function` for value …
> Add Template factory function and use it in the ui/builder, Repeater and ListView components

- package.json
Still crashing with stack overflow when enabling the unused variables check, but at least it's newer :disappointed_relieved:
> Upgrade tslint to latest version.

- ui/core/view.android.ts
- ui/core/view.ios.ts
`_addViewCommon` accepts index param in [view-common.ts](https://github.com/NativeScript/NativeScript/blob/master/ui/core/view-common.ts#L985) but it is ignored in ios/android implementations.
> FIX: Platform specific _addViewCore, ignoring index parameter

- data/observable/observable.ts
Fixes issue with updating another property within a property setter.
set value1(value) {
if (this._value1 !== value) {
this._value1 = value;
this.value2 = value + " something";
this.notifyPropertyChange("value1", value);
}
}
set value2 (value) {
...
}
The problem is that notification of `value2` is not raised.
> Fixed issue with two way binding update.

- apps/tests/http-tests.ts
- http/http-request.android.ts
- http/http-request.ios.ts
It seems that this url is a special case since url encoding techniques
failed for both ios and android.
For ios:
stringByAddingPercentEscapesUsingEncoding
stringByAddingPercentEncodingWithAllowedCharacters
For android:
java.net.URLEncoder
> url with % fixed

- build/run-testsapp.grunt.js
The test failed due to a huge output by the `tns platform add ios`
command. Change the grunt `exec` task to `shell` and specify max
length.
> Fix the test run on iOS

- file-system/file-system.ts
- globals/globals.ts
- js-libs/polymer-expressions/path-parser.js
- ui/builder/builder.ts
- ui/builder/component-builder.ts
- ui/frame/frame-common.ts
Fix several issues I encountered while bundling modules code.
The biggest one being that webpack can't handle dynamic `require` calls at compile time and needs a hint.
The way to make this work is to expose an API that registers well-known modules such as:
```typescript
global.registerModule("ui/dialogs", () => require("ui/dialogs"));
```
The latter `require` gets changed by webpack to its own require function, and we can easily resolve it at runtime.
> webpack  improvements

- globals/globals.ts
Not redefining global properties to avoid breaking monkey patchers such as
zone.js (Angular 2).
> More reliable global objects lazy loader.

- ui/builder/builder.ts
- Check every parsed namespace instead of running a global regex on the
whole input
- Check for namespaces ending in tns.xsd and allow schemas hosted on
different URL's than the default one.
> Improve default XML namespace skips.

- org.nativescript.widgets.d.ts
- ui/core/view.android.ts
Use the OriginPoint class in android widgets for the originX/Y implementation.
It will listen for layout events and recalculate the pivot point in pixels based on the origin point that is relative to the view size.
> Fix originX/Y not applied when set before layout in android

- apps/tests/ui/proxy-view-container/proxy-view-container-tests.ts
- ui/core/view-common.ts
- ui/core/view.d.ts
- ui/layouts/grid-layout/grid-layout.ios.ts
- ui/layouts/layout-base.d.ts
- ui/layouts/layout-base.ts
- ui/proxy-view-container/proxy-view-container.ts
Fixes a crash when used in a GridLayout on iOS since the layout needs to be
notified of any layout children changes.
/CC: @vakrilov, @hshristov
> Register ProxyViewContainer children with parent layout.

- gruntfile.js
- package.json
Will output build times for the grunt tasks by using:
```
grunt --profile
```
Profile will not print very small tasks. To list all tasks use:
```
grunt --profile=true --verbose=true
```
> Enable build times profiling

- ui/transition/transition.ios.ts
It appears that `-[NSObject performSelector:]` returns a dummy value when calling a void method on the iOS Simulator, whereas it correctly returns `nil` on a device. Since `-[NSObject performSelector:]` is declared as returning `id`, the iOS runtime tries to marshal the dummy value to a JavaScript object and fails because the dummy value is not a valid Objective-C object.
The fix is to use `-[NSObject valueForKey:]` for non-void zero-parameter methods and `NSInvocation` for everything else.
> Replace -[NSObject performSelector:] with NSInvocation

- ui/list-view/list-view.android.ts
Apply the fix, suggested by Github user @x4080, issue #1371
> Fix ListView crash in android when realized items more than left items

- declarations.d.ts
- gruntfile.js
- module.d.ts
- tsconfig.json
- tns-core-modules-base.d.ts containing modules definitions with as little
platform stuff as possible. Angular apps will reference this one.
- tns-core-modules.es6.d.ts adding some platform stuff to base. Intended to
be used in environments supporting ES6 (obviously)
- tns-core-modules.d.ts adding to the previous one definitions for our ES6
polyfills: promises, collections, weakmaps, etc. The usual reference point
for most apps.
Fixes #1457 too.
> Generate segmented d.ts files and resolve Angular type clashes

- README.md
There is a bug on NativeScript web configuration, translating http://nativescript.org/blog to http://nativescript.orgblog.
Adding www fixed the issue. (http://www.nativescript.org/blog)
> Fixed blog href

- ui/search-bar/search-bar.ios.ts
searchBarTextDidChange only fires when the user changes the text. 
In the following scenario, clearEvent was not being fired:
1. User clears the text (clearEvent is fired from searchBarTextDidChange)
2. Text is programmatically set to a non-empty string (searchBarTextDidChange is not called)
3. User clears the text again (searchBarTextDidChange is called, but clearEvent is not fired)
This PR allows the clearEvent to fire at step 3. 
I would also suggest that a separate event be used when the cancel button is clicked (cancelEvent), as the cancel button being clicked does not imply that the text is cleared.
> Fix clearEvent after programmatically setting text

- globals/globals.ts
When `emitDecoratorMetadata` compiler option is set to true in `tsconfig.json`, TypeScript generates some calls to `__metadata` function.
By default in our NativeScript TypeScript projects the `noEmitHelpers` option is set to true, so TypeScript compiler does not generate the `__metadata` function.
So the application crashes at runtime. Add the missing method, so we can have both `noEmitHelpers` and `emitDecoratorMetadata` set to true in `tsconfig.json`.
> Add global __metadata function

- ui/transition/slide-transition.ios.ts
Slide transition does not animate the appearing page correctly when navigating back.
> Slide transition broken when navigating back on iOS.

- es-collections.d.ts
Right now we are extending the types in d.ts files included in angular projects, but it would be easiest for users if those were just included in the core typings.
> Unify our Map/Set typings with the ones in es6-shim (angular)

- console/console.ts
Related to a [fix in the android-runtime](https://github.com/NativeScript/android-runtime/commit/09914a491e624da3d99cea08c92729e373a8d695), handling the escapes.
> Remove message escaping

- apps/tests/ui/segmented-bar/segmented-bar-tests.ts
@burkeholland [suggested an addition to the HowTo document of the `segmented-bar`](https://github.com/NativeScript/docs/pull/245), declaring the component in the XML. This applies the addition to the unit-tests to have it persisted in the future versions of the API-Reference.
> Add SegmentedBar-XML creation to HowTo

- ui/frame/frame.android.ts
This pull fixes #1569. The problem was that the `clearHistory` option resets the `_currentEntry` field and the
```
let isFirstNavigation = types.isNullOrUndefined(this._currentEntry);
```
expression returned true when it is actually false and this corrupts the native Android backstack.
> Fixes breaking app on back btn clearHistory: true on android

- .gitignore
- gruntfile.js
- package.json
- tsconfig.json
There is a `grunt inplace` task now that outputs the js files near the ts instead of in the bin folder.
The `npm pack` after `grunt inplace` produces a package similar to the one produced in `build/modules` with the only difference that it includes all readme and licence files.
> Allow the build to produce js files near the ts files

- apps/tests/Readme.md
- apps/tests/fetch-tests.ts
- apps/tests/layouts/absolute-layout-tests.ts
- apps/tests/layouts/dock-layout-tests.ts
- apps/tests/layouts/stack-layout-tests.ts
- apps/tests/layouts/wrap-layout-tests.ts
- apps/tests/ui/action-bar/action-bar-tests-common.ts
- apps/tests/ui/activity-indicator/activity-indicator-tests.ts
- apps/tests/ui/border/border-tests.ts
- apps/tests/ui/button/button-tests.ts
- apps/tests/ui/html-view/html-view-tests.ts
- apps/tests/ui/image/image-tests.ts
- apps/tests/ui/label/label-tests.ts
- apps/tests/ui/list-view/list-view-tests.ts
- apps/tests/ui/placeholder/placeholder-tests.ts
- apps/tests/ui/progress/progress-tests.ts
- apps/tests/ui/repeater/repeater-tests.ts
- apps/tests/ui/scroll-view/scroll-view-tests.ts
- apps/tests/ui/search-bar/search-bar-tests.ts
- apps/tests/ui/segmented-bar/segmented-bar-tests.ts
- apps/tests/ui/slider/slider-tests.ts
- apps/tests/ui/switch/switch-tests.ts
- apps/tests/ui/tab-view/tab-view-tests.ts
- apps/tests/ui/text-field/text-field-tests.ts
- apps/tests/ui/text-view/text-view-tests.ts
- apps/tests/ui/web-view/web-view-tests.ts
The doc-snippets were inconsistent
(no spaces before title, small-caps, JS
instead of JavaScript, etc.)
Not bound to an issue. Change related to generated How-to articles.
The change itself is in the unit test comments.
> Fix language tags in doc-snippets

- ui/frame/frame-common.ts
- ui/frame/frame.android.ts
Frame.navigate used to crash when in background, now it delays the navigation until activity resume.
Fixes #1389
The Android app should be sent to background to reproduce the issue so it should have ui tests.
> Frame.navigate while in background

- globals/globals.ts
Used by decorated constructor parameters, and you don't need to emit helpers for every file.
> Add the global __params helper.

- es-collections.d.ts
This will reduce the amount of boilerplate for Angular projects we drag around in a `compat.d.ts` reference file.
> Add typings for the ES6 Iterator interface for compatibility with rxjs.

- apps/tests/ui/proxy-view-container/proxy-view-container-tests.ts
- ui/list-view/list-view.android.ts
- ui/list-view/list-view.ios.ts
Not a regular {N} usage scenario, but it can happen with Angular components
which get wrapped in a proxy container.
> Fix a crash when using a ProxyViewContainer in ListView item templates.

- CrossPlatformModules.csproj
- apps/perf-tests/custom-transition.android.ts
- apps/tests/navigation/custom-transition.android.ts
- declarations.android.d.ts
- ui/transition/fade-transition.android.ts
- ui/transition/flip-transition.android.ts
- ui/transition/slide-transition.android.ts
The [better syntax for Java arrays](https://github.com/NativeScript/android-runtime/issues/70) feature has landed in the Android Runtime and this pull takes advantage of it.
> Replace reflection calls for native Java arrays

- .gitignore
- apps/tests/ui/date-picker/date-picker-tests.ts
- ui/date-picker/date-picker-common.ts
- ui/date-picker/date-picker.android.ts
- ui/date-picker/date-picker.d.ts
- ui/date-picker/date-picker.ios.ts
Added a cumulative `date` property - a result from already existing year, month and day properties. The reason for adding such property is to allow Angular2 `ngModel` support via the new property and also its type - `JavaScript Date type` allows using Angular2 built-in date pipes.
> Introducing DatePicker date property.

- apps/tests/ui/action-bar/action-bar-tests-common.ts
- ui/core/proxy.ts
- ui/core/view-common.ts
- utils/debug.ts
This pull fixes #1691. The problem was with an erroneous check within the `ProxyObject` class.
> [Android] Fix an issue with id not applied to ActionBar in XML

- apps/tests/ui/time-picker/time-picker-tests.ts
- ui/time-picker/time-picker-common.ts
- ui/time-picker/time-picker.android.ts
- ui/time-picker/time-picker.d.ts
- ui/time-picker/time-picker.ios.ts
Added `time` property for TimePicker. This property is cumulative for both existing properties (hour and minute) and will be used as a single input option in `Angular2 ngModel support` (two-way data binding).
> Introducing time property for TimePicker.

- ui/frame/frame-common.ts
As title. Please see https://github.com/NativeScript/NativeScript/issues/1693 for details.
> Fixed 'NavigationEntry.transitionAndroid' not used bug #1693

- ui/date-picker/date-picker.android.ts
Fixed an issue with emitting date change twice. When month is changed from Dec to Jan DatePicker by default also increments year. Therefore {N} emits two changes which in some reason cannot handled by Angular2 change detection infrastructure.
> Hot fix for DatePicker to emit date change only once.

- ui/time-picker/time-picker-common.ts
- ui/time-picker/time-picker.android.ts
A little change to the way `time` property is changed, since within Angular2 scenario too close (in time) changes are not handled correctly. The problem comes from the fact that android native time picker widget when minutes change from (0 to 59 and vice versa) also changes hour - which in previous implementation results in two changes of the `time` property.
> Change time only once due to Angular issues.

- CodingConvention.md
Recommend the usual JavaScript convention of stacking `else/throw` clauses on the same line as the
previous block's closing brace.
*Right:*
~~~ {.javascript}
if (i % 2 === 0) {
console.log('even');
} else {
console.log('odd');
}
~~~
*Wrong:*
~~~ {.javascript}
if (i % 2 === 0) {
console.log('even');
}
else {
console.log('odd');
}
~~~
> Update coding conventions doc for `else/throw` clauses

- apps/tests/xml-declaration/examples/test-page.xml
- apps/tests/xml-declaration/xml-declaration-tests.ts
- ui/builder/builder.ts
- ui/core/view-common.ts
- ui/core/view.ios.ts
Closes #828
`ui/builder` will now attach source url, line and column to the created views.
view.toString() will now append `@file://file:line:column` to the view information.
The utils/debug.Source.get method can be used to extract SourceCode information from view instances.
> Add source information on the view

- ui/text-base/text-base.ios.ts
Prevent stack overflow when re-applying iOS formatted text after a style property changes
Related to #1078
> Prevent stack overflow when re-applying iOS formatted text

- gruntfile.js
- tsconfig.json
The grunt file respected the --leavecomments option, used when
generating the How-To articles of the API Reference. This was broken with
the passthrough option to grunt-ts.
> Fix the leave comments option of the build

- ui/frame/frame.ios.ts
Going back with the stock "Back" button on iOS will now respect the animated setting used when coming to the current page
Fixes #1787
> Go back with no animation on iOS using the stock "Back" button

- apps/tests/navigation/transition-tests.ts
http://stackoverflow.com/questions/33188485/resultindex-is-1-the-polygon-must-be-invalid-adter-addview
> Disable custom transition test on Android 6.9 (API 23)

- ui/frame/frame.android.ts
I took a look at the frame implementation and I think I found the issue. As I am not very familiar with the code, feel free to ignore this PR if it is inappropriate. 
Function `getFrameById` may [return](https://github.com/NativeScript/NativeScript/blob/v1.7.0/ui/frame/frame.android.ts#L565) `null` value. This may happen because the weak reference created in the [constructor](https://github.com/NativeScript/NativeScript/blob/v1.7.0/ui/frame/frame.android.ts#L407) may be GC'ed. Latter in `onCreate` we [call](https://github.com/NativeScript/NativeScript/blob/v1.7.0/ui/frame/frame.android.ts#L711) `getFrameById` which returns `null` and a few lines below we [call](https://github.com/NativeScript/NativeScript/blob/v1.7.0/ui/frame/frame.android.ts#L740) `_onAttached` on a `null` value and we …
> fix issue #1614

- apps/tests/ui/animation/animation-tests.ts
- ui/animation/animation-common.ts
- ui/animation/animation.android.ts
- ui/animation/animation.d.ts
- ui/animation/animation.ios.ts
- ui/core/view-common.ts
- ui/core/view.d.ts
Fixed: https://github.com/NativeScript/NativeScript/issues/1811
Yes, updated the animation-tests to have a test to test this feature (and fixed the test for the cancelling of the normal animation object)
When attempting to switch this from JS to TS -- I originally created a class that extended from the Promise; unfortunately; the v8 engine actually has an issue with an descendant promise class and will throw the error **Uncaught TypeError: #<AnimationPromise> is not a promise** when you try in create it.  So, the implementation I had to use was to create a dummy class (so that TS would allow the users to be able to use Promise.cancel() in TS ).  Then I create a new normal Promise; but then use casting to make TS think it is a AnimationPromise so that everywhere else you can use the new …
> This adds the ability to Cancel the Animation via the Promise returned

- application/application.android.ts
- application/application.d.ts
- ui/frame/frame.android.ts
Fixes #1434 and #1451 
No
If not, why?
You have to manually select any permissions, you are unable to programmatically accept permissions.
If not, please tell us why tests are not included, and list all steps needed to test your pull request manually.
You have to add a "dangerous" permission to the manifest, run it on a Android 6+ device, make sure to build for API 23+, add the code to ask for a permission and then manually accept the permission.  
Unfortunately, not something that can be "automatically" tested.   
As an aside; you can install nativescript-permissions (shortly to be released) that will make this whole getting permissions very easy (assuming this patch is accepted).  The other possibility is to merge my NS-permissions plugin into the core; but I figured I had a much better …
> Adds Android 6.0+ Permissions to NativeScript

- ui/core/view-common.ts
- ui/core/view.android.ts
- ui/layouts/stack-layout/stack-layout.ios.ts
Resolves issue #1822.
Replaces incorrectly formed switch-case statements with multiple options on the same case-line:
case option1 || option2:
...
break;
with correctly formed multiple case statements:
case option1:
case option2:
...
break;
This bug prevented from using "middle" and "center" options for `verticalAlignment` style.
I can include tests, but it's a trivial change. Let me know if you need them.
> Fixes incorrectly formed switch-case statements

- ui/page/page-common.ts
- ui/page/page.d.ts
Added a `showModal` method overload that accepts page instance as a first argument
> Page.showModal API extended to accept page instance

- application/application-common.ts
- application/application.android.ts
- application/application.d.ts
- application/application.ios.ts
- apps/tests/ui/style/style-tests.ts
- ui/styling/css-selector.ts
- ui/styling/style-scope.d.ts
- ui/styling/style-scope.ts
Expose an `application.addCss` method and hide `application.cssSelectors`
from end-user typings. Update StyleScope's with new application selectors
on style application.
NOT updating existing controls/views unless reloaded, or forced (via a
change to className, etc).
This feature grew out of a demand for the Angular renderer, where we need
to apply component styles globally and have them take effect on all pages.
Part of a fix for the second issue discussed in NativeScript/nativescript-angular#115
> Allow updates to application CSS rules.

- apps/tests/ui/page/page-tests-common.ts
- apps/tests/ui/page/page-tests.ios.ts
- ui/page/page-common.ts
- ui/page/page.android.ts
- ui/page/page.d.ts
- ui/page/page.ios.ts
Fix: The `shownModally` event should be fired when the dialog is shown in Android.
> ShownModally fired when the dialog is actually shown in Android

- gruntfile.js
- tsconfig.json
Allows an app to be debugged using the TS modules.
Allows breakpoints to be set in TS modules source code, locals to be inspected in modules TS etc.
No, this affects builds, not the delivery.
> The 'grunt inplace' build generate source maps

- gruntfile.js
This one addresses #1853 and allows user to specify the theme and output directory for the `grunt typedoc` task like this:
```
grunt typedoc --theme <theme-name> --out <output-path>
```
> Custom typedoc theme

- build/platform-declarations/.gitignore
- build/platform-declarations/gruntfile.js
- build/platform-declarations/package.json
- build/platform-declarations/run.sh
Implements #1599
No unit tests, for the implementation of the test would duplicate the code for the generation of the package. To manually test it, the package must contain the files, that don't get packed to the tns-core-modules package.
Needs refactoring so that the command is part of the main build script.
Needs publishing to the [typings registry](https://github.com/typings/registry).
> Generate a package for the platform definitions

- apps/tests/ui/date-picker/date-picker-tests.ts
- ui/transition/transition.android.ts
- ui/transition/transition.ios.ts
It seems Webpack can't discover aliased modules that relative-import other
aliased modules e.g. "ui/transition", aliased to
"ui/transition/transition.android", not discovering "./slide-transition"
which is aliased to "ui/transition/slide-transition.android.js"
> Work around a webpack bundling fail in transitions by using full imports

- build/platform-declarations/gruntfile.js
- build/platform-declarations/run.sh
No issue set. This is a small improvement only.
No unit tests. Everyday builds will prove the validity.
Read the version field of the extracted tns-core-modules package
and set it to the declarations package.json
Remove the redundant run.sh file
> Set declaration package have the main repo version

- ui/frame/frame.ios.ts
The nativescript-marketplace-demo has an ActionBar defined on its first page and hideActionBar set to true. When the app is launched the action bar appears for milliseconds displaying its animation when disappearing. It sounds reasonable to disable the action bar animations when showing/hiding when the main page is still loading, and only use animation for subsequent navigation or dynamically setting hideActionBar=true/false after onLoaded.
> No iOS UINavigationBar animation for the first Page

- declarations.d.ts
- globals/globals.ts
- timer/timer.android.ts
- timer/timer.ios.ts
Instead of waiting for zone.js to patch our global declarations and break
the lazy module loading optimizations there, we'll let it patch stuff
before "globals" gets loaded, so that it doesn't touch (and break) the code
there.
Of course, that requires that functions that need legit patching need to be
made aware of the zone, or get patched later on. The global.zonedCallback
function makes that easy, and we use it for setTimeout/setInterval.
TODO: Think this over again and identify other functions that need zone awareness.
//cc @vakrilov, @nsndeck
> Zone-aware versions of certain APIs: setTimeout/setInterval mostly.

- es6.d.ts
Silences TypeScript compiler warning:
```
error TS2339: Property 'assign' does not exist on type 'ObjectConstructor'
```
This is especially problematic for `nativescript-angular` projects that utilize various es6 features and including the `es6-shim` definition file is not an option as it creates numerous duplicate warnings due to same definitions found throughout tns-core-modules (es6-promise.d.ts, es-collections.d.ts, etc.).
A better fix down the line would be to remove all the individual es6 definitions (es6-promise.d.ts, es-collections.d.ts, etc.) in this repo and replace with the single `es6-shim` found here: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/es6-shim/es6-shim.d.ts
> fix(es6): objectcontstructor assign

- apps/tests/ui/style/style-tests.ts
- ui/styling/css-selector.ts
Bug does not allow to place an attribute css selector alone (Application crash):
```
[testAttr='top'] { background-color: blue; }
```
> Fix for using css attribute selector alone.

- globals/globals.ts
Handle some breaking changes in Zone 0.6.* 
- Global object changed: `zone` -> `Zone`
- `bind` method no longer exists - use `wrap`
> Support for zone 0.6 callback wrapping

- .gitignore
- .travis.yml
- build/run-testsapp.grunt.js
- build/travis-scripts/check-testrun-broken.js
- gruntfile.js
Add android definitions to check if they will get downloaded
Set the language to android
Disable the CLI install prompt
Add buildOnly- and runOnly- commands
Update the version of the packages used
Install android 23 to make the app build
Build the test app with the @next android runtime
Specify oracle java version 8
Use switcher to switch to oraclejdk8
Make the final build a single step so that it breaks on first failure
Reorder attempting to use higher nodejs
Use nodejs 5.10.1
Detect test failure
Decrease verbosity
Unignore the build folder recursively
Remove the redundant node-version messages
Run the tests with Api level 21
> Run tests in travis-CI

- README.md
No issue related; The fix is really small and applies to GitHub only.
No unit tests. The status gets displayed on GitHub.
> Make the Travis-CI image valid for the master branch only

- .travis.yml
- build/run-testsapp.grunt.js
- build/travis-scripts/add-publishConfig.js
- build/travis-scripts/check-testrun-broken.js
Related to #1943
No tests - the builds run on Travis-CI and are actually running the tests.
Modify the AndroidManifest file in the app dir to fix the HTTP tests
Pull the test results in XML format
Publish the test results as artifacts
Have the test-results checks as a single command
Parametrize AVD version; Use the package version, retrieved from package.json for builds and runs
Make the package name a variable
> Publish XML Test results and publish @next

- ui/animation/animation.android.ts
- ui/animation/animation.ios.ts
Animation behavior was different in Android and iOS when applying a rotate animation on 360 degrees. 
In Android you should reset the rotate property to 0 in order to reapply the animation. In iOS this is not necessary. The correct behavior is the Android one.
> Aligned the rotate animation behaviour between Android and iOS

- apps/tests/file-system-tests.ts
- file-system/file-system-access.android.ts
- file-system/file-system-access.ios.ts
createNewFile throws an exception if the parent directory doesn't exist
Fixes #1887
> Ensure parent directory when creating a new file

- ui/segmented-bar/segmented-bar-common.ts
- ui/segmented-bar/segmented-bar.android.ts
- ui/segmented-bar/segmented-bar.d.ts
- ui/segmented-bar/segmented-bar.ios.ts
Implemented AddChildFromBuilder for SegmentedBar. This is required by Angular, since in NativeScript-Angular nested properties are not supported:
```HTML
<SegmentedBar>
<SegmentedBar.items>
<SegmentedBarItem title="All" ></SegmentedBarItem>
</SegmentedBar.items>
</SegmentedBar>
```
now users will be able to use short syntax:
```HTML
<SegmentedBar>
<SegmentedBarItem title="All" ></SegmentedBarItem>
</SegmentedBar>
```
> Implemented AddChildFromBuilder for SegmentedBar.

- apps/tests/ui/bindable-tests.ts
- ui/core/bindable.ts
When converter is added to application.resources then this converters is copied to bindingContext. This pull request is fix this wrong behavior.
> Fixed adding converters to bindingContext.

- js-libs/easysax/easysax.js
- node-tests/test-xml.ts
Fixes/Implements #1797 
Yes, updated the node-tests/test-xml.ts test suite to now test this feature.
---
Please note; One of the issues that was raised when I proposed this feature was that it might be slower.   
I have tested the speed of this using a 112 meg XML file, in a parsing loop of 20 times, and the speed went from 27.79 seconds to 26.67 seconds.   On average it saved slightly over 1 second each time I ran the tests.   This implementation is FASTER than the original and now supports any characters inside quoted strings.   
If you would like a copy of the benchmark & xml file; feel free to ask and I can drop them somewhere as I didn't figure we would want to add a 112 meg xml file added to the repo...  :grinning: 
To keep this patch simple; I didn't do any other optimizations …
> Add ability to add & < > inside XML quoted strings

- gruntfile.js
Just added the `global` typings file to the build.
Now running `node-tests` target for all builds too.
> Fix broken node tests compilation.

- CrossPlatformModules.csproj
- tsconfig.json
- ui/animation/animation.android.ts
- ui/transition/slide-transition.android.ts
- ui/transition/transition.android.ts
- utils/lazy.d.ts
- utils/lazy.ts
Related to: https://github.com/NativeScript/NativeScript/issues/1563
ping @atanasovg, @KristinaKoeva
> Evaluate lazily Android specific global values

- ui/styling/font.android.ts
> Fix: Bold and italic do not work on Android when no font family

- apps/tests/file-system-tests.ts
- file-system/file-system-access.android.ts
> Fixed: Folder.clear fails to remove empty subfolders on Android

- file-system/file-system-access.android.ts
- file-system/file-system-access.d.ts
- file-system/file-system-access.ios.ts
- file-system/file-system.ts
When running in the case of snapshot `__dirname` is not defined. Circumvent this by using platform-specific logic for finding the correct path.
Related to: https://github.com/NativeScript/NativeScript/issues/1563
ping @atanasovg, @KristinaKoeva
> Make FileSystem.currentAppPath platform specific

- apps/tests/ui/style/style-tests.ts
- ui/styling/css-selector.ts
Fixes css selectors specificity when mixed type and class selector is used (Label.red).
> Fixed css specificity levels for type selectors.

- camera/camera.android.ts
Implements https://github.com/NativeScript/NativeScript/issues/2059.
`saveToGallery` returns the image path defaults to false.
```js
cameraModule.takePicture({ saveToGallery: true }).then(function (path) {
console.log(path)
});
```
Updated the default option to return the image path also
```js
cameraModule.takePicture().then(function (picture,path) {
console.log(picture,path)
});
```
> Added save to gallery option - Android

- apps/tests/application-settings-tests.ts
- apps/tests/camera-tests.ts
- apps/tests/color-tests.ts
- apps/tests/connectivity-tests.ts
- apps/tests/data/observable-array-tests.ts
- apps/tests/data/observable-tests.ts
- apps/tests/data/virtual-array-tests.ts
- apps/tests/fetch-tests.ts
- apps/tests/file-system-tests.ts
- apps/tests/ui/activity-indicator/activity-indicator-tests.ts
- apps/tests/ui/animation/animation-tests.ts
- apps/tests/ui/button/button-tests.ts
- apps/tests/ui/dialogs/dialog-tests.ts
- apps/tests/ui/image-cache/image-cache-tests.ts
- apps/tests/ui/image/image-tests.ts
- apps/tests/ui/label/label-tests.ts
- apps/tests/ui/layouts/absolute-layout-tests.ts
- apps/tests/ui/layouts/grid-layout-tests.ts
- apps/tests/ui/list-view/list-view-tests.ts
- apps/tests/ui/page/page-tests-common.ts
- apps/tests/ui/repeater/repeater-tests.ts
- apps/tests/ui/slider/slider-tests.ts
- apps/tests/ui/switch/switch-tests.ts
- apps/tests/ui/text-field/text-field-tests.ts
- apps/tests/ui/text-view/text-view-tests.ts
Fixing the double comments in all how-to's in the new COOKBOOK section
> how-to's fixed slashes in code comments

- apps/tests/ui/layouts/grid-layout-tests.ts
- ui/layouts/grid-layout/grid-layout-common.ts
- ui/layouts/grid-layout/grid-layout.android.ts
- ui/layouts/grid-layout/grid-layout.d.ts
- ui/layouts/grid-layout/grid-layout.ios.ts
Changed callback names to _onRowRemoved, etc and changed visibility to
public to work around a TypeScript "protected" limitation.
Originally reported in NativeScript/nativescript-angular#211.
> Call row/column removed callbacks on removeRows/removeColumns.

- ui/gestures/gestures.ios.ts
Pointer.getY method for iOS returned this.location.x instead of this.location.y
> Typo in Pointer.getY method for iOS

- .ctags_exclude
- ui/styling/css-selector.ts
- ui/styling/style-property.d.ts
- ui/styling/style-property.ts
Extract single style property resolution to an exported API.
Used by CSS selectors, and now the Angular `setElementStyle` renderer API.
> Export single CSS property resolution API.

- application-settings/package.json
- application/package.json
- camera/package.json
- color/package.json
- connectivity/package.json
- console/package.json
- css-value/package.json
- css/package.json
- data/package.json
- debugger/package.json
- fetch/package.json
- file-system/package.json
- fps-meter/package.json
- globals/package.json
- http/package.json
- image-source/package.json
- location/package.json
- platform/package.json
- text/package.json
- timer/package.json
- trace/package.json
- utils/package.json
- xhr/package.json
- xml/package.json
https://github.com/NativeScript/android-runtime/issues/436 - more optimized build.
In order for a more optimized build, we need to make a difference between pure javascript modules and native script specific ones. We will make the difference when we read the `package.json` file of each plugin, including the native script modules. That's why we need to add a native script key inside each modules `package.json`.
Cli already has this logic for plugins and uses the "nativescript" key of the plugins `package.json`. This PR will simply follow the established practice.
ping: @enchev @vakrilov @hshristov @PanayotCankov
> add native script key in package.son files

- build/tsc-dev.js
- build/tsc-dev.ts
The following script emits and typechecks the `.ts` files but skips type checking for `.d.ts`-es. These are the time differences with regular tsc:
```
mcsofcankov:NativeScript cankov$ time node build/tsc-dev.js
Process exiting with code 0.
real	0m14.991s
user	0m15.791s
sys	0m0.834s
mcsofcankov:NativeScript cankov$ time tsc
real	0m27.993s
user	0m29.276s
sys	0m1.204s
```
> Add compiler that won't typecheck .d.ts-es

- ui/tab-view/tab-view.android.ts
Deleted code within `desctoyItem` method, since it leads to some problems when trying to create new contents in a TabView.
> Removed unnecessary view state creation.

- apps/tests/ui/image/image-tests.ts
- http/http-request.ios.ts
- http/http.ts
- image-source/image-source.android.ts
- image-source/image-source.d.ts
- image-source/image-source.ios.ts
- package.json
- tsconfig.json
- ui/image/image-common.ts
- ui/image/image.d.ts
Implements a `loadMode="async"` setting for `Image` that will use async loading for images on the local file system.
Requires the following PR in widgets: https://github.com/NativeScript/android-widgets/pull/22/files
> Optional async mode for loading images from local files

- globals/globals.ts
This is required when preparing only the tns-core-modules for snapshotting. Otherwise webpack replaces this with custom webpack contexts (https://webpack.github.io/docs/configuration.html#automatically-created-contexts-defaults-module-xxxcontextxxx) which is not what we want.
Related to #1563
@hdeshev Do you think this change is going to conflict in any way with the webpack plugin?
> Use global.require in loadModule

- apps/tests/ui/list-view/list-view-tests.ts
- ui/core/view-common.ts
- ui/list-view/list-view-common.ts
- ui/list-view/list-view.android.ts
- ui/list-view/list-view.d.ts
- ui/list-view/list-view.ios.ts
Clear bindingContext is now done in refresh method instead of preparing cell.
Added test for nulling cells bindingContext.
Obsoleted isScrolling property on ListView.
Removed android scroll listener.
Uncommented few tests and made them work.
Fixed android ListView eachChildView to return the wrapping StackLayout so that Unloading now works as expected.
onUnload method in view-common now raise unloaded only if item isLoaded=true.
> Manually applying CSS in removed and now it is done once per cell.

- build/tsc-dev.js
- build/tsc-dev.ts
- package.json
- tests/app/platform-tests.ts
- tests/app/ui/image/image-tests.ts
- tns-core-modules/platform/platform.android.ts
- tns-core-modules/platform/platform.d.ts
- tns-core-modules/platform/platform.ios.ts
- tns-core-modules/ui/image/image.ios.ts
This will improve the performance in cases when the **Image** **src** is set on image that is in **GridLayout** with **start** row and column. The layout won't be invalidated.
Added a few npm scripts that:
Do `tns-core-modules$ npm link` and `tests$ npm link tns-core-modules`:
```
npm run link-tests
```
So you can easily run the tests.
Do a `tsc` using the locally installed typescript compiler:
```
npm run tsc
```
Transpile TS files to JS files and watch TS for changes. The transpiling does not type-check so it is fast but make sure to call `npm run tsc` before commit to do full TypeScript compilation:
```
npm run tsc-tiw
```
> Image should not requestLayout when measured with 'exactly' spec

- gruntfile.js
- node-tests/node-shims.ts
- node-tests/test-angular-xml.ts
- node-tests/test-xml.ts
- tests/app/ui/segmented-bar/segmented-bar-tests.ts
- tns-core-modules/ui/segmented-bar/segmented-bar-common.ts
- tns-core-modules/ui/segmented-bar/segmented-bar.android.ts
Fix SegmentedBar selectedIndex change event not being fired if items are declared in markup (`_addChildFromBuilder`).
Also fix running node-tests on OS X.
> SegmentedBar unbound items not firing selectedIndex change events

- build/tsc-dev.js
- build/tsc-dev.ts
- package.json
Add two helper scripts:
* npm run dev-tests-android
* npm run dev-tests-ios
Force `noImplicitUseStrict` when transpiling with tsc-dev.
Ping @PanayotCankov
> Add dev tests scripts

- tests/app/ui/page/page-tests.android.ts
- tns-core-modules/ui/frame/frame.android.ts
- tns-core-modules/ui/frame/frame.d.ts
The specific use case is to enable the YouTube player plugin in a {N} app. The Google API works either through extending [YouTubeBaseActivity](https://developers.google.com/youtube/android/player/reference/com/google/android/youtube/player/YouTubeBaseActivity) or by creating an instance of the [YouTubePlayerFragment](https://developers.google.com/youtube/android/player/reference/com/google/android/youtube/player/YouTubePlayerFragment) class. Since navigation in the core Modules is fragment-based, it is more naturally to use the second approach of the player API.
This pull adds a method on the `AndroidFrame` interface that returns the native `android.app.Fragment` created for a Page instance. This native Fragment instance is needed so that we can take advantage of the [nested …
> [Second Try] Add API that resolves the native android.app.Fragment instance created for a Page

- tns-core-modules/application/application.android.ts
- tns-core-modules/application/application.d.ts
- tns-core-modules/utils/utils.android.ts
This pull removes the Android Application object extend from the core modules. The change enables the following scenarios:
- Make the modules Heap snap-shottable
- Allow users to provide custom `android.app.Application` implementation. This includes
- Entirely custom application type
- Implement an additional interface on the default `com.tns.NativeScriptApplication` class
The change also introduces the following paths for application initialization:
- User provides custom application extend. In the `onCreate` method he should manually initialize the application module via `application.android.init(this)`. The static-binding-generator will take care of the `*.JAVA` file generation.
- No custom extend is defined. Application will use the default `com.tns.NativeScriptApplication` …
> Remove the android.app.Application extend from the core modules

- tns-core-modules/declarations.d.ts
Expose the `zonedCallback` function so that it can be used from plugin developers to wrap callbacks that come from native inside zone. This is needed in Angular project to trigger the change detection.
> Expose the zonedCallback function

- tns-core-modules/ui/transition/transition.android.ts
When we are on API Level 23 and we have cachePagesOnNavigate=true, the exit transition of the current (disappearing) page ends immediately after its start, which in turn removes the page UI from the fragment and leaves a white spot in place of the current page while the enter transition of the new page is being played.
Related to #2225
> Fixed: Exit transition on API Level 23 with cachePagesOnNavigate=true

- tns-core-modules/ui/core/view-common.ts
- tns-core-modules/ui/core/view.android.ts
- tns-core-modules/ui/core/view.d.ts
- tns-core-modules/ui/core/view.ios.ts
- tns-core-modules/ui/list-view/list-view-common.ts
- tns-core-modules/ui/list-view/list-view.ios.ts
Added View.isLayoutRequired - to check if Layout call is needed after a measure call. Use in list-view.
Measure pass now get all its properties from nativeLayoutParams property instead of using instance dependency properties (e.g. perf improvement).
List-view now layouts cells only if there is need to.
List-view now measure rows with the specified rowHeight.
> Avoid excessive requestLayout calls

- tests/app/ui/list-view/list-view-tests.ts
- tns-core-modules/ui/list-view/list-view.android.ts
When ListView is added to modal dialog in a nativescript-angular application closing the modal dialog removes all angular views in recursive way from child to parents (which conflicts with NativeScript way of removing views - some already removed views does not have a proper parent - and application crashes).
> Fixed crash when ListView is used in a modal dialog (Android).

- tests/app/ui/dependency-observable-tests.ts
- tns-core-modules/ui/frame/activity.android.ts
- tns-core-modules/ui/frame/frame.android.ts
- tns-core-modules/ui/frame/frame.d.ts
- tns-core-modules/ui/package.json
- tsconfig.json
This pull removes the prerequisite for a specific Activity type for the core modules and enables scenarios where users will need custom Activity base type - e.g. `YouTubeBaseActivity`. The modules now depend on being notified externally for an `Activity` event - like `onCreate`.
Steps for providing extended Activity at user level:
1. Add a new file, having the `*.android.*` suffix.
2. Implement/override the needed methods.
3. User must notify the core modules for the needed callbacks through the `ui/frame/AndroidActivityCallbacks` interface.
4. The static-binding-generator will take care of generating the new Activity class. The default one provided by the modules will be either overridden or will not be used (in case of a new Activity name).
5 User must update the manifest file if the …
> Extract the Activity implementation logic in a separate class.

- tns-core-modules/ui/frame/fragment.android.ts
- tns-core-modules/ui/frame/frame.android.ts
- tns-core-modules/ui/frame/frame.d.ts
- tns-core-modules/ui/transition/transition.android.ts
- tsconfig.json
This pull decouples the android.app.Fragment extend in a separate file, which allows it to be safely skipped from the snapshot bundle. It also allows users to provide custom extend logic, given they utilize the `frame` module as needed (calling back through the provided `_callbacks` member).
> Decouple Fragment implementation logic from the Extend call.

- tests/app/ui/bindable-tests.ts
- tns-core-modules/ui/core/bindable.ts
Converter should be called even when source property value is null or undefined.
> Fixed binding converter calls.

- gruntfile.js
- tns-core-modules/ui/frame/frame.d.ts
The `tns-core-modules` file reorg had broken the platform d.ts excludes and was not correctly checking that our public dts files do not expose platform types.
That was breaking the `grunt docs` typedoc build as well
> Fix ts:buildDts check

- tests/app/ui/styling/style-tests.ts
- tns-core-modules/ui/core/view-common.ts
Adding a class name `cssClass` after page loaded does not reapplying all nested elements styles.
> Fixed issue #1655 cascading css selectors.

- tests/app/ui/styling/style-tests.ts
- tns-core-modules/ui/styling/style-scope.ts
- tns-core-modules/utils/utils-common.ts
- tns-core-modules/utils/utils.d.ts
In some cases when a lot css selectors are used unstable sort of CssSelectors results in problems with correct order of applying css selectors.
> Fixed sorting issue with Css Selectors with same specificity.

- tns-core-modules/ui/animation/animation.android.ts
- tns-core-modules/ui/animation/animation.ios.ts
- tns-core-modules/ui/animation/keyframe-animation.ts
- tns-core-modules/ui/core/view-common.ts
- tns-core-modules/ui/core/view.android.ts
- tns-core-modules/ui/core/view.ios.ts
- tns-core-modules/ui/styling/css-selector.ts
Fixes the following scenario (existing in iOS):
1. Execute an animation (e.g. translate 0, 100)
2. Reset transformX, transformY values with code
3. Animate again (translate 0, 100) and the animation will look wrong because style property values will be out of sync compared to the View properties.
> Fixed animation value sync issues

- tests/app/xhr-tests.ts
- tns-core-modules/xhr/xhr.ts
According to the RFC: https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2
"Field names are case-insensitive".
For instance, Google Cloud Endpoints use "content-type" in the response.
> Ignore the case when getting a response header

- tns-core-modules/declarations.android.d.ts
- tns-core-modules/http/http-request.android.ts
- tns-core-modules/ui/frame/frame.android.ts
- tns-core-modules/ui/image-cache/image-cache.android.ts
The Async.java implementation is moved from the Android Runtime project template to the widgets repo. This pull renames the package - `com.tns.Async` is now `org.nativescript.widgets.Async`.
**Note:** Do not merge for now, these two pulls should be merged first:
* https://github.com/NativeScript/android-runtime/pull/478
* https://github.com/NativeScript/tns-core-modules-widgets/pull/26
> Rename com.tns.Async.xxx to org.nativescript.widgets.Async.xxx

- tns-core-modules/globals/globals.ts
This comes from this test: https://github.com/NativeScript/NativeScript/blob/15df94ca829192f1d52796e19b6f41f599c53405/tests/app/fetch-tests.ts#L15
Ping @atanasovg, @enchev.
PR is for release branch.
> Export all fetch types to the global object when running in snapshot context

- tns-core-modules/ui/frame/frame.d.ts
- tns-core-modules/ui/frame/frame.ios.ts
- tns-core-modules/ui/tab-view/tab-view.ios.ts
Resolves #2121
The action bar will now be hidden when we have "< More" visible.
> Fix:  The navigation bar duplicates when going to TabView's "More" tab

- tests/app/ui/text-view/text-view-tests.ts
- tns-core-modules/ui/editable-text-base/editable-text-base.android.ts
so that no exception is thrown if android raise textChanged but we destroyed our android object in onDestroy of edit-text.
Fixes #2391
> TextWatchListener is removed at onDetach 

- tns-core-modules/application/application-common.ts
- tns-core-modules/bundle-entry-points.ts
- Prefer registered modules in `builder` and `component-builder`.
- Implemented a bundle entrypoint registration mechanism using a package.json attribute.
- Register well-known modules used by the component builder as bundle entrypoints.
- Move text/(formatted-string|span) modules to subfolders, so we can register those as entry points (meh!)
> webpack fixes

- tns-core-modules/ui/tab-view/tab-view.ios.ts
Fixes/Implements #1278 
Very small change. Does not impact the TabView unit tests.
Changes the UIImageRenderingMode for tab icons from "AlwaysOriginal" to "Automatic." This allows icon images to inherit the `selectedColor` specified for the tabview (eliminating the need to provide two versions of every tab icon).
Unclear why this behavior was changed in NativeScript 1.5 (history of tab-view.ios.ts only goes back to May). This change restores behavior of tabview icons to pre-1.5 styling and is a huge time saver for iOS tabview styling.
> Update iOS TabView to use Automatic rendering mode

- tns-core-modules/globals/globals.ts
Fixes snapshot build:
```
ReferenceError: __decorate is not defined
```
The `dialogsModule` is registered before the `__decorate` function is initialized.
Triggered by: https://github.com/NativeScript/NativeScript/commit/c1aeeb51a73330f67b5a7df6ff69a1fa189c1615#diff-af6934b3c0bc88859553f50be3bd6415R59
> [Snapshot] Register TypeScript helpers at the very start

- package.json
No tests. The change is in the build of the documentation, which was broken due to using new TypeScript features. The TypeDoc referred was old, hence the problem.
> Update grunt-typedoc to make it get new TS features

- tests/app/navigation/navigation-tests.ts
- tns-core-modules/ui/frame/frame.ios.ts
- tns-core-modules/ui/page/page.ios.ts
FIX: `isBackNavigation=true` in navigation event when navigating **forward** with clearHistory in ios.
Similar to #2479 
cc: @hshristov
> FIX: Wrong isBackNavigation value

- gruntfile.js
No related issue. Small change to ease the documentation build script.
No tests, for the change is in the build scripts.
> Use the nativescript theme by default for api-ref

- package.json
Increase the version of the docs template used to have the api-ref header aligned to the docs one.
> Use an improved docs header

- tns-core-modules/ui/styling/font.ios.ts
Use fs.knownFolders to get the app dir instead of the __dirname hack
> Fix iOS font registration when bundling scripts.

- tns-core-modules/application/application.android.ts
Adding "SET_THEME_ON_LAUNCH" on the activity in the android manifest will allow a second theme to be applied on create after the activity is launched.
``` XML
<activity
android:name="com.tns.NativeScriptActivity"
android:label="@string/title_activity_kimera"
android:configChanges="keyboardHidden|orientation|screenSize"
android:theme="@style/LaunchScreenTheme">
<meta-data android:name="SET_THEME_ON_LAUNCH" android:resource="@style/AppTheme" />
</activity>
```
> Add a mechanism the launch screen theme to be reset after launch

- tns-core-modules/ui/core/view-common.ts
An element that is not an instance of a View should not be added directly to its parent and thus triggering the logic for setting any inherited or style properties. 
For example - ActionBar.actionItems in ng app.
> Element that isn't a View should not be added to its parent

- tns-core-modules/es6-promise.d.ts
- tns-core-modules/ui/animation/animation.d.ts
Also change the Promise generic param from R to T.
Make it similar to TypeScript's lib.es6.d.ts until we actually
remove those typings.
/cc @PanayotCankov
> Rename Thenable<T> to PromiseLike<T>

- tests/app/App_Resources/Android/AndroidManifest.xml
Without it Location tests fails on some devices (Samsung S4)
> Added permission for location.

- tests/app/ui/bindable-tests.ts
- tns-core-modules/ui/core/bindable.ts
Fixing an issue with binding an element to its bindingContext property. The issue can be reproduced if an element is bound to `bindingContext` and any other property. By design the other property should be relative to the local bindingContext (the new one which is result from the first binding to `bindingContext`). Unfortunately due to bug this local `bindingContext` is not taken into account - instead bindingContext object value when binding is created is used.
> Fixed issue when bind to bindingContext and other property.

- tests/app/ui/label/label-tests.ts
- tns-core-modules/ui/label/label.ios.ts
Rendering issue with a Label rendered for the first time with an empty string as text. This results in a zero height of the label and due to bug after changing text later layout request is rejected and text is not visible.
> Label zero height issue fixed.

- tests/app/data/observable-tests.ts
- tests/app/ui/bindable-tests.ts
- tns-core-modules/data/observable/observable.d.ts
- tns-core-modules/data/observable/observable.ts
Static functions `fromJSON` and `fromJSONRecursive` renamed to `fromObject` and `fromObjectRecursive` respectively (as the new names are more correct). Also functions are moved to Observable module instead exported as static functions of Observable class.
> Renamed and moved to module Observable creation functions.

- tns-core-modules/ui/dialogs/dialogs.android.ts
The color of buttons inside dialogs is not modified in case the following CSS is defined:
Page Button {
background-color: #30BCFF;
color: #FFFFFF;
}
Button {
font-size: 15;
color: springgreen; 
}
In this case, the color of a button inside dialog will be still "#ffffff", while the desired one is "springgreen".
> Color of buttons inside dialogs is not applied if there'are nested css styles

- gruntfile.js
Fixes an OOM crash in docs build.
> Ignore iOS platform definitions in typedoc builds.

- tns-core-modules/es6.d.ts
TypeScript 2.0 now has its own Object typings which clash with our own.
Note that this does not switch tns-core-modules to using TypeScript 2.0 yet! It only allows app developers to use TypeScript 2.0 for their code.
//cc @PanayotCankov
> Remove global Object var declaration to avoid clashing with TS 2.0

- tns-core-modules/declarations.d.ts
Decorator can be used when extending a Java class to implement an array of Java interfaces.
@hshristov
> Add android interfaces decorator definition in declarations.d.ts

- tests/app/ui/view/view-tests.ios.ts
- tns-core-modules/ui/core/view.ios.ts
As suggested by @tsonevn I'm updating the `automationText` property on `ui/view` on iOS to set both `accessibilityIdentifier` and `accessibilityLabel`.
This fixes basic `VoiceOver` behavior on iOS.
> Fixes #2621: Add accessibility labels to views

- tns-core-modules/ui/frame/frame.d.ts
setActivityCallbacks moved as public function so that this article can be completed in TypeScript.
http://docs.nativescript.org/runtimes/android/advanced-topics/extend-application-activity
Fix: https://github.com/NativeScript/NativeScript/issues/2526
> setActivityCallbacks moved as public function

- tns-core-modules/camera/camera.android.ts
The result ImageSource is limited to device screen dimensions in order to prevent OutOfMemory exception.
> Image from camera will be resized to screen dimensions.

- tests/app/file-system-tests.ts
- tns-core-modules/file-system/file-system-access.ios.ts
- tns-core-modules/file-system/file-system.ts
GetFolder method in file-system-access creates a new folder if the requested one does not exist. This action cannot be performed on IOS device for folders outside the scope of the app, consequently - the failing test on ios device (_testIOSSpecificKnownFolder).
> IOS Known folders are not created if do not exist

- expect.exp
Tinkering with the expect script...
> Add timeout warning log for test runner. Increase timeout to 1200

- tns-core-modules/ui/styling/background.android.ts
If an element has both padding and border-related (width, color, radius, etc,) properties set, the padding is not reset. 
_Element_:  
`<Button text="padding and borderWidth"  style="padding: 0; border-width: 5; border-color: red; border-radius: 8"/>`
_Reset_:
`view.eachDescendant(stackLayout, function (v: view.View) {      
v.style._resetValue(style.paddingLeftProperty);
....
v.style._resetValue(style.borderColorProperty);
....
return true;
});`
> Padding is not reset if an element has a border-related property set

- tns-core-modules/image-source/image-source.android.ts
- tns-core-modules/image-source/image-source.ios.ts
- tns-core-modules/ui/enums/enums.d.ts
- tns-core-modules/ui/enums/enums.ts
Added acronym **jpg** in enums.ImageFormat and in image-source module
Related to [https://github.com/NativeScript/NativeScript/issues/2766](https://github.com/NativeScript/NativeScript/issues/2766)
> added jpg as synonim for ImageFormat jpeg

- tests/app/ui/label/label-tests.ts
Follow up: https://github.com/NativeScript/NativeScript/pull/2800.
These label tests fail on Android device due to `actualNative = testLabel.android.getText();` sometimes returns `SpannableString`, but not `String`. This PR makes it explicitly return `String`.
> Update label tests

- tns-core-modules/ui/page/page-common.ts
- tns-core-modules/ui/page/page.d.ts
- tns-core-modules/ui/page/page.ios.ts
Fixes #2836
Adds `iosSwipeBackNavigationEnabled` property to page
> Added iosSwipeBackNavigationEnabled

- tns-core-modules/ui/transition/transition.android.ts
Most of the OOM Exceptions were caused by holding Bitmap references inside image-source. Image component was using imageSource internally. Now Image component is loading images in Java so OOM should be rare. 
Removing the GC call improve the UX but there still could be a case were manual gc call is needed.
> remove gc call

- tns-core-modules/ui/action-bar/action-bar.android.ts
When `NavigationButton` is defined in `ActionBar` in causes memory leak in android.
Fix #2712
> Fix memory leak in android

- tns-core-modules/fps-meter/fps-meter.ts
Wrap the callbacks in fps-meter module in `zonedCallback`.
The callbacks are called form native code and we need to make sure they are fired in the same zone as the `addCallback` method to work with angular (or any other zoned app)
cc @tsonevn
> Make fps-meter callback execute in the same zone as they are created

- tns-core-modules/ui/dialogs/dialogs-common.ts
The new cool Pseudo selector cool have a negative interaction with Dialogs; the code will now create a "NSInternalInconsistencyException" later in an iOS application.  (Depending on when GC occurs)
The issue is that the dialog-common creates a new button, applies the CSS selector and grabs its color.  The process of applying the CSS selector causes the pseudo selector code to be registered via the _updateHandler code inside the button.ios.ts file.    For every "observer" registered, you must de-register it before deallocation.   However, since the "onUnloaded" code is never called (because the button is not actually put into the DOM) the observer is never un-registered.   This patch manually calls the onUnloaded() function which de-registers the observer so everything is great again. …
> Fix for Dialogs crashing on iOS

- apps/app/cuteness.io/reddit-app-view-model.ts
- tests/app/ui/image/image-tests.ts
- tns-core-modules/ui/image/image.android.ts
- tns-core-modules/ui/tab-view/tab-view.android.ts
TabView doesn't save/restore its visual hierarchy.
Cuteness.io source changed to use https.
> ImageSource was reset in CreateUI wrongly.

- tns-core-modules/timer/timer.android.ts
The current setTimeout code for android uses getMainLooper() which will cause the worker timer to fire on the main thread.   The code needs to actually run on the correct thread that started it; switching to "myLooper" will work on both the main thread and on worker threads.
To duplicate:
`app.js`
```
var x =new Worker('timer.js');
setTimeout(function() { console.log("Main thread worked"); }, 100);
```
`timer.js`
```
require('globals');
setTimeout(function() { console.log("Worker Worked"); }, 100);
```
Will produce on unfixed core modules: 
> An uncaught Exception occurred on "main" thread.
> com.tns.NativeScriptException: Cannot find object id for instance=com.tns.gen.java.lang.Runnable@52a37664
> 	at com.tns.Runtime.callJSMethodImpl(Runtime.java:889)
> 	at …
> Fixes using setTimeout/setInterval in a Android Worker

- tns-core-modules/image-asset/image-asset-common.ts
- tns-core-modules/image-asset/image-asset.android.ts
- tns-core-modules/image-asset/image-asset.ios.ts
Fixes issue with resizing image for ios. For android this will also work but will return an image that is smaller sample size (based on requested size). For a complete solution we will update `tns-core-modules-widgets` to make such resizing on native side.
> Fixed issue with image resizing.

- apps/app/gallery-app/main-page.ts
- build/tslint.json
- package.json
- tests/app/location-tests.ts
- tests/app/pages/page17.ts
- tests/app/platform-tests.ts
- tests/app/ui/button/button-tests-native.d.ts
- tests/app/ui/list-picker/list-picker-tests-native.ios.ts
- tests/app/ui/list-view/list-view-tests.ts
- tests/app/ui/repeater/repeater-tests.ts
- tests/app/ui/search-bar/search-bar-tests-native.ios.ts
- tns-core-modules/bundle-entry-points.ts
- tns-core-modules/js-libs/easysax/easysax.d.ts
- tns-core-modules/text/text.d.ts
- tns-core-modules/timer/timer.ios.ts
- tns-core-modules/trace/trace.ts
- tns-core-modules/ui/builder/builder.ts
- tns-core-modules/ui/frame/frame-common.ts
- tns-platform-declarations/test.ts
- tsconfig.public.es2016.json
- tsconfig.public.es6.json
Moving one step closer to remove the grunt file.
The `tsconfig.public.es2016.json` now adds tsconfig that can be used to type check the public .d.ts-es exported by the tis-core-modules-es2016.d.ts using `npm run test-tsc-es2016`.
The tslint has been added as npm script too: `npm run tslint`.
> npm scripts for typechecking public .d.ts-es and running tslint

- tns-core-modules/bundle-entry-points.ts
When web-packing the bundle-entry-points.ts is used to register the different framework modules; added missing listview...
> Added missing ListView to bundle-entry-points.ts

- apps/app/ui-tests-app/action-bar/background-css.css
- apps/app/ui-tests-app/action-bar/background-css.ts
- apps/app/ui-tests-app/action-bar/background-css.xml
- apps/app/ui-tests-app/action-bar/main-page.ts
- tns-core-modules/ui/core/view-common.ts
- tns-core-modules/ui/core/view.d.ts
- tns-core-modules/ui/styling/style-scope.ts
Resolves NativeScript/nativescript-angular#516
Added ui test case: in the `ui-test-app`:
1. Navigate to `action-bar`
2. Navigate to  `actBGCss`
3. Navigate to cleared page (`go to cleared page` button)
4. Verify that the action bar is white. The bug fixed was that the action bar was styled red - with the style form the previous page.
cc: @PanayotCankov @SvetoslavTsenov
> Don't apply css on unloaded

- tns-core-modules/bundle-entry-points.ts
Avoiding a crash if the import happens too soon.
> Fix bundle-entry-points by importing globals first.

- tests/app/fetch-tests.ts
- tns-core-modules/fetch/fetch.js
Fixes/Implements #2952.
Added one test to cover this case.  Since I do not know what the error message will be on iOS, a pattern was used rather than checking for an exact message.
Additionally some cleanup of the existing tests was done to improve correctness of the tests.  Some would timeout, rather than fail, swallowing the failure message.
> Improve error message of `fetch` when xhr.onerror occurs

- tns-core-modules/ui/layouts/flexbox-layout/flexbox-layout.ios.ts
This will fix only the iOS version of the FlexboxLayout and may damage other functionality.
> Shrink will not damage the last item when it is shrink=0

- tests/app/ui/tab-view/tab-view-tests.ts
- tns-core-modules/ui/tab-view/tab-view-common.ts
- tns-core-modules/ui/tab-view/tab-view.android.ts
- tns-core-modules/ui/tab-view/tab-view.d.ts
Resolves #2815
* Gets or sets the number of tabs that should be retained to either side of the current tab in the view hierarchy in an idle state.
* Tabs beyond this limit will be recreated from the TabView when needed.
> Add TabView.androidOffscreenTabLimit property

- tests/app/ui/frame/frame-tests.android.ts
Test for verifying percent margin on page uses only floor func for android.
> percent_margin test on android uses only floor func

- apps/app/ui-tests-app/mainPage.ts
- apps/app/ui-tests-app/page/main-page.ts
- apps/app/ui-tests-app/page/main-page.xml
- apps/app/ui-tests-app/page/page-status-bar-css.ts
- apps/app/ui-tests-app/page/page-status-bar-css.xml
- tns-core-modules/ui/enums/enums.d.ts
- tns-core-modules/ui/enums/enums.ts
- tns-core-modules/ui/page/page-common.ts
- tns-core-modules/ui/page/page.android.ts
- tns-core-modules/ui/page/page.d.ts
- tns-core-modules/ui/page/page.ios.ts
- tns-core-modules/ui/styling/style.d.ts
- tns-core-modules/ui/styling/style.ts
- tns-core-modules/ui/styling/styling.d.ts
Page exposes two properties:
- statusBarStyle - it can be 'dark' or 'light' - dark background with light letters and vice versus. 
- androidStatusBarBackground - only for Android since the background color of the status bar in ios cannot be modified.
> CSS support for styling status bar

- apps/app/ui-tests-app/issues/issue-3164.ts
- apps/app/ui-tests-app/issues/issue-3164.xml
- apps/app/ui-tests-app/issues/main-page.ts
- tns-core-modules/ui/styling/background.ios.ts
If the border width is set to a value, it cannot be reset to 0 again:
So, 
button.borderWidth = 3; 
and then 
button.borderWidth = 0;
The border of the button will stay 3.
> Border width cannot be reset to 0 on IOS

- tns-core-modules/application/application-common.ts
- tns-core-modules/application/application.d.ts
Added functions for setting NS application `cssFile` and `resources`, because with es6 these fields can be used only in read-only mode.
> Export set function for cssFile and resources.

- tns-core-modules/ui/text-field/text-field.android.ts
In android if we toggle the `secure` property of `text-field`, the cursor position was getting reset to first character. 
This PR solves that issue by setting cursor position after setting `inputType`.
Find more details at #3181.
> Fix for issue #3181 of cursor position for secure text-field in Android

- apps/app/ui-tests-app/flexbox/flexbox-perf-comparison.xml
- tns-core-modules/ui/layouts/flexbox-layout/flexbox-layout.ios.ts
Performance tests showed that the flex box in some cases fall up to 30% slower than grid and stack counterparts. After profiling the problems narrow down to intense use of inline styles and some redundant code. Measurement now shows times like:
iOS 
flexbox-grid: 865
gird: 790
-10%
flex-stack: 710
stack: 675
-5%
Android
flexbox-grid: 1115
gird: 1195
+7%
flexbox-stack: 1039
stack: 960
-10%
Which makes the flex box about 10% slower. This should be acceptable. We should also check if we can speed up inline styles.
> FlexboxLayout profiling and improvements

- apps/app/ui-tests-app/issues/issue-3211.css
- apps/app/ui-tests-app/issues/issue-3211.ts
- apps/app/ui-tests-app/issues/issue-3211.xml
- apps/app/ui-tests-app/issues/main-page.ts
- tns-core-modules/ui/dialogs/dialogs-common.ts
- tns-core-modules/ui/dialogs/dialogs.android.ts
Android: 
modifying the background of the button in CSS will be applied to the buttons inside dialogs. 
Button {
background-color: cyan;
}
Buttons inside the dialog in IOS are placed in a private view - _UIAlertControllerActionView -> not recommended to change their look and feel.
> Background of the buttons inside dialog can be modified with CSS

- apps/app/ui-tests-app/css/list-picker.ts
- apps/app/ui-tests-app/css/list-picker.xml
- apps/app/ui-tests-app/css/main-page.ts
- tns-core-modules/ui/list-picker/list-picker.android.ts
- tns-core-modules/ui/list-picker/list-picker.ios.ts
So far, ListPicker hasn't respected its color (both for IOS and Android) and background-color (for IOS) properties.
ListPicker {
color: pink;
background-color: lightskyblue;
}
> ListPicker respects color and bckgColor set from CSS

- tns-core-modules/ui/editable-text-base/editable-text-base.android.ts
When text-field has returnKeyType set to 'next', keyboard disapears when tap 'next' button, and second text-field is focused. This PR changes this behavior. Now keyboard is not dismissed after tap.
> Do not dismiss keyboard on android, when text-field has return key type set to 'next'

- tests/app/ui/text-field/text-field-tests.ts
- tns-core-modules/ui/text-field/text-field.ios.ts
Setting `placeholder-color` on `TextField` crashes if the `hint` property is not set.
Fixes #3242
> Fix(IOS): Setting placeholder color crashes

- tns-core-modules/ui/tab-view/tab-view-common.ts
1. TabViewItem is now added as a child to TabView
2. TabViewItem.view can now be set directly without specifying `.view` element:
```
<TabViewItem>
<StackLayout>
<Label text="no .view!!!" />
</StackLayout>
</TabViewItem>
```
> fix TabView

- tns-core-modules/debugger/webinspector.ios.ts
Chrome calls compileScript method when an expression is evaluated in the console. So to enable the console evaluate add an empty compileScript implementation.
Also send an Runtime.executionContextCreated which is needed for Console evaluation.
Both of the command and the event do not exist in the Webkit protocol, so we cannot use InspectorBackendCommands definition file
> Enable evaluating in Chrome Console

- package.json
- tests/package.json
Works around an incompatibility between TypeScript 2.1 and the android runtime tools.
> Pin typescript dependency to 2.0.x

- tns-core-modules/http/http-request.android.ts
- tns-core-modules/http/http-request.ios.ts
- tns-core-modules/http/http.d.ts
- tns-platform-declarations/android/org.nativescript.widgets.d.ts
This implements the option to have http.request() not follow server's 3xx redirection replies
but instead return the exact redirection code and headers.
* on iOS, it uses a different NSURLSession instance for non-following request,
with a NSURLSessionTaskDelegate implementing URLSessionTaskWillPerformHTTPRedirection...
* on Android, it passes the option on to org.nativescript.widgets.Async.Http;
requires a related [feature in tns-core-modules-widgets](https://github.com/dturing/tns-core-modules-widgets/commit/a8bfd4babd3cd6e55cf03d070a15b0f43a4745b3) to work
> Add option to have http.request() not follow HTTP 3xx redirections

- tests/app/ui/list-view/list-view-tests.ts
- tns-core-modules/ui/list-view/list-view.android.ts
The android version of the implementation of the Styler for separator color was missing a getter. This could result in an undefined value in the reset-property function.
> Getter in ListViewStyler for separatorColor

- tests/app/ui/layouts/flexbox-layout-tests.ts
- tns-core-modules/ui/layouts/flexbox-layout/flexbox-layout-common.ts
- tns-core-modules/ui/layouts/flexbox-layout/flexbox-layout.android.ts
- tns-core-modules/ui/layouts/flexbox-layout/flexbox-layout.ios.ts
- tns-platform-declarations/android/org.nativescript.widgets.d.ts
Items are not reordered on changing the order property more than once. For example:
1. Step 1:
FlexboxLayout.setOrder(text1, 3);
FlexboxLayout.setOrder(text2, 1);
FlexboxLayout.setOrder(text3, 2);
2. Step 2: 
FlexboxLayout.setOrder(text1, 1);
FlexboxLayout.setOrder(text2, 2);
FlexboxLayout.setOrder(text3, 3);
The order property of the item will be respected - FlexboxLayout.getOrder(text1) will return the second value, but the item will not be reordered and will be arranged in the previous position.
> Order property is not respected if set more than once

- .travis.yml
Temporarily disable deploy of next versions in order to merge a major performance refactoring of the cross-platform modules to master and stabilize it.
> Comment out deploy of next version to npm

- tns-core-modules/module.d.ts
Add __requireOverride as an optional `global` member.
Related to #3642
> Fix webpack project compilation for TypeScript 2.1.

- apps/app/ui-tests-app/layouts/main-page.ts
- apps/app/ui-tests-app/tab-view/all.xml
- tns-core-modules/ui/gestures/gestures-common.ts
- tns-core-modules/ui/gestures/gestures.android.ts
* Gestures circular dependency
* Invalid examples removed
* Added android-highlight to action bar example
> Gestures/view circ-dep and examples cleanup

- .travis.yml
Use `internal-preview` instead of `next`.
> Travis: reenable npm tag-based publish on master build.

- .travis.yml
- build/run-testsapp.grunt.js
- Use tns-core-modules-widgets@rc
- Pin to android runtime 2.5.0 since the `next` build currently has an issue that eats `console.log` messages.
> Fix the travis PR build

- apps/package.json
- gruntfile.js
- package.json
- tests/app/TKUnit.ts
- tests/package.json
- tns-core-modules/declarations.d.ts
- tns-core-modules/docs-shims.d.ts
- tsconfig.base-dts.json
- tsconfig.json
- tsconfig.typedoc.json
- Fix typings, remove Request, etc clashes with the new lib.dom.d.ts
- Use a forked build of typedoc if/until TypeStrong/typedoc#434 is accepted.
- Add `docs-shims.d.ts` to make API reference build using TypeScript 2.1 (until TypeDoc fully supports TypeScript 2.2)
> Hdeshev/typescript 2.2

- tns-core-modules/ui/text-base/text-base-common.ts
- tns-core-modules/ui/text-base/text-base.d.ts
- tns-core-modules/ui/text-base/text-base.ios.ts
- tns-core-modules/ui/text-view/text-view.ios.ts
Setting underline to none was not applied.
Setting decoration and text immediately was not applying the decoration.
> Fix text view decorations

- package.json
As usual, invoking binaries is special there. Reported by @hshristov.
> Fix tsc invocation on Windows.

- tests/app/ui/label/label-tests.ts
- tests/app/ui/view/view-tests.ios.ts
- tns-core-modules/ui/action-bar/action-bar.ios.ts
- tns-core-modules/ui/core/view/view.ios.ts
- tns-core-modules/ui/frame/frame.ios.ts
- tns-core-modules/ui/html-view/html-view.ios.ts
- tns-core-modules/ui/label/label.ios.ts
- tns-core-modules/ui/layouts/grid-layout/grid-layout.ios.ts
- tns-core-modules/ui/list-view/list-view.ios.ts
- tns-core-modules/ui/scroll-view/scroll-view.ios.ts
- tns-core-modules/ui/styling/background.ios.ts
- tns-core-modules/ui/switch/switch.ios.ts
- tns-core-modules/ui/tab-view/tab-view.ios.ts
- tns-core-modules/ui/utils.ios.ts
- tns-core-modules/utils/utils.ios.ts
Length offers both dip and px as units but px so far behaved as dip in iOS. This PR aims to resolve 1px on retina display (@2, @3) to 1/2 dip or 1/3 dip respectively. All native APIs use dip, {N} layouts work in px, some APIs like the GridLayout that support rows and columns still support just dip and as such some actual sizes return dips. Effective values are supposed to work in px. Layout rounding will now round to px even when sizes are specified in px.
> Pixels ios

- apps/app/ui-tests-app/issues/issue-2942.ts
- apps/app/ui-tests-app/issues/issue-2942.xml
- tns-core-modules/utils/utils.android.ts
- tns-core-modules/utils/utils.d.ts
Fixes:
- Android keyboard does not hide when focusing away from TextView
-  The `nativeView` parameter of `dismissSoftInput` (from `utils`) is now optional.
> FIX: Android keyboard

- tests/app/TKUnit.ts
- tests/app/ui/bindable-tests.ts
- tests/app/ui/styling/style-properties-tests.ts
- tns-core-modules/text/formatted-string.ts
- tns-core-modules/ui/button/button.android.ts
- tns-core-modules/ui/core/properties/properties.d.ts
- tns-core-modules/ui/core/properties/properties.ts
- tns-core-modules/ui/core/view-base/view-base.ts
- tns-core-modules/ui/editable-text-base/editable-text-base.android.ts
- tns-core-modules/ui/frame/frame.android.ts
- tns-core-modules/ui/text-base/text-base-common.ts
- tns-core-modules/ui/text-base/text-base.android.ts
- tns-core-modules/ui/text-base/text-base.ios.ts
- tns-core-modules/ui/text-field/text-field.android.ts
- tns-core-modules/ui/transition/transition.android.ts
TKUnit default message change to empty string
isSet method is now instance method of Property classes
fix detaching from parent bindingContext - were using oldParent.parent instead of parent
editable-text-base.android - onTextChanged implementation commented. Does nothing.
frame - onCreateView wrapped in try/catch and shows label with exception message if any
text-base.android - should support reset of nativeView. TransformationMethod won’t be set if TextField is secure
Change some types to their string couterparts
TextField.android won’t support multilines anymore in order to work as iOS
In android when page is removed from native backstack we won’t call tearDownUI again a second time
> whiteSpace default value change to undefined

- tns-core-modules/ui/core/view-base/view-base.ts
- tns-core-modules/ui/list-view/list-view.android.ts
Fix disappearing list item styles when navigating back to a page.
Clear style scope when removing views instead of the `unload` event.
> ListView disappearing styles on back navigation (Angular)

- tns-core-modules/debugger/debugger.ts
- tns-core-modules/http/http-request/http-request.android.ts
- tns-core-modules/module.d.ts
- tns-platform-declarations/android/org.nativescript.widgets.d.ts
Add calls to runtime-exposed methods to communicate with the Network Agent of Chrome DevTools inside the android `http-request` implementation. Method calls to the Network Agent will only be made in debug and when the inspector has been fired up, meaning no overhead should occur when not debugging inside DevTools or VSCode
This PR depends on a small addition in the widgets -> https://github.com/NativeScript/tns-core-modules-widgets/pull/91
> Network Agent implementation (Android)

- tns-core-modules/globals/globals.ts
Recent fixes in the android debugger forced that the same v8 (javascript) context is used in both user code execution and devtools inspector. That meant that attaching a debugger (building in debug configuration) will apply predefined properties to the global object (`console` being one). This would cause the check in `globals` module to fail when checking whether to initialize the custom implementation. 
The proposed changes ensure that the modules' console implementation will always be used when running on Android devices, while still not polluting the iOS's global object.
> Always attach console implementation on android

- tns-core-modules/globals/globals.ts
Follow up of https://github.com/NativeScript/NativeScript/pull/3815
The property that identifies the android platform is not available on the global object when snapshotting, so make sure console object is attached to global.
> Fix: attach android console implementation always when snapshot is enabled

- tns-core-modules/ui/animation/animation.android.ts
- tns-core-modules/ui/animation/keyframe-animation.ts
- tns-core-modules/ui/styling/style-scope.ts
- Not crashing when we get a LinearInterpolator for android curves.
- Always starting animations and not doing that only for fully loaded elements (nothing to start them once the element loads)
- Catch rejections in keyframe child animations to avoid unhandled rejection warnings.
Fixes NativeScript/nativescript-angular#431, NativeScript/nativescript-angular#534
> Fix several angular animation issues

- tns-core-modules/debugger/debugger.ts
Check if mimeType is defined before assuming the response's Document type.
Otherwise navigating to a page that returns no `content-type` header in the response will result in application crash.
> Android Network Agent fix

- tests/app/testRunner.ts
- tests/app/ui/styling/style-properties-tests.ts
- tns-core-modules/ui/editable-text-base/editable-text-base.android.ts
Default implementation use `setTransformationMethod` which throws exception in android. On top of that`getTransformation` is not called when user is typing so we can't change the text. A possible implementation would be to use `InputType`
> text-decoration won’t be applied to edit-text

- tns-core-modules/ui/animation/animation.android.ts
- tns-core-modules/ui/animation/animation.ios.ts
- tns-core-modules/ui/core/view/view.android.ts
Animations were always played as keyframes and kept overriding the local values. Android setAlpha has deprecated int overload, now it is guided to use the float one. Android background color was animated using css values instead of local or the keyframe one.
> Fix animation's "Reset"

- tns-core-modules/ui/action-bar/action-bar.ios.ts
Thanks to @lfabreges for making the original PR. This is the same PR as #3585, but rebased onto mater.
This small PR is useful to ensure that the titleView is reset when using multiples ActionBar on iOS. Bellow an example with angular and tabs:
First tab:
```xml
<ActionBar *ngIf="selected" class="action-bar" title="{{ 'page.home.title' | L }}">
<ActionItem (tap)="goToAdd()"
ios.systemIcon="4" ios.position="right"
android.systemIcon="ic_menu_add" android.position="actionBar">
</ActionItem>
</ActionBar>
```
Second tab:
```xml
<ActionBar *ngIf="selected" class="action-bar" title="{{ 'page.search.title' | L }}">
<SearchBar hint="Search..."></SearchBar>
</ActionBar>
```
If I navigate to the second tab, the search bar is shown, then when I navigate back to the first tab, it isn't removed, this …
> Ensure navigation title view is removed if undefined

- tns-core-modules/ui/core/view-base/view-base.ts
- tns-core-modules/ui/styling/style-scope.ts
Inital animations were not played in android, since CSS in android is now applied before the native view is created/assigned.
> Inital animations were not played in android

- tns-core-modules/ui/core/view/view.ios.ts
Note If 0 is used in the native transform the underlying matrix can not be decomposed and the animations fail.
> Setting scale to 0 in iOS was actually using 0, it will now use 1e-6

- apps/app/ui-tests-app/web-view/main-page.ts
- apps/app/ui-tests-app/web-view/query-params.ts
- apps/app/ui-tests-app/web-view/query-params.xml
- apps/app/ui-tests-app/web-view/query.html
- tns-core-modules/ui/web-view/web-view-common.ts
- tns-core-modules/ui/web-view/web-view.android.ts
- tns-core-modules/ui/web-view/web-view.ios.ts
Respect query params when setting `src` to `WebView`.
Added test page in `ui-test-app` -> `webview -> query`
It covers the following test cases:
1. `rel` - set `src` to a relative url (`"~/..."`)
2. `abs` - set `src` to a absolute url (`"/..."`)
3. `file` - set `src` to a file-prefixed url (`"file:///..."`)
4. `str` - set `src` to an html string - no query params passed in this case
CC: @SvetoslavTsenov @vchimev 
Resolves #3872.
> Web view query params

- tns-core-modules/ui/text-base/text-base.android.ts
The default value of `text-align` should be initial. This way you can reset property properly.
> Fix: TextAlign initial value

- tns-core-modules/utils/utils.d.ts
Remove `getColor` form utils.d.ts. It is no longer implemented.
Related to #3913
> Remove getColor form utils.d.ts

- tns-core-modules/ui/editable-text-base/editable-text-base-common.ts
- tns-core-modules/ui/editable-text-base/editable-text-base.android.ts
- tns-core-modules/ui/editable-text-base/editable-text-base.d.ts
- tns-core-modules/ui/editable-text-base/editable-text-base.ios.ts
- tns-core-modules/ui/enums/enums.ts
Property values should be lowercased to pass validation.
> FIX: Crash when setting autocapitalizationType=allCharacters in xml 

- Modules30Changes.md
- fix a few typos
- use `ts` for syntax highlighting of the code samples
> docs: Modules30Changes.md minor styling updates

- tests/app/file-system/file-system-tests.ts
The test is searching for `logo.png` file in the wrong place.
> Fix relative path

- tests/app/ui/styling/style-properties-tests.ts
- tests/app/ui/view/view-tests-common.ts
- tns-core-modules/ui/animation/animation.ios.ts
- tns-core-modules/ui/core/view/view-common.ts
- tns-core-modules/ui/core/view/view.android.ts
- tns-core-modules/ui/core/view/view.d.ts
- tns-core-modules/ui/core/view/view.ios.ts
- tns-core-modules/ui/styling/style-properties.d.ts
- tns-core-modules/ui/styling/style-properties.ts
- tns-core-modules/ui/styling/style/style.d.ts
- tns-core-modules/ui/styling/style/style.ts
- tns-core-modules/utils/utils.d.ts
- Lengths will now prefer to result in dip number rather than { unit: "dip", value: <dip number> } to make general computations with the stored dip easier.
- translateX/translateY will be no longer in Length, now it is in dip
- Aliased number with px, dip and percent types to indicate the expected units in several APIs.
> Revert the translateX/Y to be in dip, Length prefer number to object type

- tns-core-modules/tns-core-modules.d.ts
Remove Request enums. They are already in the `lib.dom.d.ts` of Typescript 2.3
> Remove redundant definitions

- tns-core-modules/ui/image/image.android.ts
This fix image view losing bitmap when ImageSource was set.
> ImageView clear bitmap only when src is null/undefined

- apps/app/ui-tests-app/action-bar/main-page.ts
- apps/app/ui-tests-app/action-bar/modal-page-hidden-action-bar.ts
- apps/app/ui-tests-app/action-bar/modal-page-hidden-action-bar.xml
- apps/app/ui-tests-app/action-bar/modal-page.ts
- apps/app/ui-tests-app/action-bar/modal-page.xml
- apps/app/ui-tests-app/action-bar/modal-test-hidden-action-bar.ts
- apps/app/ui-tests-app/action-bar/modal-test-hidden-action-bar.xml
- apps/app/ui-tests-app/action-bar/modal-test-with-action-bar.ts
- apps/app/ui-tests-app/action-bar/modal-test-with-action-bar.xml
- tns-core-modules/ui/frame/frame.ios.ts
Related to #4157 and #4141
Fixes action bar incorrectly updating when showing modal dialogs in IOS.
Two ui tests scenarios added in `ui-tests-app`:
* (#4141) Go to `action-bar -> modalShownActBar` page. Open and then close the modal. The action bar should be visible after closing.
* (#4157) Go to `action-bar -> modalHiddenActBar` page. Open and then close the modal. The action bar should remain hidden after closing.
CC @SvetoslavTsenov @tsonevn
> Fix: ActionBar update in IOS with modal dialogs

- tns-core-modules/ui/page/page.ios.ts
it needs to be considered for merging.
=
Before 3.0.0, Page class calls setNeedsLayout() by it self. 
After commit:6b61335675587343f053b6f6607eae9e3f7907f1. Page class belongs parent Frame class.  Frame class also calls setNeedsLayout()  on this requestLayout(). 
But in condition a Page is Modal Page , Parent Frame class can't get "nativeView.window' , so the frame class fails to call setNeedsLayout().  And child Page class doesn't call setNeedsLayout() if they have parent property(before 3.0.0, modal page doesn't have parent)
I tried to get window by UIApplication.sharedApplication().delegate.window or UIApplica.....windows.first  in Frame class, but setNeedsLayout() doesn't update modal controls.
I am not expert for ios native application. so I don't know about this behavior.
This PR is …
> Fixes ios modal layout issue #4151

- tns-core-modules/application/application-common.ts
- tns-core-modules/application/application.android.ts
- tns-core-modules/application/application.d.ts
- tns-core-modules/application/application.ios.ts
This event is launched at the latest possible moment I've found that can be used to track app start time. This event takes about 300ms in iOS and about 1 sec. more in Android than the time to "launched".
> App "displayed" event

- tns-core-modules/ui/editable-text-base/editable-text-base.android.ts
so that TextView doesn’t throw exception when Return is pressed.
Fix https://github.com/NativeScript/NativeScript/issues/4123
> Change onReturnPress to non abstract

- tns-core-modules/ui/frame/frame-common.ts
That method needs to be exposed because it's used in NativeScript Angular (https://github.com/NativeScript/nativescript-angular/blob/master/nativescript-angular/platform-common.ts#L91).
> fix(livesync): attach __onLiveSyncCore to global

- tns-core-modules/ui/button/button.ios.ts
This change switches iOS Button text alignment from using the generic `nativeView.contentHorizontalAlignment` to using the Button's `nativeView.titleLabel.textAlignment`. This change allows text in a Button to properly center align when wrapped on to multiple lines. Left and Right alignment behavior are unchanged, but using new syntax for consistency.
Fixes/Implements #4266.
> Fixing Button text alignment behavior

- apps/app/ui-tests-app/issues/issue-3354.ts
- apps/app/ui-tests-app/issues/issue-3354.xml
- apps/app/ui-tests-app/issues/main-page.ts
- tns-core-modules/ui/text-view/text-view.ios.ts
Related to #3354 
UI test added as this involves keyboard focus. Steps to reproduce in ui-tests-app:
1. Go to `issues->3354-ios`
2. Type some text in the text-view
3. Click the `clear` button. 
**Expected result:** The focus remains inside the text-view, but the text is cleared.
**Result before the fix:** The focus remains inside the text-view, however the hint text is shown instead.
cc: @SvetoslavTsenov @vchimev
> Fix: IOS text view hint should never show while editing

- tns-core-modules/package.json
In the context of a snapshot, all `__extends` calls are postpone till the app is running on device. However, some native Java classes, created by JS code, needs their JS part to be loaded early as part of the app bootstrapping because their native part is being touched by the system, e.g. `NativeScriptActivity` and `FragmentClass` (or for some other reason). In order to be properly snapshotted every {N} plugin should specify the files which contain such Java classes successors.
> Support for local snapshots

- tests/app/ui/animation/css-animation-tests.ts
- tns-core-modules/matrix/matrix.d.ts
- tns-core-modules/matrix/matrix.ts
- tns-core-modules/matrix/package.json
- tns-core-modules/ui/animation/animation.d.ts
- tns-core-modules/ui/animation/keyframe-animation.d.ts
- tns-core-modules/ui/animation/keyframe-animation.ts
- tns-core-modules/ui/styling/converters.ts
- tns-core-modules/ui/styling/css-animation-parser.ts
- tns-core-modules/ui/styling/style-properties.d.ts
- tns-core-modules/ui/styling/style-properties.ts
- tns-core-modules/ui/styling/style-scope.ts
- tns-core-modules/utils/number-utils.ts
- tns-core-modules/utils/utils-common.ts
- tns-core-modules/utils/utils.d.ts
- adds `matrix` module for converting css transform properties (the supported affinities - translate, rotate and scale) to transformation matrices. 2623925
- modifies transformation converter behavior for cases with more than one affinity of the same type (ex. `translateX(100) translateY(200)` or `scale(2) rotate(45) scale(1.5)`):
- each affinity is converted to the corresponding augmented matrix and then all matrices are multiplied (left to right). [code](https://github.com/NativeScript/NativeScript/pull/4296/files#diff-5308e29352c0da58fcb9ad6905f4e1f5R549)
- finally, the resulting matrix is [decomposed](https://github.com/NativeScript/NativeScript/pull/4296/files#diff-057b4f11a58d469d455312c92fd30c42R53) and [`TransformFunctionsInfo`](https://github.com/NativeScript/NativeScript/pull/429 …
> Refactor transform animations

- tests/app/ui/slider/slider-tests.ts
- tns-core-modules/ui/slider/slider.android.ts
The setter should invoke setNativeValuesSilently with the new value and the new
max value respectively.
fixes #4343
> fix(slider): correct maxValue setter for android 

- apps/app/devtools-app/app.css
- apps/app/devtools-app/app.ts
- apps/app/devtools-app/main-page.ts
- apps/app/devtools-app/main-page.xml
- apps/app/package.json
- tests/app/debugger/dom-node-tests.ts
- tests/app/testRunner.ts
- tns-core-modules/debugger/css-agent.ts
- tns-core-modules/debugger/devtools-elements.ts
- tns-core-modules/debugger/dom-node.ts
- tns-core-modules/ui/core/properties/properties.d.ts
- tns-core-modules/ui/core/properties/properties.ts
- tns-core-modules/ui/core/view-base/view-base.d.ts
- tns-core-modules/ui/core/view-base/view-base.ts
- tns-core-modules/ui/frame/frame-common.ts
- tns-core-modules/ui/slider/slider.d.ts
- tns-core-modules/ui/text-base/text-base.android.ts
Enable chrome devtools elements tab for android.
Supported features:
- Devtools browser is updated when views are added/deleted and upon navigation
- Devtools browser is updated on property changes
- Can see CSS computed styles
- Can update/remove attributes form devtools
- Can remove elements from devtools
Related to NativeScript/android-runtime#745 and NativeScript/android-runtime#746
Pair-codeded with @Pip3r4o
> Chrome devtools elements tab support for Android

- tns-core-modules/debugger/dom-node.d.ts
The d.ts is needed because `dom-node` is imported in `text-base.d.ts`
> fix: add dom-node declarations

- tests/app/profiling/profiling-tests.ts
Profiling tests stability fixes.
There is a dedicated perf test for start/stop. No need to test performance in the `test_start_stop` test.
> Profiling tests stability

- tests/app/timer/timer-tests.ts
- tns-core-modules/timer/timer.android.ts
- tns-core-modules/timer/timer.d.ts
- tns-core-modules/timer/timer.ios.ts
Specifications define timers capable of accepting optional parameters.
https://www.w3.org/TR/2011/WD-html5-20110525/timers.html#timers
This PR goal is to standardize such behavior in NativeScript too.
> Standard timers - fix for #4384

- .travis.yml
The {N} team's having a hard time maintaining the unit tests app execution in Travis CI.
The main problem is that PROFILING, HTTP, WEB-VIEW tests fail randomly due to timeouts, caused by the unstable environment.
The unit tests app execution remains by default on PRs in {N} Jenkins CI.
> chore(travis): do not run unit tests app in Travis

- README.md
We’re trying to make the CoC a bit more prominent on our bigger sites/repos. This idea came from @jlooper.
> Add a (hopefully) prominent link to our CoC

- tests/app/xhr/xhr-tests.ts
- tns-core-modules/xhr/xhr.ts
SOAP APIs return a content-type of "text/xml" which (on iOS) was resulting in a response body of a string-ified NSData object rather than XML. This was because "text/xml" was not recognized as a text response.
Per https://www.w3.org/TR/2000/NOTE-SOAP-20000508/#_Toc478383526
> HTTP applications MUST use the media type "text/xml" according to RFC 2376 [3] when including SOAP entity bodies in HTTP messages.
Before the fix, the included test output
`CONSOLE ERROR file:///app/tns_modules/tns-core-modules/trace/trace.js:165:30: Test: XHR.test_soap_content_types_recognized_as_text FAILED: text/xml failed to be recognized as a text response type`
After the fix, the included test output
`CONSOLE INFO file:///app/tns_modules/tns-core-modules/trace/trace.js:159:29: Test: --- …
> Fixes #4514: text/xml responses are now treated as text on iOS

- tests/app/app/mainPage.ts
These permissions are not required anymore as the app stopped writing `test-results.xml`.
I leave them commented if needed in future.
> Remove permission request from tests app

- tests/app/TKUnit.ts
- tests/app/ui/helper.ts
Disable reflection recycling tests for api levels <= 19. Too many methods throw exceptions for newly created widgets.
> Disable reflection recycling tests for api lvls 17 and 19

- tests/app/ui/text-view/text-view-tests.ts
- tns-core-modules/ui/styling/style-properties.d.ts
- tns-core-modules/ui/styling/style/style.d.ts
- tns-core-modules/ui/styling/style/style.ts
- tns-core-modules/ui/text-base/text-base-common.ts
- tns-core-modules/ui/text-base/text-base.android.ts
- tns-core-modules/ui/text-base/text-base.ios.ts
Implements #1664
Btw, added a density multiplier for Android so spacing is better aligned with iOS, as shown in this screenshot:
> Add CSS support for line-height

- tns-core-modules/ui/styling/css-selector/css-selector.d.ts
- tns-core-modules/ui/styling/css-selector/css-selector.ts
- tns-core-modules/ui/styling/style-scope.ts
The exported method is needed for NativeScript Angular's animation driver
> refactor(css-selector): export createSelector method

- tns-core-modules/xhr/xhr.ts
Implements: Provides the app with  `set-cookie` and `set-cookie2` besides `Set-Cookie` and `Set-Cookie2`, so app can implement its own cookie jar. This is useful to retain session between app start/stop cycle. 
Tests: No unit tests, because there was no unit tests for XHR Cookies initially, and the patch is trivial.
> xhr: include cookies in the XHR response header

- tns-core-modules/ui/animation/animation.android.ts
In NativeScript Angular, if the NativeScriptAnimationModule is imported in another
NgModule more than once (which shouldn't be done), the renderer will be instantiated twice. This
causes animations with empty targets to be created. If such animation is
removed, the app will crash. The additional check if the target is present
will prevent this.
> fix(animations): check if target is present before removing its animation

- apps/app/ui-tests-app/text-view/hint-text-color.xml
- tns-core-modules/ui/text-field/text-field.ios.ts
- tns-core-modules/ui/text-view/text-view.ios.ts
Original PR by @dturing (#4357):
> The Caret (blinking cursor line) in TextViews is always blue on iOS. It should be a separate CSS property, or be the same as the text color.
> 
> This had been tackled with #1013 a long time ago, but seems to have regressed?
> 
> Setting .tintColor as well as .textColor in [Line 198 of text-field.ios.ts](https://github.com/NativeScript/NativeScript/blob/master/tns-core-modules/ui/text-field/text-field.ios.ts#L198) (as seen in the commented-out line 195) seems to fix this.
> Set text-field and text-view tintColor to textColor (iOS) (fixes #4357) EXTENDED

- .gitignore
We have decided to fail as early as possible on broken dependencies so we can fix such problems as early as possible. package-lock.json will be very valuable for app and app developers but if we apply this in our repo, we risk to let issues go unnoticed.
> Git ignore package-lock.json

- tests/app/ui/view/view-tests-common.ts
- tns-core-modules/ui/core/properties/properties.ts
As part of the issue #4450 there was a problem with the shorthand properties.
Setting the transform shorthand sets the underlying translateX/Y scaleX/Y etc.
Then these smaller composite properties are individually set on animation complete.
Setting the transform shorthand again to the same value won't work as it caches the string the last time it was set and wouldn't fire change again.
> Shorthand properties does not update if sub-property is changed

- tests/app/ui/helper.ts
Some of these methods depends on the parent Layout. In the tests we are using `FlexboxLayout` as parent so items are positioned on different rectangle.
> Fix unitests on API <20

- tns-core-modules/application/application.d.ts
.. at least, that's what my IDE was screaming at me. So I created this PR to shut it up 🤐
> Commas should be semicolons in TS definition

- apps/app/ui-tests-app/tab-view/main-page.ts
- apps/app/ui-tests-app/tab-view/tab-view-icon-change.ts
- apps/app/ui-tests-app/tab-view/tab-view-icon-change.xml
- tns-core-modules/ui/tab-view/tab-view.android.ts
This is an extended version of #4606 by @NathanaelA 
Original description:
> This Fixes/Implements #4138 .
> 
> This issue has two fixes; the first is that the item is now a couple levels deeper in the hierarchy; so we have to go up a couple parents to get to the actual TabView root controller in NS 3.  
>  
> The second issue; is even though we change the itemSource value, the item assigned to this tab view was never refreshed; so we call the function that recreates the tabview item with the new values.
> Fixes TabView icons changes.

- tns-core-modules/debugger/webinspector.ios.ts
This is cherrypick of the commits by #3405 which where lost in the 2.5 -> 3.0 migration.
@pkoleva Can you verify the Chrome console eval works with this fix?
> Enable evaluating in Chrome Console (#3405)

- tns-core-modules/ui/core/view/view.android.ts
- tns-core-modules/ui/segmented-bar/segmented-bar.android.ts
- tns-core-modules/ui/styling/background.android.ts
- tns-core-modules/ui/tab-view/tab-view.android.ts
Changed all controls that were using getConstantState.
> Fix crash where some android Drawables doesn't implement getConstantState

- tests/app/image-source/image-source-tests.ts
Android API 26 generates different base64 encoded png - tests needed to be updated
> fix(image-source): Fix test for base64 image source for android API 26

- tests/app/TKUnit.ts
This should heal failing tests on Android 4.x
> FIX: Async test runner check-timeout bumped.

- tns-core-modules/platform/platform.ios.ts
This pr changes the way UUID is created on iOS because of api changes on iOS 6 version.
[iOS Documentation about this](https://developer.apple.com/documentation/foundation/nsuuid?language=objc)
Fixes #4603 .
> fix: update UUID implementation to new api introduced on IOS6

- tns-core-modules/ui/editable-text-base/editable-text-base-common.ts
- tns-core-modules/ui/editable-text-base/editable-text-base.android.ts
- tns-core-modules/ui/editable-text-base/editable-text-base.d.ts
- tns-core-modules/ui/text-field/text-field.ios.ts
- tns-core-modules/ui/text-view/text-view.ios.ts
Implements #2181 
Locally tested with a {N} 3.0 starter app with this added to the XML:
```xml
<TextField focus="{{ onFocusTextField }}"
blur="{{ onBlurTextField }}"
tap="{{ onTapTextField }}"
text="textField"/>
<TextView focus="{{ onFocusTextView }}"
blur="{{ onBlurTextView }}"
tap="{{ onTapTextView }}"
text="textView"/>
```
And this added to `main-view-model.js`:
```js
viewModel.onTapTextField = function(arg) {
console.log(">> onTapTextField: " + arg);
};
viewModel.onTapTextView = function(arg) {
console.log(">> onTapTextView: " + arg);
};
viewModel.onBlurTextField = function(arg) {
console.log(">> onBlurTextField: " + arg);
};
viewModel.onFocusTextField = function(arg) {
console.log(">> onFocusTextField: " + arg);
};
viewModel.onBlurTextView = function(arg) {
console.log(">> …
```
> Add a 'focus' event to text input fields

- tns-core-modules/debugger/debugger.ts
Fix https://github.com/NativeScript/NativeScript/issues/4419
mimeType set to "application/octet-stream" according to RFC if content-type is not specified.
See: http://mattryall.net/blog/2008/03/default-content-type, https://stackoverflow.com/questions/1176022/unknown-file-type-mime
> mimeType set to "application/octet-stream" if content-type is not specified

- tests/app/TKUnit.ts
- tests/app/testRunner.ts
This is needed for more stable CI builds. _Fresh_ emulators sometimes take too much time on initial http requests which cause tests to fail.
> Increase timeout for HTTP tests

- tns-core-modules/ui/editable-text-base/editable-text-base.android.ts
Based on this: https://developer.android.com/reference/android/widget/TextView.OnEditorActionListener.html
And assuming that the developer will run dismissSoftInput in the owner.dismissSoftInput() only if they need to.
Returning False will close the keyboard regardless.
Fixes/Implements #4858
> TextField onEditorAction should return true if developer has consumed the action

- apps/app/ui-tests-app/main-page.xml
- tests/app/testRunner.ts
- tests/app/ui/lifecycle/lifecycle-tests.ts
- tests/app/ui/lifecycle/pages/button-counter.ts
- tests/app/ui/lifecycle/pages/page-two.css
- tests/app/ui/lifecycle/pages/page-two.xml
- tests/app/ui/segmented-bar/segmented-bar-tests-native.ios.ts
- tests/app/ui/styling/style-tests.ts
- tests/app/ui/styling/value-source-tests.ts
- tns-core-modules/ui/builder/component-builder/component-builder.ts
- tns-core-modules/ui/core/properties/properties.d.ts
- tns-core-modules/ui/core/properties/properties.ts
- tns-core-modules/ui/core/view-base/view-base.d.ts
- tns-core-modules/ui/core/view-base/view-base.ts
- tns-core-modules/ui/core/view/view.android.ts
- tns-core-modules/ui/core/view/view.d.ts
- tns-core-modules/ui/dialogs/dialogs-common.ts
- tns-core-modules/ui/frame/frame-common.ts
- tns-core-modules/ui/layouts/grid-layout/grid-layout-common.ts
- tns-core-modules/ui/page/page-common.ts
- tns-core-modules/ui/page/page.d.ts
- tns-core-modules/ui/styling/style-scope.ts
- tns-core-modules/ui/styling/style/style.d.ts
- tns-core-modules/ui/styling/style/style.ts
- tsconfig.shared.json
The branch have to achieve the following objectives:
- CSS should be applied just once when a visual tree is instantiated during navigation
- Setting id or className should not trigger excessive property change notifications nor native setter calls
In the `nativescript-sdk-examples-ng`, navigation to `Color/Creating Colors` times:
|              | PageRouterOutlet.activateWith | ViewBase._addView | Total       |
| ------- | ------------------------------- | -------------------- | -------- |
| before  | 172 ms.                                        | 123 ms.                      | 295 ms. |
| after     | 127 ms.                                        | 132 ms.                      | 259 ms. |
CSS-es are now querried a little bit before onLoaded is raised, and so the CSS application is …
> Avoid applying CSS multiple times

- tns-core-modules/ui/button/button.android.ts
If you set tap gesture on a button parent (e.g. some layout for example) and set tap handler on the button and click the button there is a chance to execute navigation with clear history. This will remove current fragment and will clear the button listener owner. Still android will fire the click handler and we will throw an exception.
Fix https://github.com/NativeScript/NativeScript/issues/4897
> Added check for owner in button listener

- tns-core-modules/ui/frame/frame.android.ts
Initial transitions are ingored on android (as they are on ios) because on API 21+ Transition class requires at least one layout pass before transitions are executed. If we don't ignore it our transition handlers won't execute and frame navigation won't execute because it thinks there is a pending navigation.
Fix https://github.com/NativeScript/NativeScript/issues/4895
> Fix android navigation when there is default/initial transition on API 21+

- tns-core-modules/ui/styling/style-scope.ts
Before all properties where set on the view, and that covered some incorrectly reset animation properties. I am now resetting all animatable properties when the keyframe animations are cancelled.
Also stopping animations was not batched together with the property setters for css values, and some views appeared to flicker, moved the batch-ing to enclose the animations.
> Animations improperly reset

- tns-core-modules/ui/core/view/view.android.ts
constantState.newDrawable(nativeView.getResources()); throws exception in Java.
Fix https://github.com/bradmartin/nativescript-floatingactionbutton/issues/57
Addition to https://github.com/NativeScript/NativeScript/issues/4728
> Fix crash on API 23

- tns-core-modules/ui/frame/frame-common.ts
The PR aims to make troubleshooting of missing XML views easier. I personally find the current error very vague, and it took peeking inside the device's files to realize that the `xml` files are being referred to as `page`. The mention of `entry.moduleName`, when I have nothing of the sorts in my code made it harder even.
> fix(minor): reword missing-xml-error to be clearer

- tns-core-modules/ui/text-field/text-field.ios.ts
the attributedPlaceholder and placeholder was set following two very distinct paths.
> Fix hint color in iOS

- tns-core-modules/ui/core/view/view.ios.ts
https://github.com/NativeScript/NativeScript/issues/4804 is fixed in 3.2 but there is another bug which doesn't render borderRadius on Image element.
> Fix missing borderRadius on Image in iOS

- tns-core-modules/ui/text-base/text-base.ios.ts
> Line-height property breaks text alignment (iOS)

- tns-core-modules/ui/web-view/web-view.ios.ts
- The symptom is the app would crash when web view tries to load
certain (valid) requests.
Fixes https://github.com/NativeScript/NativeScript/issues/3328
> FIX: Checking webView.request.URL is not null before getting properties

- apps/app/navigation-app/app.css
- apps/app/navigation-app/app.ts
- apps/app/navigation-app/main-page.ts
- apps/app/navigation-app/main-page.xml
- apps/app/package.json
- tests/app/ui/helper.ts
- tests/app/ui/scroll-view/scroll-view-tests.ts
- tns-core-modules/ui/frame/fragment.android.ts
- tns-core-modules/ui/frame/fragment.transitions.android.ts
- tns-core-modules/ui/frame/fragment.transitions.d.ts
- tns-core-modules/ui/frame/frame-common.ts
- tns-core-modules/ui/frame/frame.android.ts
- tns-core-modules/ui/frame/frame.d.ts
- tns-core-modules/ui/frame/frame.ios.ts
Fix https://github.com/NativeScript/NativeScript/issues/4950
Implemented custom fragment save/restore state.
When navigating back we reverse manually transitions/animations because we no longer add them to navite backstack.
Fragment instance stored on entry.
Animation and Transition listeners now holds reference to entry instead of fragment for easier update of fragment.
Animation and Transition listeners removed when entry removed from backstack.
Animation and Transition removed from fragment when fragment activity is destroyed.
> Fix clear history transition

- tns-core-modules/ui/list-view/list-view.ios.ts
This PR addresses this issue https://github.com/NativeScript/NativeScript/issues/4916. In iOS 11 there is a new [contentInsetAdjustmentBehavior](https://developer.apple.com/documentation/uikit/uiscrollview/2902261-contentinsetadjustmentbehavior) behavior of the UIScrollView which is inherited by the ListView's UITableView. The default value of this new behavior is [automatic](https://developer.apple.com/documentation/uikit/uiscrollviewcontentinsetadjustmentbehavior/2902258-automatic) which adjusts the top offset as described by the API description: 
> Content is always adjusted vertically when the scroll view is the content view of a view controller that is currently displayed by a navigation or tab bar controller. If the scroll view is horizontally scrollable, the horizontal content …
> Fix for iOS 11 ListView top offset 

- apps/app/ui-tests-app/app.ts
- tns-core-modules/debugger/devtools-elements.common.ts
- tns-core-modules/debugger/dom-node.ts
- tns-core-modules/inspector_modules.ios.ts
This should fix crash when starting debugger in IOS
> fix: Require core modules used for inspector lazily

- apps/app/ui-tests-app/search-bar/issue-5039-view-model.ts
- apps/app/ui-tests-app/search-bar/issue-5039.ts
- apps/app/ui-tests-app/search-bar/issue-5039.xml
- apps/app/ui-tests-app/search-bar/main-page.ts
- tns-core-modules/ui/search-bar/search-bar.android.ts
This PR fixes https://github.com/NativeScript/NativeScript/issues/5039
Searching twice for the same item in the search bar leads to a bug where `submit` event won't be raised.
> Fix android search-bar bug

- package.json
- tns-core-modules/application/application-common.ts
- tns-core-modules/file-system/file-name-resolver/file-name-resolver.ts
- tns-core-modules/file-system/file-system-access.ios.ts
- tns-core-modules/http/http.ts
- tns-core-modules/image-source/image-source.d.ts
- tns-core-modules/module.d.ts
- tns-core-modules/ui/core/bindable/bindable.ts
- tns-core-modules/ui/core/view-base/view-base.ts
- tns-core-modules/ui/core/view/view-common.ts
- tns-core-modules/ui/core/view/view.ios.ts
- tns-core-modules/ui/frame/frame-common.ts
- tns-core-modules/ui/frame/frame.android.ts
- tns-core-modules/ui/frame/frame.ios.ts
- tns-core-modules/ui/styling/style-properties.ts
- tns-core-modules/ui/styling/style-scope.ts
- tns-core-modules/utils/utils-common.ts
- tns-core-modules/utils/utils.d.ts
- tns-core-modules/utils/utils.ios.ts
There is one left for ios and android:
- http -> http-request -> image-source
that can't be fixed easily and will be removed once we delete image-source module because it is obsolete anyway.
And one more for android only:
- frame -> fragment 
that could be removed if we use global object.
Updated madge version
> Fix most module cyclic references

- tests/app/ui/text-field/text-field-tests.ts
- tns-core-modules/ui/editable-text-base/editable-text-base.android.ts
Fixes https://github.com/NativeScript/NativeScript/issues/5033
When clicking next arrow on the virtual keyboard we were returning true which means we handled the event so the OS doesn't move the focus to the next item. This PR delete the `return true` when the action is `IME_ACTION_NEXT` so that next focusable item is automatically focused.
> Click next moves the focus to next focusable textfield

- tns-core-modules/ui/frame/frame.ios.ts
JS object that extend NSObject was not held into memory and was collected by gc.
Here is the stacktrace:
```
Successfully synced application org.nativescript.apps on device 5521452A-8299-42CF-83D5-E569BFCA1583.
CONSOLE LOG file:///app/ui-tests-app/app.ts:1:12: ####### ------ APP MODULES START
Class PLBuildVersion is implemented in both /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 10.3.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/AssetsLibraryServices.framework/AssetsLibraryServices (0x11d5a9cc0) and /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 10.3.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/PhotoLibraryServices.framework/PhotoLibraryServices (0x11d3c06f0). One of the two will be used. Which one is undefined. …
```
> Fix crash on iOS 

- tns-core-modules/globals/globals.ts
- tns-core-modules/module.d.ts
- tns-core-modules/ui/builder/builder.ts
- tns-core-modules/ui/builder/component-builder/component-builder.ts
- tns-core-modules/ui/styling/style-scope.ts
The web pack require can now create a dynamic require context, and that context can be fed into the modules so the .js and .css files can be loaded through web pack loaders.
Consider the following `bundle.config.js`:
```JavaScript
if (global.TNS_WEBPACK) {
// registers tns-core-modules UI framework modules
require("bundle-entry-points");
// register application modules
// This will register each xml, css, js, ts, scss etc. in the app/ folder
const context = require.context("~/", true, /page\.(xml|css|js|ts|scss)$/);
global.registerWebpackModules(context);
}
```
This will make a context for the entire app (`~/` is the `app/`) folder and recursively require all files that end in `...page.xml`, `...page.css`, `...page.ts` etc. Webpack will create a map such as:
```
var map = { …
```
> Add a globals.registerWebpackModules that can register dynamic require webpack context

- CONTRIBUTING.md
Since `up-for-grabs` label is outdated, the starting point for contributions is changed to filter by `help wanted` label.
> docs: Change up-for-grabs filter with `help wanted`

- tns-core-modules/ui/core/properties/properties.d.ts
- tns-core-modules/ui/core/properties/properties.ts
Needed for validation in the `AnimationDriver` in nativescript-angular.
> refactor: export list of valid css animation properties

- tns-core-modules/ui/list-view/list-view-common.ts
- tns-core-modules/ui/list-view/list-view.android.ts
- tns-core-modules/ui/list-view/list-view.d.ts
Following the principle of the `itemTemplateSelector`, I added an `itemIdGenerator` function that defaults to simply returning the index of the item (this is the current behaviour of the Adapter implementation for android). 
Users can set the `itemIdGenerator` to return any number as unique id for the given item (index and items). In my project I use a hash function to generate that number from a unique string property.
#4729 #4962 #4724
> Expose itemIdGenerator that can be used to generate unique ID for items on ListView

- tns-core-modules/ui/styling/background.ios.ts
UIGraphicsBeginImageContextWithOptions with scale factor 0 makes sure the device scale factor is used automatically and not 1.0
Fixes/Implements #5112.
> Fix background scale quality

- tests/app/application-settings/application-settings-tests.ts
- tns-core-modules/application-settings/application-settings.android.ts
- tns-core-modules/application-settings/application-settings.d.ts
- tns-core-modules/application-settings/application-settings.ios.ts
Fixes #4871
Changes to Application-Settings were blocking, meaning that changes would completely block the main (UI) thread until they were written to disk. This had some pretty nasty stuttering effects when saving large strings or stringified objects with Application-Settings.
On Android, calling `apply` instead of `commit`, saves changes to the in-memory cache, and starts an async save to disk. `commit` blocks and is only relevant when you actually need the return value indicating whether the disk write succeeded, which Nativescript does not care about. [source](https://developer.android.com/reference/android/content/SharedPreferences.Editor.html#apply())
> Unlike commit(), which writes its preferences out to persistent storage synchronously, apply() commits its changes to the in-memory …
> Application-Settings: Non-blocking changes

- tns-core-modules/ui/core/view-base/view-base.d.ts
- tns-core-modules/ui/core/view-base/view-base.ts
Setter:
You can set a '_templateParent' by setting node.parentNode. This won't
affect the native parent of the node.
Getter:
Returns '_templateParent', if set, or the native parent otherwise.
Reason:
This will help us remove that abstraction from nativescript-angular as
it matches the DOM Nodes API name.
> refactor: set parentNode property to ViewBase

- tns-core-modules/application/application-common.ts
- tns-core-modules/globals/globals.ts
This will let us register the app.css in webpack from a context, and potentially
have a configuration such as:
```
const appCssContext = require.context("~/", false, /^\.\/app\.(css|scss|less|sass)$/);
global.registerWebpackModules(appCssContext);
```
That will work with all of the app.css, app.scss, app.less etc. without further manual reconfiguration.
> feat: Register ./app.css instead of app.css so it can be provided by webpack context

- tns-core-modules/tns-core-modules.d.ts
Add WebpackRequire interface and append it with the require typing,
this will let us use `require.context("~/", true, /page\.(xml|js|css)/g)`
> feat: Add require.context typings

- tns-core-modules/ui/builder/builder.ts
- tns-core-modules/ui/styling/style-scope.ts
Support css files for fragments to be registered using global.registerModule
and global.registerWebpackModules.
> fix(webpack): fix fragment css not being applied with webpack

- tns-core-modules/globals/globals.ts
Currently only ```main/main-page``` and ```./main/main-page.js``` work. Enable
```./main/main-page``` and ```main/main-page.js```. Note that ```main/main-page.ts```
for TS will not work. It doesn't work without webpack too. This fixes the Tab Navigation
JS template.
> refactor(core webpack): enable more module aliases to work with webpack

- README.md
In order to make our working boards more visible, I'm adding links to the corresponding waffle.io boards in the Repositories section. 
NOTE: Since runtimes and CLI are displayed on the same board, the link for each of the 3 repos is also the same.
> chore: link waffle.io board from README

- tns-core-modules/ui/core/view/view.d.ts
- tns-core-modules/ui/core/view/view.ios.ts
- tns-core-modules/ui/page/page.ios.ts
- tns-core-modules/ui/tab-view/tab-view.ios.ts
Set `automaticallyAdjustsScrollViewInsets` of viewControllers to `false` when no scrollable content is detected inside them.
> fix(layouts): Set automaticallyAdjustsScrollViewInsets

- tns-core-modules/ui/core/view/view.ios.ts
`layoutParent` method crashes with `ProxyViewContainer` as it does not have a native view.
> fix: layoutParent crash with ProxyViewContainer

- tns-core-modules/ui/frame/frame.android.ts
Fix https://github.com/NativeScript/NativeScript/issues/5318
> fix(android-frame): recreate frame if no cached one found on app resume

- tns-core-modules/data/observable/observable.d.ts
- tns-core-modules/data/observable/observable.ts
- unit-tests/observable/observable.ts
Node has a handy one-liner method on its EventEmitter called "once".
It is similar to "on", but fires a single time and automatically unsubscribes.
> feat(observable): Implement observable .once

- tns-core-modules/application/application-common.ts
- tns-core-modules/application/application.ios.ts
- tns-core-modules/profiling/profiling.d.ts
- tns-core-modules/profiling/profiling.ts
This PR is just the iOS part of #5316.
> feat(ios): fire onDisplayed event when first frame is ready to be displayed

- tns-core-modules/ui/frame/activity.android.ts
Avoid getting a wrong intent from the main activity when the [android:launchMode](https://developer.android.com/guide/topics/manifest/activity-element.html)  is set to `singleTop` or `singleTask`.
fix issues: 
* https://github.com/NativeScript/push-plugin/issues/188
* https://github.com/NativeScript/push-plugin/issues/193
> feat: support intent replacement in the android activity

- tns-core-modules/ui/frame/frame.android.ts
- tns-core-modules/ui/tab-view/tab-view.android.ts
Force the android TabView pager adapter to detach tab fragments on TabView unloaded and to re-attach them on TabView loaded. Keeping the tab fragments attached after unload/navigate is problematic since they will try to recreate their native views on suspend/resume of the app.
This handles the scenario:
1. TabView is in a Frame.
2. Navigate to a new page.
3. Suspend/resume the app with "Don't keep activities".
4. Go back to the page with tabs.
Result: the tabs are empty.
> fix-next(android-tabview): handle tab fragments attach/detach properly

- tns-core-modules/bundle-entry-points.ts
This is required in order the XML component builder to be able to find the `ui/frame` module for the `<Frame>` element.
> fix-next: register ui/frame module in global

- tns-core-modules/css/parser.ts
- tns-core-modules/ui/styling/css-selector/css-selector.ts
- unit-tests/css/parser.ts
Typescript 2.7 introduces [stricter tuple type-checking](https://blogs.msdn.microsoft.com/typescript/2018/01/31/announcing-typescript-2-7/#fixed-length-tuples).
> refactor: Handle TS2.7 stricter tuples checks

- tests/app/ui/scroll-view/scroll-view-tests.ts
Execute all ScrollView tests inside a page with `scrollableContent = false`.  IOS 9 and 10 are setting wrong scrollable insets during navigation in pages.
> fix: Stabilise scroll-view tests for ios 9 and 10

- README.md
Add link to [NativeScript roadmap](https://www.nativescript.org/roadmap) in the Readme.
> docs: add link to NativeScript roadmap

- tests/app/app/app.ts
- tests/app/app/appRoot.xml
- tests/app/app/mainPage.ts
- tests/app/app/mainPage.xml
- tests/app/ui/page/page-tests-common.ts
- tests/package.json
- tns-core-modules/package.json
- tns-core-modules/ui/core/view/view.d.ts
- tns-core-modules/ui/frame/frame-common.ts
- tns-core-modules/ui/page/page.d.ts
- tns-core-modules/ui/page/page.ios.ts
- tns-platform-declarations/package.json
- Fixes https://github.com/NativeScript/NativeScript/issues/5323
- Fixes https://github.com/NativeScript/NativeScript/issues/5340
- Updates unit tests project for application.run(...)
- Moves showingModallyEvent/shownModallyEvent static strings from Page to View.d.ts
~~TODO: _Error: Cannot pop a Frame which is not at the top of the navigation stack._ in a scenario with root tabview when switching tabs whose tabitems contain Frames.~~
> fix-next(modal): navigation events' workflow in modal dialog scenarios Fixes #5323 #5340

- apps/app/ui-tests-app/tab-view/main-page.ts
- apps/app/ui-tests-app/tab-view/tab-view-bottom-position.xml
- tns-core-modules/ui/tab-view/tab-view-common.ts
- tns-core-modules/ui/tab-view/tab-view.android.ts
- tns-core-modules/ui/tab-view/tab-view.d.ts
- tns-platform-declarations/android/org.nativescript.widgets.d.ts
Changes:
1. Add `androidTabsPosition` property that enables positioning the tab view items `top` or `bottom`. 
2. Switch to the new [`TabViewPager`](https://github.com/NativeScript/tns-core-modules-widgets/pull/112) in order to disable swipe gestures over the content area (when  `androidTabsPosition="bottom"`.
> feat(tab-view-android): enable tabs repositioning

- tns-core-modules/ui/frame/activity.android.ts
From #5337
> Avoid getting a wrong intent from the main activity when the [android:launchMode](https://developer.android.com/guide/topics/manifest/activity-element.html)  is set to `singleTop` or `singleTask`.
> 
> fix issues: 
> * https://github.com/NativeScript/push-plugin/issues/188
> * https://github.com/NativeScript/push-plugin/issues/193
>
> feat: support intent replacement in the android activity (#5337)

- apps/app/ui-tests-app/scroll-view/main-page.ts
- apps/app/ui-tests-app/scroll-view/safe-area-root-element.xml
- apps/app/ui-tests-app/scroll-view/safe-area-sub-element.xml
- tns-core-modules/ui/core/view-base/view-base.d.ts
- tns-core-modules/ui/core/view-base/view-base.ts
- tns-core-modules/ui/core/view/view.ios.ts
- tns-core-modules/ui/scroll-view/scroll-view.ios.ts
Do not auto adjust the `ScrollView` insets, by disabling [contentInsetAdjustmentBehavior](https://developer.apple.com/documentation/uikit/uiscrollviewcontentinsetadjustmentbehavior) property, when `ScrollView` is used as a root `Page` element.
_Node:_ By default UIScrollView is auto adjusting its content inset depending on the constants indicating how safe area insets are added. This 'scrolls' the `ScrollView` under the ActionBar and the safe area when it's placed as a child of the root `Page` element:
```
<Page>
<ActionBar/>
<GridLayout>
<ScrollView/>
</GridLayout>
</Page>
>  fix(ios-layouts): switch contentInsetAdjustmentBehavior on ScrollView 

- tns-core-modules/ui/frame/frame.ios.ts
- tns-core-modules/ui/page/page.ios.ts
The problem:
Currently the entries backstack is updated on every page navigation (even if the entry is the same as the current one) which leads to unnecessary unload events.
The Solution: Prevent backstack update when navigating to the same entry ([already done for Android](https://github.com/NativeScript/NativeScript/blob/b8e0beccddbc538860ba72991e3c225fa470836f/tns-core-modules/ui/frame/frame.android.ts#L202))
> fix(ios-frame): do not update backstack when navigating the same page

- tests/app/ui/page/page-tests-common.ts
- tests/app/ui/tab-view/tab-view-tests.ts
- tns-core-modules/ui/core/view/view.android.ts
- tns-core-modules/ui/tab-view/tab-view.android.ts
Fixes #5391 
Alternative solutions that were considered but ultimately couldn't be used as they exhibited different problems on different API levels and/or in the test harness app:
- Do not force the tabview pager adapter transaction:
``` ts
class FragmentPagerAdapter extends android.support.v4.view.PagerAdapter {
// ...
finishUpdate(container: android.view.ViewGroup): void {
/*if (this.mCurTransaction != null) {
if (android.os.Build.VERSION.SDK_INT >= 24) {
(<any>this.mCurTransaction).commitNowAllowingStateLoss();
} else {
this.mCurTransaction.commitAllowingStateLoss();
this.owner._getFragmentManager().executePendingTransactions();
}
this.mCurTransaction = null;
}*/
if (this.mCurTransaction != null) {
(<any>this.mCurTransaction).commitAllowingStateLoss();
this.mCurTransaction = null;
}
} …
```
> fix-next(modal) fix crash when closing modal dialog with root tabview Fixes #5391

- tns-core-modules/ui/action-bar/action-bar-common.ts
- tns-core-modules/ui/action-bar/action-bar.android.ts
- tns-core-modules/ui/action-bar/action-bar.d.ts
- tns-core-modules/ui/action-bar/action-bar.ios.ts
**The problem**: Cannot hide back button when navigating between pages with transition. The problem occurs because of the native fade-in/fade-out animation of the back button.
**The solution**: Disable back button animation when transitioning between pages. Animation should occurs only on manual `NavigationButton` visibility change
Fix https://github.com/NativeScript/NativeScript/issues/5406
Fix https://github.com/NativeScript/nativescript-angular/issues/1194
> fix(ios-action-bar): NavigationButton cannot be hidden

- tns-core-modules/debugger/devtools-elements.common.ts
The devtools module polutes the log when debugging a iOS app with: tns debug ios --inspector --debug-brk. See issue: https://github.com/NativeScript/ios-runtime/issues/887, https://github.com/NativeScript/ios-runtime/issues/886
The devtools module does not log each attempt to resolve the topmost frame anymore. The polling is silent up until the frame is resolved.
> fix(inspector): Fix --debug-brk issue with Inspector

- tests/app/navigation/reset-root-view-tests.ts
- tests/app/testRunner.ts
- tests/app/ui/helper.ts
- tests/app/ui/tab-view/tab-view-root-tests.ts
- tns-core-modules/ui/frame/frame.android.ts
- tns-core-modules/ui/frame/frame.ios.ts
- tns-core-modules/ui/tab-view/tab-view.ios.ts
* Add an executePendingTransactions() call to resetRootView, so that current transactions are executed properly. Add a test for this.
* [iOS] execute the Frame setCurrent() method only if the entry has changed, so that navigatedTo and navigatedFrom events are fired properly.
* [iOS] assign the willSelectViewController to tab pages on selectedIndexChanged, so that navigatingFrom isn't thrown if using the property directly.
> fix-next: ensure proper events on tab change

- tns-core-modules/ui/frame/frame.ios.ts
**The problem**: NavigationButton (a.k.a back button) won't change its title on first navigation when there 
is no transition animation - iOS 11+ only.
**The solution**: Set empty back button title on the parent view controller when navigating
For reference: [stackoverflow1](https://stackoverflow.com/questions/44815042/uinavigationcontroller-back-button-doesnt-hide-title-on-ios-11)  and  [stackoverflow2](https://stackoverflow.com/questions/1449339/how-do-i-change-the-title-of-the-back-button-on-a-navigation-bar) 
Fix https://github.com/NativeScript/NativeScript/issues/5169
> fix(ios-action-bar): NavigationButton text change on first navigation

- tns-core-modules/image-source/image-source.ios.ts
the current implementation does not work if one specifies "jpg", it works only with "jpeg" due to the || syntax used before. 
fixes #4873
Using "jpg" as image format spectification does not work as expected on ios.
"jpg" can be used the same as "jpeg".
Fixes/Implements/Closes #4873.
> fix(image-source.ios): case statement, allow jpg and jpeg

- tests/app/ui/page/modal-tab-page.ts
- tests/app/ui/page/modal-tab-page.xml
- tests/app/ui/page/modal-tab-root.ts
- tests/app/ui/page/modal-tab-root.xml
- tests/app/ui/page/page-tests-common.ts
- tns-core-modules/ui/core/view-base/view-base.ts
- tns-core-modules/ui/frame/frame-common.ts
- Revises and generalizes fix for https://github.com/NativeScript/NativeScript/issues/5340
- Add test for the more general modal tab with frame scenario
> fix(frame): add generic frame cleanup logic after modal dialog close

- tns-core-modules/application/application-common.ts
Catching the error will prevent bundling with snapshot to fail with:
```
com is not defined
```
> fix: throw if global css file is not found in webpack context

- tests/app/testRunner.ts
- tests/app/ui/helper.ts
- tests/app/ui/root-view/mymodule/MyControl.css
- tests/app/ui/root-view/mymodule/MyControl.ts
- tests/app/ui/root-view/mymodule/package.json
- tests/app/ui/root-view/reset-root-view-tests.ts
- tests/app/ui/root-view/root-modules/custom-component-root.css
- tests/app/ui/root-view/root-modules/custom-component-root.xml
- tests/app/ui/root-view/root-modules/gridlayout-root.css
- tests/app/ui/root-view/root-modules/gridlayout-root.xml
- tests/app/ui/root-view/root-modules/tabview-root.css
- tests/app/ui/root-view/root-modules/tabview-root.xml
- tests/app/ui/root-view/root-view-tests.ts
- tns-core-modules/ui/builder/builder.ts
When RadSideDrawer from the Pro UI suite is used as a root of the app and there is an .css file for that module, it is not applied for the drawer's `.drawerContent`.
The .css file is applied to the RadSideDrawer's `.drawerContent` content when the component is used as a root element.
https://github.com/telerik/nativescript-ui-feedback/issues/507
> fix-next(css): CSS not applied to "drawerContent" when RadSideDrawer is used as root

- apps/app/ui-tests-app/modal-view/login-page.xml
- tns-core-modules/ui/core/view/view.android.ts
- tns-core-modules/ui/tab-view/tab-view.android.ts
Fixes https://github.com/NativeScript/NativeScript/issues/5392
See comments below.
~~In a modal dialog scenario with root tabview inside, the DialogFragment content at some point is set via PhoneWindow.setContentView(view) call where `view` is the gridLayout root element of the tabview. This results in `setContentView(view, new ViewGroup.LayoutParams(MATCH_PARENT, MATCH_PARENT))` call that unconditionally overwrites the default instance of CommonLayoutParams attached to the gridLayout by us. As the default setter essentially created `new ViewGroup.LayoutParams(LayoutParams.MATCH_PARENT, LayoutParams.MATCH_PARENT, Gravity.FILL)` we lose the Gravity.FILL setting and that prevents the gridLayout from stretching horizontally so tab item titles do not distribute the excess whitespace among …
> fix-next(tabview): fix tab title layout in modal root tabview Fixes #5392

- tns-core-modules/ui/image/image-common.ts
- tns-core-modules/ui/image/image.android.ts
Currently `decodeWidth` and `decodeHeight` properties accept values as pixels which can lead to confusion and poor picture quality in some scenarios. 
From now on `decodeWidth` and `decodeHeight` can be used in the following way:
- `decodeHeight="200"` - will be converted to DIP
- `decodeHeight="200dip"` - will be converted to DIP
- `decodeHeight="200px"` - used as exact pixels with no convertion.
BREAKING CHANGE: change decodeHeight/decodeWidth properties from accepting exact pixels to device independent pixels (DIP) by default.
> fix(android-images): set decodeHeight/decodeWidth default values to dip

- tests/app/ui/animation/animation-tests.ts
- tns-core-modules/ui/animation/animation-common.ts
- tns-core-modules/ui/animation/animation.android.ts
- tns-core-modules/ui/animation/animation.ios.ts
- tns-core-modules/ui/animation/keyframe-animation.ts
Fixes cause of crashes/bugs in production apps using animation.
Developers create apps using animation library and under normal circumstances and well coded scenarios the app will `throw` when navigating or other normal app usage causing bugginess.
Developers can now see the warning in the console when developing if tracing is enabled to let them know but keep their app stable.
See screenshot of Crashlytics reports on this.
/cc @atanasovg @vakrilov @sis0k0 @DickSmith
> fix(animations): change throw -> trace to avoid unnecessary app crash

- tests/app/image-source/image-source-tests.ts
- tns-core-modules/image-source/image-source.d.ts
- tns-core-modules/image-source/image-source.ios.ts
Normalize quality in saveToFile and toBase64String to follow 0-100 scale - standardize implementation on both platforms
closes #5474
quality parameter in image-source follows different scales for both the platforms. On iOS it goes from 0.0-1.0 and on Android it goes from 0-100. Developer needs to manually check for platform when using quality.
iOS implementation of image-source toBase64String and saveToFile now normalizes the quality scale so that both the platforms follow the same scale from 0-100. For iOS the values of 0-100 are converted to a scale of 0.0-1.0.
Fixes/Implements/Closes #[5474].
> feat(ios-image-source): standardize quality scale in image-source 

- package.json
- tests/app/ui/frame/frame-tests-common.ts
- tns-core-modules/ui/frame/frame-common.ts
- tns-core-modules/ui/frame/frame.android.ts
- tns-core-modules/ui/frame/frame.d.ts
- tns-core-modules/ui/tab-view/tab-view.android.ts
- tns-core-modules/ui/tab-view/tab-view.ios.ts
Rework the frame api to support working with multiple Frames.
* frameModule.topmost() - now returns the last navigated Frame or
the currently selected tab item's Frame if the tab item's view is a
Frame.
* frameModule.getFrameById(id: string) - returns a navigated Frame by id.
* args.object.page.frame - can be used in page elements event handlers.
Returns the Frame of the current element's page.
Related to https://github.com/NativeScript/NativeScript/issues/5407
> feat(frame): rework frame retrieval api

- tns-core-modules/ui/core/view/view-common.ts
- tns-core-modules/ui/core/view/view.android.ts
- tns-core-modules/ui/core/view/view.d.ts
- tns-core-modules/ui/frame/frame.android.ts
- tns-core-modules/ui/tab-view/tab-view.android.ts
Expose method on View class onBackPressed(). Third party controls
like RadSideDrawer can use this method to override the default Android
back button handling. By default the app closes.
> feat(view): expose method for android back override

- e2e/modal-navigation/e2e/e2e-spec-tab-root/tab-root-modal-frame.e2e-spec.ts
- e2e/modal-navigation/e2e/e2e-spec-tab-root/tab-root-modal-page.e2e-spec.ts
- e2e/modal-navigation/e2e/e2e-spec-tab-root/tab-root-modal-tab.e2e-spec.ts
- e2e/modal-navigation/package.json
- e2e/modal-navigation/tsconfig.json
- tns-core-modules/ui/frame/frame.android.ts
Problem:
When we reset root view and minimize/restore application with "Don't keep activities" turned ON, we try to restore the latest fragment. However, it is not available anymore, so could not be restored. In this case, remove it when changing root view in order to create a new one.
Steps to reproduce:
- run the [modal-navigation](https://github.com/NativeScript/NativeScript/tree/vchimev/reset-root-view/e2e/modal-navigation) app
- turn on  the "Don't keep activities" setting in the Developer options for Android
- tap on "Change root view" to set `TabView` as the application root
- minimize and restore application
Stack trace:
```
System.err: Error: Cannot find Frame for NO ENTRY, FragmentClass{f14f72e #0 id=0x1 fragment0[0]}
System.err: File: …
```
> fix-next(frame): remove current entry fragment on reset root view

- tns-core-modules/ui/text-base/text-base.ios.ts
NOTE: Cherry-picked from https://github.com/NativeScript/NativeScript/pull/5251 due to CI infrastructure issues with the original PR.
When setting line-height using a stylesheet, line break mode will stop working.
__Working line break mode:__
https://play.nativescript.org/?template=play-ng&id=3HPeu8
__Now adding a style to home.component.css:__
```css
Label {
line-height: 1;
}
```
__Results in broken line break mode:__
https://play.nativescript.org/?template=play-ng&id=3HPeu8&v=5
My Pull Request fixes this behavior.
> fix(uilabel): line height setter should not break line break mode

- tns-core-modules/ui/image/image.ios.ts
NOTE: Cherry-picked from https://github.com/NativeScript/NativeScript/pull/5266 due to CI infrastructure issues with the original PR.
Fixes #4778 
Previously image was reset on every second call to setTintColor, which led to some weird behavior on iOS. Especially since setTintColor could be called many times, when set through property or style.
It now only resets image to non-template when tintColor is changed to a non-color value (e.g. removed).
NOTE: Fix for Android Image.tintColor here: https://github.com/NativeScript/tns-core-modules-widgets/pull/110
> fix(image): apply tintColor correctly on iOS

- tests/app/image-source/image-source-tests.ts
- tns-core-modules/image-asset/image-asset-common.ts
Additional fix for https://github.com/NativeScript/tns-core-modules-widgets/pull/115 to cover the scenario with ImageSource.fromAsset(...) that does not go through the widgets logic.
> fix(image): image aspect dimensions for ImageSource.fromAsset(...)

- tns-core-modules/ui/editable-text-base/editable-text-base-common.ts
- tns-core-modules/ui/editable-text-base/editable-text-base.android.ts
- tns-core-modules/ui/text-base/text-base-common.ts
- tns-core-modules/ui/text-base/text-base.android.ts
- tns-core-modules/ui/text-base/text-base.d.ts
- tns-core-modules/ui/text-base/text-base.ios.ts
Instead of using -1 as a special value, use Symbol(-1)
so that it can't be reset accidentally
Closes issue #5559
https://github.com/NativeScript/NativeScript/issues/5559
Replaced -1 with Symbol(-1) so that it reset can't be set accidentally
#5556
> fix(android/text ios/text): allow -1 to be a valid binding value

- tns-core-modules/bundle-entry-points.ts
Currently webpack fails if app is using wrap layout since it is not registered here. Registering it manually in the app works as a workaround, but still I think it would be nice to have it here by default.
> fix(webpack): register wrap layout

- apps/app/ui-tests-app/list-view/scrolling-and-sizing.xml
- tns-core-modules/ui/list-view/list-view-common.ts
- tns-core-modules/ui/list-view/list-view.d.ts
- tns-core-modules/ui/list-view/list-view.ios.ts
`iosEstimatedRowHeight` property sets [estimatedRowHeight](https://developer.apple.com/documentation/uikit/uitableview/1614925-estimatedrowheight) of the UITableView which forces the ListView to auto-measure its items.
Setting `iosEstimatedRowHeight="0"` can easily resolve [issue](https://github.com/NativeScript/NativeScript/issues/3818)
> feat(ios-list-view): introduce iosEstimatedRowHeight property.

- tests/app/ui/list-view/list-view-tests.ts
- tns-core-modules/ui/core/view/view.ios.ts
- tns-core-modules/ui/dialogs/dialogs.ios.ts
- tns-core-modules/ui/list-view/list-view.ios.ts
tns-core-modules@4.0 require iOS9 or later due to the UILayoutGuide usage so we no longer need the iOS8 (and lower) checks in the codebase.
> refactor(ios): clean up iOS8 or lower specific checks in codebase

- tns-core-modules/ui/core/view/view.d.ts
Move the onBackPressed() definition out of the `//@private` -- `//@endprivate` scope, so that it is not trimmed on build.
> chore(view): expose onBackPressed in d.ts

- e2e/modal-navigation/app/app.ts
- e2e/modal-navigation/app/home/home-page.ts
- e2e/modal-navigation/app/home/home-page.xml
- e2e/modal-navigation/app/layout-root.xml
- e2e/modal-navigation/app/modal-layout/modal-layout.ts
- e2e/modal-navigation/app/modal-layout/modal-layout.xml
- e2e/modal-navigation/e2e/screen.ts
- tns-core-modules/ui/core/view/view-common.ts
- tns-core-modules/ui/core/view/view.android.ts
- tns-core-modules/ui/core/view/view.d.ts
- tns-core-modules/ui/frame/frame-common.ts
- tns-core-modules/ui/frame/frame-stack.ts
- Delegate back navigation handling to the topmost Frame, if it's a child of the current View, to prevent closing modal view or app termination.
- Introduce `FrameStack` module to handle `frameStack` access and avoid circular dependencies (`topmost(), _pushInFrameStack()` etc) 
- Add tests where the root modal element is common layout (`GridLayout/StackLayout` eg.)
> feat(frame): handle back navigation when common layout is used as a root element

- tns-core-modules/ui/core/view/view.ios.ts
__The problem__: Empty modal view when using common layout (`GridLayout/StackLayout` e.g.) as a root element.
__The solution__: The `UIView` was not added as a child of the `UIViewController`
_e2e/modal-navigation tests already available for this scenario_
> fix-next(ios-modal): fix empty modal view when using common layout as root

- apps/app/ui-tests-app/search-bar/issue-5655.xml
- apps/app/ui-tests-app/search-bar/main-page.ts
- tns-core-modules/ui/search-bar/search-bar.ios.ts
Apparently iOS11 SDK does not support passing sizeThatFits(...) non-finite width value any more.
In a scenario where searchbar should be auto-sized(grid with auto column) our [measure logic](https://github.com/NativeScript/NativeScript/blob/9717bbf8477052a6306fd09c55efc58399141d82/tns-core-modules/ui/core/view/view.ios.ts#L125) always [passes infinity values](https://github.com/NativeScript/NativeScript/blob/9717bbf8477052a6306fd09c55efc58399141d82/tns-core-modules/utils/utils.ios.ts#L38) in case layout mode is unspecified so we extend the UISearchBar widget and add the fix there.
- Fixes https://github.com/NativeScript/NativeScript/issues/5655
- Added test page in UI tests app (/search-bar/issue-5655.xml) with the following output:
> fix(ios-searchbar): fix crash with auto-sized searchbar in iOS11 Fixes #5655

- tests/app/ui/core/weak-event-listener/weak-event-listener-tests.ts
with the v8 6.5 the GC does not release WeakRefs so fast if you pass them to a method
that's why we are making the call to the addWeakEventListener in a closure so that the WeakRef will be easier released
> Updated weak event listener tests for v8 6.5

- tns-core-modules/connectivity/connectivity.android.ts
- tns-core-modules/connectivity/connectivity.d.ts
When calling getConnectionType on an emulator, the connection type can be returned as "ethernet", which causes getConnectionType to return none when there is a connection.
2 failed on emulator un-releated to the connectivity code being changed here
To the extent to match the existing connectivity test
If the connection type is "ethernet" getConnectionType will return none.
If the connection type is "ethernet" getConnectionType will properly return the "ethernet" connection type
Fixes/Implements/Closes #5669.
> fix(android-connectivity): Add ethernet connection type

- tns-core-modules/ui/frame/frame.android.ts
Fixes https://github.com/NativeScript/NativeScript/issues/5674
Fixes Android Lollipop (API Level 21 and 22) crash on changing activity context (e.g. starting external activity with `utils.openurl(...)` call or minimizing app) after navigation with animated transition has been executed within the app.
> fix(android): crash on changing activity context after animated navigation Fixes #5674

- tns-core-modules/ui/core/view-base/view-base.d.ts
- tns-core-modules/ui/core/view/view.d.ts
It seems we released the new `showModal(...)` API with incomplete d.ts metadata. This causes a problem in the following scenario where at the moment an additional type checking is needed: https://github.com/NativeScript/nativescript-angular/pull/1293
> chore(modal): update d.ts for showModal(...) parameters

- tns-core-modules/debugger/debugger.ts
- tns-core-modules/debugger/dom-node.ts
In the upcoming release of the android-runtime the V8 engine will be upgraded to the latest stable version _6.6.346.23_. In this version some changes have been introduced to the inspector protocol and more specifically a couple of new fields have been made required.
The runtime sets default values to those fields if not provided but it would be more appropriate if the modules could pass them.
> Add required inspector fields for Elements and Network

- apps/app/ui-tests-app/tab-view/main-page.ts
- apps/app/ui-tests-app/tab-view/tab-view-tab-text-font-size.xml
- tns-core-modules/ui/styling/style/style.d.ts
- tns-core-modules/ui/styling/style/style.ts
- tns-core-modules/ui/tab-view/tab-view-common.ts
- tns-core-modules/ui/tab-view/tab-view.android.ts
- tns-core-modules/ui/tab-view/tab-view.d.ts
- tns-core-modules/ui/tab-view/tab-view.ios.ts
- tns-platform-declarations/android/org.nativescript.widgets.d.ts
Allow setting tab titles font size without changing the font size of all contents of the tab. The basic font-size css property is inherited and changes the contents of the tabs.
> feat(tabview): add tab text font size property

- tns-core-modules/application/application.android.ts
To avoid early GC which will trigger MarkReachableObjects on startup I'm storing some callback locally which are cleared once they are not needed anymore.
> keep some variable from early GC to speed up start time

- tns-core-modules/ui/styling/gradient.d.ts
- tns-core-modules/ui/styling/linear-gradient.ts
- TypeScript < 2.8.* will throw compile time error when resolving `/ui/styling/linear-gradient.js` without `--allowJs` flag. 
- There should be definition file for `linear-gradient` since it's a public API.
> fix(styling-gradient): introduce gradient definition file

- apps/app/ui-tests-app/events/layout-changed-event.ts
- apps/app/ui-tests-app/events/layout-changed-event.xml
- apps/app/ui-tests-app/events/main-page.ts
- tests/app/ui/helper.ts
- tests/app/ui/tab-view/tab-view-root-tests.ts
- tests/app/ui/view/view-tests-layout-event.ts
Extending time for layoutChanged event tests, since it could be fired later compared to other events
> chore(layout-changed): update layoutChanged event tests delay

- tns-core-modules/ui/frame/fragment.transitions.android.ts
Reference: https://developer.android.com/preview/restrictions-non-sdk-interfaces
Android P introduces new restrictions on the use of non-SDK interfaces, whether directly, via reflection, or via JNI. These restrictions are applied whenever an app references a non-SDK interface or attempts to obtain its handle using reflection or JNI.
In particular, fallback default transition to fade transition.
We use reflection to obtain a non-SDK interface and initialize default transition.
Fallback default transition to fade transition.
Fixes https://github.com/NativeScript/NativeScript/issues/5798.
> fix: crash at application launch on Android P

- e2e/modal-navigation/app/home/home-page.ts
- e2e/modal-navigation/app/home/home-page.xml
- e2e/modal-navigation/app/layout-root.ios.ts
- e2e/modal-navigation/app/layout-root.ios.xml
- e2e/modal-navigation/app/modal-no-page/modal-no-page.ts
- e2e/modal-navigation/app/modal-no-page/modal-no-page.xml
- e2e/modal-navigation/app/modal/modal-page.ts
- e2e/modal-navigation/app/modal/modal-page.xml
- tns-core-modules/ui/core/view/view.d.ts
- tns-core-modules/ui/core/view/view.ios.ts
- tns-core-modules/ui/dialogs/dialogs.ios.ts
Fix https://github.com/NativeScript/NativeScript/issues/5879
**The original problem** occurred in an Angular app (Plugins team teamplate), that displays some dialogs inside modal view, bacause [we are no longer wrapping modal view inside a Page in nativescript-angular@next](https://github.com/NativeScript/nativescript-angular/pull/1298/commits/0b965a4b4cc9d6c198fb94977dba75f153f565f4).
This could also happen in a non Angular application (modal view without `<Page>`) 
**The solution** is to search up in the hierarchy for a parent with UIViewController on which we should present the dialog.
Added test in modal-navigation app that opens dialog from modal view (with and without wrapping modal view content in Page)
> fix(ios-dialogs): unable to show dialog from modal view without a page

- tests/app/ui/tab-view/tab-view-root-tests.ts
- tests/package.json
- tns-core-modules/ui/tab-view/tab-view.ios.ts
On iOS TabView the initial load didn't set topmost frame correctly.
> fix(ios): set current tab as topmost frame on load

- tns-core-modules/http/http.ts
- tns-core-modules/ui/image/image-common.ts
closes https://github.com/NativeScript/nativescript-angular/issues/851
addresses part of https://github.com/NativeScript/NativeScript/issues/3381
Apps fail when this error occurs.
Developers can now have a meaningful and productive debugging session to make great apps. Error is now properly caught and with tracing enabled with `Debug` category developers may now easily pick up these types of issues.
closes https://github.com/NativeScript/nativescript-angular/issues/851
addresses part of https://github.com/NativeScript/NativeScript/issues/3381
> fix(Image): catch Response content may not be converted to an Image

- tns-core-modules/ui/frame/frame.android.ts
It's a bit of a blind fix since I can't reproduce this issue. The scenario should be with racing between navigation and the activity destroy/recreate (with the native back button or don't keep activities and restore). The idea is to tear down the native UI in current/navigating entries while still caching the new entry, so that the app continues from the same entry once the activity is recreated. 
Examining the latest changes [here](https://github.com/NativeScript/NativeScript/commit/4e74c3731376179ff1b72305b982d0937e3415c6#diff-c1ad77120477acf9bacdaabe6af2518d) shows that the bool flags were moved to the end of the block. The current entry flag was moved without the guard.
Fixes https://github.com/NativeScript/NativeScript/issues/5614
> fix(android): prevent error during tear down

- tests/app/ui/action-bar/action-bar-tests.android.ts
- tns-core-modules/ui/action-bar/action-bar.android.ts
The navigation button for the vision-impaired users were always read as:
"Button" by the TalkBack service on Android.
Fixes #5948
None to my knowledge
[Describe the impact of the changes here.]
Sets navigation content description with the value of NavigationButton.text on android.
Adds a test.
Migration steps:
Not required but NavigationButton property text should be set for the benefit of the vision-impaired users.
> fix(android): NavigationButton was read as "Button" by screenreaders.

- tests/app/ui/tab-view/tab-view-root-tests.ts
These tests fail on Android api19 only with waitUntilReady timeout. 5 seconds is the max timeout of the tests themselves.
> test(): add more timeout to tab navigations tests

- gruntfile.js
`platforms` folder is still excluded from the built NPM package
`platforms` folder is now being added by `grunt` build
> fix(grunt): Add platforms folder to produced NPM package

- tns-core-modules/ui/animation/keyframe-animation.ts
Reuse the already created animation objects in a keyframe animation on next iterations.
https://github.com/NativeScript/NativeScript/issues/5731
> fix(animations): avoid steady mem consumption rise

- tsconfig.typedoc.json
> ignore transition-definitions.android.d.ts from typedoc

- tests/app/http/http-tests.ts
Related to https://github.com/NativeScript/tns-core-modules-widgets/pull/128
@SvetoslavTsenov Currently we are not executing unit tests that have external dependencies (like http tests) -- we need to resolve this one way or another (either change external service, or introduce local server, etc.)
> chore: add test for http gzip request

- tns-core-modules/ui/frame/frame.android.ts
This is a workaround for the issue with `@ngtools/webpack@6.1.0-rc.2`, described here: https://github.com/NativeScript/nativescript-dev-webpack/issues/607#issuecomment-405209925
> fix: require devtools-elements.js with the extension mentioned explicitly

- CHANGELOG.md
- tns-core-modules/globals/globals.ts
- tns-core-modules/package.json
- tns-core-modules/ui/frame/frame.android.ts
- fix: require devtools-elements.js with the extension mentioned explicly
This is a workaround for the issue with `@ngtools/webpack@6.1.0-rc.2`, described here: NativeScript/nativescript-dev-webpack#607 (comment)
- chore: Fix TS transpile error with 2.9 (#5906)
> release: cut the 4.1.1 release

- tns-core-modules/ui/time-picker/time-picker.ios.ts
Fix for the TimePicker's `minuteInterval` property not working on iOS. 
Fixes [https://github.com/NativeScript/NativeScript/issues/4662](https://github.com/NativeScript/NativeScript/issues/4662)
> fix: iOS TimePicker minuteInterval property

- tests/app/image-source/image-source-tests.ts
- tns-core-modules/image-asset/image-asset-common.ts
- tns-core-modules/image-asset/image-asset.d.ts
- tns-core-modules/image-asset/image-asset.ios.ts
- tns-core-modules/image-source/image-source.ios.ts
__iOS Specific__: Currently `imageSource.fromAsset` returns an ImageSource that is automatically rescaled with the scale factor of the devices's main screen (depending on the Retina display 1x/2x/3x). This results in bigger images even if the user has specified an explicit `width/height` (inside`ImageAsset` options). See this [issue](https://github.com/NativeScript/NativeScript/issues/6011) for reference. 
Changes:
- Introduce `autoScaleFactor` option for `ImageAssetOptions` that can disable auto scaling.
_NOTE:`autoScaleFactor` remains `true` by default_
- Reduce default JPEG compression quality to 0.9 to lower final image size ([see this for more info on the topic](https://stackoverflow.com/questions/26330492/what-should-compressionquality-be-when-using-uiimagejpegrepresentation)
- …
> feat(image-asset-ios): add autoScaleFactor option to switch auto scaling

- tests/app/navigation/custom-transition.android.ts
- tns-core-modules/application/application.android.ts
- tns-core-modules/application/application.d.ts
- tns-core-modules/ui/core/view/view.android.ts
- tns-core-modules/ui/core/view/view.d.ts
- tns-core-modules/ui/editable-text-base/editable-text-base.android.ts
- tns-core-modules/ui/frame/activity.android.ts
- tns-core-modules/ui/frame/fragment.android.ts
- tns-core-modules/ui/frame/fragment.transitions.android.ts
- tns-core-modules/ui/frame/fragment.transitions.d.ts
- tns-core-modules/ui/frame/frame.android.ts
- tns-core-modules/ui/frame/frame.d.ts
- tns-core-modules/ui/page/page.android.ts
- tns-core-modules/ui/tab-view/tab-view.android.ts
- tns-core-modules/ui/transition/fade-transition.android.ts
- tns-core-modules/ui/transition/flip-transition.android.ts
- tns-core-modules/ui/transition/slide-transition.android.ts
- tns-core-modules/ui/transition/transition.android.ts
- tns-core-modules/ui/transition/transition.d.ts
- tns-core-modules/ui/transition/transition.ios.ts
- tns-core-modules/utils/utils.android.ts
Switch Android Activity/Fragment/FragmentManager to support library APIs (guideline from Google that this is the way to go as they are deprecating framework fragments from Android P onwards).
Note that migrating to support library FragmentManager implies the rather tedious switch from Animators to Animations API as well (as the [supportlib manager](https://android.googlesource.com/platform/frameworks/support/+/cef09fe/v4/java/android/support/v4/app/FragmentManager.java) only works with Animations).
This should facilitate/enable future Android work with Material Design, shared element transitions, etc.
Fixes https://github.com/NativeScript/NativeScript/issues/5785
Related to https://github.com/NativeScript/NativeScript/pull/5789
BREAKING CHANGE:
NativeScript core framework now extends …
> feat(android): migrate to support library apis

- tns-core-modules/ui/frame/fragment.transitions.android.ts
- tns-core-modules/ui/frame/fragment.transitions.d.ts
- tns-core-modules/ui/frame/frame.android.ts
Fixes `Error: java.lang.CloneNotSupportedException: Class android.support.v4.app.FragmentManagerImpl$AnimationOrAnimator doesn't implement Cloneable` in specific projects.
I was able to reproduce the problem when added the firebase plugin to a working hello-world app (cli next, android runtime next, tns-core-modules next). The root of the problem is the fact that different versions of the support library expose different API for android.support.v4.app.FragmentManagerImpl.loadAnimations(...) -- one returns Animation, the other AnimationOrAnimatior (that is not cloneable). Might be related to 
https://github.com/NativeScript/nativescript-cli/issues/3773 as we are really unsure which support library version is used (and why).
Related to #5785
Related to #6129 
BREAKING CHANGE
Before:
Default …
> fix(android): suppress reflection for default animations

- tns-core-modules/xhr/xhr.ts
enabling `reportProgress` property for NativeScirpt Angular's HTTPClient
> enabling reportProgress property for NativeScirpt Angular's HTTPClient

- tns-core-modules/ui/core/view/view.android.ts
Behavior does not change but casting this to `android.support.v4.app.FragmentActivity` is semantically more correct as this is the base class where getSupportFragmentManager() is implemented.
Related to https://github.com/NativeScript/NativeScript/pull/6129
> refactor: update getSupportFragmentManager cast

- tns-core-modules/connectivity/connectivity.android.ts
- tns-core-modules/connectivity/connectivity.d.ts
Related to [https://github.com/NativeScript/NativeScript/issues/6158](https://github.com/NativeScript/NativeScript/issues/6158)
Added [Bluetooth](https://developer.android.com/reference/android/net/ConnectivityManager#TYPE_BLUETOOTH) as `connectivityType`.
> feat(android): add Bluetooth connectivity type for Android

- CONTRIBUTING.md
- tns-core-modules/package.json
- tns-platform-declarations/package.json
Merge tag `4.2.0` - the latest tag respected by the `conventional-changelog` tool as *previousTag* and returned by `git describe --tags`.
The versions of packages in `master` to reflect the `latest` official release in `npm`.
Bumping up versions will execute in CI job through the `npm --no-git-tag-version version minor` command with this [pull request](https://github.com/NativeScript/jenkins/pull/39).
Add *Releasing new versions* section to `CONTRIBUTING.md` on how to bump versions, tag releases and generate changelogs for **NativeScript Core Team Members**.
This is to unify the release process across the `NativeScript`, `nativescript-angular` and `nativescript-dev-webpack` repositories.
Documentation of the [`npm version`](https://docs.npmjs.com/cli/version) command.
>  chore: add npm version script

- apps/app/ui-tests-app/list-view/item-re-layout.css
- apps/app/ui-tests-app/list-view/item-re-layout.ts
- apps/app/ui-tests-app/list-view/item-re-layout.xml
- apps/app/ui-tests-app/list-view/main-page.ts
- tests/app/ui/list-view/list-view-tests.ts
- tns-core-modules/ui/list-view/list-view.ios.ts
IOS: Layout for views inside list-view template was not triggered whenever a property that requires layout is changed or you call `requestLayout()` manually.
ListView will now do a layout pass for its current items.
>Note: Changing the `height` of list-view-cell is still not supported. 
Related to https://github.com/NativeScript/nativescript-angular/issues/377
> fix(list-view): Layout list-view items on request

- tns-core-modules/platform/platform.android.ts
When getting the screen width/height on android those are the same, no matter if you rotate the device or not. Unlike iOS where the properties always reflect the actual device width/height. 
`platform.screen.mainScreen` width and height properties will always show the actual values like on iOS. 
Fixes #4588.
> fix(android/platform): reinitialise screen metrics on orientation change

- README.md
Images in docs.nativescript.org/api-reference are not visualised.
Images in docs.nativescript.org/api-reference are visualised correctly.
> fix: README's images are not visualised in api reference

- tns-core-modules/ui/frame/frame.android.ts
- tns-core-modules/ui/tab-view/tab-view.android.ts
Fixes https://github.com/NativeScript/NativeScript/issues/6188
Related to https://github.com/NativeScript/NativeScript/pull/6129
Related to https://github.com/NativeScript/NativeScript/pull/5700 (cleaned up some hacks that are no longer necessary with support library APIs)
Also, cleaned up combination of transaction.commitAllowingStateLoss() + fragmentManager.executePendingTransactions for all API levels (with support library APIs fragmentManager.commitNowAllowingStateLoss() is available for all API levels).
> fix(android-next): force frame fragment disposal on unload

- tests/app/data/observable-array-tests.ts
- tns-core-modules/data/observable-array/observable-array.ts
ObservableArray reduce function fails when the InitialValue is not supplied. This PR is to fix that bug.
The new behavior is a bug fix where is the InitialValue is not supplied then appropriate array delegate function will be called.
https://github.com/NativeScript/NativeScript/issues/5868
> 5868 observable array reduce bug

- e2e/modal-navigation/app/android-back-button/android-back-button-page.ts
- e2e/modal-navigation/app/android-back-button/android-back-button-page.xml
- e2e/modal-navigation/app/home/home-page.ts
- e2e/modal-navigation/app/home/home-page.xml
- tns-core-modules/ui/core/view/view.android.ts
`application.android.on("activityBackPressed", () => { ... })` event is not fired when pressing the back button while showing modal.
The event is now fired and can be canceled.
Resolves #3908
cc @SvetoslavTsenov Test page added in `e2e\modal-navigation` app -> `Android Back Btn Events` button
> fix(modals): application activityBackPressed event not fired for modals

- tns-core-modules/ui/core/view-base/view-base.ts
- tns-core-modules/ui/core/view/view.android.ts
- tns-core-modules/ui/frame/frame.android.ts
- tns-core-modules/ui/styling/style-scope.ts
Based on #6187 by @NathanWalker 
Resloves #6179
> ## PR Checklist
> 
> - [x] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/CONTRIBUTING.md#commit-messages.
> - [x] There is an issue for the bug/feature this PR is for. To avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it.
> - [x] You have signed the [CLA](http://www.nativescript.org/cla).
> - [x] All existing tests are passing: https://github.com/NativeScript/NativeScript/blob/master/DevelopmentWorkflow.md#running-unit-tests.
> - [ ] Tests for the changes are included - https://github.com/NativeScript/NativeScript/blob/master/WritingUnitTests.md.
> 
> ## What is the current behavior?
> 
> App's can randomly crash when various …
> fix: Page and Frame isLoaded undefined checks

- build-docs.sh
Right now the docs build fails if you have already built either the /apps or /tests apps.
> docs: gather snippets from apps app folder only

- tests/app/navigation/navigation-tests.ts
- tests/app/testRunner.ts
- tests/app/ui/layouts/flexbox-layout-tests.ts
Fix failing navigation tests with cli next so we can process https://github.com/NativeScript/NativeScript/pull/6293
~~NOTE: temporarily commented out two flexbox tests that started failing with off by 1.5px after update to cli next as they are should be unrelated to the support library / nested frames stories. Will investigate them after I am done with the support lib tasks as most probably there is a real issue with rendering / rounding somewhere.~~
> chore: fix nav tests with cli next

- tns-core-modules/ui/action-bar/action-bar-common.ts
- tns-core-modules/ui/action-bar/action-bar.android.ts
- tns-core-modules/ui/action-bar/action-bar.ios.ts
- tns-core-modules/ui/tab-view/tab-view-common.ts
- tns-core-modules/ui/tab-view/tab-view.android.ts
- tns-core-modules/ui/tab-view/tab-view.ios.ts
Referring missing icons in ActionBar and TabView items should not cause crashes. They should log a console error with the name of the missing resource instead.
> fix: Don't crash on missing resources in tab-view and action-bar

- tests/app/application-settings/application-settings-tests.ts
- tns-core-modules/application-settings/application-settings.android.ts
- tns-core-modules/application-settings/application-settings.d.ts
- tns-core-modules/application-settings/application-settings.ios.ts
There is no way to get all key from application-settings.
There is a method `.allKeys()` that returns all the keys from application-settings.
Fixes #6210.
> feat(application-settings): implemented allKeys method

- tns-core-modules/ui/core/view/view.ios.ts
Applying the safe area adjustments while there is a transform on the UIView leads to unexpected/undefined results. See warning in https://developer.apple.com/documentation/uikit/uiview/1622459-transform. This PR restricts the safe area logic when there is a transform set on the view. This should lead to the same behavior as 4.0.
An alternative would be to remove the transform, adjust the safe area, then re-apply the transform. Will check how this behaves.
Test with Groceries and NS-ng animations demo
> fix-next: restrict to safe area when transform

- tests/app/ui/layouts/layout-tests-helper.ts
- tests/app/ui/layouts/safe-area-tests.ts
- tests/app/ui/list-view/list-view-safe-area-tests.ts
- tests/app/ui/page/page-tests-common.ts
- tests/app/ui/scroll-view/scroll-view-safe-area-tests.ts
* Add longer text for `WrapLayout` tests, so that the setup is the same in landscape
* Add wait until actual ios modal is closed. This should be a temp fix for unit tests.
* Add `greaterOrCloseEnough` assert method similar to `lessOrCloseEnough`, so that landscape cases are covered.
> test(safe-area): fix ios 12 landscape tests

- tns-core-modules/ui/core/view/view.ios.ts
This ensures the same behavior between container views with transform and the ones without a transform.
> fix-next: apply ios safe area before transform

- tests/app/navigation/navigation-tests.ts
- tns-core-modules/ui/frame/frame-common.ts
- tns-core-modules/ui/frame/frame.android.ts
- tns-core-modules/ui/frame/frame.ios.ts
- Navigate __back__ in parent frame, if canGoBack in parent is true, when no back states available.
- Set current frame as topmost after every back navigation
- Unit test added
_Note: required when nesting frames, since __back__ in inner frame could lead to app exit even if there are previous pages on its parent frame._
>  feat(frame): back in parent frame when back states available

- tns-core-modules/ui/frame/fragment.transitions.android.ts
- tns-core-modules/ui/frame/frame.android.ts
- tns-core-modules/ui/tab-view/tab-view.android.ts
Fix issues with "popExit" fragment animation when FragmentTransaction.setCustomAnimations(...) are used.
Also reworked fix from https://github.com/NativeScript/NativeScript/pull/6339 
Kudos to @MartoYankov for the assistance! 👍
> fix-next(android): popExit fragment animation

- tns-core-modules/ui/core/view/view.ios.ts
Currently the layoutChanged event can be raised even when there is no change due to safe area calculations.
The check if the frame is actually changed is performed before the safe area transformations are applied.
> fix-next: correct raising of layoutChanged event

- tns-core-modules/ui/frame/frame.android.ts
Restore animation (default fade) for simulated first navigation that was removed with https://github.com/NativeScript/NativeScript/pull/6421.
Reason is that without animation the flickering when navigating between bottom-positioned tabs in a TabView is even more pronounced than with the fade animation (eventually we should fix the flicker altogether).
> fix-next(android): restore fade animation for simulated nav

- tns-core-modules/ui/frame/frame.android.ts
Reverts NativeScript/NativeScript#6463
Reverting this as it breaks ng e2e tests but needs further research (ideally we would want to keep animated=false but fix the tabview flickering).
> fix-next: revert "fix-next(android): restore fade animation for simulated nav"

- apps/package.json
- apps/tsconfig.json
- tsconfig.shared.json
tns run ios --path apps doesn't launch the manual testing app because the tslib module isn't found. Also, there are error messages about 'sourceMap' cannot be specified with option 'inlineSourceMap'.
The manual testing app does launch, and the sourceMap errors are gone.
> fix: prevent errors on launching manual testing app

- tns-core-modules/ui/styling/style-scope.ts
This is a resurrection of the https://github.com/NativeScript/NativeScript/pull/6353 but it fixed the source rather than the effect that causes memory leak in NativeScript + Angular apps that use `ListView` or `RadListView` from _nativescript-ui-listview_ plugin.
When using the Angular `createEmbeddeedView` from the `ViewContainerRef`, after calling `clear()` the created NativeScript Views are left in the memory
When using the Angular `createEmbeddeedView` from the `ViewContainerRef`, after calling `clear()` the created NativeScript Views are collected by the GC and a no longer in the memory
https://github.com/telerik/nativescript-ui-feedback/issues/825
> Resolve incorrect name of listener when unsubscribing causing Views to be leaked in memory

- tns-core-modules/ui/frame/frame.android.ts
Fixes: https://github.com/NativeScript/NativeScript/issues/6490
Related to: https://github.com/NativeScript/NativeScript/pull/6339
Related to: https://github.com/NativeScript/NativeScript/pull/6421
This fix was originally applied with https://github.com/NativeScript/NativeScript/pull/6339 but was later reworked with https://github.com/NativeScript/NativeScript/pull/6421 (basically the part in frame.android.ts where disposing the fragments is performed after super.unloaded(...) logic).
The original fix did not work properly when called in onDestroyView(...) as it essentially removed the fragment view too early hence breaking exit transition. I actually tested onDestroy(...) then as well but due to a different bug addressed with https://github.com/NativeScript/NativeScript/pull/6421 and …
> fix(android): IllegalStateException with tabview&nested frames

- tns-core-modules/http/http-request/http-request.ios.ts
- tns-core-modules/http/http.ts
Apps can error if url is invalid or response content is invalid.
Error is properly caught and rejected to avoid `Error: Uncaught (in promise)` errors.
> fix(image): uncaught error in promise with image handling

- tns-core-modules/ui/tab-view/tab-view.android.ts
This fix has been tested in production with no new issues occurring.
Long-term solution would be one of the following, though:
1. reintroduce overrides for `saveState`/`restoreState` in the current PagerAdapter implementation (removed on this commit NativeScript@ac04ede#diff-f1459d509d1432b432c29bcd30e462fbL97)
2. use FragmentPagerAdapter
3. use FragmentStatePagerAdapter
Both 2 and 3 manage the save/restore cycles. The main difference between 2 and 3 is that 2 uses more memory, but allows for quicker switching between Fragments than 3. Since tabs should usually be limited to 5 or less, this may be the best choice to maintain performance, which is important for top level navigation tabs.
When I have more time I may experiment with these options myself to see what the difference to …
> fix: crash on Android Tab-View #6466

- apps/app/ui-tests-app/issues/issue-6439.css
- apps/app/ui-tests-app/issues/issue-6439.xml
- apps/app/ui-tests-app/issues/issue-ng-repo-1599.css
- apps/app/ui-tests-app/issues/issue-ng-repo-1599.xml
- apps/app/ui-tests-app/issues/main-page.ts
- apps/app/ui-tests-app/scroll-view/safe-area-sub-element.xml
- tns-core-modules/ui/core/view/view.ios.ts
Fixes https://github.com/NativeScript/NativeScript/issues/6439
Fixes https://github.com/NativeScript/nativescript-angular/issues/1593
Fixes https://github.com/NativeScript/nativescript-angular/issues/1599
Both tests should scroll to bottom and compare image.
Bonus test on issue-ng-repo-1599: scroll one horizontal scrollview to end and compare image first.
> fix(ios): safe area handling in scrollview

- tns-core-modules/ui/frame/frame-common.ts
Endless loop while searching for parent frame that can go back.
Caught in Angular app when trying to go back from nested named lazy loaded outlet using the android hadrware back button.
> fix(back-navigation): app freeze on going back in parent frame

- tns-core-modules/ui/enums/enums.d.ts
As of this moment most of the modules exported from tns-core-modules/ui/enums are not usable with the corresponding element properties in TypeScript.
For example:
```TypeScript
import { KeyboardType, Orientation } from "tns-core-modules/ui/enums";
export function onTFLoaded(args: EventData) {
let tf = <TextField>args.object; // TextField
let stack = <StackLayout>tf.parent; // Stacklayout
stack.orientation = Orientation.horizontal; // this won't work in as the type of the porperty differs from the type of the exported module("enum")
// or
stack.orientation = "horizontal"; // works
tf.keyboardType = KeyboardType.number; // this won't work in as the type of the porperty differs from the type of the exported module("enum")
// or
tf.keyboardType = "number"; ; // works
```
With the PR both …
> fix(ui/enums) make exported enums compatible with TypeScript and the corresponding properties

- tns-core-modules/application/application-common.ts
Error:
```
JS ERROR TypeError: undefined is not an object (evaluating
'application_1.getRootView()._onCssStateChange')
```
Steps:
- `tns run <platform> --hmr`
- make a change in application styles
- restart the application
> fix-next: undefined root view when reapplying styles

- tns-core-modules/ui/tab-view/tab-view.android.ts
Android back button will exit the app, instead going back to previous list page, when using lazy loaded nested named <page-router-outlets> inside TabViewItems. 
_This happens only if using <TabView> as a root component (template-tab-navigation-ng template)._
Remove onBackPressed override, since the topmost() frame is now properly assigned when switching between tab view items.
Fix https://github.com/NativeScript/nativescript-angular/issues/1680
> fix(tab-view): remove onBackPressed override

- tns-core-modules/application/application-common.ts
- tns-core-modules/application/application.android.ts
- tns-core-modules/application/application.ios.ts
Importing `getRootView` from the `application` module causes a circular reference.
Pass `rootView` as a parameter to the `livesync` function.
Fixes https://github.com/NativeScript/NativeScript/issues/6811.
> fix-next: avoid circular reference

- tns-core-modules/ui/core/view/view.ios.ts
[Setting native view frame optimizations](https://github.com/NativeScript/NativeScript/blob/19dfd163e090ef8de789d1b62a39538e0ffc9892/tns-core-modules/ui/core/view/view.ios.ts#L157) were effectively disabled by changing the value of the cached frame and this was particularly visible in nested frame scenarios (resulting in multiple layout passes both top-down and bottom-up).
Fixes: https://github.com/NativeScript/NativeScript/issues/6728
> fix(ios): native view frame optimizations in nested scenario

- tests/app/xml-declaration/tns.xsd
- tns-core-modules/color/known-colors.d.ts
- tns-core-modules/color/known-colors.ts
- tns-core-modules/css/parser.ts
`rebeccapurple` is not recognized as a color name in NativeScript. (It is a part of the [CSS Color Module Level 4](https://drafts.csswg.org/css-color/#named-colors)).
`rebeccapurple` will be recognized as `#663399`.
Fixes/Implements/Closes #6818.
> feat: add rebeccapurple to known CSS colors

- tns-core-modules/ui/core/view/view.android.ts
_Alternative fix: make `fragment: DialogFragmentImpl` a WeakRef<DialogFragmentImpl> property_
Related to Modal view memory issue: https://github.com/NativeScript/NativeScript/issues/6799
> fix(view-android): clear dialog fragment when closing modal view

- apps/app/ui-tests-app/action-bar/flat-scrollview.xml
- apps/app/ui-tests-app/action-bar/flat-tab.xml
- apps/app/ui-tests-app/action-bar/main-page.ts
- apps/app/ui-tests-app/nested-frames/full-screen-n-y-flat.xml
- apps/app/ui-tests-app/nested-frames/full-screen-y-n-flat.xml
- apps/app/ui-tests-app/nested-frames/full-screen-y-y-flat.xml
- apps/app/ui-tests-app/nested-frames/main-page.ts
- apps/app/ui-tests-app/nested-frames/mid-screen-n-y-flat.xml
- apps/app/ui-tests-app/nested-frames/mid-screen-y-n-flat.xml
- apps/app/ui-tests-app/nested-frames/mid-screen-y-y-flat.xml
- apps/app/ui-tests-app/nested-frames/nested-page-flat.xml
- apps/app/ui-tests-app/nested-frames/tab-n-y-flat.xml
- apps/app/ui-tests-app/nested-frames/tab-y-n-flat.xml
- apps/app/ui-tests-app/nested-frames/tab-y-y-flat.xml
- tns-core-modules/ui/page/page.ios.ts
Basically, when there is a flat action bar on a page, the safe area insets coming from parent views should be ignored.
Fixes https://github.com/NativeScript/NativeScript/issues/6788
Fixes https://github.com/NativeScript/NativeScript/issues/5855
@SvetoslavTsenov There are 10 new e2e test pages.
> feat(action-bar): flat mode breaks ios safe area

- tns-core-modules/ui/text-view/text-view.ios.ts
Fixes: https://github.com/NativeScript/NativeScript/issues/6863
> fix(ios): textview content clipped on every other newline

- tns-core-modules/ui/frame/frame.ios.ts
__The problem__: The memory allocated for the modal view, with Frame inside,  is not released.
__Solution__: [iOS] Reset reference to UINavigationController in Frame when UINavigationController view disappeared. _`_teadDownUI` method will call `disposeNativeView` where the clean up is done_    
Fix https://github.com/NativeScript/NativeScript/issues/6799
> fix(ios-frame): tearDownUI and reset UINavigationController

- tns-core-modules/application/application.ios.ts
The application launch is crashing with `JS ERROR TypeError: undefined is not an object (evaluating 'this._rootView._onLivesync')` when there is an app.css change in a hot module update.
The application launches successfully when there is an app.css change in a hot module update.
> fix: app launch with app.css hot module update

- tests/app/ui/search-bar/search-bar-tests-native.android.ts
- tests/app/ui/search-bar/search-bar-tests-native.d.ts
- tests/app/ui/search-bar/search-bar-tests-native.ios.ts
- tests/app/ui/search-bar/search-bar-tests.ts
- tns-core-modules/ui/styling/style-scope.ts
Based on the docs - https://docs.nativescript.org/ui/styling#accessing-nativescript-component-properties-with-css - A developer can declare non-CSS widgets properties in the CSS and this would work if the properties accept text based value.
This works only for lowercase only properties, i.e. single word camel case, and it seems this never worked for multi-word camel case properties. The example in the docs works, but properties like `textFieldBackgroundColor` of the `SearchBar` didn't work. The solution to this bug is to allow the developer to declare such properties as kebab case like this `text-field-background-color`.
This actually implements a number of issues marked as features:
Fixes https://github.com/NativeScript/NativeScript/issues/5355
Fixes …
> fix(css): widget properties in css didn't work

- tns-core-modules/debugger/webinspector-css.ios.ts
- tns-core-modules/debugger/webinspector-dom.ios.ts
- tns-core-modules/debugger/webinspector-network.ios.ts
When the application is being debugged with `--debug-brk --bundle`
options, the JS implementation objects handling the debugging protocol
are created after their corresponding domains' `enable` methods have
been called by the debugger frontend. As a workaround we now manually
call `enable` in their constructors.
related to https://github.com/NativeScript/ios-runtime/issues/1055 and https://github.com/NativeScript/ios-runtime/issues/1057
The Elements, DOM, CSS, and Networking inspector modules are enabled when the `enable` event is received from the debugger.
The Elements, DOM, CSS, and Networking inspector modules are enabled explicitly in their constructors.
> fix(debugger): Enable iOS inspector modules on creation

- tns-core-modules/application/application-common.ts
- tns-core-modules/application/application.d.ts
- tns-core-modules/module.d.ts
- tns-core-modules/nativescript-error.d.ts
- tns-core-modules/ui/core/view/view.d.ts
- tns-core-modules/ui/page/page.d.ts
It is used by `application.d.ts` and needs to be documented. The reason
that it wasn't included in the documentation by now is that `tns-core-modules.d.ts`
(which imports `module.d.ts`) defines types which are part of the internal
modules and runtimes APIs. As such they are excluded from the generation
of API documentation.
related to https://github.com/NativeScript/docs/issues/1541
> fix(docs): Move `NativeScriptError` declaration to a separate file

- apps/app/ui-tests-app/action-bar/flat-layout.xml
- apps/app/ui-tests-app/action-bar/flat-tab-opaque-bar.ts
- apps/app/ui-tests-app/action-bar/flat-tab-opaque-bar.xml
- apps/app/ui-tests-app/action-bar/flat-tab.xml
- apps/app/ui-tests-app/action-bar/flat.xml
- apps/app/ui-tests-app/action-bar/main-page.ts
- apps/app/ui-tests-app/nested-frames/mid-screen-y-n-flat.xml
- tests/app/ui/layouts/safe-area-tests.ts
- tests/app/ui/list-view/list-view-safe-area-tests.ts
- tests/app/ui/repeater/repeater-safe-area-tests.ts
- tests/app/ui/scroll-view/scroll-view-safe-area-tests.ts
- tests/app/ui/web-view/web-view-safe-area-tests.ts
- tns-core-modules/ui/core/view/view.ios.ts
- tns-core-modules/ui/page/page.ios.ts
- tns-core-modules/ui/tab-view/tab-view.ios.ts
The `extendedLayoutIncludesOpaqueBars` property set to `true` unifies layout behavior between translucent and opaque bars in iOS. Remove additional special handling for flat action bars.
fixes https://github.com/NativeScript/NativeScript/issues/6891
fixes https://github.com/NativeScript/NativeScript/issues/6684
Has 2 new ui tests - `/action-bar/flat-layout` and `/action-bar/flat-tab-opaque-bar`.
> fix(ios): opaque bars break ui layout

- tns-core-modules/ui/animation/animation.android.ts
- tns-core-modules/ui/animation/animation.d.ts
- tns-core-modules/ui/animation/keyframe-animation.ts
Do not recreate native animators when looping animation inside keyframe animation. 
__Android API > 23:__ Reusing animatorSet instead of recreating it on every animation iteration. This results in even less memory usage. Recreating it on every loop will lead to higher memory peaks (that will be collected a bit later by the GC)
_Side note: `pulse` CSS animation consist multiple keyframes that animate the scale of an object to different values in a different times. New Animation is created for every keyframe in the keyframes rule. These animations (keyframes) will play sequentially and will repeat all together for specified iterations (or `infinite`). Every Animation (keyframe) has a AnimatorSet that holds multiple Animators depending on the number of properties it should animate. We do not …
> fix(android-animations): reuse animatorSet to prevent high memory usage

- tns-core-modules/ui/frame/fragment.transitions.android.ts
Fixes: https://github.com/NativeScript/NativeScript/issues/6810
The problem is not related to the sidedrawer and can be reproduced with plain navigation between pages as well:
1. Default home page (no nested frames/fragments)
2. Navigate to a second page that contains tabview (implicitly this means nested frames/fragments)
3. Navigate to a third page (no nested frames/fragments) --> exception occurs
This problem is caused by https://github.com/NativeScript/NativeScript/pull/6677 and basically is triggered by not properly setting up transitions/animators logic upon handling fragments with and without nested fragments upon navigation.
> fix(android): resource ID #0xffffffec not found on nav

- tns-core-modules/tns-core-modules.d.ts
See https://github.com/NativeScript/NativeScript/issues/6961
Now there are no linter errors if using `webpack-env` dependency.
Closes https://github.com/NativeScript/NativeScript/issues/6961
> Make NodeRequire declaration match the latest webpack-env one.

- apps/app/ui-tests-app/scroll-view/layout-outside-scroll-view-model.ts
- apps/app/ui-tests-app/scroll-view/layout-outside-scroll.ts
- apps/app/ui-tests-app/scroll-view/layout-outside-scroll.xml
- apps/app/ui-tests-app/scroll-view/main-page.ts
- tns-core-modules/ui/core/view/view.ios.ts
Fixes https://github.com/NativeScript/NativeScript/issues/6915
Added one new e2e test - `scroll-view/layout-outside-scroll`. Steps:
1. Tap on `Scroll To Bottom`.
2. Tap on `Change w/ Visibility`. This will hide both the label at the bottom and the label at the top of the scroll view.
3. Tap on `Scroll To Top`.
4. Verify layout is okay.
> fix(ios): resize of scrollview content breaks layout

- tns-core-modules/ui/tab-view/tab-view.ios.ts
On iOS by default the TabView resets the navigation in a single tab when the tab is re-selected. This breaks navigation as it's not handled by NS.
This behavior is disabled.
Fixes https://github.com/NativeScript/nativescript-angular/issues/1466
> fix(ios): disable default tab reselect behavior

- apps/app/ui-tests-app/action-bar/icons.ts
- apps/app/ui-tests-app/action-bar/icons.xml
- apps/app/ui-tests-app/action-bar/local-icons.ts
- apps/app/ui-tests-app/action-bar/local-icons.xml
- apps/app/ui-tests-app/action-bar/main-page.ts
- apps/app/ui-tests-app/tab-view/main-page.ts
- apps/app/ui-tests-app/tab-view/tab-view-icon-local.ts
- apps/app/ui-tests-app/tab-view/tab-view-icon-local.xml
- tns-core-modules/ui/action-bar/action-bar-common.ts
- tns-core-modules/ui/action-bar/action-bar.android.ts
- tns-core-modules/ui/action-bar/action-bar.d.ts
- tns-core-modules/ui/action-bar/action-bar.ios.ts
- tns-core-modules/ui/tab-view/tab-view.android.ts
- tns-core-modules/ui/tab-view/tab-view.d.ts
On Android, icons rendered in TabView and Actionbar are not scaled correctly due to the use of a deprecated native Android constructor https://developer.android.com/reference/android/graphics/drawable/BitmapDrawable#BitmapDrawable(android.graphics.Bitmap). 
On iOS, there was no property on ActionBar to specify icon rendering mode and it is hard coded to `alwaysOriginal`, which made the use of image icons limited.
Fixed the Android issue with the use of the new constructor.
Added `iosIconRenderingMode` on ActionBar. To avoid breaking changes, on ActionBar this property defaults to `alwaysOriginal` and on TabView, it defaults to `automatic`. We should probably change this for 6.0.
Fixes https://github.com/NativeScript/NativeScript/issues/5887
* Added 2 new e2e tests for Action Bar - …
> feat(): local icon handling in actionbar and tabview

- tests/app/app/main-page.css
- tests/app/livesync/livesync-tests.ts
- tests/app/testRunner.ts
- tests/app/ui/builder/builder-tests.ts
- tests/app/ui/builder/component-module.xml
- tns-core-modules/ui/builder/builder.ts
- tns-core-modules/ui/core/view-base/view-base.d.ts
- tns-core-modules/ui/core/view-base/view-base.ts
- tns-core-modules/ui/core/view/view-common.ts
- tns-core-modules/ui/core/view/view.d.ts
- tns-core-modules/ui/frame/frame-common.ts
A change in styles applies at runtime only for a `Frame` root applications.
This pull request enables changes in styles to apply at runtime, no matter of the root application: layouts, `Frame`, `TabView` or `SideDrawer`.
Implements a part of https://github.com/NativeScript/NativeScript/issues/6953.
> feat(HMR): style views at runtime

- apps/app/ui-tests-app/css/background-image.css
- apps/app/ui-tests-app/css/background-image.xml
- apps/app/ui-tests-app/css/main-page.ts
- tns-core-modules/ui/core/view/view-common.ts
Expose backgroundSize, backgroundRepeat, and backgroundPosition on View. Previously they were only accessible through View.style property and could not be set through xml markup, only css.
This will now work:
``` xml
<Button backgroundImage="url('https://d2odgkulk9w7if.cloudfront.net/images/default-source/home/header-graphic-hp-min.png?sfvrsn=31b70efe_6')"
borderRadius='125' borderWidth='1' borderColor='black'
backgroundRepeat="no-repeat" backgroundSize="contain"
backgroundPosition="center" height='150' width='150' />
```
Fixes: https://github.com/NativeScript/NativeScript/issues/6978
> fix: expose missing css background* properties on View

- tns-core-modules/application/application.ios.ts
- tns-core-modules/ui/frame/frame.android.ts
Handles a scenario with NS Playground where it's possible to start the app from a notification, but the app itself doesn't have bootstrap `application.run()` or alternatives on Angular and Vue called.
> refactor: add better err msg for missing main entry

- tns-core-modules/application/application.android.ts
- tns-core-modules/application/application.ios.ts
Currently app.run relies on app.start so deprecation warning was shown all the time.
> chore: fix app.start deprecation

- tests/app/app/app.ts
- tns-core-modules/application/application.android.ts
- tns-core-modules/application/application.d.ts
- tns-core-modules/ui/frame/activity.android.ts
- tns-core-modules/ui/frame/frame.android.ts
- tns-core-modules/ui/frame/frame.d.ts
This resolves #2747 by implementing a 'new intent' event that gets triggered if the Android activity receives an `onNewIntent` event. Because Android won't invoke this method when an Intent is used to coldstart the app, we also check for an event in `onCreate`.
Notable usecases for having this event are:
- Using Custom URL schemes
- Using Dynamic Links (fi. [through the Firebase plugin](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/issues/692))
- Depending on the plugin/implementation it may help catching the notification data when the app was not running (killed).
- Any other reason an app or plugin has to override the Android activity in order to 'catch' the intents will no longer have to override the activity. For instance, using …
> feat(android): implement a 'activityNewIntent' event

- tns-core-modules/ui/styling/style-scope.ts
Currently our happy path for loading css (no webpack) is expected to throw https://github.com/NativeScript/NativeScript/blob/c5e046e3edc14b6caca5e22387a0386f5ae3bd13/tns-core-modules/ui/styling/style-scope.ts#L86 (global.require on css file) so we always fall back to loading css from file https://github.com/NativeScript/NativeScript/blob/c5e046e3edc14b6caca5e22387a0386f5ae3bd13/tns-core-modules/ui/styling/style-scope.ts#L103
However, when app.css is empty the global.require(...) passes and tries to load css via https://github.com/NativeScript/NativeScript/blob/c5e046e3edc14b6caca5e22387a0386f5ae3bd13/tns-core-modules/ui/styling/style-scope.ts#L96 but cssOrAst variable does not contain actionable string source but [object Object] instead.
Guarding against [object Object] is not the most …
> fix: no trace message on empty app.css

- tests/app/app/app.ts
- tests/app/application/application-tests-common.ts
- tns-core-modules/application/application.ios.ts
Seems we started raising application.displayedEvent only for profiling with https://github.com/NativeScript/NativeScript/pull/5344 but as it is a [public and documented event](https://docs.nativescript.org/core-concepts/application-lifecycle) I've removed the profiling condition now 
Fixes: https://github.com/NativeScript/NativeScript/issues/5572
> fix(ios): application.displayedEvent does not depend on trace to fire

- apps/app/ui-tests-app/css/progress-switch.xml
- tns-core-modules/ui/switch/switch-common.ts
- tns-core-modules/ui/switch/switch.android.ts
- tns-core-modules/ui/switch/switch.d.ts
- tns-core-modules/ui/switch/switch.ios.ts
Add a new property `offBackgroundColor` that can be used in CSS as `off-background-color` to provide on/off customization of the Switch without the need to dynamically set `background-color` on `checked`, because this causes a nasty visual glitch on iOS.
resolves https://github.com/NativeScript/NativeScript/issues/7095
> feat(switch): add property for off state background color

- tns-core-modules/ui/gestures/gestures.ios.ts
We tracked 80+ of these crashes the past week in production:
```text
TypeError: null is not an object (evaluating 'this.view.touchesEndedWithEvent')
```
Adds a null check to `TouchGestureRecognizer` to avoid crash on iOS.
fixes: #7181
> fix(ios): add null check to TouchGestureRecognizer
